<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\booking\shared\Booking.Infrastructure\Booking.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\customer\shared\Customer.Infrastructure\Customer.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\location\shared\Location.Infrastructure\Location.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\marketplace\shared\Marketplace.Infrastructure\Marketplace.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\msteams\shared\MsTeams.Infrastructure\MsTeams.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\notification\shared\Notification.Infrastructure\Notification.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\organization\shared\Organization.Infrastructure\Organization.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\payment\shared\Payment.Infrastructure\Payment.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\slack\shared\Slack.Infrastructure\Slack.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\team\shared\Team.Infrastructure\Team.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\core\shared\Core.Infrastructure\Core.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
