<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>AllApis</AssemblyName>
        <AssemblyTitle>AllApis</AssemblyTitle>
        <Product>Skedular AllApis</Product>
        <Description>Skedular AllApis</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GitRepositoryRoot>$(SolutionDir)</GitRepositoryRoot>
        <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>
        <UseFullSemVerForNuGet>true</UseFullSemVerForNuGet>
        <UpdateVersionProperties>true</UpdateVersionProperties>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitVersion.MsBuild" Version="6.6.2">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\gateway\apis\Gateway\Gateway.csproj"/>
        <ProjectReference Include="..\..\booking\apis\Booking.Api\Booking.Api.csproj"/>
        <ProjectReference Include="..\..\customer\apis\Customer.Api\Customer.Api.csproj"/>
        <ProjectReference Include="..\..\location\apis\Location.Api\Location.Api.csproj"/>
        <ProjectReference Include="..\..\marketplace\apis\Marketplace.Api\Marketplace.Api.csproj"/>
        <ProjectReference Include="..\..\msteams\apis\MsTeams.Api\MsTeams.Api.csproj"/>
        <ProjectReference Include="..\..\organization\apis\Organization.Api\Organization.Api.csproj"/>
        <ProjectReference Include="..\..\slack\apis\Slack.Api\Slack.Api.csproj"/>
        <ProjectReference Include="..\..\team\apis\Team.Api\Team.Api.csproj"/>
        <ProjectReference Include="..\..\core\apis\Core.Api\Core.Api.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
