schema {
  query: Query
  mutation: Mutation
}

type CdnFile {
  url: String!
  height: Int
  width: Int
}

type CdnImageFile {
  original: CdnFile
  thumbnail: CdnFile
}

type DeleteFloorPlanPayload {
  clientMutationId: String
  success: Boolean!
}

type DesksOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type FloorPlanDetails {
  name: String!
  floorLevel: Int!
  floorName: String
  imagePath: String!
  thumbnailPath: String
  width: Int!
  height: Int!
  isActive: Boolean!
  resourcePositions: [ResourcePosition!]!
  id: ID!
}

type FloorPlanPayload {
  clientMutationId: String
  floorPlan: FloorPlanDetails!
}

type LocationAddressDetails {
  formattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String!
  city: String!
  province: String
  zipcode: String!
  country: String!
}

type LocationAnalytics {
  name: String!
  desksOccupancyPercentage: [DesksOccupancyPercentage!]!
  roomsOccupancyPercentage: [RoomsOccupancyPercentage!]!
  dailyBookingsTotals: [LocationDailyBookingsTotal!]!
}

type LocationConnection {
  pageInfo: PageInfo!
  edges: [LocationEdge!]!
  totalCount: Int
}

type LocationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type LocationDetails {
  name: String!
  about: String
  organization: Location_OrganizationDetails!
  timezone: String
  openingHours: OpeningHours!
  deskCapacity: Int!
  roomCapacity: Int!
  hasFutureBooking: Boolean!
  canModify: Boolean!
  canDelete: Boolean!
  canViewAnalytics: Boolean!
  resources: [ResourceDetails!]!
  physicalAddress: LocationAddressDetails!
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  resourceTypes: [Location_OrganizationTagDetails!]!
  locationTags: [Location_OrganizationTagDetails!]!
  contactEmail: String
  contactPhone: String
  primaryFeatureImage: CdnImageFile
  floorPlans: [FloorPlanDetails!]!
  id: ID!
}

type LocationEdge {
  node: LocationDetails!
  cursor: String!
}

type LocationPayload {
  clientMutationId: String
  location: LocationDetails!
}

type Location_OrganizationDetails {
  uniqueId: ID!
  name: String!
  logoUrl: String
}

type Location_OrganizationTagDetails {
  uniqueId: ID!
  name: String
  tagType: String
  color: String
}

type Mutation {
  addLocation(input: AddLocationInput!): LocationPayload @cost(weight: "10")
  updateLocation(input: UpdateLocationInput!): LocationPayload @cost(weight: "10")
  deleteLocation(input: DeleteLocationInput!): LocationPayload @cost(weight: "10")
  addResource(input: AddResourceInput!): ResourcePayload @cost(weight: "10")
  updateResource(input: UpdateResourceInput!): ResourcePayload @cost(weight: "10")
  deleteResource(input: DeleteResourceInput!): ResourcePayload @cost(weight: "10")
  deleteResources(input: DeleteResourcesInput!): ResourcesPayload @cost(weight: "10")
  activateResources(input: ActivateResourcesInput!): ResourcesPayload @cost(weight: "10")
  deactivateResources(input: DeactivateResourcesInput!): ResourcesPayload @cost(weight: "10")
  updateLocationOpeningHours(input: UpdateLocationOpeningHoursInput!): LocationPayload @cost(weight: "10")
  updateLocationResourceAvailableHours(input: UpdateLocationResourceAvailableHoursInput!): ResourcePayload @cost(weight: "10")
  addFloorPlan(input: AddFloorPlanInput!): FloorPlanPayload! @cost(weight: "10")
  updateFloorPlan(input: UpdateFloorPlanInput!): FloorPlanPayload! @cost(weight: "10")
  deleteFloorPlan(input: DeleteFloorPlanInput!): DeleteFloorPlanPayload! @cost(weight: "10")
  updateResourcePositions(input: UpdateResourcePositionsInput!): UpdateResourcePositionsPayload! @cost(weight: "10")
  updateResourcePosition(input: UpdateResourcePositionInput!): ResourcePositionPayload! @cost(weight: "10")
  removeResourcePosition(input: RemoveResourcePositionInput!): RemoveResourcePositionPayload! @cost(weight: "10")
}

type OpeningHours {
  weekOpeningHours: WeekOpeningHours!
  closedDates: [DateTime!]!
  datesWithVariedOpeningHours: [VariedDateOpeningHours!]!
}

type OpeningHoursDetails {
  closed: Boolean!
  openAllDay: Boolean!
  from: String
  until: String
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  locationVersion: Version!
  locationCustomerRecordSynced: Boolean! @cost(weight: "10")
  location(id: String!): LocationDetails @cost(weight: "10")
  locations(after: String first: Int before: String last: Int where: LocationWhereInput! orderBy: [LocationOrderInput!]): LocationConnection! @cost(weight: "10")
  myLocations(organizationId: String): [LocationDetails!] @cost(weight: "10")
  locationAnalytics(locationId: String! from: DateTime! until: DateTime!): LocationAnalytics @cost(weight: "10")
  locationsAnalytics(from: DateTime! until: DateTime! where: LocationWhereInput! orderBy: [LocationOrderInput!]): [LocationAnalytics!]! @cost(weight: "10")
  resources(after: String first: Int before: String last: Int where: ResourceWhereInput! orderBy: [ResourceOrderInput!]): ResourceConnection! @cost(weight: "10")
  resource(id: String!): ResourceDetails @cost(weight: "10")
  floorPlan(id: String!): FloorPlanDetails @cost(weight: "10")
  floorPlansByLocation(locationId: String!): [FloorPlanDetails!]! @cost(weight: "10")
}

type RemoveResourcePositionPayload {
  clientMutationId: String
  success: Boolean!
}

type ResourceConnection {
  pageInfo: PageInfo!
  edges: [ResourceEdge!]!
  totalCount: Int
}

type ResourceDetails {
  name: String!
  inactive: Boolean!
  requireBookingApproval: Boolean!
  color: String
  capacity: Int!
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  productTags: [Location_OrganizationTagDetails!]!
  resourceType: Location_OrganizationTagDetails!
  isAvailableHoursOverridden: Boolean!
  availableHours: OpeningHours
  id: ID!
}

type ResourceEdge {
  node: ResourceDetails!
  cursor: String!
}

type ResourcePayload {
  clientMutationId: String
  resource: ResourceDetails!
}

type ResourcePosition {
  id: ID!
  x: Int!
  y: Int!
  width: Int!
  height: Int!
  shape: String
  metadata: String
  resource: ResourceDetails!
}

type ResourcePositionPayload {
  clientMutationId: String
  resourcePosition: ResourcePosition!
}

type ResourcesPayload {
  clientMutationId: String
  resources: [ResourceDetails!]!
}

type RoomsOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type UpdateResourcePositionsPayload {
  clientMutationId: String
  resourcePositions: [ResourcePosition!]!
}

type VariedDateOpeningHours {
  date: DateTime!
  openingHoursDetails: OpeningHoursDetails!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

type WeekOpeningHours {
  monday: OpeningHoursDetails!
  tuesday: OpeningHoursDetails!
  wednesday: OpeningHoursDetails!
  thursday: OpeningHoursDetails!
  friday: OpeningHoursDetails!
  saturday: OpeningHoursDetails!
  sunday: OpeningHoursDetails!
}

input ActivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input AddFloorPlanInput {
  clientMutationId: String
  locationId: String!
  name: String!
  floorLevel: Int!
  floorName: String
  imageBase64: String!
  imageFileName: String!
}

input AddLocationInput {
  clientMutationId: String
  id: String
  name: String!
  about: String
  organizationId: String!
  timezone: String
  physicalAddress: LocationAddressDetailsInput!
  locationTagIds: [String!]!
  contactEmail: String
  contactPhone: String
  primaryFeatureImage: CdnImageFileInput
}

input AddResourceInput {
  clientMutationId: String
  id: String
  name: String!
  inactive: Boolean!
  locationId: String!
  customTagIds: [String!]!
  zoneIds: [String!]!
  productTagIds: [String!]!
  requireBookingApproval: Boolean!
  color: String
  capacity: Int!
  organizationResourceTypeId: String!
}

input CdnFileInput {
  url: String!
  height: Int
  width: Int
}

input CdnImageFileInput {
  original: CdnFileInput
  thumbnail: CdnFileInput
}

input DeactivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteFloorPlanInput {
  clientMutationId: String
  id: String!
}

input DeleteLocationInput {
  clientMutationId: String
  id: String!
}

input DeleteResourceInput {
  clientMutationId: String
  id: String!
}

input DeleteResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input LocationAddressDetailsInput {
  addressLine1: String!
  addressLine2: String
  suburb: String!
  city: String!
  province: String
  zipcode: String!
  country: String!
}

input LocationOrderInput {
  direction: OrderDirection!
  field: LocationOrderField!
}

input LocationWhereInput {
  organizationId: String
  locationIds: [String!]
  nameContains: String
  customTagIds: [String!]
  zoneIds: [String!]
}

input OpeningHoursDetailsInput {
  closed: Boolean!
  openAllDay: Boolean!
  from: String
  until: String
}

input RemoveResourcePositionInput {
  clientMutationId: String
  resourceId: String!
}

input ResourceOrderInput {
  direction: OrderDirection!
  field: ResourceOrderField!
}

input ResourcePositionInput {
  id: String
  resourceId: String!
  x: Int!
  y: Int!
  width: Int!
  height: Int!
  shape: String
  metadata: String
}

input ResourceWhereInput {
  locationId: String!
  nameContains: String
  customTagIds: [String!]
  zoneIds: [String!]
  productTagIds: [String!]
}

input UpdateFloorPlanInput {
  clientMutationId: String
  id: String!
  name: String!
  floorLevel: Int!
  floorName: String
  isActive: Boolean!
}

input UpdateLocationInput {
  clientMutationId: String
  id: String!
  name: String!
  about: String
  timezone: String
  physicalAddress: LocationAddressDetailsInput!
  locationTagIds: [String!]!
  contactEmail: String
  contactPhone: String
  primaryFeatureImage: CdnImageFileInput
}

input UpdateLocationOpeningHoursInput {
  clientMutationId: String
  id: String!
  weekOpeningHours: WeekOpeningHoursInput!
}

input UpdateLocationResourceAvailableHoursInput {
  clientMutationId: String
  id: String!
  overrideAvailableHours: Boolean!
  availableHours: WeekOpeningHoursInput
}

input UpdateResourceInput {
  clientMutationId: String
  id: String!
  name: String!
  inactive: Boolean!
  requireBookingApproval: Boolean!
  color: String
  capacity: Int!
  customTagIds: [String!]!
  zoneIds: [String!]!
  productTagIds: [String!]!
  organizationResourceTypeId: String!
}

input UpdateResourcePositionInput {
  clientMutationId: String
  resourceId: String!
  floorPlanId: String!
  x: Int!
  y: Int!
  width: Int!
  height: Int!
  shape: String
  metadata: String
}

input UpdateResourcePositionsInput {
  clientMutationId: String
  floorPlanId: String!
  positions: [ResourcePositionInput!]!
}

input WeekOpeningHoursInput {
  monday: OpeningHoursDetailsInput!
  tuesday: OpeningHoursDetailsInput!
  wednesday: OpeningHoursDetailsInput!
  thursday: OpeningHoursDetailsInput!
  friday: OpeningHoursDetailsInput!
  saturday: OpeningHoursDetailsInput!
  sunday: OpeningHoursDetailsInput!
}

enum LocationOrderField {
  NAME
  ABOUT
  TIMEZONE
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

enum ResourceOrderField {
  NAME
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")