schema {
  query: Query
  mutation: Mutation
}

type AcceptInvitationToJoinLocationPayload {
  clientMutationId: String
}

type BulkDeskPayload {
  clientMutationId: String
  desks: [DeskDetails!]!
}

type CancelInvitationToJoinLocationPayload {
  clientMutationId: String
}

type DeskConnection {
  pageInfo: PageInfo!
  edges: [DeskEdge!]!
  totalCount: Int
}

type DeskDetails {
  name: String!
  deactivated: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  id: ID!
}

type DeskEdge {
  node: DeskDetails!
  cursor: String!
}

type DeskPayload {
  clientMutationId: String
  desk: DeskDetails!
}

type DesksOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type DesksPayload {
  clientMutationId: String
  desks: [DeskDetails!]!
}

type InviteCustomersToJoinLocationPayload {
  clientMutationId: String
}

type LocationAddressDetails {
  formattedAddress: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
}

type LocationAnalytics {
  name: String!
  desksOccupancyPercentage: [DesksOccupancyPercentage!]!
  roomsOccupancyPercentage: [RoomsOccupancyPercentage!]!
  dailyBookingsTotals: [LocationDailyBookingsTotal!]!
}

type LocationConnection {
  pageInfo: PageInfo!
  edges: [LocationEdge!]!
  totalCount: Int
}

type LocationCustomerDetails {
  uniqueId: ID!
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
}

type LocationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type LocationDetails {
  name: String!
  about: String
  organization: LocationOrganizationDetails
  timezone: String
  deskCapacity: Int!
  roomCapacity: Int!
  hasFutureBooking: Boolean!
  canModify: Boolean!
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canViewAnalytics: Boolean!
  desks: [DeskDetails!]!
  rooms: [RoomDetails!]!
  physicalAddress: LocationAddressDetails
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  id: ID!
}

type LocationEdge {
  node: LocationDetails!
  cursor: String!
}

type LocationMemberConnection {
  pageInfo: PageInfo!
  edges: [LocationMemberEdge!]!
  totalCount: Int
}

type LocationMemberDetails {
  role: LocationMemberRole
  customer: LocationCustomerDetails!
  id: ID!
}

type LocationMemberDetailsPayload {
  clientMutationId: String
  member: LocationMemberDetails
}

type LocationMemberEdge {
  node: LocationMemberDetails!
  cursor: String!
}

type LocationOrganizationDetails {
  uniqueId: ID!
  name: String!
  logoUrl: String
}

type LocationPayload {
  clientMutationId: String
  location: LocationDetails!
}

type Location_OrganizationTagDetails {
  uniqueId: ID!
  name: String
  tagType: String
  color: String
}

type Mutation {
  addLocation(input: AddLocationInput!): LocationPayload @cost(weight: "10")
  updateLocation(input: UpdateLocationInput!): LocationPayload @cost(weight: "10")
  deleteLocation(input: DeleteLocationInput!): LocationPayload @cost(weight: "10")
  addDesk(input: AddDeskInput!): DeskPayload @cost(weight: "10")
  bulkAddDesk(input: BulkAddDeskInput!): BulkDeskPayload @cost(weight: "10")
  updateDesk(input: UpdateDeskInput!): DeskPayload @cost(weight: "10")
  deleteDesk(input: DeleteDeskInput!): DeskPayload @cost(weight: "10")
  deleteDesks(input: DeleteDesksInput!): DesksPayload @cost(weight: "10")
  activateDesks(input: ActivateDesksInput!): DesksPayload @cost(weight: "10")
  deactivateDesks(input: DeactivateDesksInput!): DesksPayload @cost(weight: "10")
  changeLocationMemberRole(input: ChangeLocationMemberRoleInput!): LocationMemberDetailsPayload @cost(weight: "10")
  inviteCustomersToJoinLocation(input: InviteCustomersToJoinLocationInput!): InviteCustomersToJoinLocationPayload @cost(weight: "10")
  acceptInvitationToJoinLocation(input: AcceptInvitationToJoinLocationInput!): AcceptInvitationToJoinLocationPayload @cost(weight: "10")
  rejectInvitationToJoinLocation(input: RejectInvitationToJoinLocationInput!): RejectInvitationToJoinLocationPayload @cost(weight: "10")
  cancelInvitationToJoinLocation(input: CancelInvitationToJoinLocationInput!): CancelInvitationToJoinLocationPayload @cost(weight: "10")
  addRoom(input: AddRoomInput!): RoomPayload @cost(weight: "10")
  updateRoom(input: UpdateRoomInput!): RoomPayload @cost(weight: "10")
  deleteRoom(input: DeleteRoomInput!): RoomPayload @cost(weight: "10")
  deleteRooms(input: DeleteRoomsInput!): RoomsPayload @cost(weight: "10")
  activateRooms(input: ActivateRoomsInput!): RoomsPayload @cost(weight: "10")
  deactivateRooms(input: DeactivateRoomsInput!): RoomsPayload @cost(weight: "10")
  addResource(input: AddResourceInput!): ResourcePayload @cost(weight: "10")
  updateResource(input: UpdateResourceInput!): ResourcePayload @cost(weight: "10")
  deleteResource(input: DeleteResourceInput!): ResourcePayload @cost(weight: "10")
  deleteResources(input: DeleteResourcesInput!): ResourcesPayload @cost(weight: "10")
  activateResources(input: ActivateResourcesInput!): ResourcesPayload @cost(weight: "10")
  deactivateResources(input: DeactivateResourcesInput!): ResourcesPayload @cost(weight: "10")
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  locationVersion: Version!
  locationCustomerRecordSynced: Boolean! @cost(weight: "10")
  locationMemberRoles: [LocationMemberRole!]!
  location(id: String!): LocationDetails @cost(weight: "10")
  locations(after: String first: Int before: String last: Int where: LocationWhereInput! orderBy: [LocationOrderInput!]): LocationConnection @cost(weight: "10")
  myLocations(organizationId: String): [LocationDetails!] @cost(weight: "10")
  locationMembers(after: String first: Int before: String last: Int where: LocationMemberWhereInput! orderBy: [LocationMemberOrderInput!]): LocationMemberConnection @cost(weight: "10")
  desks(after: String first: Int before: String last: Int where: DeskWhereInput! orderBy: [DeskOrderInput!]): DeskConnection @cost(weight: "10")
  desk(id: String!): DeskDetails @cost(weight: "10")
  locationAnalytics(locationId: String! from: DateTime! until: DateTime!): LocationAnalytics @cost(weight: "10")
  locationsAnalytics(from: DateTime! until: DateTime! where: LocationWhereInput! orderBy: [LocationOrderInput!]): [LocationAnalytics!]! @cost(weight: "10")
  rooms(after: String first: Int before: String last: Int where: RoomWhereInput! orderBy: [RoomOrderInput!]): RoomConnection @cost(weight: "10")
  room(id: String!): RoomDetails @cost(weight: "10")
  resources(after: String first: Int before: String last: Int where: ResourceWhereInput! orderBy: [ResourceOrderInput!]): ResourceConnection @cost(weight: "10")
  resource(id: String!): ResourceDetails @cost(weight: "10")
}

type RejectInvitationToJoinLocationPayload {
  clientMutationId: String
}

type ResourceConnection {
  pageInfo: PageInfo!
  edges: [ResourceEdge!]!
  totalCount: Int
}

type ResourceDetails {
  name: String!
  inactive: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  id: ID!
}

type ResourceEdge {
  node: ResourceDetails!
  cursor: String!
}

type ResourcePayload {
  clientMutationId: String
  resource: ResourceDetails!
}

type ResourcesPayload {
  clientMutationId: String
  resources: [ResourceDetails!]!
}

type RoomConnection {
  pageInfo: PageInfo!
  edges: [RoomEdge!]!
  totalCount: Int
}

type RoomDetails {
  name: String!
  deactivated: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTags: [Location_OrganizationTagDetails!]!
  zones: [Location_OrganizationTagDetails!]!
  id: ID!
}

type RoomEdge {
  node: RoomDetails!
  cursor: String!
}

type RoomPayload {
  clientMutationId: String
  room: RoomDetails!
}

type RoomsOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type RoomsPayload {
  clientMutationId: String
  rooms: [RoomDetails!]!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AcceptInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input ActivateDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input ActivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input ActivateRoomsInput {
  clientMutationId: String
  ids: [String!]!
}

input AddDeskInput {
  clientMutationId: String
  id: String
  name: String!
  locationId: String!
  customTagIds: [String!]!
  zoneIds: [String!]!
  color: String
}

input AddLocationInput {
  clientMutationId: String
  id: String
  name: String!
  about: String
  organizationId: String
  timezone: String
  physicalAddress: LocationAddressDetailsInput
}

input AddResourceInput {
  clientMutationId: String
  id: String
  name: String!
  locationId: String!
  customTagIds: [String!]!
  zoneIds: [String!]!
  color: String
  organizationResourceTypeId: String!
}

input AddRoomInput {
  clientMutationId: String
  id: String
  name: String!
  locationId: String!
  customTagIds: [String!]!
  zoneIds: [String!]!
  color: String
}

input BulkAddDeskInput {
  clientMutationId: String
  id: String
  namePrefix: String
  locationId: String!
  count: Int!
  customTagIds: [String!]!
  zoneIds: [String!]!
  deactivated: Boolean!
  color: String
  requireBookingApproval: Boolean!
}

input CancelInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input ChangeLocationMemberRoleInput {
  clientMutationId: String
  id: String!
  role: LocationMemberRole!
}

input DeactivateDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input DeactivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeactivateRoomsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteDeskInput {
  clientMutationId: String
  id: String!
}

input DeleteDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteLocationInput {
  clientMutationId: String
  id: String!
}

input DeleteResourceInput {
  clientMutationId: String
  id: String!
}

input DeleteResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteRoomInput {
  clientMutationId: String
  id: String!
}

input DeleteRoomsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeskOrderInput {
  direction: OrderDirection!
  field: DeskOrderField!
}

input DeskWhereInput {
  locationId: String!
  nameContains: String
  zoneIds: [String!]
  customTagIds: [String!]
}

input InviteCustomersToJoinLocationInput {
  clientMutationId: String
  locationId: String!
  emails: [String!]!
}

input LocationAddressDetailsInput {
  formattedAddress: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
}

input LocationMemberOrderInput {
  direction: OrderDirection!
  field: LocationMemberOrderField!
}

input LocationMemberWhereInput {
  locationId: String!
  nameContains: String
}

input LocationOrderInput {
  direction: OrderDirection!
  field: LocationOrderField!
}

input LocationWhereInput {
  organizationId: String
  locationIds: [String!]
  nameContains: String
  zoneIds: [String!]
  customTagIds: [String!]
}

input RejectInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input ResourceOrderInput {
  direction: OrderDirection!
  field: ResourceOrderField!
}

input ResourceWhereInput {
  locationId: String!
  nameContains: String
  zoneIds: [String!]
  customTagIds: [String!]
}

input RoomOrderInput {
  direction: OrderDirection!
  field: RoomOrderField!
}

input RoomWhereInput {
  locationId: String!
  nameContains: String
  zoneIds: [String!]
  customTagIds: [String!]
}

input UpdateDeskInput {
  clientMutationId: String
  id: String!
  name: String!
  deactivated: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTagIds: [String!]!
  zoneIds: [String!]!
}

input UpdateLocationInput {
  clientMutationId: String
  id: String!
  name: String!
  about: String
  organizationId: String
  timezone: String
  physicalAddress: LocationAddressDetailsInput
}

input UpdateResourceInput {
  clientMutationId: String
  id: String!
  name: String!
  inactive: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTagIds: [String!]!
  zoneIds: [String!]!
  organizationResourceTypeId: String!
}

input UpdateRoomInput {
  clientMutationId: String
  id: String!
  name: String!
  deactivated: Boolean!
  requireBookingApproval: Boolean!
  color: String
  customTagIds: [String!]!
  zoneIds: [String!]!
}

enum DeskOrderField {
  Name
}

enum LocationMemberOrderField {
  Role
  Name
  GivenName
  MiddleName
  FamilyName
}

enum LocationMemberRole {
  Owner
  Administrator
  Member
}

enum LocationOrderField {
  Name
  About
  Timezone
}

enum OrderDirection {
  Ascending
  Descending
}

enum ResourceOrderField {
  Name
}

enum RoomOrderField {
  Name
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")