<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <AssemblyName>Location.Jobs</AssemblyName>
        <AssemblyTitle>Location.Jobs</AssemblyTitle>
        <Product>Skedular Location Jobs</Product>
        <Description>Skedular Location Jobs</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/skedular/skedular</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../shared/Location.Shared/Location.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
