<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Slack.Shared</AssemblyName>
        <AssemblyTitle>Slack.Shared</AssemblyTitle>
        <Product>Skedular Slack Shared</Product>
        <Description>Skedular Slack Shared</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/skedular/skedular</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools / gRPC (Client) -->
        <PackageReference Include="Grpc.Tools" Version="2.83.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- Slack Integration -->
        <PackageReference Include="SlackNet" Version="0.17.11"/>
        <PackageReference Include="SlackNet.AspNetCore" Version="0.17.11"/>

        <!-- Entity Framework Core (Design / Migration) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Analyzers -->
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../shared/Api.Shared.Clients/Api.Shared.Clients.csproj"/>
        <ProjectReference Include="../../../shared/Api.Shared.Services/Api.Shared.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="EmailTemplates/NewSlackWorkspaceJoined/template.html"/>
        <EmbeddedResource Include="EmailTemplates/NewSlackWorkspaceJoined/template.txt"/>
    </ItemGroup>
</Project>
