<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>Booking.Domain.FakeDependencies</AssemblyName>
        <AssemblyTitle>Booking.Domain.FakeDependencies</AssemblyTitle>
        <Product>Skedular Booking Domain Fake Dependencies</Product>
        <Description>Booking domain fake dependency host for integration tests</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools / gRPC (Server) -->
        <PackageReference Include="Grpc.Tools" Version="2.81.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- gRPC (Server) -->
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0"/>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="../../../shared/Enterprise.Shared/Enterprise.Shared.csproj"/>
        <ProjectReference Include="../../../shared/Api.Shared.Clients/Api.Shared.Clients.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
