namespace Organization.Shared.Workflows.OrganizationOfferingRenewal;

public record ScheduleRenewOrganizationOfferingInput(string OrganizationId, string OrganizationOfferingId, DateTimeOffset RenewalDate);
