@startuml container_diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <tupadr3/common>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/devicons/redis>
!include <tupadr3/devicons/aws>

Person(individualUser, "Individual User", "Books resources from marketplace or organizations")
Person(coworkingOwner, "Co-working Space Owner", "Manages co-working spaces")
Person(orgOwner, "Organization Owner", "Manages an organization")

System_Boundary(skedular, "Skedular") {
    Container(webApp, "Web Application", "React/Next.js", "User interface for booking and management via Web")
    Container(slackApp, "Slack Application", ".Net Core", "User interface for booking and management via Slack")
    Container(msTeamsApp, "MsTeams Application", "React/Next.js", "User interface for booking and management via Microsoft Teams")
    Container(gateway, "API Gateway", ".Net Core", "API Gateway, Federated GraphQL and reverse proxy")

    Container(coreDomain, "Core Domain", "Microservice", "File upload, CDN, private files")
    DEV_POSTGRESQL(coreDb, "Core Database")
    
    Container(customerDomain, "Customer Domain", "Microservice", "Customer data and identities")
    DEV_POSTGRESQL(customerDb, "Customer Database")

    Container(organizationDomain, "Organization Domain", "Microservice", "Organizations and members")
    DEV_POSTGRESQL(organizationDb, "Organization Database")

    Container(locationDomain, "Location Domain", "Microservice", "Locations and resources")
    DEV_POSTGRESQL(locationDb, "Location Database")

    Container(teamDomain, "Team Domain", "Microservice", "Teams within organizations")
    DEV_POSTGRESQL(teamDb, "Team Database")

    Container(bookingDomain, "Booking Domain", "Microservice", "Manages bookings")
    DEV_POSTGRESQL(bookingDb, "Booking Database")

    Container(marketplaceDomain, "Marketplace Domain", "Microservice", "Marketplace products and orgs")
    DEV_POSTGRESQL(marketplaceDb, "Marketplace Database")

    Container(msTeamsDomain, "MsTeams Domain", "Microservice", "MsTeams related data and integration")
    DEV_POSTGRESQL(msTeamsDb, "MsTeams Database")

    Container(slackDomain, "Slack Domain", "Microservice", "Slack interface and integration")
    DEV_POSTGRESQL(slackDb, "Slack Database")
}

DEV_AWS(aws, "Email delivery")
System_Ext(workOS, "WorkOS", "Trusted Identity Provider")
System_Ext(stripe, "Stripe", "Payment processing")
System_Ext(azure, "Azure", "MsTeams integration")
System_Ext(cloudflare, "Cloudflare R2 & CDN", "Object Storage and CDN")
System_Ext(temporal, "Temporal", "Workflow Orchestration", "Temporal for managing workflows and long-running processes")
System_Ext(kafka, "Kafka", "Event Streaming Platform", "Core asynchronous messaging backbone")
DEV_REDIS(redis, "redis")

Rel(skedular, aws, "Uses for sending emails")
Rel(skedular, kafka, "Publishes/Consumes events")
Rel(skedular, redis, "Caches frequently accessed data")
Rel(skedular, temporal, "Worflows and long-running processes")
Rel(skedular, workOS, "Uses for authentication")
Rel(skedular, cloudflare, "Uses for CDN and file storage")
Rel(skedular, stripe, "Uses for payment processing")
Rel(skedular, azure, "Uses for MsTeams integration")

Rel(individualUser, webApp, "Uses")
Rel(coworkingOwner, webApp, "Uses")
Rel(orgOwner, webApp, "Uses")

Rel(individualUser, slackApp, "Uses")
Rel(coworkingOwner, slackApp, "Uses")
Rel(orgOwner, slackApp, "Uses")

Rel(individualUser, msTeamsApp, "Uses")
Rel(coworkingOwner, msTeamsApp, "Uses")
Rel(orgOwner, msTeamsApp, "Uses")

Rel(webApp, gateway, "API calls")
Rel(slackApp, gateway, "API calls")
Rel(msTeamsApp, gateway, "API calls")

Rel(gateway, coreDomain, "Requests")
Rel(coreDomain, coreDb, "Reads/Writes")

Rel(gateway, customerDomain, "Requests")
Rel(customerDomain, customerDb, "Reads/Writes")

Rel(gateway, organizationDomain, "Requests")
Rel(organizationDomain, organizationDb, "Reads/Writes")

Rel(gateway, locationDomain, "Requests")
Rel(locationDomain, locationDb, "Reads/Writes")

Rel(gateway, teamDomain, "Requests")
Rel(teamDomain, teamDb, "Reads/Writes")

Rel(gateway, bookingDomain, "Requests")
Rel(bookingDomain, bookingDb, "Reads/Writes")

Rel(gateway, marketplaceDomain, "Requests")
Rel(marketplaceDomain, marketplaceDb, "Reads/Writes")

Rel(gateway, msTeamsDomain, "Requests")
Rel(msTeamsDomain, msTeamsDb, "Reads/Writes")

Rel(gateway, slackDomain, "Requests")
Rel(slackDomain, slackDb, "Reads/Writes")

@enduml
