networks:
  unityhubio_network:

volumes:
  unityhubio_postgres_data:
  unityhubio_redis_data:
  unityhubio_kafka1_data:

services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 5000:8080
    networks:
      unityhubio_network:
        aliases:
          - dozzle.localhost

  postgres:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=10000'
    restart: unless-stopped
    volumes:
      - unityhubio_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${UNITYHUBIO_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${UNITYHUBIO_POSTGRES_PASSWORD}
    ports:
      - "13450:5432"
    networks:
      unityhubio_network:
        aliases:
          - postgres.localhost

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - unityhubio_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - redis.localhost

  kafka1:
    image: confluentinc/cp-kafka:latest
    volumes:
      - unityhubio_kafka1_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://kafka1.localhost:19092"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIR: "/tmp/kafka-logs"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      unityhubio_network:
        aliases:
          - kafka1.localhost

  kowl:
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    depends_on:
      - kafka1
    environment:
      KAFKA_BROKERS: "kafka1.localhost:19092"
    ports:
      - 8888:8080
    networks:
      - unityhubio_network

  staging-infra-provision:
    image: ghcr.io/unityhubio/allinfra:latest
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Application__Environment: staging
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
    networks:
      - unityhubio_network

  staging-apis-01:
    image: ghcr.io/unityhubio/allapis:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
    ports:
      - 49000:9000
      - 40000:10000
      - 40100:10100
      - 40200:10200
      - 40300:10300
      - 40400:10400
      - 40500:10500
      - 40600:10600
      - 40700:10700
      - 40800:10800
      - 40900:10900
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC
      Application__IdentityProviders__Cognito__Audiences: 3tnq0lamc2gbgp8dmu404mj0us
      Application__IdentityProviders__Google__ApplicationId: 661765198440-lgar8febodjaudbn3ij5tgngqiv0qioi.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://staging.unityhub.io
      Application__WebAppBaseDomain: https://app.staging.unityhub.io
      Application__ApiBaseDomain: https://apistaging.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Subgraphs__Billing__Url: http://localhost:10800/billing/api/v1/graphql
      Subgraphs__Booking__Url: http://localhost:10300/booking/api/v1/graphql
      Subgraphs__Customer__Url: http://localhost:10000/customer/api/v1/graphql
      Subgraphs__Location__Url: http://localhost:10600/location/api/v1/graphql
      Subgraphs__Notification__Url: http://localhost:10400/notification/api/v1/graphql
      Subgraphs__Organization__Url: http://localhost:10200/organization/api/v1/graphql
      Subgraphs__Payment__Url: http://localhost:10100/payment/api/v1/graphql
      Subgraphs__Slack__Url: http://localhost:10700/slack/api/v1/graphql
      Subgraphs__Team__Url: http://localhost:10500/team/api/v1/graphql
      Billing__ApiKey: ${STAGING_UNITYHUBIO_BILLING_APIKEY}
      Booking__ApiKey: ${STAGING_UNITYHUBIO_BOOKING_APIKEY}
      Customer__ApiKey: ${STAGING_UNITYHUBIO_CUSTOMER_APIKEY}
      Location__ApiKey: ${STAGING_UNITYHUBIO_LOCATION_APIKEY}
      Notification__ApiKey: ${STAGING_UNITYHUBIO_NOTIFICATION_APIKEY}
      Organization__ApiKey: ${STAGING_UNITYHUBIO_ORGANIZATION_APIKEY}
      Payment__ApiKey: ${STAGING_UNITYHUBIO_PAYMENT_APIKEY}
      Slack__ApiKey: ${STAGING_UNITYHUBIO_SLACK_APIKEY}
      Team__ApiKey: ${STAGING_UNITYHUBIO_TEAM_APIKEY}
      Stripe__PublishableKey: ${STAGING_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://staging.unityhub.io/slack-success-install
      AzureEntra__ClientId: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/health/readiness || exit 1 && curl -f http://localhost:10000/health/readiness || exit 1 && curl -f http://localhost:10100/health/readiness || exit 1 && curl -f http://localhost:10200/health/readiness || exit 1 && curl -f http://localhost:10300/health/readiness || exit 1 && curl -f http://localhost:10400/health/readiness || exit 1 && curl -f http://localhost:10500/health/readiness || exit 1 && curl -f http://localhost:10600/health/readiness || exit 1 && curl -f http://localhost:10700/health/readiness || exit 1 && curl -f http://localhost:10800/health/readiness || exit 1 && curl -f http://localhost:10900/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - staging-apis-01.localhost

  staging-processors-01:
    image: ghcr.io/unityhubio/allprocessors:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
      staging-apis-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC
      Application__IdentityProviders__Cognito__Audiences: 3tnq0lamc2gbgp8dmu404mj0us
      Application__IdentityProviders__Google__ApplicationId: 661765198440-lgar8febodjaudbn3ij5tgngqiv0qioi.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://staging.unityhub.io
      Application__WebAppBaseDomain: https://app.staging.unityhub.io
      Application__ApiBaseDomain: https://apistaging.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Billing__ApiKey: ${STAGING_UNITYHUBIO_BILLING_APIKEY}
      Billing__GrpcUrl: http://staging-apis-01:10802
      Booking__ApiKey: ${STAGING_UNITYHUBIO_BOOKING_APIKEY}
      Booking__GrpcUrl: http://staging-apis-01:10302
      Customer__ApiKey: ${STAGING_UNITYHUBIO_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://staging-apis-01:10002
      Location__ApiKey: ${STAGING_UNITYHUBIO_LOCATION_APIKEY}
      Location__GrpcUrl: http://staging-apis-01:10602
      Notification__ApiKey: ${STAGING_UNITYHUBIO_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://staging-apis-01:10402
      Organization__ApiKey: ${STAGING_UNITYHUBIO_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://staging-apis-01:10202
      Payment__ApiKey: ${STAGING_UNITYHUBIO_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://staging-apis-01:10102
      Slack__ApiKey: ${STAGING_UNITYHUBIO_SLACK_APIKEY}
      Slack__GrpcUrl: http://staging-apis-01:10702
      Team__ApiKey: ${STAGING_UNITYHUBIO_TEAM_APIKEY}
      Team__GrpcUrl: http://staging-apis-01:10502
      Stripe__PublishableKey: ${STAGING_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://staging.unityhub.io/slack-success-install
      AzureEntra__ClientId: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${STAGING_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${STAGING_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10004/health/readiness || exit 1 && curl -f http://localhost:10104/health/readiness || exit 1 && curl -f http://localhost:10204/health/readiness || exit 1 && curl -f http://localhost:10304/health/readiness || exit 1 && curl -f http://localhost:10404/health/readiness || exit 1 && curl -f http://localhost:10504/health/readiness || exit 1 && curl -f http://localhost:10604/health/readiness || exit 1 && curl -f http://localhost:10704/health/readiness || exit 1 && curl -f http://localhost:10804/health/readiness || exit 1 && curl -f http://localhost:10904/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - staging-processors-01.localhost

  staging-jobs-01:
    image: ghcr.io/unityhubio/alljobs:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
      staging-processors-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC
      Application__IdentityProviders__Cognito__Audiences: 3tnq0lamc2gbgp8dmu404mj0us
      Application__IdentityProviders__Google__ApplicationId: 661765198440-lgar8febodjaudbn3ij5tgngqiv0qioi.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://staging.unityhub.io
      Application__WebAppBaseDomain: https://app.staging.unityhub.io
      Application__ApiBaseDomain: https://apistaging.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Billing__ApiKey: ${STAGING_UNITYHUBIO_BILLING_APIKEY}
      Billing__GrpcUrl: http://staging-apis-01:10802
      Booking__ApiKey: ${STAGING_UNITYHUBIO_BOOKING_APIKEY}
      Booking__GrpcUrl: http://staging-apis-01:10302
      Customer__ApiKey: ${STAGING_UNITYHUBIO_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://staging-apis-01:10002
      Location__ApiKey: ${STAGING_UNITYHUBIO_LOCATION_APIKEY}
      Location__GrpcUrl: http://staging-apis-01:10602
      Notification__ApiKey: ${STAGING_UNITYHUBIO_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://staging-apis-01:10402
      Organization__ApiKey: ${STAGING_UNITYHUBIO_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://staging-apis-01:10202
      Payment__ApiKey: ${STAGING_UNITYHUBIO_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://staging-apis-01:10102
      Slack__ApiKey: ${STAGING_UNITYHUBIO_SLACK_APIKEY}
      Slack__GrpcUrl: http://staging-apis-01:10702
      Team__ApiKey: ${STAGING_UNITYHUBIO_TEAM_APIKEY}
      Team__GrpcUrl: http://staging-apis-01:10502
      Stripe__PublishableKey: ${STAGING_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://staging.unityhub.io/slack-success-install
      AzureEntra__ClientId: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${STAGING_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${STAGING_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@staging.unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10007/health/readiness || exit 1 && curl -f http://localhost:10107/health/readiness || exit 1 && curl -f http://localhost:10207/health/readiness || exit 1 && curl -f http://localhost:10307/health/readiness || exit 1 && curl -f http://localhost:10407/health/readiness || exit 1 && curl -f http://localhost:10507/health/readiness || exit 1 && curl -f http://localhost:10607/health/readiness || exit 1 && curl -f http://localhost:10707/health/readiness || exit 1 && curl -f http://localhost:10807/health/readiness || exit 1 && curl -f http://localhost:10907/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - staging-processors-01.localhost

  prod-infra-provision:
    image: ghcr.io/unityhubio/allinfra:latest
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Application__Environment: prod
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
    networks:
      - unityhubio_network

  prod-apis-01:
    image: ghcr.io/unityhubio/allapis:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      staging-apis-01:
        condition: service_healthy
    ports:
      - 9000:9000
      - 10000:10000
      - 10100:10100
      - 10200:10200
      - 10300:10300
      - 10400:10400
      - 10500:10500
      - 10600:10600
      - 10700:10700
      - 10800:10800
      - 10900:10900
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd
      Application__IdentityProviders__Cognito__Audiences: 4lfik3fdpunv0tj94h5gp1ugd3
      Application__IdentityProviders__Google__ApplicationId: 874220940328-a7o1801134uepnlijk69sue6fs1nl8gr.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://unityhub.io
      Application__WebAppBaseDomain: https://app.unityhub.io
      Application__ApiBaseDomain: https://api.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Subgraphs__Billing__Url: http://localhost:10800/billing/api/v1/graphql
      Subgraphs__Booking__Url: http://localhost:10300/booking/api/v1/graphql
      Subgraphs__Customer__Url: http://localhost:10000/customer/api/v1/graphql
      Subgraphs__Location__Url: http://localhost:10600/location/api/v1/graphql
      Subgraphs__Notification__Url: http://localhost:10400/notification/api/v1/graphql
      Subgraphs__Organization__Url: http://localhost:10200/organization/api/v1/graphql
      Subgraphs__Payment__Url: http://localhost:10100/payment/api/v1/graphql
      Subgraphs__Slack__Url: http://localhost:10700/slack/api/v1/graphql
      Subgraphs__Team__Url: http://localhost:10500/team/api/v1/graphql
      Billing__ApiKey: ${PRODUCTION_UNITYHUBIO_BILLING_APIKEY}
      Booking__ApiKey: ${PRODUCTION_UNITYHUBIO_BOOKING_APIKEY}
      Customer__ApiKey: ${PRODUCTION_UNITYHUBIO_CUSTOMER_APIKEY}
      Location__ApiKey: ${PRODUCTION_UNITYHUBIO_LOCATION_APIKEY}
      Notification__ApiKey: ${PRODUCTION_UNITYHUBIO_NOTIFICATION_APIKEY}
      Organization__ApiKey: ${PRODUCTION_UNITYHUBIO_ORGANIZATION_APIKEY}
      Payment__ApiKey: ${PRODUCTION_UNITYHUBIO_PAYMENT_APIKEY}
      Slack__ApiKey: ${PRODUCTION_UNITYHUBIO_SLACK_APIKEY}
      Team__ApiKey: ${PRODUCTION_UNITYHUBIO_TEAM_APIKEY}
      Stripe__PublishableKey: ${PRODUCTION_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://unityhub.io/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/health/readiness || exit 1 && curl -f http://localhost:10000/health/readiness || exit 1 && curl -f http://localhost:10100/health/readiness || exit 1 && curl -f http://localhost:10200/health/readiness || exit 1 && curl -f http://localhost:10300/health/readiness || exit 1 && curl -f http://localhost:10400/health/readiness || exit 1 && curl -f http://localhost:10500/health/readiness || exit 1 && curl -f http://localhost:10600/health/readiness || exit 1 && curl -f http://localhost:10700/health/readiness || exit 1 && curl -f http://localhost:10800/health/readiness || exit 1 && curl -f http://localhost:10900/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - prod-apis-01.localhost

  prod-processors-01:
    image: ghcr.io/unityhubio/allprocessors:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      prod-apis-01:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 3
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd
      Application__IdentityProviders__Cognito__Audiences: 4lfik3fdpunv0tj94h5gp1ugd3
      Application__IdentityProviders__Google__ApplicationId: 874220940328-a7o1801134uepnlijk69sue6fs1nl8gr.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://unityhub.io
      Application__WebAppBaseDomain: https://app.unityhub.io
      Application__ApiBaseDomain: https://api.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Billing__ApiKey: ${PRODUCTION_UNITYHUBIO_BILLING_APIKEY}
      Billing__GrpcUrl: http://prod-apis-01:10802
      Booking__ApiKey: ${PRODUCTION_UNITYHUBIO_BOOKING_APIKEY}
      Booking__GrpcUrl: http://prod-apis-01:10302
      Customer__ApiKey: ${PRODUCTION_UNITYHUBIO_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://prod-apis-01:10002
      Location__ApiKey: ${PRODUCTION_UNITYHUBIO_LOCATION_APIKEY}
      Location__GrpcUrl: http://prod-apis-01:10602
      Notification__ApiKey: ${PRODUCTION_UNITYHUBIO_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://prod-apis-01:10402
      Organization__ApiKey: ${PRODUCTION_UNITYHUBIO_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://prod-apis-01:10202
      Payment__ApiKey: ${PRODUCTION_UNITYHUBIO_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://prod-apis-01:10102
      Slack__ApiKey: ${PRODUCTION_UNITYHUBIO_SLACK_APIKEY}
      Slack__GrpcUrl: http://prod-apis-01:10702
      Team__ApiKey: ${PRODUCTION_UNITYHUBIO_TEAM_APIKEY}
      Team__GrpcUrl: http://prod-apis-01:10502
      Stripe__PublishableKey: ${PRODUCTION_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://unityhub.io/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${PRODUCTION_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10004/health/readiness || exit 1 && curl -f http://localhost:10104/health/readiness || exit 1 && curl -f http://localhost:10204/health/readiness || exit 1 && curl -f http://localhost:10304/health/readiness || exit 1 && curl -f http://localhost:10404/health/readiness || exit 1 && curl -f http://localhost:10504/health/readiness || exit 1 && curl -f http://localhost:10604/health/readiness || exit 1 && curl -f http://localhost:10704/health/readiness || exit 1 && curl -f http://localhost:10804/health/readiness || exit 1 && curl -f http://localhost:10904/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - prod-processors-01.localhost

  prod-jobs-01:
    image: ghcr.io/unityhubio/alljobs:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      prod-processors-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      Application__IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd/.well-known/jwks.json
      Application__IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd
      Application__IdentityProviders__Cognito__Audiences: 4lfik3fdpunv0tj94h5gp1ugd3
      Application__IdentityProviders__Google__ApplicationId: 874220940328-a7o1801134uepnlijk69sue6fs1nl8gr.apps.googleusercontent.com
      Application__IdentityProviders__Google__Issuer: https://accounts.google.com
      Application__PublicWebSiteBaseDomain: https://unityhub.io
      Application__WebAppBaseDomain: https://app.unityhub.io
      Application__ApiBaseDomain: https://api.unityhub.io
      Postgres__Username: ${UNITYHUBIO_POSTGRES_USERNAME}
      Postgres__Password: ${UNITYHUBIO_POSTGRES_PASSWORD}
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Billing__ApiKey: ${PRODUCTION_UNITYHUBIO_BILLING_APIKEY}
      Billing__GrpcUrl: http://prod-apis-01:10802
      Booking__ApiKey: ${PRODUCTION_UNITYHUBIO_BOOKING_APIKEY}
      Booking__GrpcUrl: http://prod-apis-01:10302
      Customer__ApiKey: ${PRODUCTION_UNITYHUBIO_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://prod-apis-01:10002
      Location__ApiKey: ${PRODUCTION_UNITYHUBIO_LOCATION_APIKEY}
      Location__GrpcUrl: http://prod-apis-01:10602
      Notification__ApiKey: ${PRODUCTION_UNITYHUBIO_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://prod-apis-01:10402
      Organization__ApiKey: ${PRODUCTION_UNITYHUBIO_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://prod-apis-01:10202
      Payment__ApiKey: ${PRODUCTION_UNITYHUBIO_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://prod-apis-01:10102
      Slack__ApiKey: ${PRODUCTION_UNITYHUBIO_SLACK_APIKEY}
      Slack__GrpcUrl: http://prod-apis-01:10702
      Team__ApiKey: ${PRODUCTION_UNITYHUBIO_TEAM_APIKEY}
      Team__GrpcUrl: http://prod-apis-01:10502
      Stripe__PublishableKey: ${PRODUCTION_UNITYHUBIO_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_UNITYHUBIO_STRIPE_SECRET_KEY}
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_UNITYHUBIO_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_UNITYHUBIO_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.unityhub.io/slack/api/v1/callback
      Slack__SuccessInstallUrl: https://unityhub.io/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_UNITYHUBIO_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${PRODUCTION_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "UnityHub <no-reply@unityhub.io>"
      OpenTelemetry__ZipkinEnabled: false
      OpenTelemetry__JaegerEnabled: false
      OpenTelemetry__OtlpEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10007/health/readiness || exit 1 && curl -f http://localhost:10107/health/readiness || exit 1 && curl -f http://localhost:10207/health/readiness || exit 1 && curl -f http://localhost:10307/health/readiness || exit 1 && curl -f http://localhost:10407/health/readiness || exit 1 && curl -f http://localhost:10507/health/readiness || exit 1 && curl -f http://localhost:10607/health/readiness || exit 1 && curl -f http://localhost:10707/health/readiness || exit 1 && curl -f http://localhost:10807/health/readiness || exit 1 && curl -f http://localhost:10907/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - prod-jobs-01.localhost
