networks:
  skedular_network:

volumes:
  unityhubio_postgres_data:
  skedular_redis_data:
  skedular_kafka1_data:

services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 5001:8080
    networks:
      - skedular_network

  postgres:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=10000'
    restart: unless-stopped
    volumes:
      - unityhubio_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SKEDULAR_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SKEDULAR_POSTGRES_PASSWORD}
    ports:
      - "13450:5432"
    networks:
      - skedular_network

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - skedular_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  kafka1:
    image: confluentinc/cp-kafka:latest
    volumes:
      - skedular_kafka1_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:19092"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - skedular_network

  kowl:
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    depends_on:
      - kafka1
    environment:
      KAFKA_BROKERS: "kafka1:29092"
    ports:
      - 8888:8080
    networks:
      - skedular_network

  staging-temporal:
    image: temporalio/auto-setup:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=postgres
      - DB_PORT=5432
      - DBNAME=staging.temporal
      - VISIBILITY_DBNAME=staging.temporal_visibility
      - POSTGRES_USER=${SKEDULAR_POSTGRES_USERNAME}
      - POSTGRES_PWD=${SKEDULAR_POSTGRES_PASSWORD}
      - TEMPORAL_ADDRESS=staging-temporal:7233
      - TEMPORAL_CLI_ADDRESS=staging-temporal:7233
    networks:
      - skedular_network

  prod-temporal:
    image: temporalio/auto-setup:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=postgres
      - DB_PORT=5432
      - DBNAME=prod.temporal
      - VISIBILITY_DBNAME=prod.temporal_visibility
      - POSTGRES_USER=${SKEDULAR_POSTGRES_USERNAME}
      - POSTGRES_PWD=${SKEDULAR_POSTGRES_PASSWORD}
      - TEMPORAL_ADDRESS=prod-temporal:7233
      - TEMPORAL_CLI_ADDRESS=prod-temporal:7233
    networks:
      - skedular_network

  staging-infra-provision:
    image: ghcr.io/unityhubio/allinfra:latest
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__billingdb: ${STAGING_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${STAGING_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${STAGING_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${STAGING_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${STAGING_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${STAGING_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${STAGING_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${STAGING_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${STAGING_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${STAGING_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${STAGING_POSTGRES_TEAM_CONNECTIONSTRING}
      Application__Environment: staging
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
    networks:
      - skedular_network

  staging-apis-01:
    image: ghcr.io/unityhubio/allapis:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
    ports:
      - 49000:9000
      - 40000:10000
      - 40100:10100
      - 40200:10200
      - 40300:10300
      - 40400:10400
      - 40500:10500
      - 40600:10600
      - 40700:10700
      - 40800:10800
      - 40900:10900
      - 41000:11000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC/.well-known/jwks.json
      IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Dtk1H0LC
      IdentityProviders__Cognito__Audiences: 3tnq0lamc2gbgp8dmu404mj0us
      IdentityProviders__Google__ApplicationId: 661765198440-lgar8febodjaudbn3ij5tgngqiv0qioi.apps.googleusercontent.com
      IdentityProviders__Google__Issuer: https://accounts.google.com
      IdentityProviders__WorkOS__JwksUri: https://api.workos.com/sso/jwks/client_01H0Q195NGRARQSJT1TTDAKKR9
      IdentityProviders__WorkOS__Issuer: https://api.workos.com
      IdentityProviders__WorkOS__ApiKey: ${STAGING_SKEDULAR_WORKOS_API_KEY}
      Application__PublicWebSiteBaseDomain: https://staging.getskedular.com
      Application__WebAppBaseDomain: https://staging.skedular.app
      Application__ApiBaseDomain: https://apistaging.skedular.app
      Cookie__EncryptionKey__Key: ${STAGING_SKEDULAR_COOKIE_ENCRYPTION_KEY}
      Cookie__EncryptionKey__Iv: ${STAGING_SKEDULAR_COOKIE_ENCRYPTION_IV}
      ConnectionStrings__billingdb: ${STAGING_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${STAGING_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${STAGING_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${STAGING_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${STAGING_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${STAGING_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${STAGING_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${STAGING_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${STAGING_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${STAGING_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${STAGING_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Subgraphs__Billing__Url: http://localhost:10800/v1/graphql
      Subgraphs__Booking__Url: http://localhost:10300/v1/graphql
      Subgraphs__Customer__Url: http://localhost:10000/v1/graphql
      Subgraphs__Location__Url: http://localhost:10600/v1/graphql
      Subgraphs__Marketplace__Url: http://localhost:11000/v1/graphql
      Subgraphs__MsTeams__Url: http://localhost:10900/v1/graphql
      Subgraphs__Notification__Url: http://localhost:10400/v1/graphql
      Subgraphs__Organization__Url: http://localhost:10200/v1/graphql
      Subgraphs__Payment__Url: http://localhost:10100/v1/graphql
      Subgraphs__Slack__Url: http://localhost:10700/v1/graphql
      Subgraphs__Team__Url: http://localhost:10500/v1/graphql
      Billing__ApiKey: ${STAGING_SKEDULAR_BILLING_APIKEY}
      Booking__ApiKey: ${STAGING_SKEDULAR_BOOKING_APIKEY}
      Customer__ApiKey: ${STAGING_SKEDULAR_CUSTOMER_APIKEY}
      Location__ApiKey: ${STAGING_SKEDULAR_LOCATION_APIKEY}
      Notification__ApiKey: ${STAGING_SKEDULAR_NOTIFICATION_APIKEY}
      Organization__ApiKey: ${STAGING_SKEDULAR_ORGANIZATION_APIKEY}
      Payment__ApiKey: ${STAGING_SKEDULAR_PAYMENT_APIKEY}
      Slack__ApiKey: ${STAGING_SKEDULAR_SLACK_APIKEY}
      Team__ApiKey: ${STAGING_SKEDULAR_TEAM_APIKEY}
      Stripe__PublishableKey: ${STAGING_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: true
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://staging.skedular.app/slack-success-install
      AzureEntra__ClientId: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapistaging.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/health/readiness || exit 1 && curl -f http://localhost:10000/health/readiness || exit 1 && curl -f http://localhost:10100/health/readiness || exit 1 && curl -f http://localhost:10200/health/readiness || exit 1 && curl -f http://localhost:10300/health/readiness || exit 1 && curl -f http://localhost:10400/health/readiness || exit 1 && curl -f http://localhost:10500/health/readiness || exit 1 && curl -f http://localhost:10600/health/readiness || exit 1 && curl -f http://localhost:10700/health/readiness || exit 1 && curl -f http://localhost:10800/health/readiness || exit 1 && curl -f http://localhost:10900/health/readiness || exit 1 && curl -f http://localhost:11000/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  staging-processors-01:
    image: ghcr.io/unityhubio/allprocessors:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
      staging-apis-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      Application__PublicWebSiteBaseDomain: https://staging.getskedular.com
      Application__WebAppBaseDomain: https://staging.skedular.app
      Application__ApiBaseDomain: https://apistaging.skedular.app
      ConnectionStrings__billingdb: ${STAGING_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${STAGING_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${STAGING_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${STAGING_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${STAGING_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${STAGING_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${STAGING_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${STAGING_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${STAGING_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${STAGING_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${STAGING_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Billing__ApiKey: ${STAGING_SKEDULAR_BILLING_APIKEY}
      Billing__GrpcUrl: http://staging-apis-01:10802
      Booking__ApiKey: ${STAGING_SKEDULAR_BOOKING_APIKEY}
      Booking__GrpcUrl: http://staging-apis-01:10302
      Customer__ApiKey: ${STAGING_SKEDULAR_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://staging-apis-01:10002
      Location__ApiKey: ${STAGING_SKEDULAR_LOCATION_APIKEY}
      Location__GrpcUrl: http://staging-apis-01:10602
      Notification__ApiKey: ${STAGING_SKEDULAR_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://staging-apis-01:10402
      Organization__ApiKey: ${STAGING_SKEDULAR_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://staging-apis-01:10202
      Payment__ApiKey: ${STAGING_SKEDULAR_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://staging-apis-01:10102
      Slack__ApiKey: ${STAGING_SKEDULAR_SLACK_APIKEY}
      Slack__GrpcUrl: http://staging-apis-01:10702
      Team__ApiKey: ${STAGING_SKEDULAR_TEAM_APIKEY}
      Team__GrpcUrl: http://staging-apis-01:10502
      Stripe__PublishableKey: ${STAGING_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: true
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://staging.skedular.app/slack-success-install
      AzureEntra__ClientId: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${STAGING_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${STAGING_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapistaging.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10030/health/readiness || exit 1 && curl -f http://localhost:10130/health/readiness || exit 1 && curl -f http://localhost:10230/health/readiness || exit 1 && curl -f http://localhost:10330/health/readiness || exit 1 && curl -f http://localhost:10430/health/readiness || exit 1 && curl -f http://localhost:10530/health/readiness || exit 1 && curl -f http://localhost:10630/health/readiness || exit 1 && curl -f http://localhost:10730/health/readiness || exit 1 && curl -f http://localhost:10830/health/readiness || exit 1 && curl -f http://localhost:10930/health/readiness || exit 1 && curl -f http://localhost:11030/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  staging-jobs-01:
    image: ghcr.io/unityhubio/alljobs:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      staging-infra-provision:
        condition: service_completed_successfully
      staging-processors-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: staging
      Application__PublicWebSiteBaseDomain: https://staging.getskedular.com
      Application__WebAppBaseDomain: https://staging.skedular.app
      Application__ApiBaseDomain: https://apistaging.skedular.app
      ConnectionStrings__billingdb: ${STAGING_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${STAGING_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${STAGING_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${STAGING_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${STAGING_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${STAGING_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${STAGING_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${STAGING_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${STAGING_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${STAGING_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${STAGING_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: staging
      Kafka__OutgoingTopicPrefix: staging
      Billing__ApiKey: ${STAGING_SKEDULAR_BILLING_APIKEY}
      Billing__GrpcUrl: http://staging-apis-01:10802
      Booking__ApiKey: ${STAGING_SKEDULAR_BOOKING_APIKEY}
      Booking__GrpcUrl: http://staging-apis-01:10302
      Customer__ApiKey: ${STAGING_SKEDULAR_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://staging-apis-01:10002
      Location__ApiKey: ${STAGING_SKEDULAR_LOCATION_APIKEY}
      Location__GrpcUrl: http://staging-apis-01:10602
      Notification__ApiKey: ${STAGING_SKEDULAR_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://staging-apis-01:10402
      Organization__ApiKey: ${STAGING_SKEDULAR_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://staging-apis-01:10202
      Payment__ApiKey: ${STAGING_SKEDULAR_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://staging-apis-01:10102
      Slack__ApiKey: ${STAGING_SKEDULAR_SLACK_APIKEY}
      Slack__GrpcUrl: http://staging-apis-01:10702
      Team__ApiKey: ${STAGING_SKEDULAR_TEAM_APIKEY}
      Team__GrpcUrl: http://staging-apis-01:10502
      Stripe__PublishableKey: ${STAGING_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${STAGING_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${STAGING_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: true
      Slack__AppId: A05H0126U7Q
      Slack__ClientId: "118234978193.5578036232262"
      Slack__ClientSecret: ${STAGING_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${STAGING_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapistaging.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://staging.skedular.app/slack-success-install
      AzureEntra__ClientId: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${STAGING_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${STAGING_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${STAGING_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@staging.skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapistaging.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10020/health/readiness || exit 1 && curl -f http://localhost:10120/health/readiness || exit 1 && curl -f http://localhost:10220/health/readiness || exit 1 && curl -f http://localhost:10320/health/readiness || exit 1 && curl -f http://localhost:10420/health/readiness || exit 1 && curl -f http://localhost:10520/health/readiness || exit 1 && curl -f http://localhost:10620/health/readiness || exit 1 && curl -f http://localhost:10720/health/readiness || exit 1 && curl -f http://localhost:10820/health/readiness || exit 1 && curl -f http://localhost:10920/health/readiness || exit 1 && curl -f http://localhost:11020/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  prod-infra-provision:
    image: ghcr.io/unityhubio/allinfra:latest
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__billingdb: ${PRODUCTION_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${PRODUCTION_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${PRODUCTION_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${PRODUCTION_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${PRODUCTION_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${PRODUCTION_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${PRODUCTION_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${PRODUCTION_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${PRODUCTION_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${PRODUCTION_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${PRODUCTION_POSTGRES_TEAM_CONNECTIONSTRING}
      Application__Environment: prod
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
    networks:
      - skedular_network

  prod-apis-01:
    image: ghcr.io/unityhubio/allapis:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      staging-apis-01:
        condition: service_healthy
    ports:
      - 9000:9000
      - 10000:10000
      - 10100:10100
      - 10200:10200
      - 10300:10300
      - 10400:10400
      - 10500:10500
      - 10600:10600
      - 10700:10700
      - 10800:10800
      - 10900:10900
      - 11000:11000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      IdentityProviders__Cognito__JwksUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd/.well-known/jwks.json
      IdentityProviders__Cognito__Issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XBe135wsd
      IdentityProviders__Cognito__Audiences: 4lfik3fdpunv0tj94h5gp1ugd3
      IdentityProviders__Google__ApplicationId: 874220940328-a7o1801134uepnlijk69sue6fs1nl8gr.apps.googleusercontent.com
      IdentityProviders__Google__Issuer: https://accounts.google.com
      IdentityProviders__WorkOS__JwksUri: https://api.workos.com/sso/jwks/client_01H0Q195RQETQ0NFNDPE3GWBQK
      IdentityProviders__WorkOS__Issuer: https://api.workos.com
      IdentityProviders__WorkOS__ApiKey: ${PRODUCTION_SKEDULAR_WORKOS_API_KEY}
      Application__PublicWebSiteBaseDomain: https://getskedular.com
      Application__WebAppBaseDomain: https://skedular.app
      Application__ApiBaseDomain: https://api.skedular.app
      Cookie__EncryptionKey__Key: ${PRODUCTION_SKEDULAR_COOKIE_ENCRYPTION_KEY}
      Cookie__EncryptionKey__Iv: ${PRODUCTION_SKEDULAR_COOKIE_ENCRYPTION_IV}
      ConnectionStrings__billingdb: ${PRODUCTION_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${PRODUCTION_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${PRODUCTION_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${PRODUCTION_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${PRODUCTION_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${PRODUCTION_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${PRODUCTION_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${PRODUCTION_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${PRODUCTION_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${PRODUCTION_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${PRODUCTION_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Subgraphs__Billing__Url: http://localhost:10800/v1/graphql
      Subgraphs__Booking__Url: http://localhost:10300/v1/graphql
      Subgraphs__Customer__Url: http://localhost:10000/v1/graphql
      Subgraphs__Location__Url: http://localhost:10600/v1/graphql
      Subgraphs__Marketplace__Url: http://localhost:11000/v1/graphql
      Subgraphs__MsTeams__Url: http://localhost:10900/v1/graphql
      Subgraphs__Notification__Url: http://localhost:10400/v1/graphql
      Subgraphs__Organization__Url: http://localhost:10200/v1/graphql
      Subgraphs__Payment__Url: http://localhost:10100/v1/graphql
      Subgraphs__Slack__Url: http://localhost:10700/v1/graphql
      Subgraphs__Team__Url: http://localhost:10500/v1/graphql
      Billing__ApiKey: ${PRODUCTION_SKEDULAR_BILLING_APIKEY}
      Booking__ApiKey: ${PRODUCTION_SKEDULAR_BOOKING_APIKEY}
      Customer__ApiKey: ${PRODUCTION_SKEDULAR_CUSTOMER_APIKEY}
      Location__ApiKey: ${PRODUCTION_SKEDULAR_LOCATION_APIKEY}
      Notification__ApiKey: ${PRODUCTION_SKEDULAR_NOTIFICATION_APIKEY}
      Organization__ApiKey: ${PRODUCTION_SKEDULAR_ORGANIZATION_APIKEY}
      Payment__ApiKey: ${PRODUCTION_SKEDULAR_PAYMENT_APIKEY}
      Slack__ApiKey: ${PRODUCTION_SKEDULAR_SLACK_APIKEY}
      Team__ApiKey: ${PRODUCTION_SKEDULAR_TEAM_APIKEY}
      Stripe__PublishableKey: ${PRODUCTION_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: false
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://skedular.app/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapi.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/health/readiness || exit 1 && curl -f http://localhost:10000/health/readiness || exit 1 && curl -f http://localhost:10100/health/readiness || exit 1 && curl -f http://localhost:10200/health/readiness || exit 1 && curl -f http://localhost:10300/health/readiness || exit 1 && curl -f http://localhost:10400/health/readiness || exit 1 && curl -f http://localhost:10500/health/readiness || exit 1 && curl -f http://localhost:10600/health/readiness || exit 1 && curl -f http://localhost:10700/health/readiness || exit 1 && curl -f http://localhost:10800/health/readiness || exit 1 && curl -f http://localhost:10900/health/readiness || exit 1 && curl -f http://localhost:11000/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  prod-processors-01:
    image: ghcr.io/unityhubio/allprocessors:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      prod-apis-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      Application__PublicWebSiteBaseDomain: https://getskedular.com
      Application__WebAppBaseDomain: https://skedular.app
      Application__ApiBaseDomain: https://api.skedular.app
      ConnectionStrings__billingdb: ${PRODUCTION_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${PRODUCTION_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${PRODUCTION_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${PRODUCTION_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${PRODUCTION_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${PRODUCTION_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${PRODUCTION_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${PRODUCTION_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${PRODUCTION_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${PRODUCTION_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${PRODUCTION_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Billing__ApiKey: ${PRODUCTION_SKEDULAR_BILLING_APIKEY}
      Billing__GrpcUrl: http://prod-apis-01:10802
      Booking__ApiKey: ${PRODUCTION_SKEDULAR_BOOKING_APIKEY}
      Booking__GrpcUrl: http://prod-apis-01:10302
      Customer__ApiKey: ${PRODUCTION_SKEDULAR_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://prod-apis-01:10002
      Location__ApiKey: ${PRODUCTION_SKEDULAR_LOCATION_APIKEY}
      Location__GrpcUrl: http://prod-apis-01:10602
      Notification__ApiKey: ${PRODUCTION_SKEDULAR_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://prod-apis-01:10402
      Organization__ApiKey: ${PRODUCTION_SKEDULAR_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://prod-apis-01:10202
      Payment__ApiKey: ${PRODUCTION_SKEDULAR_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://prod-apis-01:10102
      Slack__ApiKey: ${PRODUCTION_SKEDULAR_SLACK_APIKEY}
      Slack__GrpcUrl: http://prod-apis-01:10702
      Team__ApiKey: ${PRODUCTION_SKEDULAR_TEAM_APIKEY}
      Team__GrpcUrl: http://prod-apis-01:10502
      Stripe__PublishableKey: ${PRODUCTION_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: false
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://skedular.app/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${PRODUCTION_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapi.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10030/health/readiness || exit 1 && curl -f http://localhost:10130/health/readiness || exit 1 && curl -f http://localhost:10230/health/readiness || exit 1 && curl -f http://localhost:10330/health/readiness || exit 1 && curl -f http://localhost:10430/health/readiness || exit 1 && curl -f http://localhost:10530/health/readiness || exit 1 && curl -f http://localhost:10630/health/readiness || exit 1 && curl -f http://localhost:10730/health/readiness || exit 1 && curl -f http://localhost:10830/health/readiness || exit 1 && curl -f http://localhost:10930/health/readiness || exit 1 && curl -f http://localhost:11030/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  prod-jobs-01:
    image: ghcr.io/unityhubio/alljobs:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      prod-infra-provision:
        condition: service_completed_successfully
      prod-processors-01:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Application__Environment: prod
      Application__PublicWebSiteBaseDomain: https://getskedular.com
      Application__WebAppBaseDomain: https://skedular.app
      Application__ApiBaseDomain: https://api.skedular.app
      ConnectionStrings__billingdb: ${PRODUCTION_POSTGRES_BILLING_CONNECTIONSTRING}
      ConnectionStrings__bookingdb: ${PRODUCTION_POSTGRES_BOOKING_CONNECTIONSTRING}
      ConnectionStrings__customerdb: ${PRODUCTION_POSTGRES_CUSTOMER_CONNECTIONSTRING}
      ConnectionStrings__locationdb: ${PRODUCTION_POSTGRES_LOCATION_CONNECTIONSTRING}
      ConnectionStrings__marketplacedb: ${PRODUCTION_POSTGRES_MARKETPLACE_CONNECTIONSTRING}
      ConnectionStrings__msteamsdb: ${PRODUCTION_POSTGRES_MSTEAMS_CONNECTIONSTRING}
      ConnectionStrings__notificationdb: ${PRODUCTION_POSTGRES_NOTIFICATION_CONNECTIONSTRING}
      ConnectionStrings__organizationdb: ${PRODUCTION_POSTGRES_ORGANIZATION_CONNECTIONSTRING}
      ConnectionStrings__paymentdb: ${PRODUCTION_POSTGRES_PAYMENT_CONNECTIONSTRING}
      ConnectionStrings__slackdb: ${PRODUCTION_POSTGRES_SLACK_CONNECTIONSTRING}
      ConnectionStrings__teamdb: ${PRODUCTION_POSTGRES_TEAM_CONNECTIONSTRING}
      Kafka__BootstrapServers: "kafka1:29092"
      Kafka__IncomingTopicPrefix: prod
      Kafka__OutgoingTopicPrefix: prod
      Billing__ApiKey: ${PRODUCTION_SKEDULAR_BILLING_APIKEY}
      Billing__GrpcUrl: http://prod-apis-01:10802
      Booking__ApiKey: ${PRODUCTION_SKEDULAR_BOOKING_APIKEY}
      Booking__GrpcUrl: http://prod-apis-01:10302
      Customer__ApiKey: ${PRODUCTION_SKEDULAR_CUSTOMER_APIKEY}
      Customer__GrpcUrl: http://prod-apis-01:10002
      Location__ApiKey: ${PRODUCTION_SKEDULAR_LOCATION_APIKEY}
      Location__GrpcUrl: http://prod-apis-01:10602
      Notification__ApiKey: ${PRODUCTION_SKEDULAR_NOTIFICATION_APIKEY}
      Notification__GrpcUrl: http://prod-apis-01:10402
      Organization__ApiKey: ${PRODUCTION_SKEDULAR_ORGANIZATION_APIKEY}
      Organization__GrpcUrl: http://prod-apis-01:10202
      Payment__ApiKey: ${PRODUCTION_SKEDULAR_PAYMENT_APIKEY}
      Payment__GrpcUrl: http://prod-apis-01:10102
      Slack__ApiKey: ${PRODUCTION_SKEDULAR_SLACK_APIKEY}
      Slack__GrpcUrl: http://prod-apis-01:10702
      Team__ApiKey: ${PRODUCTION_SKEDULAR_TEAM_APIKEY}
      Team__GrpcUrl: http://prod-apis-01:10502
      Stripe__PublishableKey: ${PRODUCTION_SKEDULAR_STRIPE_PUBLISH_KEY}
      Stripe__SecretKey: ${PRODUCTION_SKEDULAR_STRIPE_SECRET_KEY}
      Stripe__PlatformAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_PLATFORM_ACCOUNT_WEBHOOK_KEY}
      Stripe__ConnectAccountWebhookKey: ${PRODUCTION_SKEDULAR_STRIPE_CONNECT_ACCOUNT_WEBHOOK_KEY}
      Stripe__RemoveStripeConnectAccountFromStripe: false
      Slack__AppId: A05H015F9QE
      Slack__ClientId: "118234978193.5578039519830"
      Slack__ClientSecret: ${PRODUCTION_SKEDULAR_SLACK_CLIENT_SECRET}
      Slack__SigningSecret: ${PRODUCTION_SKEDULAR_SLACK_SIGNING_SECRET}
      Slack__RedirectUrl: https://slackapi.skedular.app/v1/slack/callback
      Slack__SuccessInstallUrl: https://skedular.app/slack-success-install
      AzureEntra__ClientId: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_ID}
      AzureEntra__ClientSecret: ${PRODUCTION_SKEDULAR_AZURE_ENTRA_CLIENT_SECRET}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${PRODUCTION_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PRODUCTION_AWS_SECRET_ACCESS_KEY}
      Email__NewCustomerFeedbackThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewCustomerJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinOrganizationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinLocationExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamNewCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__InviteToJoinTeamExistingCustomerEmailSender: "Skedular <no-reply@skedular.app>"
      Email__NewSlackWorkspaceJoinedThroughWebSubmittedEmailSender: "Skedular <no-reply@skedular.app>"
      Email__EnableNewCustomerJoinedThroughWebEmail: true
      Email__EnableNewSlackWorkspaceJoinedThroughWebEmail: true
      OpenTelemetry__ConsoleEnabled: false
      OpenTelemetry__ZipkinEndpoint: ""
      OpenTelemetry__JaegerEndpoint: ""
      OpenTelemetry__MetricsIngestEnabled: false
      OpenTelemetry__EntityFrameworkEnabled: false
      Organization__ApiBaseDomain: https://organizationapi.skedular.app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:10020/health/readiness || exit 1 && curl -f http://localhost:10120/health/readiness || exit 1 && curl -f http://localhost:10220/health/readiness || exit 1 && curl -f http://localhost:10320/health/readiness || exit 1 && curl -f http://localhost:10420/health/readiness || exit 1 && curl -f http://localhost:10520/health/readiness || exit 1 && curl -f http://localhost:10620/health/readiness || exit 1 && curl -f http://localhost:10720/health/readiness || exit 1 && curl -f http://localhost:10820/health/readiness || exit 1 && curl -f http://localhost:10920/health/readiness || exit 1 && curl -f http://localhost:11020/health/readiness || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network
