networks:
  skedular_network:

volumes:
  skedular_postgres_data:
  skedular_redis_data:
  skedular_kafka1_data:
  skedular_keycloak_data:
  skedular_temporal_data:

services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 5001:8080
    networks:
      - skedular_network

  postgres:
    image: postgis/postgis:17-master
    platform: linux/amd64
    command: postgres -c 'max_connections=10000' -c 'shared_preload_libraries=pg_stat_statements'
    restart: unless-stopped
    volumes:
      - skedular_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "8b974997c3c54b10a556f089377505d7"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    networks:
      - skedular_network

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - skedular_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      - skedular_network

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - skedular_network

  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "19092:19092"
    volumes:
      - skedular_kafka1_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:19092"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - skedular_network

  kowl:
    image: redpandadata/console:latest
    restart: unless-stopped
    depends_on:
      - schema-registry
      - kafka1
    environment:
      KAFKA_BROKERS: "kafka1:29092"
      SCHEMAREGISTRY_ENABLED: "true"
      SCHEMAREGISTRY_URLS: "http://schema-registry:9100"
    ports:
      - 8888:8080
    networks:
      - skedular_network

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - kafka1
    ports:
      - "9100:9100"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9100
    networks:
      - skedular_network

  zipkin:
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    ports:
      - 9411:9411
    networks:
      - skedular_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
    networks:
      - skedular_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
      KEYCLOAK_IMPORT_STRATEGY: OVERWRITE_EXISTING
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - skedular_keycloak_data:/opt/keycloak/data
      - ./keyckloak.json:/opt/keycloak/data/import/realm.json
    networks:
      - skedular_network

  temporal:
    image: temporalio/auto-setup:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 7233:7233
    environment:
      - DB=postgres12
      - POSTGRES_SEEDS=postgres
      - DB_PORT=5432
      - DBNAME=temporal
      - VISIBILITY_DBNAME=temporal_visibility
      - POSTGRES_USER=8b974997c3c54b10a556f089377505d7
      - POSTGRES_PWD=123456
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - skedular_network

  temporal-admin-tools:
    image: temporalio/admin-tools:latest
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    networks:
      - skedular_network

  temporal-ui:
    image: temporalio/ui:latest
    restart: unless-stopped
    depends_on:
      - temporal
    ports:
      - 8080:8080
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    networks:
      - skedular_network
