networks:
  unityhubio_network:

volumes:
  unityhubio_postgres_data:
  unityhubio_redis_data:
  unityhubio_kafka1_data:

services:
  dozzle:
    image: amir20/dozzle:latest
    profiles:
      - core
      - all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 5000:8080
    networks:
      unityhubio_network:
        aliases:
          - dozzle.localhost

  postgres:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=10000'
    restart: unless-stopped
    volumes:
      - unityhubio_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "8b974997c3c54b10a556f089377505d7"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    profiles:
      - core
      - all
      - gateway
    networks:
      unityhubio_network:
        aliases:
          - postgres.localhost

  redis:
    image: redis:latest
    profiles:
      - core
      - all
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - unityhubio_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 100
    networks:
      unityhubio_network:
        aliases:
          - redis.localhost

  redisinsight:
    image: redislabs/redisinsight:latest
    profiles:
      - core
      - all
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      unityhubio_network:
        aliases:
          - redisinsight.localhost

  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "19092:19092"
    volumes:
      - unityhubio_kafka1_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://kafka1.localhost:19092"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIR: "/tmp/kafka-logs"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    profiles:
      - core
      - all
    networks:
      unityhubio_network:
        aliases:
          - kafka1.localhost

  kowl:
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    depends_on:
      - schema-registry
      - kafka1
    environment:
      KAFKA_BROKERS: "kafka1.localhost:19092"
      KAFKA_SCHEMAREGISTRY_URLS: http://schema-registry.localhost:9100
      KAFKA_SCHEMAREGISTRY_ENABLED: "TRUE"
    ports:
      - 8888:8080
    profiles:
      - core
      - all
    networks:
      - unityhubio_network

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka1
    ports:
      - "9100:9100"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9100
    profiles:
      - core
      - all
    networks:
      unityhubio_network:
        aliases:
          - schema-registry.localhost

  zipkin:
    image: openzipkin/zipkin:latest
    profiles:
      - core
      - all
    restart: unless-stopped
    ports:
      - 9411:9411
    networks:
      unityhubio_network:
        aliases:
          - zipkin.localhost

  jaeger:
    image: jaegertracing/all-in-one:latest
    profiles:
      - core
      - all
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
    networks:
      unityhubio_network:
        aliases:
          - jaeger.localhost
