<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>Location.Domain.FakeDependencies</AssemblyName>
        <AssemblyTitle>Location.Domain.FakeDependencies</AssemblyTitle>
        <Product>Skedular Location Domain Fake Dependencies</Product>
        <Description>Location domain fake dependency host for integration tests</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GitRepositoryRoot>$(SolutionDir)</GitRepositoryRoot>
        <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>
        <UseFullSemVerForNuGet>true</UseFullSemVerForNuGet>
        <UpdateVersionProperties>true</UpdateVersionProperties>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Location.Domain.FakeDependencies</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools -->
        <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <!-- gRPC (Server) -->
        <PackageReference Include="Grpc.AspNetCore" Version="2.76.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../shared/Enterprise.Shared/Enterprise.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
