<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Booking.Shared</AssemblyName>
        <AssemblyTitle>Booking.Shared</AssemblyTitle>
        <Product>Skedular Booking Shared</Product>
        <Description>Skedular Booking Shared</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools / gRPC (Client) -->
        <PackageReference Include="Grpc.Tools" Version="2.83.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- Entity Framework Core (Design / Migration) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Analyzers -->
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../shared/Api.Shared.Clients/Api.Shared.Clients.csproj"/>
        <ProjectReference Include="../../../shared/Api.Shared.Services/Api.Shared.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Booking.Shared.UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="EmailTemplates/BookingInvoice/template.html"/>
        <EmbeddedResource Include="EmailTemplates/BookingInvoice/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/OrganizationArrearsInvoice/template.html"/>
        <EmbeddedResource Include="EmailTemplates/OrganizationArrearsInvoice/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/RefundStatusCustomer/template.html"/>
        <EmbeddedResource Include="EmailTemplates/RefundStatusCustomer/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/RefundStatusInternal/template.html"/>
        <EmbeddedResource Include="EmailTemplates/RefundStatusInternal/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/BookingFailureCustomer/template.html"/>
        <EmbeddedResource Include="EmailTemplates/BookingFailureCustomer/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/BookingFailureInternal/template.html"/>
        <EmbeddedResource Include="EmailTemplates/BookingFailureInternal/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/MarketplaceBookingModificationCustomer/template.html"/>
        <EmbeddedResource Include="EmailTemplates/MarketplaceBookingModificationCustomer/template.txt"/>
        <EmbeddedResource Include="EmailTemplates/MarketplaceBookingModificationOrganization/template.html"/>
        <EmbeddedResource Include="EmailTemplates/MarketplaceBookingModificationOrganization/template.txt"/>
    </ItemGroup>
</Project>
