<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>AllInfra</AssemblyName>
        <AssemblyTitle>AllInfra</AssemblyTitle>
        <Product>Skedular AllInfra</Product>
        <Description>Skedular AllInfra</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/skedular/skedular</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../booking/shared/Booking.Infrastructure/Booking.Infrastructure.csproj"/>
        <ProjectReference Include="../../customer/shared/Customer.Infrastructure/Customer.Infrastructure.csproj"/>
        <ProjectReference Include="../../location/shared/Location.Infrastructure/Location.Infrastructure.csproj"/>
        <ProjectReference Include="../../marketplace/shared/Marketplace.Infrastructure/Marketplace.Infrastructure.csproj"/>
        <ProjectReference Include="../../msteams/shared/MsTeams.Infrastructure/MsTeams.Infrastructure.csproj"/>
        <ProjectReference Include="../../organization/shared/Organization.Infrastructure/Organization.Infrastructure.csproj"/>
        <ProjectReference Include="../../slack/shared/Slack.Infrastructure/Slack.Infrastructure.csproj"/>
        <ProjectReference Include="../../team/shared/Team.Infrastructure/Team.Infrastructure.csproj"/>
        <ProjectReference Include="../../core/shared/Core.Infrastructure/Core.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
