schema {
  query: Query
  mutation: Mutation
}

type AcceptInvitationToJoinTeamPayload {
  clientMutationId: String
}

type CancelInvitationToJoinTeamPayload {
  clientMutationId: String
}

type InviteCustomersToJoinTeamPayload {
  clientMutationId: String
}

type Mutation {
  addTeam(input: AddTeamInput!): TeamPayload @cost(weight: "10")
  updateTeam(input: UpdateTeamInput!): TeamPayload @cost(weight: "10")
  deleteTeam(input: DeleteTeamInput!): TeamPayload @cost(weight: "10")
  changeTeamMemberOwnershipType(input: ChangeTeamMemberOwnershipTypeInput!): TeamMemberDetailsPayload @cost(weight: "10")
  inviteCustomersToJoinTeam(input: InviteCustomersToJoinTeamInput!): InviteCustomersToJoinTeamPayload @cost(weight: "10")
  acceptInvitationToJoinTeam(input: AcceptInvitationToJoinTeamInput!): AcceptInvitationToJoinTeamPayload @cost(weight: "10")
  rejectInvitationToJoinTeam(input: RejectInvitationToJoinTeamInput!): RejectInvitationToJoinTeamPayload @cost(weight: "10")
  cancelInvitationToJoinTeam(input: CancelInvitationToJoinTeamInput!): CancelInvitationToJoinTeamPayload @cost(weight: "10")
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  teamVersion: Version!
  teamCustomerRecordSynced: Boolean! @cost(weight: "10")
  teamMemberMembershipTypes: [TeamMemberMembershipType!]!
  team(id: String!): TeamDetails @cost(weight: "10")
  teams(after: String first: Int before: String last: Int where: TeamWhereInput! orderBy: [TeamOrderInput!]): TeamConnection @cost(weight: "10")
  myTeams(organizationId: String): [TeamDetails!] @cost(weight: "10")
  teamMembers(after: String first: Int before: String last: Int where: TeamMemberWhereInput! orderBy: [TeamMemberOrderInput!]): TeamMemberConnection @cost(weight: "10")
}

type RejectInvitationToJoinTeamPayload {
  clientMutationId: String
}

type TeamConnection {
  pageInfo: PageInfo!
  edges: [TeamEdge!]!
  totalCount: Int
}

type TeamCustomerDetails {
  uniqueId: ID!
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
}

type TeamDetails {
  name: String!
  about: String
  members: [TeamMemberDetails!]!
  organization: TeamOrganizationDetails
  primaryLocation: TeamLocationDetails
  timezone: String
  hasFutureBooking: Boolean!
  canModify: Boolean!
  canDelete: Boolean!
  canInvitePeople: Boolean!
  id: ID!
}

type TeamEdge {
  node: TeamDetails!
  cursor: String!
}

type TeamLocationDetails {
  uniqueId: ID!
  name: String!
}

type TeamMemberConnection {
  pageInfo: PageInfo!
  edges: [TeamMemberEdge!]!
  totalCount: Int
}

type TeamMemberDetails {
  membershipType: TeamMemberMembershipType
  customer: TeamCustomerDetails!
  organizationMember: TeamOrganizationMemberDetails
  id: ID!
}

type TeamMemberDetailsPayload {
  clientMutationId: String
  member: TeamMemberDetails
}

type TeamMemberEdge {
  node: TeamMemberDetails!
  cursor: String!
}

type TeamOrganizationDetails {
  uniqueId: ID!
  name: String!
  logoUrl: String
}

type TeamOrganizationMemberDetails {
  uniqueId: ID!
  customer: TeamCustomerDetails!
}

type TeamPayload {
  clientMutationId: String
  team: TeamDetails!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AcceptInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input AddTeamInput {
  clientMutationId: String
  id: String
  name: String!
  about: String
  customerIds: [String!]!
  organizationId: String
  primaryLocationId: String
  timezone: String
  organizationMemberIds: [String!]!
}

input CancelInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input ChangeTeamMemberOwnershipTypeInput {
  clientMutationId: String
  id: String!
  membershipType: TeamMemberMembershipType!
}

input DeleteTeamInput {
  clientMutationId: String
  id: String!
}

input InviteCustomersToJoinTeamInput {
  clientMutationId: String
  teamId: String!
  emails: [String!]!
}

input RejectInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input TeamMemberOrderInput {
  direction: OrderDirection!
  field: TeamMemberOrderField!
}

input TeamMemberWhereInput {
  teamId: String!
  nameContains: String
}

input TeamOrderInput {
  direction: OrderDirection!
  field: TeamOrderField!
}

input TeamWhereInput {
  organizationId: String
  nameContains: String
  primaryLocationIds: [String!]
}

input UpdateTeamInput {
  clientMutationId: String
  id: String!
  name: String!
  about: String
  customerIds: [String!]!
  organizationId: String
  primaryLocationId: String
  timezone: String
  organizationMemberIds: [String!]!
}

enum OrderDirection {
  Ascending
  Descending
}

enum TeamMemberMembershipType {
  Owner
  Administrator
  Member
}

enum TeamMemberOrderField {
  MembershipType
  Name
  GivenName
  MiddleName
  FamilyName
}

enum TeamOrderField {
  Name
  About
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION