<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" Version="5.0.0-preview0012"/>
        <PackageReference Include="AutoFixture.AutoFakeItEasy" Version="5.0.0-preview0012"/>
        <PackageReference Include="AutoFixture.Xunit3" Version="5.0.0-preview0012"/>
        <PackageReference Include="FakeItEasy" Version="8.3.0"/>
        <PackageReference Include="FluentAssertions" Version="8.1.1"/>
        <PackageReference Include="GraphQL.Client" Version="6.1.0"/>
        <PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="6.1.0"/>
        <PackageReference Include="xunit.v3" Version="1.1.0"/>

        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Enterprise.Shared\Enterprise.Shared.csproj"/>
    </ItemGroup>

</Project>
