//----------------------
// <auto-generated>
// Generated using Unityhubctl v1.0.0.0. DO NOT EDIT!
// </auto-generated>
//----------------------

using System.Text.RegularExpressions;

using Api.Shared.Events;

using Google.Protobuf.WellKnownTypes;

using NanoidDotNet;

#nullable enable

namespace Api.Shared.Clients.Events.UnityHub.Billing.V1.Value;

public partial class Metadata : IMetadata { }

[KafkaTopic(
    topicName: "billing.v1.event",
    topicPartitionCount: 10,
    retryTopicNamePrefix: "billing.v1.event.retry",
    retryTopicCount: 1,
    retryTopicPartitionCount: 5,
    deadLetterTopicName: "billing.v1.event.deadletter",
    deadLetterTopicPartitionCount: 3,
    protobufSchema: "syntax = \"proto3\";package billing;import \"google/protobuf/timestamp.proto\";option csharp_namespace = \"Api.Shared.Clients.Events.UnityHub.Billing.V1.Value\";enum Type {  BillingOrganizationOfferingUpserted = 0;  BillingOrganizationOfferingDeleted = 1;  OrganizationBillingInfoUpdated = 2;}message Event {  Metadata metadata = 1;  Data data = 2;}message Metadata {  string id = 1;  google.protobuf.Timestamp deletedAt = 2;  string domainSource = 3;  string appSource = 4;  Type type = 5;  google.protobuf.Timestamp time = 6;  string correlationId = 7;}message Data {  OrganizationOfferingBilling organizationOfferingBillingAfterState = 1;  OrganizationBillingInfo organizationBillingInfoAfterState = 2;}message OrganizationOfferingBilling {  string offeringId = 1;  string organizationId = 2;  int64 totalCost = 3;  google.protobuf.Timestamp invoiceDate = 4;}message OrganizationBillingInfo {  string organizationId = 1;  string billingContactEmail = 2;  string billingContactAddressLine1 = 3;  string billingContactAddressLine2 = 4;  string billingContactSuburb = 5;  string billingContactCity = 6;  string billingContactProvince = 7;  string billingContactZipcode = 8;  string billingContactCountry = 9;}")]
public partial class Event : IMetadataEvent
{
    private static readonly Regex ValidKafkaTopicCharacters =
        new(@"^[a-z0-9\.\-_]+$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private const string TopicName = "billing.v1.event";
    private const string RetryTopicNamePrefix = "billing.v1.event.retry";
    private const int RetryTopicCount = 1;
    private const string DeadLetterTopicName = "billing.v1.event.deadletter";

    public static Metadata NewMetadata(
        string domainSource,
        string appSource,
        Type type,
        string correlationId,
        string? id = null) =>
        new() {
            Id = id ?? NanoidDotNet.Nanoid.Generate(),
            DomainSource = domainSource,
            AppSource = appSource,
            Type = type,
            Time = Timestamp.FromDateTime(System.DateTime.UtcNow),
            CorrelationId = correlationId,
    };

    public string GetTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? TopicName : $"{prefix}.{TopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public int GetRetryTopicCount() => RetryTopicCount;

    public string GetRetryTopicName(string prefix, int idx)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? $"{RetryTopicNamePrefix}.{idx}" : $"{prefix}.{RetryTopicNamePrefix}.{idx}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string GetDeadLetterTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? DeadLetterTopicName : $"{prefix}.{DeadLetterTopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string? GetCorrelationId() => Metadata.CorrelationId;
}
