<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <AssemblyName>Organization.Infrastructure</AssemblyName>
        <AssemblyTitle>Organization.Infrastructure</AssemblyTitle>
        <Product>Skedular Organization Infrastructure</Product>
        <Description>Skedular Organization Infrastructure</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Organization.Shared/Organization.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
