<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.11.20">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\billing\jobs\Billing.Jobs\Billing.Jobs.csproj"/>
        <ProjectReference Include="..\..\booking\jobs\Booking.Jobs\Booking.Jobs.csproj"/>
        <ProjectReference Include="..\..\customer\jobs\Customer.Jobs\Customer.Jobs.csproj"/>
        <ProjectReference Include="..\..\location\jobs\Location.Jobs\Location.Jobs.csproj"/>
        <ProjectReference Include="..\..\msteams\jobs\MsTeams.Jobs\MsTeams.Jobs.csproj"/>
        <ProjectReference Include="..\..\notification\jobs\Notification.Jobs\Notification.Jobs.csproj"/>
        <ProjectReference Include="..\..\organization\jobs\Organization.Jobs\Organization.Jobs.csproj"/>
        <ProjectReference Include="..\..\payment\jobs\Payment.Jobs\Payment.Jobs.csproj"/>
        <ProjectReference Include="..\..\slack\jobs\Slack.Jobs\Slack.Jobs.csproj"/>
        <ProjectReference Include="..\..\team\jobs\Team.Jobs\Team.Jobs.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
