syntax = "proto3";
package billing;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Billing.V1.Value";

enum Type {
  BillingOrganizationOfferingUpserted = 0;
  BillingOrganizationOfferingDeleted = 1;
  CustomerBillingInfoUpdated = 2;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string domainSource = 3;
  string appSource = 4;
  Type type = 5;
  google.protobuf.Timestamp time = 6;
  string correlationId = 7;
}

message Data {
  oneof payload {
    OrganizationOfferingBilling organizationOfferingBilling = 1;
    CustomerBillingContact customerBillingContact = 3;
  }
}

message OrganizationOfferingBilling {
  string offeringId = 1;
  string organizationId = 2;
  int64 totalCost = 3;
  google.protobuf.Timestamp invoiceDate = 4;
}

message CustomerBillingContact {
  string customerId = 1;
  string companyName = 2;
  string email = 3;
  string addressLine1 = 4;
  string addressLine2 = 5;
  string suburb = 6;
  string city = 7;
  string province = 8;
  string zipcode = 9;
  string country = 10;
}