syntax = "proto3";
package booking;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Booking.V1.Value";

enum Type {
  BookingUpserted = 0;
  BookingDeleted = 1;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { Booking booking = 1; }

message Booking {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  google.protobuf.Timestamp from = 3;
  google.protobuf.Timestamp until = 4;
  string notes = 5;
  BookingType type = 6;
  BookingStatus status = 7;
  repeated string involvedCustomerIds = 8;
  repeated string involvedOrganizationIds = 9;
  repeated string involvedLocationIds = 10;
  repeated string involvedTeamIds = 11;
  repeated Resource resources = 12;
  repeated BookingSchedule Schedules = 13;
  string paidByCustomerId = 14;
  string paidByOrganizationId = 15;
  string createdByCustomerId = 16;
  string lastModifiedByCustomerId = 17;
  string deletedByCustomerId = 18;
}

enum BookingType
{
    WorkingFromHome = 0;
    WorkingFromOffice = 1;
    SickLeave = 2;
    AnnualLeave = 3;
    WellbeingLeave = 4;
    ClientOffice = 5;
    Vacation = 6;
    TravelingForWork = 7;
    NonWorkingDay = 8;
}

message Resource {
  string id = 1;
  repeated string customerIds = 2;
}

message BookingSchedule {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp until = 2;
}

enum BookingStatus
{
  Pending = 0;
  Rejected = 1;
  Confirmed = 2;
}
