syntax = "proto3";
package booking;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Booking.V1.Value";

enum Type {
  BookingUpserted = 0;
  BookingDeleted = 1;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { Booking booking = 1; }

message Booking {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string customerId = 3;
  string organizationId = 4;
  google.protobuf.Timestamp from = 5;
  google.protobuf.Timestamp until = 6;
  string notes = 7;
  string locationId = 8;
  repeated Resource resources = 9;
  string teamId = 10;
  BookingType type = 11;
  repeated BookingSchedule Schedules = 12;
  repeated string involvedCustomerIds = 13;
  repeated string involvedOrganizationIds = 14;
  repeated string involvedLocationIds = 15;
  repeated string involvedTeamIds = 16;
}

enum BookingType
{
    WorkingFromHome = 0;
    WorkingFromOffice = 1;
    SickLeave = 2;
    AnnualLeave = 3;
    WellBeingLeave = 4;
    ClientOffices = 5;
    Vacation = 6;
    TravelingForWork = 7;
    NonWorkingDay = 8;
}

message Resource {
  string id = 1;
  repeated string customerIds = 2;
}

message BookingSchedule {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp until = 2;
}
