syntax = "proto3";
package customer;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Customer.V1.Value";

enum Type {
  Type_CustomerUpserted = 0;
  Type_CustomerDeleted = 1;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { 
  Customer customer = 1; 
}

message Customer {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  repeated Identity identities = 3;
  string designation = 4;
  string title = 5;
  string name = 6;
  string givenName = 7;
  string middleName = 8;
  string familyName = 9;
  string photoUrl = 10;
  string photoUrl24 = 11;
  string photoUrl32 = 12;
  string photoUrl48 = 13;
  string photoUrl72 = 14;
  string photoUrl192 = 15;
  string photoUrl512 = 16;
  string timezone = 17;
  string locale = 18;
  repeated Location preferredLocations = 19;
  string preferredOrganizationId = 20;
  repeated Resource preferredResources = 21;
  Settings settings = 22;
  repeated Team preferredTeams = 23;
  repeated OrganizationTag preferredOrganizationTags = 24;
  string phoneNumber = 25;
  CustomerBillingDetails billingDetails = 26;
  PersonalInformationVisibility personalInformationVisibility = 27;
}

message Identity {
  string id = 1;
  string email = 2;
  bool emailVerified = 3;
}

message Settings {
  string id = 1;
  bool isOnboardingDone = 2;
}

message Location {
  string id = 1;
  string organizationId = 2;
}

message Team {
  string id = 1;
  string organizationId = 2;
}

message Resource {
  string id = 1;
  string locationId = 2;
}

message OrganizationTag {
  string id = 1;
  string organizationId = 2;
}

message CustomerBillingDetails {
  string id = 1;
  string companyName = 2;
  string email = 3;
  string addressLine1 = 4;
  string addressLine2 = 5;
  string suburb = 6;
  string city = 7;
  string province = 8;
  string zipcode = 9;
  string country = 10;
  string countryCode = 11;
  string formattedAddress = 12;
  string osmType = 13;
  string osmId = 14;
  string placeId = 15;
  Coordinates coordinates = 16;
}

message Coordinates {
  double longitude = 1;
  double latitude = 2;
}

enum PersonalInformationVisibility {
  PersonalInformationVisibility_Visible = 0;
  PersonalInformationVisibility_Redacted = 1;
}