syntax = "proto3";
package location;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Location.V1.Value";

enum Type {
  LocationUpserted = 0;
  LocationDeleted = 1;
  InvitationToJoinLocationUpserted = 2;
  InvitationToJoinLocationDeleted = 3;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { 
  oneof payload {
    Location location = 1;
    InvitationToJoinLocation invitationToJoinLocation = 2;
  }
}

message Location {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string name = 3;
  string about = 4;
  repeated LocationMember members = 5;
  string organizationId = 6;
  string timezone = 7;
  repeated Resource resources = 8;
  OpeningHours openingHours = 9;
}

enum Role {
  Owner = 0;
  Administrator = 1;
  Member = 2;
}

message LocationMember {
  string id = 1;
  Role role = 2;
  string customerId = 3;
}

message Resource {
  string id = 1;
  string name = 2;
  bool inactive = 3;
  bool requireBookingApproval = 4;
  repeated string tagIds = 5;
  string color = 6;
  bool isAvailableHoursOverridden = 7;
  OpeningHours availableHours = 8;
  int32 capacity = 9;
}

message InvitationToJoinLocation {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string locationId = 3;
  string invitedById = 4;
  string inviteeId = 5;
}

message OpeningHours {
  WeekOpeningHours weekOpeningHours = 1;
  repeated google.protobuf.Timestamp closedDates = 2;
  repeated VariedDateOpeningHours DatesWithVariedOpeningHours = 3;
}

message WeekOpeningHours {
  OpeningHoursDetails monday = 1;
  OpeningHoursDetails tuesday = 2;
  OpeningHoursDetails wednesday = 3;
  OpeningHoursDetails thursday = 4;
  OpeningHoursDetails friday = 5;
  OpeningHoursDetails saturday = 6;
  OpeningHoursDetails sunday = 7;
}

message VariedDateOpeningHours {
  google.protobuf.Timestamp date = 1;
  OpeningHoursDetails openingHoursDetails = 2;
}

message OpeningHoursDetails {
  bool closed = 1;
  bool openAllDay = 2;
  string from = 3;
  string until = 4;
}
