syntax = "proto3";
package location;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Location.V1.Value";

enum Type {
  LocationUpserted = 0;
  LocationDeleted = 1;
  InvitationToJoinLocationUpserted = 2;
  InvitationToJoinLocationDeleted = 3;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { 
  oneof payload {
    Location location = 1;
    InvitationToJoinLocation invitationToJoinLocation = 2;
  }
}

message Location {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string name = 3;
  string about = 4;
  repeated LocationMember members = 5;
  string organizationId = 6;
  string timezone = 7;
  repeated Resource resources = 8;
  repeated Desk desks = 9;
  repeated Room rooms = 10;
}

enum Role {
  Owner = 0;
  Administrator = 1;
  Member = 2;
}

message LocationMember {
  string id = 1;
  Role role = 2;
  string customerId = 3;
}

message Resource {
  string id = 1;
  string name = 2;
  bool deactivated = 3;
  bool requireBookingApproval = 4;
  string organizationResourceTypeId = 5;
  repeated string customTagIds = 6;
  repeated string zoneIds = 7;
  string color = 8;
}

message Desk {
  string id = 1;
  string name = 2;
  bool deactivated = 3;
  bool requireBookingApproval = 4;
  repeated string customTagIds = 5;
  repeated string zoneIds = 6;
  string color = 7;
}

message Room {
  string id = 1;
  string name = 2;
  bool deactivated = 3;
  bool requireBookingApproval = 4;
  repeated string customTagIds = 5;
  repeated string zoneIds = 6;
  string color = 7;
}

message InvitationToJoinLocation {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string locationId = 3;
  string invitedById = 4;
  string inviteeId = 5;
}
