syntax = "proto3";
package marketplace;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value";

enum Type {
  Type_ProductUpserted = 0;
  Type_ProductDeleted  = 1;
}

message Event {
  Metadata metadata = 1;
  Data     data     = 2;
}

message Metadata {
  string                    id            = 1;
  string                    domainSource  = 2;
  string                    appSource     = 3;
  Type                      type          = 4;
  google.protobuf.Timestamp time          = 5;
  string                    correlationId = 6;
}

message Data {
  oneof payload {
    Product product = 1;
  }
}

message Product {
  string                    id                   = 1;
  google.protobuf.Timestamp deletedAt            = 2;
  bool                      inactive             = 3;
  string                    organizationId       = 4;
  ProductVersion            latestProductVersion = 5;
}

message ProductVersion {
  string                  id             = 1;
  string                  name           = 2;
  string                  description    = 3;
  Currency                currency       = 4;
  repeated string         productTagIds  = 5;
  repeated string         locationTagIds = 6;
  repeated CdnImageFile   featureImages  = 7;
  repeated ProductPricing pricingOptions = 8;
}

message CdnImageFile {
  CdnFile original  = 1;
  CdnFile thumbnail = 2;
}

message CdnFile {
  string url    = 1;
  int32  height = 2;
  int32  width  = 3;
}

enum ProductPricingCadence {
  ProductPricingCadence_OneTimeV1   = 0;
  ProductPricingCadence_PerMinuteV1 = 1;
  ProductPricingCadence_PerHourV1   = 2;
  ProductPricingCadence_DailyV1     = 3;
  ProductPricingCadence_WeeklyV1    = 4;
  ProductPricingCadence_MonthlyV1   = 5;
}

enum PaymentMethod {
  PaymentMethod_Card         = 0;
  PaymentMethod_BankTransfer = 1;
}

enum Currency {
  Currency_Nzd = 0;
  Currency_Usd = 1;
}

message ProductPricing {
  string                 id                                             = 1;
  int32                  index                                          = 2;
  string                 name                                           = 3;
  string                 description                                    = 4;
  ProductPricingCadence  cadence                                        = 5;
  double                 price                                          = 6;
  bool                   isTaxInclusive                                 = 7;
  Currency               currency                                       = 8;
  repeated PaymentMethod acceptedBookingPaymentMethods                  = 9;
  int32                  minDurationMinutes                             = 10;
  int32                  maxDurationMinutes                             = 11;
  int32                  maxAllowedResourcesLockTimePaidViaCard         = 12;
  int32                  maxAllowedResourcesLockTimePaidViaBankTransfer = 13;
  int32                  numberOfResourcesToBook                        = 14;
}