syntax = "proto3";
package marketplace;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value";

enum Type {
  ProductUpserted = 0;
  ProductDeleted = 1;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { 
  oneof payload {
    Product product = 1;
  }
}

message Product {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  bool inactive = 3;
  string organizationId = 4;
  ProductVersion productVersion = 5;
}

message ProductVersion {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string name = 3;
  string description = 4;
  string price = 5;
  string priceUnit = 6;
  string currency = 7;
  int32 minDurationMinutes = 8;
  int32 maxDurationMinutes = 9;
  bool bookAllLocationResources = 10;
  int32 recurrenceIntervalDays = 11;
  bool forceContinuousSlots = 12;
  int32 maxSpreadDays = 13;
  repeated string productTagIds = 14;
  repeated string locationTagIds = 15;
}
