syntax = "proto3";
package marketplace;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Marketplace.V1";

enum Type {
  Type_ProductUpserted = 0;
  Type_ProductDeleted  = 1;
}

message Event {
  Metadata metadata = 1;
  Data     data     = 2;
}

message Metadata {
  string                    id            = 1;
  string                    domainSource  = 2;
  string                    appSource     = 3;
  Type                      type          = 4;
  google.protobuf.Timestamp time          = 5;
  string                    correlationId = 6;
}

message Data {
  oneof payload {
    Product product = 1;
  }
}

message Product {
  string                    id                   = 1;
  google.protobuf.Timestamp deletedAt            = 2;
  bool                      inactive             = 3;
  string                    organizationId       = 4;
  ProductVersion            latestProductVersion = 5;
}

message ProductVersion {
  string                  id              = 1;
  ListingMetadata         listingMetadata = 2;
  Currency                currency        = 3;
  repeated string         tagIds          = 4;
  repeated CdnImageFile   featureImages   = 5;
  repeated ProductPricing pricingOptions  = 6;
  ProductType             type            = 7;
}

message CdnImageFile {
  CdnFile original  = 1;
  CdnFile thumbnail = 2;
}

message CdnFile {
  string url    = 1;
  int32  height = 2;
  int32  width  = 3;
}

enum ProductPricingCadence {
  ProductPricingCadence_NotSet       = 0;
  ProductPricingCadence_OneTime      = 1;
  ProductPricingCadence_PerMinute    = 2;
  ProductPricingCadence_PerHour      = 3;
  ProductPricingCadence_HalfDay      = 4;
  ProductPricingCadence_Daily        = 5;
  ProductPricingCadence_Weekly       = 6;
  ProductPricingCadence_Monthly      = 7;
  ProductPricingCadence_Per15Minutes = 8;
  ProductPricingCadence_Per30Minutes = 9;
  ProductPricingCadence_TwoMonths    = 10;
  ProductPricingCadence_Quarterly    = 11;
  ProductPricingCadence_FourMonths   = 12;
  ProductPricingCadence_FiveMonths   = 13;
  ProductPricingCadence_SixMonths    = 14;
  ProductPricingCadence_Yearly       = 15;
  ProductPricingCadence_Fortnightly  = 16;
}

enum ProductPricingBillingMode {
  ProductPricingBillingMode_NotSet    = 0;
  ProductPricingBillingMode_Upfront   = 1;
  ProductPricingBillingMode_InArrears = 2;
}

enum ProductPricingCancellationPolicyType {
  ProductPricingCancellationPolicyType_NotSet                 = 0;
  ProductPricingCancellationPolicyType_NoCancellation         = 1;
  ProductPricingCancellationPolicyType_FullRefundBeforeCutoff = 2;
  ProductPricingCancellationPolicyType_TieredRefund           = 3;
}

enum PaymentMethod {
  PaymentMethod_Card         = 0;
  PaymentMethod_BankTransfer = 1;
}

enum Currency {
  Currency_Nzd = 0;
  Currency_Usd = 1;
}

message ProductPricing {
  string                                        id                                             = 1;
  int32                                         index                                          = 2;
  ListingMetadata                               listingMetadata                                = 3;
  ProductPricingCadence                         purchaseCadence                                = 4;
  ProductPricingCadence                         bookingCadence                                 = 5;
  double                                        price                                          = 6;
  bool                                          isTaxInclusive                                 = 7;
  Currency                                      currency                                       = 8;
  repeated PaymentMethod                        acceptedBookingPaymentMethods                  = 9;
  int32                                         minDurationMinutes                             = 10;
  int32                                         maxDurationMinutes                             = 11;
  int32                                         maxAllowedResourcesLockTimePaidViaCard         = 12;
  int32                                         maxAllowedResourcesLockTimePaidViaBankTransfer = 13;
  int32                                         numberOfResourcesToBook                        = 14;
  ProductPricingBillingMode                     billingMode                                    = 15;
  bool                                          supportsSubscriptionAutoRenewal                = 16;
  ProductPricingCancellationPolicyType          cancellationPolicyType                         = 17;
  repeated ProductPricingCancellationRefundRule cancellationRefundRules                        = 18;
  repeated string                                availableDays                                 = 19;
  int32                                          requiredDaysPerWeek                           = 20;
}

message ProductPricingCancellationRefundRule {
  int32 minutesBefore    = 1;
  int32 refundPercentage = 2;
}

message ListingMetadata {
  string          about            = 1;
  string          title            = 2;
  string          subTitle         = 3;
  repeated string includedFeatures = 4;
}

enum ProductType {
  ProductType_Resource = 0;
  ProductType_Event    = 1;
}
