syntax = "proto3";
package organization;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Organization.V1.Value";

enum Type {
  OrganizationUpserted = 0;
  OrganizationDeleted = 1;
  InvitationToJoinOrganizationUpserted = 2;
  InvitationToJoinOrganizationDeleted = 3;
  OrganizationOfferingUpdated = 4;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data {
  oneof payload {
    Organization organization = 1;
    InvitationToJoinOrganization invitationToJoinOrganization = 2;
    Offering offering = 3;
  }
}

message Organization {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string name = 3;
  string about = 4;
  string logoUrl = 5;
  string website = 6;
  repeated OrganizationMember members = 7;
  Offering Offering = 8;
  repeated string azureTenantIds = 9;
  repeated Tag tags = 10;
}

enum Role {
  Owner = 0;
  Administrator = 1;
  Member = 2;
}

message OrganizationMember {
  string id = 1;
  string customerId = 2;
  Role role = 3;
  Status status = 4;
}

enum Status {
  Active = 0;
  Inactive = 1;
}

message Offering {
  string id = 1;
  string code = 2;
  google.protobuf.Timestamp start = 3;
  google.protobuf.Timestamp end = 4;
  bool autoRenew = 5;
  int32 unitPrice = 6;
  repeated string activeCustomerIds = 7;
  string organizationId = 8;
}

message Location { string id = 1; }

message InvitationToJoinOrganization {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string organizationId = 3;
  string invitedById = 4;
  string inviteeId = 5;
}

message Tag {
  string id = 1;
  string name = 2;
  string description = 3;
  string tagType = 4;
  string color = 5;
}
