syntax = "proto3";
package payment;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Payment.V1.Value";

enum Type {
  OrganizationPaymentMethodsUpdated = 0;
  CustomerPaymentMethodsUpdated = 1;
  OrganizationStripeConnectAccountUpserted = 2;
  OrganizationStripeConnectAccountDeleted = 3;
  BookingCheckoutSessionUpserted = 4;
  BookingCheckoutSessionDeleted = 5;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data {
  oneof payload {
    OrganizationPaymentMethod organizationPaymentMethod = 1;
    CustomerPaymentMethod customerPaymentMethod = 2;
    StripeConnectAccount stripeConnectAccount = 3;
    BookingCheckoutSessionDetails bookingCheckoutSession = 4;
  }
}

message OrganizationPaymentMethod {
  string organizationId = 1;
  bool hasAttachedPaymentMethod = 2;
}

message CustomerPaymentMethod {
  string customerId = 1;
  bool hasAttachedPaymentMethod = 2;
}

message StripeConnectAccount {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string organizationId = 3;
  string stripeAccountId = 4;
  string name = 5;
  bool chargesEnabled = 6;
  bool payoutsEnabled = 7;
  string type = 8;
  string country = 9;
  string defaultCurrency = 10;
  string businessType = 11;
  string companyName = 12;
  string url = 13;
  string supportUrl = 14;
  string contactEmail = 15;
  string contactPhone = 16;
  string capabilitiesTransfers = 17;
  string capabilitiesCardPayments = 18;
  string onboardingUrl = 19;
  bool onboardingCompleted = 20;
}

message BookingCheckoutSessionDetails {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string bookingId = 3;
  string checkoutUrl = 4;
  PaymentStatus paymentStatus = 5;
}

enum PaymentStatus {
  PaymentStatusNoPaymentRequired = 0;
  PaymentStatusPending = 1;
  PaymentStatusPaid = 2;
  PaymentStatusUnpaid = 3;
}