syntax = "proto3";
package payment;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Payment.V1.Value";

enum Type { 
  OrganizationPaymentMethodsUpdated = 0;
  OrganizationStripeConnectAccountUpserted = 1;
  OrganizationStripeConnectAccountDeleted = 2;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data {
  oneof payload {
    OrganizationPaymentMethod organizationPaymentMethod = 1;
    OrganizationStripeConnectAccount organizationStripeConnectAccount = 2;
  }
}

message OrganizationPaymentMethod {
  string organizationId = 1;
  bool hasAttachedPaymentMethod = 2;
}

message OrganizationStripeConnectAccount {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string organizationId = 3;
  string name = 4;
  bool chargesEnabled = 5;
  bool payoutsEnabled = 6;
  string type = 7;
  string country = 8;
  string defaultCurrency = 9;
  string businessType = 10;
  string companyName = 11;
  string email = 12;
  string phone = 13;
  string capabilitiesTransfers = 14;
  string capabilitiesCardPayments = 15;
  string onboardingUrl = 16;
  google.protobuf.Timestamp onboardingCompletedAt = 17;
  bool onboardingCompleted = 18;
}
