syntax = "proto3";
package slackinternal;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.SlackInternal.V1.Value";

enum Type {
  Type_SendWorkspaceLocationDailyUpdateMessage = 0;
  Type_UpdateWorkspaceMemberProfileStatus = 1;
  Type_DeactivateOrganizationMembersNotFoundOnSlack = 2;
  Type_SendWorkspaceTeamDailyUpdateMessage = 3;
}

message Event {
  Metadata metadata = 1;
  oneof payload {
    string workspaceId = 2;
    string locationId = 3;
    string workspaceMemberId = 4;
    string teamId = 5;
  }
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}
