syntax = "proto3";
package team;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Clients.Events.Skedular.Team.V1.Value";

enum Type {
  TeamUpserted = 0;
  TeamDeleted = 1;
  InvitationToJoinTeamUpserted = 2;
  InvitationToJoinTeamDeleted = 3;
}

message Event {
  Metadata metadata = 1;
  Data data = 2;
}

message Metadata {
  string id = 1;
  string domainSource = 2;
  string appSource = 3;
  Type type = 4;
  google.protobuf.Timestamp time = 5;
  string correlationId = 6;
}

message Data { 
  oneof payload {
    Team team = 1;
    InvitationToJoinTeam invitationToJoinTeam = 2;
  }
}

message Team {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string name = 3;
  string about = 4;
  repeated Member members = 5;
  string organizationId = 6;
  string timezone = 7;
  string primaryLocationId = 8;
}

enum MembershipType {
  MembershipTypeOwner = 0;
  MembershipTypeAdministrator = 1;
  MembershipTypeMember = 2;
}
 
message Member {
  string id = 1;
  MembershipType membershipType = 2;
  string customerId = 3;
  OrganizationMember organizationMember = 4;
  Status status = 5;
}

enum Status {
  Active = 0;
  Inactive = 1;
}

message OrganizationMember {
  string customerId = 1;
  string organizationMemberId = 2;
  string organizationId = 3;
}

message InvitationToJoinTeam {
  string id = 1;
  google.protobuf.Timestamp deletedAt = 2;
  string teamId = 3;
  string invitedById = 4;
  string inviteeId = 5;
}
