scalar DateTime

schema {
    query: Query
    mutation: Mutation
}

type Version {
    major: Int!
    minor: Int!
    build: Int!
    revision: Int!
}

type Query {
    billingVersion: Version!
    billingCustomerRecordSynced: Boolean!
    organizationCurrentOfferingCharges(
        organizationId: String!
    ): [OrganizationCurrentOfferingChargesDetails!]
    organizationBillingInfo(organizationId: String!): OrganizationBillingInfo
}

type Mutation {
    setOrganizationBillingInfo(
        input: SetOrganizationBillingInfoInput!
    ): OrganizationBillingInfoPayload
}

input SetOrganizationBillingInfoInput {
    clientMutationId: String
    organizationId: String!
    email: String
    addressLine1: String
    addressLine2: String
    suburb: String
    city: String
    province: String
    zipcode: String
    country: String
}

type OrganizationCurrentOfferingChargesDetails {
    offeringName: String!
    start: DateTime!
    end: DateTime!
    totalNumberOfActiveCustomers: Int!
    unitPrice: Int!
    totalCost: Int!
}

type OrganizationBillingInfoPayload {
    clientMutationId: String
    organizationBillingInfo: OrganizationBillingInfo!
}

type OrganizationBillingInfo {
    organizationId: ID!
    email: String
    addressLine1: String
    addressLine2: String
    suburb: String
    city: String
    province: String
    zipcode: String
    country: String
}
