<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>WebScrapper</AssemblyName>
        <AssemblyTitle>WebScrapper</AssemblyTitle>
        <Product>Skedular WebScrapper</Product>
        <Description>Skedular WebScrapper</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GitRepositoryRoot>$(SolutionDir)</GitRepositoryRoot>
        <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>
        <UseFullSemVerForNuGet>true</UseFullSemVerForNuGet>
        <UpdateVersionProperties>true</UpdateVersionProperties>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WebScrapper</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools -->
        <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- Build Tools / gRPC (Client) -->
        <PackageReference Include="Grpc.Tools" Version="2.80.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Protobuf Include="../../api-definitions/grpc/skedular/location_v1.proto" GrpcServices="Client"/>
        <Protobuf Include="../../api-definitions/grpc/skedular/organization_v1.proto" GrpcServices="Client"/>
    </ItemGroup>

    <ItemGroup>
        <!-- CLI / Command Line -->
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>

        <!-- Data Parsing -->
        <PackageReference Include="CsvHelper" Version="33.1.0"/>

        <!-- Browser Automation -->
        <PackageReference Include="Microsoft.Playwright" Version="1.59.0"/>

        <!-- Analyzers -->
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Api.Shared.Clients/Api.Shared.Clients.csproj"/>
        <ProjectReference Include="../Api.Shared.Services/Api.Shared.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
