syntax = "proto3";
package customer;

option csharp_namespace = "Api.Shared.Grpc.Skedular.Customer.Admin.V1";

import "customer/customer_core_v1.proto";

service CustomerAdminService {
  rpc Admin_Get (Admin_GetInput) returns (Customer);
  rpc Admin_Add (Admin_AddInput) returns (Customer);
  rpc Admin_AddIdentity (Admin_AddIdentityInput) returns (Customer);
  rpc Admin_UpdateIdentity (Admin_UpdateIdentityInput) returns (Customer);
  rpc Admin_AnyCustomerExistByVerifiableToken (Admin_AnyCustomerExistByVerifiableTokenInput) returns (AnyCustomerExistByVerifiableTokenResponse);
  rpc Admin_AnyCustomerExistByEmail (Admin_AnyCustomerExistByEmailInput) returns (AnyCustomerExistByEmailResponse);
  rpc Admin_SetDefaultOrganization (Admin_SetDefaultOrganizationInput) returns (Customer);
  rpc Admin_AddPreferredLocation (Admin_AddPreferredLocationInput) returns (Customer);
}

message AnyCustomerExistByVerifiableTokenResponse {
  bool     exist    = 1;
  Customer customer = 2;
}

message AnyCustomerExistByEmailResponse {
  bool     exist    = 1;
  Customer customer = 2;
}

message Admin_GetInput {
  string customerId = 1;
}

message Admin_AnyCustomerExistByVerifiableTokenInput {
  string verifiableToken = 1;
}

message Admin_AnyCustomerExistByEmailInput {
  string email = 1;
}

message Admin_AddInput {
  string                        id                            = 1;
  repeated Identity             identities                    = 2;
  string                        designation                   = 3;
  string                        title                         = 4;
  string                        name                          = 5;
  string                        givenName                     = 6;
  string                        middleName                    = 7;
  string                        familyName                    = 8;
  string                        photoUrl                      = 9;
  string                        photoUrl24                    = 10;
  string                        photoUrl32                    = 11;
  string                        photoUrl48                    = 12;
  string                        photoUrl72                    = 13;
  string                        photoUrl192                   = 14;
  string                        photoUrl512                   = 15;
  string                        timezone                      = 16;
  string                        locale                        = 17;
  string                        defaultOrganizationId         = 18;
  repeated Location             preferredLocations            = 19;
  repeated Resource             preferredResources            = 20;
  repeated OrganizationTag      preferredOrganizationTags     = 21;
  string                        phoneNumber                   = 22;
  bool                          isOnboardingDone              = 23;
  PersonalInformationVisibility personalInformationVisibility = 24;
  CustomerType                  type                          = 25;
}

message Admin_AddIdentityInput {
  string customerId    = 1;
  string id            = 2;
  string email         = 3;
  bool   emailVerified = 4;
}

message Admin_UpdateIdentityInput {
  string customerId    = 1;
  string id            = 2;
  string email         = 3;
  bool   emailVerified = 4;
  repeated IdentityPatchField fieldsToUpdate = 5;
}

enum IdentityPatchField {
  IdentityPatchField_Email         = 0;
  IdentityPatchField_EmailVerified = 1;
}

message Admin_SetDefaultOrganizationInput {
  string customerId     = 1;
  string organizationId = 2;
}

message Admin_AddPreferredLocationInput {
  string customerId = 1;
  string locationId = 2;
}
