using Enterprise.Shared.Configurations;
using Enterprise.Shared.HealthCheck;
using Microsoft.Extensions.Hosting;
using Projects;

await EnvironmentHelper.LoadEnvFileAsync(Path.Join(Directory.GetCurrentDirectory(), "..", "..", ".env"), CancellationToken.None);
await EnvironmentHelper.LoadEnvFileAsync(Path.Join(Directory.GetCurrentDirectory(), "..", "..", "..", "..", "..", ".env"), CancellationToken.None);

var builder = DistributedApplication.CreateBuilder(args);
builder.AddGraphQLOrchestrator();
var kafka = builder.AddKafka("kafka").WithKafkaUI();
var postgres = builder.AddPostgres("postgres").WithImage("postgis/postgis", "16-3.4").WithPgAdmin();
var temporal = builder.AddTemporalServerContainer("temporal");
#pragma warning disable ASPIRECERTIFICATES001
var redis = builder.AddRedis("redis").WithoutHttpsCertificate();
#pragma warning restore ASPIRECERTIFICATES001

var sharedInfrastructure = builder
    .AddProject<Infrastructure_Shared>("infrastructureshared")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WaitFor(kafka);

/******************************************************************************************************************************/
var bookingDatabase = postgres.AddDatabase("bookingdb");
var bookingInfrastructure = builder
    .AddProject<Booking_Infrastructure>("bookinginfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(bookingDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(bookingDatabase);

var bookingApi = builder
    .AddProject<Booking_Api>("bookingapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(bookingDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(bookingDatabase)
    .WaitForCompletion(bookingInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Booking_Processors>("bookingprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(bookingDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(bookingDatabase)
    .WaitForCompletion(bookingInfrastructure);

builder
    .AddProject<Booking_Jobs>("bookingjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(bookingDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(bookingDatabase)
    .WaitForCompletion(bookingInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var coreDatabase = postgres.AddDatabase("coredb");
var coreInfrastructure = builder
    .AddProject<Core_Infrastructure>("coreinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(coreDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(coreDatabase);

var coreApi = builder
    .AddProject<Core_Api>("coreapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(coreDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(coreDatabase)
    .WaitForCompletion(coreInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Core_Processors>("coreprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(coreDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(coreDatabase)
    .WaitForCompletion(coreInfrastructure);

builder
    .AddProject<Core_Jobs>("corejobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(coreDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(coreDatabase)
    .WaitForCompletion(coreInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var customerDatabase = postgres.AddDatabase("customerdb");
var customerInfrastructure = builder
    .AddProject<Customer_Infrastructure>("customerinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(customerDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(customerDatabase);

var customerApi = builder
    .AddProject<Customer_Api>("customerapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(customerDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(customerDatabase)
    .WaitForCompletion(customerInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Customer_Processors>("customerprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(customerDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(customerDatabase)
    .WaitForCompletion(customerInfrastructure);

builder
    .AddProject<Customer_Jobs>("customerjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(customerDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(customerDatabase)
    .WaitForCompletion(customerInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var locationDatabase = postgres.AddDatabase("locationdb");
var locationInfrastructure = builder
    .AddProject<Location_Infrastructure>("locationinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(locationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(locationDatabase);

var locationApi = builder
    .AddProject<Location_Api>("locationapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(locationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(locationDatabase)
    .WaitForCompletion(locationInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Location_Processors>("locationprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(locationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(locationDatabase)
    .WaitForCompletion(locationInfrastructure);

builder
    .AddProject<Location_Jobs>("locationjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(locationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(locationDatabase)
    .WaitForCompletion(locationInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var marketplaceDatabase = postgres.AddDatabase("marketplacedb");
var marketplaceInfrastructure = builder
    .AddProject<Marketplace_Infrastructure>("marketplaceinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(marketplaceDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(marketplaceDatabase);

var marketplaceApi = builder
    .AddProject<Marketplace_Api>("marketplaceapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(marketplaceDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(marketplaceDatabase)
    .WaitForCompletion(marketplaceInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Marketplace_Processors>("marketplaceprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(marketplaceDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(marketplaceDatabase)
    .WaitForCompletion(marketplaceInfrastructure);

builder
    .AddProject<Marketplace_Jobs>("marketplacejobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(marketplaceDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(marketplaceDatabase)
    .WaitForCompletion(marketplaceInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var msteamsDatabase = postgres.AddDatabase("msteamsdb");
var msteamsInfrastructure = builder
    .AddProject<MsTeams_Infrastructure>("msteamsinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(msteamsDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(msteamsDatabase);

var msteamsApi = builder
    .AddProject<MsTeams_Api>("msteamsapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(msteamsDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(msteamsDatabase)
    .WaitForCompletion(msteamsInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<MsTeams_Processors>("msteamsprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(msteamsDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(msteamsDatabase)
    .WaitForCompletion(msteamsInfrastructure);

builder
    .AddProject<MsTeams_Jobs>("msteamsjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(msteamsDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(msteamsDatabase)
    .WaitForCompletion(msteamsInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var organizationDatabase = postgres.AddDatabase("organizationdb");
var organizationInfrastructure = builder
    .AddProject<Organization_Infrastructure>("organizationinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(organizationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(organizationDatabase);

var organizationApi = builder
    .AddProject<Organization_Api>("organizationapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(organizationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(organizationDatabase)
    .WaitForCompletion(organizationInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Organization_Processors>("organizationprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(organizationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(organizationDatabase)
    .WaitForCompletion(organizationInfrastructure);

builder
    .AddProject<Organization_Jobs>("organizationjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(organizationDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(organizationDatabase)
    .WaitForCompletion(organizationInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var slackDatabase = postgres.AddDatabase("slackdb");
var slackInfrastructure = builder
    .AddProject<Slack_Infrastructure>("slackinfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(slackDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(slackDatabase);

var slackApi = builder
    .AddProject<Slack_Api>("slackapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(slackDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(slackDatabase)
    .WaitForCompletion(slackInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Slack_Processors>("slackprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(slackDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(slackDatabase)
    .WaitForCompletion(slackInfrastructure);

builder
    .AddProject<Slack_Jobs>("slackjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(slackDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(slackDatabase)
    .WaitForCompletion(slackInfrastructure);
/******************************************************************************************************************************/

/******************************************************************************************************************************/
var teamDatabase = postgres.AddDatabase("teamdb");
var teamInfrastructure = builder
    .AddProject<Team_Infrastructure>("teaminfrastructure")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(teamDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(sharedInfrastructure)
    .WaitFor(teamDatabase);

var teamApi = builder
    .AddProject<Team_Api>("teamapi")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(teamDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(teamDatabase)
    .WaitForCompletion(teamInfrastructure)
    .WithGraphQLSchemaEndpoint();

builder
    .AddProject<Team_Processors>("teamprocessors")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(teamDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(teamDatabase)
    .WaitForCompletion(teamInfrastructure);

builder
    .AddProject<Team_Jobs>("teamjobs")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("Booking__GrpcUrl", "http://bookingapi")
    .WithEnvironment("Core__GrpcUrl", "http://coreapi")
    .WithEnvironment("Customer__GrpcUrl", "http://customerapi")
    .WithEnvironment("Location__GrpcUrl", "http://locationapi")
    .WithEnvironment("Marketplace__GrpcUrl", "http://marketplaceapi")
    .WithEnvironment("MsTeams__GrpcUrl", "http://msteamsapi")
    .WithEnvironment("Organization__GrpcUrl", "http://organizationapi")
    .WithEnvironment("Slack__GrpcUrl", "http://slackapi")
    .WithEnvironment("Team__GrpcUrl", "http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithReference(kafka)
    .WithReference(temporal)
    .WithReference(redis)
    .WithReference(teamDatabase)
    .WaitFor(kafka)
    .WaitFor(temporal)
    .WaitFor(redis)
    .WaitFor(teamDatabase)
    .WaitForCompletion(teamInfrastructure);
/******************************************************************************************************************************/

_ = builder
    .AddProject<Gateway>("gateway")
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", Environments.Development)
    .WithEnvironment("ReverseProxy__Clusters__booking__Destinations__destination1__Address", "https+http://bookingapi")
    .WithEnvironment("ReverseProxy__Clusters__core__Destinations__destination1__Address", "https+http://coreapi")
    .WithEnvironment("ReverseProxy__Clusters__customer__Destinations__destination1__Address", "https+http://customerapi")
    .WithEnvironment("ReverseProxy__Clusters__location__Destinations__destination1__Address", "https+http://locationapi")
    .WithEnvironment("ReverseProxy__Clusters__marketplace__Destinations__destination1__Address", "https+http://marketplaceapi")
    .WithEnvironment("ReverseProxy__Clusters__msteams__Destinations__destination1__Address", "https+http://msteamsapi")
    .WithEnvironment("ReverseProxy__Clusters__organization__Destinations__destination1__Address", "https+http://organizationapi")
    .WithEnvironment("ReverseProxy__Clusters__slack__Destinations__destination1__Address", "https+http://slackapi")
    .WithEnvironment("ReverseProxy__Clusters__team__Destinations__destination1__Address", "https+http://teamapi")
    .WithHttpHealthCheck(Constants.ReadinessPath)
    .WithGraphQLSchemaComposition()
    .WithReference(bookingApi)
    .WaitFor(bookingApi)
    .WithReference(coreApi)
    .WaitFor(coreApi)
    .WithReference(customerApi)
    .WaitFor(customerApi)
    .WithReference(locationApi)
    .WaitFor(locationApi)
    .WithReference(marketplaceApi)
    .WaitFor(marketplaceApi)
    .WithReference(msteamsApi)
    .WaitFor(msteamsApi)
    .WithReference(organizationApi)
    .WaitFor(organizationApi)
    .WithReference(slackApi)
    .WaitFor(slackApi)
    .WithReference(teamApi)
    .WaitFor(teamApi);

await builder.Build().RunAsync();
