<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Api.Shared</AssemblyName>
        <AssemblyTitle>Api.Shared</AssemblyTitle>
        <Product>Skedular Api.Shared</Product>
        <Description>Skedular Api.Shared</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GitRepositoryRoot>$(SolutionDir)</GitRepositoryRoot>
        <WriteVersionInfoToBuildLog>true</WriteVersionInfoToBuildLog>
        <UseFullSemVerForNuGet>true</UseFullSemVerForNuGet>
        <UpdateVersionProperties>true</UpdateVersionProperties>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Build Tools -->
        <PackageReference Include="GitVersion.MsBuild" Version="6.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.34.1"/>
    </ItemGroup>
</Project>
