schema {
  query: Query
  mutation: Mutation
}

type CustomerConnection {
  pageInfo: PageInfo!
  edges: [CustomerEdge!]!
  totalCount: Int
}

type CustomerDeskDetails {
  uniqueId: ID!
  name: String
}

type CustomerDetails {
  createdAt: DateTime!
  email: String
  identities: [CustomerEmail!]!
  designation: String
  title: String
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
  timezone: String
  locale: String
  phoneNumber: String
  isOrganizationOnboardingDone: Boolean!
  isLocationOnboardingDone: Boolean!
  isTeamOnboardingDone: Boolean!
  isDefaultOrganizationOnboardingDone: Boolean!
  isPreferredLocationOnboardingDone: Boolean!
  isPreferredZoneOnboardingDone: Boolean!
  isPreferredDeskOnboardingDone: Boolean!
  isPreferredRoomOnboardingDone: Boolean!
  defaultOrganization: CustomerOrganizationDetails
  preferredLocations: [CustomerLocationDetails!]!
  preferredTeams: [CustomerTeamDetails!]!
  preferredZones: [CustomerOrganizationTagDetails!]!
  preferredCustomTags: [CustomerOrganizationTagDetails!]!
  preferredLocationResources: [CustomerLocationResourceDetails!]!
  preferredDesks: [CustomerDeskDetails!]!
  preferredRooms: [CustomerRoomDetails!]!
  id: ID!
}

type CustomerEdge {
  node: CustomerDetails!
  cursor: String!
}

type CustomerEmail {
  email: String
  verified: Boolean!
  id: ID!
}

type CustomerLocationDetails {
  uniqueId: ID!
  name: String
  organization: CustomerOrganizationDetails
}

type CustomerLocationResourceDetails {
  uniqueId: ID!
  name: String
  organizationResourceType: Customer_OrganizationResourceTypeDetails!
}

type CustomerOrganizationDetails {
  uniqueId: ID!
  name: String
  logoUrl: String
}

type CustomerOrganizationTagDetails {
  uniqueId: ID!
  name: String
  color: String
}

type CustomerPayload {
  clientMutationId: String
  customer: CustomerDetails!
}

type CustomerRoomDetails {
  uniqueId: ID!
  name: String
}

type CustomerTeamDetails {
  uniqueId: ID!
  name: String
  organization: CustomerOrganizationDetails
}

type Customer_OrganizationResourceTypeDetails {
  uniqueId: ID!
  name: String
  color: String
  systemType: OrganizationResourceTypeSystemType
}

type Mutation {
  completeOrganizationOnboarding(input: CompleteOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeLocationOnboarding(input: CompleteLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeTeamOnboarding(input: CompleteTeamOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeDefaultOrganizationOnboarding(input: CompleteDefaultOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredLocationOnboarding(input: CompletePreferredLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredZoneOnboarding(input: CompletePreferredZoneOnboardingInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredLocation(input: AddCustomerPreferredLocationInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredLocation(input: RemoveCustomerPreferredLocationInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredTeam(input: AddCustomerPreferredTeamInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredTeam(input: RemoveCustomerPreferredTeamInput!): CustomerPayload @cost(weight: "10")
  setCustomerDefaultOrganization(input: SetCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  clearCustomerDefaultOrganization(input: ClearCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  submitCustomerFeedback(input: SubmitCustomerFeedbackInput!): SubmitCustomerFeedbackPayload @cost(weight: "10")
  updateMyCustomerDetails(input: UpdateMyCustomerDetailsInput!): CustomerPayload @cost(weight: "10")
  updateCustomerDetails(input: UpdateCustomerDetailsInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredOrganizationTag(input: AddCustomerPreferredOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredOrganizationTag(input: RemoveCustomerPreferredOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  completePreferredDeskOnboarding(input: CompletePreferredDeskOnboardingInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredDesk(input: AddCustomerPreferredDeskInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredDesk(input: RemoveCustomerPreferredDeskInput!): CustomerPayload @cost(weight: "10")
  completePreferredRoomOnboarding(input: CompletePreferredRoomOnboardingInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredRoom(input: AddCustomerPreferredRoomInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredRoom(input: RemoveCustomerPreferredRoomInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredLocationResource(input: AddCustomerPreferredLocationResourceInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredLocationResource(input: RemoveCustomerPreferredLocationResourceInput!): CustomerPayload @cost(weight: "10")
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  customerVersion: Version!
  me: CustomerDetails @cost(weight: "10")
  customer(id: String!): CustomerDetails @cost(weight: "10")
  customersByPreferredLocation(after: String first: Int before: String last: Int where: CustomersByPreferredLocationWhereInput! orderBy: [CustomerOrderInput!]): CustomerConnection @cost(weight: "10")
}

type SubmitCustomerFeedbackPayload {
  id: ID!
  clientMutationId: String
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddCustomerPreferredDeskInput {
  clientMutationId: String
  deskId: String!
}

input AddCustomerPreferredLocationInput {
  clientMutationId: String
  locationId: String!
}

input AddCustomerPreferredLocationResourceInput {
  clientMutationId: String
  locationResourceId: String!
}

input AddCustomerPreferredOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input AddCustomerPreferredRoomInput {
  clientMutationId: String
  roomId: String!
}

input AddCustomerPreferredTeamInput {
  clientMutationId: String
  teamId: String!
}

input ClearCustomerDefaultOrganizationInput {
  clientMutationId: String
}

input CompleteDefaultOrganizationOnboardingInput {
  clientMutationId: String
}

input CompleteLocationOnboardingInput {
  clientMutationId: String
}

input CompleteOrganizationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredDeskOnboardingInput {
  clientMutationId: String
}

input CompletePreferredLocationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredRoomOnboardingInput {
  clientMutationId: String
}

input CompletePreferredZoneOnboardingInput {
  clientMutationId: String
}

input CompleteTeamOnboardingInput {
  clientMutationId: String
}

input CustomerOrderInput {
  direction: OrderDirection!
  field: CustomerOrderField!
}

input CustomersByPreferredLocationWhereInput {
  locationId: String!
  nameContains: String
}

input RemoveCustomerPreferredDeskInput {
  clientMutationId: String
  deskId: String!
}

input RemoveCustomerPreferredLocationInput {
  clientMutationId: String
  locationId: String!
}

input RemoveCustomerPreferredLocationResourceInput {
  clientMutationId: String
  locationResourceId: String!
}

input RemoveCustomerPreferredOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input RemoveCustomerPreferredRoomInput {
  clientMutationId: String
  roomId: String!
}

input RemoveCustomerPreferredTeamInput {
  clientMutationId: String
  teamId: String!
}

input SetCustomerDefaultOrganizationInput {
  clientMutationId: String
  organizationId: String!
}

input SubmitCustomerFeedbackInput {
  clientMutationId: String
  id: String
  feedbackContent: String!
  channel: FeedbackChannelType!
}

input UpdateCustomerDetailsInput {
  clientMutationId: String
  id: String!
  timezone: String
  designation: String
  title: String
  name: String
  givenName: String
  middleName: String
  familyName: String
  phoneNumber: String
}

input UpdateMyCustomerDetailsInput {
  clientMutationId: String
  timezone: String
  designation: String
  title: String
  name: String
  givenName: String
  middleName: String
  familyName: String
  phoneNumber: String
}

enum CustomerOrderField {
  Designation
  Title
  Name
  GivenName
  MiddleName
  FamilyName
  Timezone
  Locale
  PhoneNumber
}

enum FeedbackChannelType {
  Web
  Slack
  MsTeams
}

enum OrderDirection {
  Ascending
  Descending
}

enum OrganizationResourceTypeSystemType {
  Desk
  Room
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")