<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0"/>
        <PackageReference Include="AWSSDK.SimpleEmail" Version="3.7.402.52"/>
        <PackageReference Include="Confluent.Kafka" Version="2.8.0"/>
        <PackageReference Include="Confluent.SchemaRegistry" Version="2.8.0"/>
        <PackageReference Include="CountryData" Version="6.10.0"/>
        <PackageReference Include="EmailValidation" Version="1.3.0"/>
        <PackageReference Include="Flurl.Http" Version="4.0.2"/>
        <PackageReference Include="Google.Apis.Auth" Version="1.69.0"/>
        <PackageReference Include="IdGen" Version="3.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" Version="9.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.2"/>
        <PackageReference Include="Microsoft.Graph" Version="5.72.0"/>
        <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="3.8.0"/>
        <PackageReference Include="Nanoid" Version="3.1.0"/>
        <PackageReference Include="NSwag.AspNetCore" Version="14.2.0"/>
        <PackageReference Include="Polly" Version="8.5.2"/>
        <PackageReference Include="Scrutor" Version="6.0.1"/>
        <PackageReference Include="StackExchange.Redis" Version="2.8.31"/>
        <PackageReference Include="Stripe.net" Version="47.4.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1"/>
        <PackageReference Include="WorkOS.net" Version="2.6.0"/>

        <PackageReference Include="Google.Protobuf" Version="3.30.0"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.67.0"/>
        <PackageReference Include="Grpc.Net.Client" Version="2.67.0"/>

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
        <PackageReference Include="Npgsql.OpenTelemetry" Version="9.0.3"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="HotChocolate" Version="15.0.3"/>
        <PackageReference Include="HotChocolate.AspNetCore" Version="15.0.3"/>
        <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="15.0.3"/>
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="15.0.3"/>
        <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.0.3"/>
        <PackageReference Include="HotChocolate.Diagnostics" Version="15.0.3"/>

        <PackageReference Include="OpenTelemetry.Api" Version="1.11.2"/>
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.11.2"/>
        <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1"/>
        <PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.11.2"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.11.0-beta.2"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.11.0-beta.2"/>

        <PackageReference Include="Quartz" Version="3.14.0"/>
        <PackageReference Include="Quartz.AspNetCore" Version="3.14.0"/>
        <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.14.0"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0"/>
        <PackageReference Include="Quartz.OpenTelemetry.Instrumentation" Version="3.14.0"/>
        <PackageReference Include="Quartz.Serialization.Json" Version="3.14.0"/>

        <PackageReference Include="Serilog" Version="4.2.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Serilog.Enrichers.Sensitive" Version="1.7.3"/>
        <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0"/>
        <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1"/>
        <PackageReference Include="System.Reactive" Version="6.0.1"/>

        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Api.Shared\Api.Shared.csproj"/>
    </ItemGroup>

</Project>
