schema {
  query: Query
  mutation: Mutation
}

type CurrencyDetails {
  type: Currency!
  name: String!
}

type Marketplace_OrganizationDetails {
  uniqueId: ID!
}

type Marketplace_OrganizationTagDetails {
  uniqueId: ID!
  name: String
  tagType: String
  color: String
}

type Mutation {
  addProduct(input: AddProductInput!): ProductPayload @cost(weight: "10")
  updateProduct(input: UpdateProductInput!): ProductPayload @cost(weight: "10")
  deleteProducts(input: DeleteProductsInput!): ProductsPayload @cost(weight: "10")
  activateProducts(input: ActivateProductsInput!): ProductsPayload @cost(weight: "10")
  deactivateProducts(input: DeactivateProductsInput!): ProductsPayload @cost(weight: "10")
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type PriceUnitDetails {
  type: PriceUnit!
  name: String!
}

type ProductConnection {
  pageInfo: PageInfo!
  edges: [ProductEdge!]!
  totalCount: Int
}

type ProductDetails {
  inactive: Boolean!
  name: String!
  description: String
  price: String!
  priceToDisplay: String!
  currencyToDisplay: String!
  priceUnit: PriceUnitDetails!
  currency: CurrencyDetails!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  productTags: [Marketplace_OrganizationTagDetails!]!
  locationTags: [Marketplace_OrganizationTagDetails!]!
  latestProductVersionId: String!
  organization: Marketplace_OrganizationDetails!
  id: ID!
}

type ProductEdge {
  node: ProductDetails!
  cursor: String!
}

type ProductPayload {
  clientMutationId: String
  product: ProductDetails!
}

type ProductsPayload {
  clientMutationId: String
  products: [ProductDetails!]!
}

type Query {
  marketplaceVersion: Version!
  marketplaceCustomerRecordSynced: Boolean! @cost(weight: "10")
  currencies: [CurrencyDetails!]!
  priceUnits: [PriceUnitDetails!]!
  product(id: String!): ProductDetails @cost(weight: "10")
  products(after: String first: Int before: String last: Int where: ProductWhereInput! orderBy: [ProductOrderInput!]): ProductConnection! @cost(weight: "10")
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input ActivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input AddProductInput {
  clientMutationId: String
  id: String
  organizationId: String!
  name: String!
  description: String
  price: String!
  priceUnit: PriceUnit!
  currency: Currency!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  productTagIds: [String!]!
  locationTagIds: [String!]!
}

input DeactivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input ProductOrderInput {
  direction: OrderDirection!
  field: ProductOrderField!
}

input ProductWhereInput {
  organizationIds: [String!]
  productIds: [String!]
  nameContains: String
  includeInactive: Boolean!
}

input UpdateProductInput {
  clientMutationId: String
  id: String!
  organizationId: String!
  name: String!
  description: String
  price: String!
  priceUnit: PriceUnit!
  currency: Currency!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  productTagIds: [String!]!
  locationTagIds: [String!]!
}

enum Currency {
  NZD
  USD
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

enum PriceUnit {
  PER_MINUTE
  PER_HOUR
  PER_USE
}

enum ProductOrderField {
  NAME
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION