syntax = "proto3";
package organization;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Services.Grpc.UnityHub.Organization.V1";

service OrganizationService {
    rpc Admin_Add (Admin_AddInput) returns (Organization);
    rpc Admin_UpdateMembers (Admin_UpdateMembersInput) returns (Organization);
    rpc Admin_AddMember (Admin_AddMemberInput) returns (Organization);

    rpc GetVersion (VersionInput) returns (Version);
    rpc GetActiveOrganizationTermsOfUse (GetActiveOrganizationTermsOfUseInput) returns (TermsOfUse);
    rpc Get (GetInput) returns (Organization);
    rpc GetPaginatedMembers (GetPaginatedMembersInput) returns (MemberConnection);
    rpc GetPermissions (GetPermissionsInput) returns (Permissions);
}

message VersionInput {
}

message Version {
    int32 major = 1;
    int32 minor = 2;
    int32 build = 3;
    int32 revision = 4;
}

enum OrderDirection {
    Ascending = 0;
    Descending = 1;
}

message PageInfo {
    bool hasNextPage = 1;
    bool hasPreviousPage =2;
    string startCursor =3;
    string endCursor =4;
}

message GetActiveOrganizationTermsOfUseInput {
}

message TermsOfUse {
    string id = 1;
    string terms = 2;
}

message Admin_AddInput {
    string id = 1;
    string name = 2;
    string about = 3;
    string logoUrl = 4;
    string website = 5;
    bool agreedToTermsOfUse = 6;
    string termsOfUseId = 7;
    repeated string industrySubCategoryIds = 8;
    string offeringCode = 9;
}

message Organization {
    string id = 1;
    string name = 2;
    string about = 3;
    string logoUrl = 4;
    string website = 5;
    bool agreedToTermsOfUse = 6;
    string termsOfUseId = 7;
    repeated IndustrySubCategory industrySubCategories = 8;
    repeated Member members = 9;
    Offering Offering = 10;
    bool hasAttachedPaymentMethod = 11;
    bool hasFutureBooking = 12;
}

message IndustrySubCategory {
    string id = 1;
    string name = 2;
    string mainCategoryName = 3;
}

message Offering {
    string id = 1;
    string code = 2;
    google.protobuf.Timestamp start = 3;
    google.protobuf.Timestamp end = 4;
    bool autoRenew = 5;
    int32 unitPrice = 6;
    repeated string activeCustomerIds = 7;
    string organizationId = 8;
}

message GetInput {
    string id = 1;
}

message Admin_UpdateMembersInput {
    string id = 1;
    repeated Member members = 2;
}

enum MembershipType {
    MembershipTypeOwner = 0;
    MembershipTypeAdministrator = 1;
    MembershipTypeMember = 2;
}

message Member {
    string id = 1;
    Customer customer = 2;
    MembershipType membershipType = 3;
    bool isOrganizationOnboardingDone = 4;
}

message Admin_AddMemberInput {
    string id = 1;
    Member member = 2;
}

message GetPaginatedMembersInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    MemberWhereInput where = 5;
    repeated MemberOrderInput orderBy = 6;
}

message MemberWhereInput {
    string organizationId  = 1;
    string nameContains  = 2;
}

message MemberOrderInput {
    OrderDirection direction = 1;
    MemberOrderField field = 2;
}

enum MemberOrderField {
    Membership = 0;
    Name= 1;
    GivenName= 2;
    MiddleName= 3;
    FamilyName= 4;
}

message MemberConnection {
    PageInfo pageInfo = 1;
    repeated MemberEdge edges = 2;
    int32 totalCount = 3;
}

message MemberEdge {
    Member node = 1;
    string cursor = 2;
}


message Customer {
    string id = 1;
    string name = 2;
    string givenName = 3;
    string middleName = 4;
    string familyName = 5;
    string photoUrl = 6;
    string photoUrl24 = 7;
    string photoUrl32 = 8;
    string photoUrl48 = 9;
    string photoUrl72 = 10;
    string photoUrl192 = 11;
    string photoUrl512 = 12;
    repeated Identity identities = 13;
}

message Identity {
    string id = 1;
    string email = 2;
    bool emailVerified = 3;
}

message GetPermissionsInput {
    string id = 1;
}

message Permissions {
    bool canView = 1;
    bool canModify = 2;
    bool canDelete = 3;
    bool canInvitePeople = 4;
    bool canCancelPeopleExistingInvitations = 5;
    bool canViewAnalytics = 6;
}
