schema {
  query: Query
  mutation: Mutation
}

type CustomerBillingContactDetails {
  companyName: String
  email: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
  id: ID!
}

type Mutation {
  updateMyBillingContactDetails(input: UpdateMyBillingContactDetailsInput!): MyBillingContactDetailsPayload @cost(weight: "10")
}

type MyBillingContactDetailsPayload {
  clientMutationId: String
  customerBillingContactDetails: CustomerBillingContactDetails!
}

type Query {
  billingVersion: Version!
  billingCustomerRecordSynced: Boolean! @cost(weight: "10")
  myBillingContactDetails: CustomerBillingContactDetails! @cost(weight: "10")
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input UpdateMyBillingContactDetailsInput {
  clientMutationId: String
  companyName: String
  email: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION