schema {
  query: Query
  mutation: Mutation
}

type AcceptInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type AcceptInvitationToJoinTeamPayload {
  clientMutationId: String
}

type AddCustomerPaymentMethodIntentPayload {
  clientMutationId: String
  clientSecret: String!
  publishedKeys: String!
}

type AddOrganizationPaymentMethodIntentPayload {
  clientMutationId: String
  clientSecret: String!
  publishedKeys: String!
}

type BookingCheckoutSessionDetails {
  amountTotal: String
  amountTotalToDisplay: String!
  checkoutUrl: String!
  currency: String
  currencyToDisplay: String!
  paymentStatus: PaymentStatus!
  uniqueId: ID!
}

type BookingConnection {
  edges: [BookingEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type BookingDetails {
  bookedOnMarketplace: Boolean!
  bookingCheckoutSession: BookingCheckoutSessionDetails
  bookingCheckoutSessionExpiry: DateTime!
  createdByCustomer: Booking_CustomerDetails
  deletedByCustomer: Booking_CustomerDetails
  from: DateTime!
  id: ID!
  involvedCustomers: [Booking_CustomerDetails!]!
  involvedLocations: [Booking_LocationDetails!]!
  involvedOrganizations: [Booking_OrganizationDetails!]!
  involvedTeams: [Booking_TeamDetails!]!
  isPaymentRequired: Boolean!
  lastModifiedByCustomer: Booking_CustomerDetails
  lineItems: [LineItemDetails!]!
  notes: String
  paidByCustomer: Booking_CustomerDetails
  paidByOrganization: Booking_OrganizationDetails
  resources: [BookingResourceDetails!]!
  status: BookingStatusDetails!
  type: BookingTypeDetails!
  until: DateTime!
}

type BookingEdge {
  cursor: String!
  node: BookingDetails!
}

type BookingPayload {
  booking: BookingDetails!
  clientMutationId: String
}

type BookingResourceDetails {
  capacity: Int!
  color: String
  customers: [Booking_CustomerDetails!]!
  customTags: [Booking_OrganizationCustomTagDetails!]!
  inactive: Boolean!
  location: Booking_LocationDetails
  name: String!
  requireBookingApproval: Boolean!
  uniqueId: ID!
  zones: [Booking_OrganizationZoneDetails!]!
}

type BookingStatusDetails {
  name: String!
  type: BookingStatus!
}

type BookingTypeDetails {
  name: String!
  type: BookingType!
}

type Booking_CurrencyDetails {
  name: String!
  type: Currency!
}

type Booking_CustomerDetails {
  familyName: String
  givenName: String
  middleName: String
  name: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type Booking_LocationDetails {
  name: String!
  uniqueId: ID!
}

type Booking_OrganizationCustomTagDetails {
  color: String
  name: String
  uniqueId: ID!
}

type Booking_OrganizationDetails {
  name: String!
  uniqueId: ID!
}

type Booking_OrganizationZoneDetails {
  color: String
  name: String
  uniqueId: ID!
}

type Booking_PriceUnitDetails {
  name: String!
  type: PriceUnit!
}

type Booking_ProductVersionDetails {
  currency: Booking_CurrencyDetails!
  name: String!
  organization: Booking_OrganizationDetails!
  price: String!
  priceToDisplay: String!
  priceUnit: Booking_PriceUnitDetails!
  uniqueId: ID!
}

type Booking_TeamDetails {
  name: String!
  uniqueId: ID!
}

type CancelInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type CancelInvitationToJoinTeamPayload {
  clientMutationId: String
}

type CancelOrganizationOfferingPayload {
  clientMutationId: String
}

type CurrencyDetails {
  name: String!
  type: Currency!
}

type CustomerBillingDetails {
  addressLine1: String!
  addressLine2: String
  city: String!
  companyName: String
  country: String!
  email: String!
  id: ID!
  province: String
  suburb: String!
  zipcode: String!
}

type CustomerConnection {
  edges: [CustomerEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type CustomerDetails {
  billingDetails: CustomerBillingDetails
  createdAt: DateTime!
  defaultOrganization: Customer_OrganizationDetails
  designation: String
  email: String
  familyName: String
  givenName: String
  hasAttachedPaymentMethod: Boolean!
  id: ID!
  identities: [CustomerIdentity!]!
  isDefaultOrganizationOnboardingDone: Boolean!
  isLocationOnboardingDone: Boolean!
  isOrganizationOnboardingDone: Boolean!
  isPreferredLocationOnboardingDone: Boolean!
  isPreferredZoneOnboardingDone: Boolean!
  isTeamOnboardingDone: Boolean!
  locale: String
  middleName: String
  name: String
  paymentMethods: [CustomerPaymentMethod!]!
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  preferredCustomTags: [Customer_OrganizationTagDetails!]!
  preferredLocations: [Customer_LocationDetails!]!
  preferredResources: [CustomerResourceDetails!]!
  preferredTeams: [CustomerTeamDetails!]!
  preferredZones: [Customer_OrganizationTagDetails!]!
  timezone: String
  title: String
}

type CustomerEdge {
  cursor: String!
  node: CustomerDetails!
}

type CustomerIdentity {
  email: String
  id: ID!
  verified: Boolean!
}

type CustomerPayload {
  clientMutationId: String
  customer: CustomerDetails!
}

type CustomerPaymentMethod {
  cardBrand: String
  cardCountry: String
  cardDescription: String
  cardExpiryMonth: Int
  cardExpiryYear: Int
  cardFingerprint: String
  cardFunding: String
  cardIssuer: String
  cardLastFourDigit: String
  id: ID!
}

type CustomerResourceDetails {
  name: String
  uniqueId: ID!
}

type CustomerTeamDetails {
  name: String
  organization: Customer_OrganizationDetails
  uniqueId: ID!
}

type Customer_LocationDetails {
  name: String
  organization: Customer_OrganizationDetails
  uniqueId: ID!
}

type Customer_OrganizationDetails {
  logoUrl: String
  name: String
  uniqueId: ID!
}

type Customer_OrganizationTagDetails {
  color: String
  name: String
  uniqueId: ID!
}

type DesksOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type InviteCustomersToJoinOrganizationPayload {
  clientMutationId: String
}

type InviteCustomersToJoinTeamPayload {
  clientMutationId: String
}

type LineItemDetails {
  productVersion: Booking_ProductVersionDetails!
  quantity: Int!
}

type LocationAddressDetails {
  addressLine1: String!
  addressLine2: String
  city: String!
  country: String!
  formattedAddress: String
  province: String
  suburb: String!
  zipcode: String!
}

type LocationAnalytics {
  dailyBookingsTotals: [LocationDailyBookingsTotal!]!
  desksOccupancyPercentage: [DesksOccupancyPercentage!]!
  name: String!
  roomsOccupancyPercentage: [RoomsOccupancyPercentage!]!
}

type LocationConnection {
  edges: [LocationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type LocationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type LocationDetails {
  about: String
  canDelete: Boolean!
  canModify: Boolean!
  canViewAnalytics: Boolean!
  contactEmail: String
  contactPhone: String
  customTags: [Location_OrganizationTagDetails!]!
  deskCapacity: Int!
  hasFutureBooking: Boolean!
  id: ID!
  locationTags: [Location_OrganizationTagDetails!]!
  name: String!
  openingHours: OpeningHours!
  organization: Location_OrganizationDetails!
  physicalAddress: LocationAddressDetails!
  primaryFeatureImageUrl: String
  resources: [ResourceDetails!]!
  resourceTypes: [Location_OrganizationTagDetails!]!
  roomCapacity: Int!
  timezone: String
  zones: [Location_OrganizationTagDetails!]!
}

type LocationEdge {
  cursor: String!
  node: LocationDetails!
}

type LocationPayload {
  clientMutationId: String
  location: LocationDetails!
}

type Location_OrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type Location_OrganizationTagDetails {
  color: String
  name: String
  tagType: String
  uniqueId: ID!
}

type Marketplace_OrganizationDetails {
  uniqueId: ID!
}

type Marketplace_OrganizationTagDetails {
  color: String
  name: String
  tagType: String
  uniqueId: ID!
}

type Mutation {
  acceptInvitationToJoinOrganization(input: AcceptInvitationToJoinOrganizationInput!): AcceptInvitationToJoinOrganizationPayload @cost(weight: "10")
  acceptInvitationToJoinTeam(input: AcceptInvitationToJoinTeamInput!): AcceptInvitationToJoinTeamPayload @cost(weight: "10")
  activateProducts(input: ActivateProductsInput!): ProductsPayload @cost(weight: "10")
  activateResources(input: ActivateResourcesInput!): ResourcesPayload @cost(weight: "10")
  addBooking(input: AddBookingInput!): BookingPayload @cost(weight: "10")
  addCustomerPaymentMethodIntent(input: AddCustomerPaymentMethodIntentInput!): AddCustomerPaymentMethodIntentPayload! @cost(weight: "10")
  addCustomerPreferredLocation(input: AddCustomerPreferredLocationInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredOrganizationTag(input: AddCustomerPreferredOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredResource(input: AddCustomerPreferredResourceInput!): CustomerPayload @cost(weight: "10")
  addCustomerPreferredTeam(input: AddCustomerPreferredTeamInput!): CustomerPayload @cost(weight: "10")
  addCustomTag(input: AddCustomTagInput!): OrganizationTagPayload @cost(weight: "10")
  addLocation(input: AddLocationInput!): LocationPayload @cost(weight: "10")
  addLocationTag(input: AddLocationTagInput!): OrganizationTagPayload @cost(weight: "10")
  addMyBillingDetails(input: AddMyBillingDetailsInput!): CustomerPayload @cost(weight: "10")
  addOrganization(input: AddOrganizationInput!): OrganizationPayload @cost(weight: "10")
  addOrganizationBillingDetails(input: AddOrganizationBillingDetailsInput!): OrganizationPayload @cost(weight: "10")
  addOrganizationPaymentMethodIntent(input: AddOrganizationPaymentMethodIntentInput!): AddOrganizationPaymentMethodIntentPayload! @cost(weight: "10")
  addOrganizationStripeConnectAccount(input: AddOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload @cost(weight: "10")
  addProduct(input: AddProductInput!): ProductPayload @cost(weight: "10")
  addProductTag(input: AddProductTagInput!): OrganizationTagPayload @cost(weight: "10")
  addResource(input: AddResourceInput!): ResourcePayload @cost(weight: "10")
  addTeam(input: AddTeamInput!): TeamPayload @cost(weight: "10")
  addTeamMember(input: AddTeamMemberInput!): TeamMemberPayload @cost(weight: "10")
  addZone(input: AddZoneInput!): OrganizationTagPayload @cost(weight: "10")
  cancelInvitationToJoinOrganization(input: CancelInvitationToJoinOrganizationInput!): CancelInvitationToJoinOrganizationPayload @cost(weight: "10")
  cancelInvitationToJoinTeam(input: CancelInvitationToJoinTeamInput!): CancelInvitationToJoinTeamPayload @cost(weight: "10")
  cancelOrganizationOffering(input: CancelOrganizationOfferingInput!): CancelOrganizationOfferingPayload @cost(weight: "10")
  changeOrganizationMemberRole(input: ChangeOrganizationMemberRoleInput!): OrganizationMemberDetailsPayload @cost(weight: "10")
  changeOrganizationMembersStatus(input: ChangeOrganizationMembersStatusInput!): OrganizationMembersDetailsPayload @cost(weight: "10")
  changeTeamMemberRole(input: ChangeTeamMemberRoleInput!): TeamMemberDetailsPayload @cost(weight: "10")
  changeTeamMembersStatus(input: ChangeTeamMembersStatusInput!): TeamMembersDetailsPayload @cost(weight: "10")
  clearCustomerDefaultOrganization(input: ClearCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  completeDefaultOrganizationOnboarding(input: CompleteDefaultOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeLocationOnboarding(input: CompleteLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeOrganizationMemberOnboarding(input: CompleteOrganizationMemberOnboardingInput!): OrganizationMemberPayload @cost(weight: "10")
  completeOrganizationOnboarding(input: CompleteOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredLocationOnboarding(input: CompletePreferredLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredZoneOnboarding(input: CompletePreferredZoneOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeTeamOnboarding(input: CompleteTeamOnboardingInput!): CustomerPayload @cost(weight: "10")
  deactivateProducts(input: DeactivateProductsInput!): ProductsPayload @cost(weight: "10")
  deactivateResources(input: DeactivateResourcesInput!): ResourcesPayload @cost(weight: "10")
  deleteBooking(input: DeleteBookingInput!): BookingPayload @cost(weight: "10")
  deleteCustomTag(input: DeleteCustomTagInput!): OrganizationTagPayload @cost(weight: "10")
  deleteCustomTags(input: DeleteCustomTagsInput!): OrganizationTagsPayload @cost(weight: "10")
  deleteLocation(input: DeleteLocationInput!): LocationPayload @cost(weight: "10")
  deleteLocationTag(input: DeleteLocationTagInput!): OrganizationTagPayload @cost(weight: "10")
  deleteLocationTags(input: DeleteLocationTagsInput!): OrganizationTagsPayload @cost(weight: "10")
  deleteOrganization(input: DeleteOrganizationInput!): OrganizationPayload @cost(weight: "10")
  deleteOrganizationStripeConnectAccount(input: DeleteOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload @cost(weight: "10")
  deleteOrganizationStripeConnectAccounts(input: DeleteOrganizationStripeConnectAccountsInput!): OrganizationStripeConnectAccountsPayload @cost(weight: "10")
  deleteProducts(input: DeleteProductsInput!): ProductsPayload @cost(weight: "10")
  deleteProductTag(input: DeleteProductTagInput!): OrganizationTagPayload @cost(weight: "10")
  deleteProductTags(input: DeleteProductTagsInput!): OrganizationTagsPayload @cost(weight: "10")
  deleteResource(input: DeleteResourceInput!): ResourcePayload @cost(weight: "10")
  deleteResources(input: DeleteResourcesInput!): ResourcesPayload @cost(weight: "10")
  deleteTeam(input: DeleteTeamInput!): TeamPayload @cost(weight: "10")
  deleteZone(input: DeleteZoneInput!): OrganizationTagPayload @cost(weight: "10")
  deleteZones(input: DeleteZonesInput!): OrganizationTagsPayload @cost(weight: "10")
  inviteCustomersToJoinOrganization(input: InviteCustomersToJoinOrganizationInput!): InviteCustomersToJoinOrganizationPayload @cost(weight: "10")
  inviteCustomersToJoinTeam(input: InviteCustomersToJoinTeamInput!): InviteCustomersToJoinTeamPayload @cost(weight: "10")
  rejectInvitationToJoinOrganization(input: RejectInvitationToJoinOrganizationInput!): RejectInvitationToJoinOrganizationPayload @cost(weight: "10")
  rejectInvitationToJoinTeam(input: RejectInvitationToJoinTeamInput!): RejectInvitationToJoinTeamPayload @cost(weight: "10")
  removeCustomerPaymentMethod(input: RemoveCustomerPaymentMethodInput!): RemoveCustomerPaymentMethodPayload @cost(weight: "10")
  removeCustomerPreferredLocation(input: RemoveCustomerPreferredLocationInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredOrganizationTag(input: RemoveCustomerPreferredOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredResource(input: RemoveCustomerPreferredResourceInput!): CustomerPayload @cost(weight: "10")
  removeCustomerPreferredTeam(input: RemoveCustomerPreferredTeamInput!): CustomerPayload @cost(weight: "10")
  removeOrganizationMembers(input: RemoveOrganizationMembersInput!): OrganizationMembersDetailsPayload @cost(weight: "10")
  removeOrganizationPaymentMethod(input: RemoveOrganizationPaymentMethodInput!): RemoveOrganizationPaymentMethodPayload @cost(weight: "10")
  removeOrganizationSsoSettings(input: RemoveOrganizationSsoSettingsInput!): UpdateOrganizationSsoSettingsPayload @cost(weight: "10")
  removeTeamMember(input: RemoveTeamMemberInput!): TeamMemberPayload @cost(weight: "10")
  removeTeamMembers(input: RemoveTeamMembersInput!): TeamMembersDetailsPayload @cost(weight: "10")
  setCustomerDefaultOrganization(input: SetCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  submitCustomerFeedback(input: SubmitCustomerFeedbackInput!): SubmitCustomerFeedbackPayload @cost(weight: "10")
  toggleOrganizationSso(input: ToggleOrganizationSsoInput!): UpdateOrganizationSsoSettingsPayload @cost(weight: "10")
  updateBooking(input: UpdateBookingInput!): BookingPayload @cost(weight: "10")
  updateCustomerDetails(input: UpdateCustomerDetailsInput!): CustomerPayload @cost(weight: "10")
  updateCustomTag(input: UpdateCustomTagInput!): OrganizationTagPayload @cost(weight: "10")
  updateLocation(input: UpdateLocationInput!): LocationPayload @cost(weight: "10")
  updateLocationOpeningHours(input: UpdateLocationOpeningHoursInput!): LocationPayload @cost(weight: "10")
  updateLocationResourceAvailableHours(input: UpdateLocationResourceAvailableHoursInput!): ResourcePayload @cost(weight: "10")
  updateLocationTag(input: UpdateLocationTagInput!): OrganizationTagPayload @cost(weight: "10")
  updateMyBillingDetails(input: UpdateMyBillingDetailsInput!): CustomerPayload @cost(weight: "10")
  updateMyCustomerDetails(input: UpdateMyCustomerDetailsInput!): CustomerPayload @cost(weight: "10")
  updateOrganization(input: UpdateOrganizationInput!): OrganizationPayload @cost(weight: "10")
  updateOrganizationBillingDetails(input: UpdateOrganizationBillingDetailsInput!): OrganizationPayload @cost(weight: "10")
  updateOrganizationOffering(input: UpdateOrganizationOfferingInput!): UpdateOrganizationOfferingPayload @cost(weight: "10")
  updateOrganizationSsoSettings(input: UpdateOrganizationSsoSettingsInput!): UpdateOrganizationSsoSettingsPayload @cost(weight: "10")
  updateOrganizationStripeConnectAccount(input: UpdateOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload @cost(weight: "10")
  updateProduct(input: UpdateProductInput!): ProductPayload @cost(weight: "10")
  updateProductTag(input: UpdateProductTagInput!): OrganizationTagPayload @cost(weight: "10")
  updateResource(input: UpdateResourceInput!): ResourcePayload @cost(weight: "10")
  updateTeam(input: UpdateTeamInput!): TeamPayload @cost(weight: "10")
  updateTeamAndTeamMembers(input: UpdateTeamAndTeamMembersInput!): TeamPayload @cost(weight: "10")
  updateTeamMembers(input: UpdateTeamMembersInput!): TeamPayload @cost(weight: "10")
  updateZone(input: UpdateZoneInput!): OrganizationTagPayload @cost(weight: "10")
}

type NotificationConnection {
  edges: [NotificationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type NotificationDetails {
  eventRaisedAt: DateTime!
  id: ID!
  invitedBy: Notification_CustomerDetails
  invitee: Notification_CustomerDetails
  location: Notification_LocationDetails
  notificationType: NotificationType!
  organization: Notification_OrganizationDetails
  sourceId: ID!
  team: Notification_TeamDetails
}

type NotificationEdge {
  cursor: String!
  node: NotificationDetails!
}

type Notification_CustomerDetails {
  emails: [String!]!
  familyName: String
  givenName: String
  middleName: String
  name: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type Notification_LocationDetails {
  name: String!
  uniqueId: ID!
}

type Notification_OrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type Notification_TeamDetails {
  name: String!
  uniqueId: ID!
}

type OpeningHours {
  closedDates: [DateTime!]!
  datesWithVariedOpeningHours: [VariedDateOpeningHours!]!
  weekOpeningHours: WeekOpeningHours!
}

type OpeningHoursDetails {
  closed: Boolean!
  from: String
  openAllDay: Boolean!
  until: String
}

type OrganizationActiveOfferingDetails {
  code: String!
  earlyBird: Boolean!
  end: DateTime!
  featureSet: [String!]!
  free: Boolean!
  id: ID!
  isEnterprise: Boolean!
  name: String!
  start: DateTime!
  underPriceLines: [String!]!
  unitPrice: Int!
}

type OrganizationAddressDetails {
  addressLine1: String!
  addressLine2: String
  city: String!
  country: String!
  formattedAddress: String
  province: String
  suburb: String!
  zipcode: String!
}

type OrganizationAnalytics {
  dailyBookingsTotals: [OrganizationDailyBookingsTotal!]!
  memberAttendancePercentage: [OrganizationMemberAttendancePercentage!]!
}

type OrganizationAvailableResources {
  availableResourcesCount: Int!
  resourcesCount: Int!
}

type OrganizationBillingDetails {
  addressLine1: String!
  addressLine2: String
  city: String!
  companyName: String
  country: String!
  email: String!
  id: ID!
  province: String
  suburb: String!
  zipcode: String!
}

type OrganizationBookingPermissions {
  canAddBooking: Boolean!
  canDeleteBooking: Boolean!
  canUpdateBooking: Boolean!
}

type OrganizationConnection {
  edges: [OrganizationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type OrganizationDetails {
  about: String
  activeOffering: OrganizationActiveOfferingDetails!
  agreedToTermsOfUse: Boolean!
  availableOfferings: [OrganizationOfferingDetails!]!
  billingDetails: OrganizationBillingDetails
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canModify: Boolean!
  canViewAnalytics: Boolean!
  contactEmail: String
  contactPhone: String
  hasAttachedPaymentMethod: Boolean!
  hasFutureBooking: Boolean!
  hasLocation: Boolean!
  hasTeam: Boolean!
  id: ID!
  industrySubCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  isMyOnboardingDone: Boolean!
  logoUrl: String
  members: [OrganizationMemberDetails!]!
  memberVisibilityPolicy: OrganizationMemberVisibilityPolicyDetails!
  name: String!
  paymentMethods: [OrganizationPaymentMethod!]!
  physicalAddress: OrganizationAddressDetails!
  resourceTypes: [OrganizationTagDetails!]!
  ssoSettings: OrganizationSsoSettingsDetails
  termsOfUse: OrganizationTermsOfUse
  type: OrganizationTypeDetails!
  website: String
}

type OrganizationEdge {
  cursor: String!
  node: OrganizationDetails!
}

type OrganizationIndustryMainCategoryReferenceDetails {
  id: ID!
  name: String!
  subCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
}

type OrganizationIndustrySubCategoryReferenceDetails {
  id: ID!
  mainCategoryName: String!
  name: String!
}

type OrganizationMemberAttendancePercentage {
  date: DateTime!
  percentage: Float!
}

type OrganizationMemberConnection {
  edges: [OrganizationMemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationMemberDetails {
  customer: Organization_CustomerDetails!
  id: ID!
  isOrganizationOnboardingDone: Boolean!
  role: OrganizationMemberRole
  status: OrganizationMemberStatus!
}

type OrganizationMemberDetailsPayload {
  clientMutationId: String
  member: OrganizationMemberDetails
}

type OrganizationMemberEdge {
  cursor: String!
  node: OrganizationMemberDetails!
}

type OrganizationMemberPayload {
  clientMutationId: String
}

type OrganizationMemberVisibilityPolicyDetails {
  name: String!
  type: OrganizationMemberVisibilityPolicy!
}

type OrganizationMembersDetailsPayload {
  clientMutationId: String
  members: [OrganizationMemberDetails!]!
}

type OrganizationOfferingDetails {
  code: String!
  earlyBird: Boolean!
  featureSet: [String!]!
  free: Boolean!
  isEnterprise: Boolean!
  name: String!
  underPriceLines: [String!]!
  unitPrice: Int!
}

type OrganizationPayload {
  clientMutationId: String
  organization: OrganizationDetails!
}

type OrganizationPaymentMethod {
  cardBrand: String
  cardCountry: String
  cardDescription: String
  cardExpiryMonth: Int
  cardExpiryYear: Int
  cardFingerprint: String
  cardFunding: String
  cardIssuer: String
  cardLastFourDigit: String
  id: ID!
}

type OrganizationSsoSettingsDetails {
  appFederationMetadataUrl: String!
  entityId: String!
  loginUrl: String!
}

type OrganizationStripeConnectAccountConnection {
  edges: [OrganizationStripeConnectAccountEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationStripeConnectAccountDetails {
  businessType: String
  capabilitiesCardPayments: String!
  capabilitiesTransfers: String!
  chargesEnabled: Boolean!
  companyName: String
  contactEmail: String
  contactPhone: String
  country: String
  defaultCurrency: String
  id: ID!
  name: String!
  onboardingCompleted: Boolean!
  onboardingUrl: String!
  organization: Payment_OrganizationDetails!
  payoutsEnabled: Boolean!
  supportUrl: String
  type: String!
  url: String
}

type OrganizationStripeConnectAccountEdge {
  cursor: String!
  node: OrganizationStripeConnectAccountDetails!
}

type OrganizationStripeConnectAccountPayload {
  account: OrganizationStripeConnectAccountDetails!
  clientMutationId: String
}

type OrganizationStripeConnectAccountsPayload {
  accounts: [OrganizationStripeConnectAccountDetails!]!
  clientMutationId: String
}

type OrganizationTagConnection {
  edges: [OrganizationTagEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationTagDetails {
  color: String
  description: String
  id: ID!
  name: String!
  tagType: String!
}

type OrganizationTagEdge {
  cursor: String!
  node: OrganizationTagDetails!
}

type OrganizationTagPayload {
  clientMutationId: String
  organizationTag: OrganizationTagDetails!
}

type OrganizationTagsPayload {
  clientMutationId: String
  organizationTags: [OrganizationTagDetails!]!
}

type OrganizationTermsOfUse {
  id: ID!
  terms: String!
}

type OrganizationTypeDetails {
  name: String!
  type: OrganizationType!
}

type Organization_CustomerDetails {
  email: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Payment_OrganizationDetails {
  name: String!
  uniqueId: ID!
  website: String
}

type PriceUnitDetails {
  name: String!
  type: PriceUnit!
}

type ProductConnection {
  edges: [ProductEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type ProductDetails {
  bookAllLocationResources: Boolean!
  currency: CurrencyDetails!
  currencyToDisplay: String!
  description: String
  id: ID!
  inactive: Boolean!
  latestProductVersionId: String!
  locationTags: [Marketplace_OrganizationTagDetails!]!
  maxBookingSpreadDays: Int
  maxDurationMinutes: Int
  minDurationMinutes: Int
  name: String!
  numberOfResourcesToBook: Int!
  organization: Marketplace_OrganizationDetails!
  price: String!
  priceToDisplay: String!
  priceUnit: PriceUnitDetails!
  primaryFeatureImageUrl: String
  productTags: [Marketplace_OrganizationTagDetails!]!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
}

type ProductEdge {
  cursor: String!
  node: ProductDetails!
}

type ProductPayload {
  clientMutationId: String
  product: ProductDetails!
}

type ProductsPayload {
  clientMutationId: String
  products: [ProductDetails!]!
}

type Query {
  activeOrganizationTermsOfUse: OrganizationTermsOfUse! @cost(weight: "10")
  allBookings(where: BookingWhereInput!): [BookingDetails!]! @cost(weight: "10")
  availableResources(where: AvailableResourcesWhereInput!): [BookingResourceDetails!]! @cost(weight: "10")
  azureTenantAdminConsentUrl: String! @cost(weight: "10")
  azureTenantOrganization: OrganizationDetails @cost(weight: "10")
  booking(id: String!): BookingDetails @cost(weight: "10")
  bookingCustomerRecordSynced: Boolean! @cost(weight: "10")
  bookings(after: String before: String first: Int last: Int orderBy: [BookingOrderInput!] where: BookingWhereInput!): BookingConnection! @cost(weight: "10")
  bookingStatuses: [BookingStatusDetails!]!
  bookingTypes: [BookingTypeDetails!]!
  bookingVersion: Version!
  coreCustomerRecordSynced: Boolean! @cost(weight: "10")
  coreVersion: Version!
  currencies: [CurrencyDetails!]!
  customer(id: String!): CustomerDetails @cost(weight: "10")
  customersByPreferredLocation(after: String before: String first: Int last: Int orderBy: [CustomerOrderInput!] where: CustomersByPreferredLocationWhereInput!): CustomerConnection! @cost(weight: "10")
  customerTeams(after: String before: String first: Int last: Int orderBy: [TeamOrderInput!] where: CustomerTeamWhereInput!): TeamConnection! @cost(weight: "10")
  customerVersion: Version!
  customTag(id: String!): OrganizationTagDetails @cost(weight: "10")
  customTags(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: CustomTagOrganizationTagWhereInput!): OrganizationTagConnection! @cost(weight: "10")
  isAzureTenantInstalled: Boolean! @cost(weight: "10")
  isOrganizationSsoTokenValid(id: String!): Boolean! @cost(weight: "10")
  location(id: String!): LocationDetails @cost(weight: "10")
  locationAnalytics(from: DateTime! locationId: String! until: DateTime!): LocationAnalytics @cost(weight: "10")
  locationCustomerRecordSynced: Boolean! @cost(weight: "10")
  locations(after: String before: String first: Int last: Int orderBy: [LocationOrderInput!] where: LocationWhereInput!): LocationConnection! @cost(weight: "10")
  locationsAnalytics(from: DateTime! orderBy: [LocationOrderInput!] until: DateTime! where: LocationWhereInput!): [LocationAnalytics!]! @cost(weight: "10")
  locationTag(id: String!): OrganizationTagDetails @cost(weight: "10")
  locationTags(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: LocationTagOrganizationTagWhereInput!): OrganizationTagConnection! @cost(weight: "10")
  locationVersion: Version!
  marketplaceBookingTypes: [BookingTypeDetails!]!
  marketplaceCustomerRecordSynced: Boolean! @cost(weight: "10")
  marketplaceVersion: Version!
  me: CustomerDetails @cost(weight: "10")
  msTeamsCustomerRecordSynced: Boolean! @cost(weight: "10")
  msTeamsVersion: Version!
  myLocations(organizationId: String): [LocationDetails!] @cost(weight: "10")
  myNotifications(after: String before: String first: Int last: Int orderBy: [NotificationOrderInput!] where: MyNotificationWhereInput!): NotificationConnection! @cost(weight: "10")
  myOrganizations: [OrganizationDetails!]! @cost(weight: "10")
  myTeams(organizationId: String): [TeamDetails!]! @cost(weight: "10")
  notificationCustomerRecordSynced: Boolean! @cost(weight: "10")
  notificationVersion: Version!
  openingHoursMinutesStep: Int!
  organization(id: String!): OrganizationDetails @cost(weight: "10")
  organizationAnalytics(from: DateTime! organizationId: String! until: DateTime!): OrganizationAnalytics @cost(weight: "10")
  organizationBookingPermissions(organizationId: String!): OrganizationBookingPermissions! @cost(weight: "10")
  organizationCustomerRecordSynced: Boolean! @cost(weight: "10")
  organizationIndustryMainCategoriesReferences: [OrganizationIndustryMainCategoryReferenceDetails!]! @cost(weight: "10")
  organizationMemberRoles: [OrganizationMemberRole!]!
  organizationMembers(after: String before: String first: Int last: Int orderBy: [OrganizationMemberOrderInput!] where: OrganizationMemberWhereInput!): OrganizationMemberConnection! @cost(weight: "10")
  organizationMemberVisibilityPolicies: [OrganizationMemberVisibilityPolicyDetails!]!
  organizationOffering(code: String!): OrganizationOfferingDetails!
  organizationResourcesAvailability(where: OrganizationAvailableResourcesWhereInput!): OrganizationAvailableResources! @cost(weight: "10")
  organizations(after: String before: String first: Int last: Int orderBy: [OrganizationOrderInput!] where: OrganizationWhereInput!): OrganizationConnection! @cost(weight: "10")
  organizationStripeConnectAccount(id: String!): OrganizationStripeConnectAccountDetails @cost(weight: "10")
  organizationStripeConnectAccounts(after: String before: String first: Int last: Int orderBy: [OrganizationStripeConnectAccountOrderInput!] where: OrganizationStripeConnectAccountWhereInput!): OrganizationStripeConnectAccountConnection! @cost(weight: "10")
  organizationTypes: [OrganizationTypeDetails!]!
  organizationVersion: Version!
  paymentCustomerRecordSynced: Boolean! @cost(weight: "10")
  paymentVersion: Version!
  pendingInvitationsCount: Int! @cost(weight: "10")
  priceUnits: [PriceUnitDetails!]!
  product(id: String!): ProductDetails @cost(weight: "10")
  products(after: String before: String first: Int last: Int orderBy: [ProductOrderInput!] where: ProductWhereInput!): ProductConnection! @cost(weight: "10")
  productTag(id: String!): OrganizationTagDetails @cost(weight: "10")
  productTags(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: ProductTagOrganizationTagWhereInput!): OrganizationTagConnection! @cost(weight: "10")
  resource(id: String!): ResourceDetails @cost(weight: "10")
  resources(after: String before: String first: Int last: Int orderBy: [ResourceOrderInput!] where: ResourceWhereInput!): ResourceConnection! @cost(weight: "10")
  slackCustomerRecordSynced: Boolean! @cost(weight: "10")
  slackVersion: Version!
  ssoLoginUrl(id: String! redirectUrl: String!): String! @cost(weight: "10")
  team(id: String!): TeamDetails @cost(weight: "10")
  teamBookingPermissions(teamId: String!): TeamBookingPermissions! @cost(weight: "10")
  teamCustomerRecordSynced: Boolean! @cost(weight: "10")
  teamMemberRoles: [TeamMemberRole!]!
  teamMembers(after: String before: String first: Int last: Int orderBy: [TeamMemberOrderInput!] where: TeamMemberWhereInput!): TeamMemberConnection! @cost(weight: "10")
  teams(after: String before: String first: Int last: Int orderBy: [TeamOrderInput!] where: TeamWhereInput!): TeamConnection! @cost(weight: "10")
  teamVersion: Version!
  zone(id: String!): OrganizationTagDetails @cost(weight: "10")
  zones(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: ZoneOrganizationTagWhereInput!): OrganizationTagConnection! @cost(weight: "10")
}

type RejectInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type RejectInvitationToJoinTeamPayload {
  clientMutationId: String
}

type RemoveCustomerPaymentMethodPayload {
  clientMutationId: String
}

type RemoveOrganizationPaymentMethodPayload {
  clientMutationId: String
}

type ResourceConnection {
  edges: [ResourceEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type ResourceDetails {
  availableHours: OpeningHours
  capacity: Int!
  color: String
  customTags: [Location_OrganizationTagDetails!]!
  id: ID!
  inactive: Boolean!
  isAvailableHoursOverridden: Boolean!
  name: String!
  productTags: [Location_OrganizationTagDetails!]!
  requireBookingApproval: Boolean!
  resourceType: Location_OrganizationTagDetails!
  zones: [Location_OrganizationTagDetails!]!
}

type ResourceEdge {
  cursor: String!
  node: ResourceDetails!
}

type ResourcePayload {
  clientMutationId: String
  resource: ResourceDetails!
}

type ResourcesPayload {
  clientMutationId: String
  resources: [ResourceDetails!]!
}

type RoomsOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type SubmitCustomerFeedbackPayload {
  clientMutationId: String
  id: ID!
}

type TeamBookingPermissions {
  canAddBooking: Boolean!
  canDeleteBooking: Boolean!
  canUpdateBooking: Boolean!
}

type TeamConnection {
  edges: [TeamEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type TeamDetails {
  about: String
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canModify: Boolean!
  hasFutureBooking: Boolean!
  id: ID!
  members: [TeamMemberDetails!]!
  name: String!
  organization: Team_OrganizationDetails!
  primaryFeatureImageUrl: String
  primaryLocation: Team_LocationDetails
  timezone: String
}

type TeamEdge {
  cursor: String!
  node: TeamDetails!
}

type TeamMemberConnection {
  edges: [TeamMemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type TeamMemberDetails {
  customer: Team_CustomerDetails!
  id: ID!
  organizationMember: TeamOrganizationMemberDetails
  role: TeamMemberRole
  status: TeamMemberStatus!
}

type TeamMemberDetailsPayload {
  clientMutationId: String
  member: TeamMemberDetails
}

type TeamMemberEdge {
  cursor: String!
  node: TeamMemberDetails!
}

type TeamMemberPayload {
  clientMutationId: String
  teamMember: TeamMemberDetails!
}

type TeamMembersDetailsPayload {
  clientMutationId: String
  members: [TeamMemberDetails!]!
}

type TeamOrganizationMemberDetails {
  customer: Team_CustomerDetails!
  uniqueId: ID!
}

type TeamPayload {
  clientMutationId: String
  team: TeamDetails!
}

type Team_CustomerDetails {
  email: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type Team_LocationDetails {
  name: String!
  uniqueId: ID!
}

type Team_OrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type UpdateOrganizationOfferingPayload {
  clientMutationId: String
}

type UpdateOrganizationSsoSettingsPayload {
  clientMutationId: String
  organization: OrganizationDetails!
}

type VariedDateOpeningHours {
  date: DateTime!
  openingHoursDetails: OpeningHoursDetails!
}

type Version {
  build: Int!
  major: Int!
  minor: Int!
  revision: Int!
}

type WeekOpeningHours {
  friday: OpeningHoursDetails!
  monday: OpeningHoursDetails!
  saturday: OpeningHoursDetails!
  sunday: OpeningHoursDetails!
  thursday: OpeningHoursDetails!
  tuesday: OpeningHoursDetails!
  wednesday: OpeningHoursDetails!
}

input AcceptInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input AcceptInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input ActivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input ActivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input AddBookingInput {
  clientMutationId: String
  customerIds: [String!]!
  from: DateTime!
  id: String
  lineItems: [LineItemInput!]!
  notes: String
  organizationIds: [String!]!
  resourceIds: [String!]!
  teamIds: [String!]!
  type: BookingType!
  until: DateTime!
}

input AddCustomTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AddCustomerPaymentMethodIntentInput {
  clientMutationId: String
}

input AddCustomerPreferredLocationInput {
  clientMutationId: String
  locationId: String!
}

input AddCustomerPreferredOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input AddCustomerPreferredResourceInput {
  clientMutationId: String
  resourceId: String!
}

input AddCustomerPreferredTeamInput {
  clientMutationId: String
  teamId: String!
}

input AddLocationInput {
  about: String
  clientMutationId: String
  contactEmail: String
  contactPhone: String
  id: String
  locationTagIds: [String!]!
  name: String!
  organizationId: String!
  physicalAddress: LocationAddressDetailsInput!
  primaryFeatureImageUrl: String
  timezone: String
}

input AddLocationTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AddMyBillingDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  clientMutationId: String
  companyName: String
  country: String!
  email: String!
  id: String
  province: String
  suburb: String!
  zipcode: String!
}

input AddOrganizationBillingDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  clientMutationId: String
  companyName: String
  country: String!
  email: String!
  id: String
  organizationId: String!
  province: String
  suburb: String!
  zipcode: String!
}

input AddOrganizationInput {
  about: String
  agreedToTermsOfUse: Boolean!
  clientMutationId: String
  contactEmail: String
  contactPhone: String
  id: String
  industrySubCategoryIds: [String!]!
  memberVisibilityPolicy: OrganizationMemberVisibilityPolicy!
  name: String!
  physicalAddress: OrganizationAddressDetailsInput!
  termsOfUseId: String!
  type: OrganizationType!
  website: String
}

input AddOrganizationPaymentMethodIntentInput {
  clientMutationId: String
  organizationId: String!
}

input AddOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String
  name: String!
  organizationId: String!
  redirectUrl: String!
}

input AddProductInput {
  bookAllLocationResources: Boolean!
  clientMutationId: String
  currency: Currency!
  description: String
  id: String
  locationTagIds: [String!]!
  maxBookingSpreadDays: Int
  maxDurationMinutes: Int
  minDurationMinutes: Int
  name: String!
  numberOfResourcesToBook: Int!
  organizationId: String!
  price: String!
  priceUnit: PriceUnit!
  primaryFeatureImageUrl: String
  productTagIds: [String!]!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
}

input AddProductTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AddResourceInput {
  capacity: Int!
  clientMutationId: String
  color: String
  customTagIds: [String!]!
  id: String
  inactive: Boolean!
  locationId: String!
  name: String!
  organizationResourceTypeId: String!
  productTagIds: [String!]!
  requireBookingApproval: Boolean!
  zoneIds: [String!]!
}

input AddTeamInput {
  about: String
  clientMutationId: String
  customerIds: [String!]!
  id: String
  name: String!
  organizationId: String!
  organizationMemberIds: [String!]!
  primaryFeatureImageUrl: String
  primaryLocationId: String
  timezone: String
}

input AddTeamMemberInput {
  clientMutationId: String
  customerId: String
  id: String!
  organizationMemberId: String
}

input AddZoneInput {
  clientMutationId: String
  color: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AvailableResourcesWhereInput {
  customTagIds: [String!]
  from: DateTime!
  locationId: String
  organizationId: String!
  productId: String
  resourceIdsToInclude: [String!]
  until: DateTime!
  zoneIds: [String!]
}

input BookingOrderInput {
  direction: OrderDirection!
  field: BookingOrderField!
}

input BookingWhereInput {
  customerIds: [String!]
  fromGt: DateTime
  fromGte: DateTime
  fromLt: DateTime
  fromLte: DateTime
  includeFutureBookingsOnly: Boolean
  includeMineOnly: Boolean
  locationIds: [String!]
  nameContains: String
  notesContains: String
  organizationIds: [String!]
  status: BookingStatus
  teamIds: [String!]
  toGt: DateTime
  toGte: DateTime
  toLt: DateTime
  toLte: DateTime
  type: BookingType
}

input CancelInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input CancelInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input CancelOrganizationOfferingInput {
  clientMutationId: String
  id: String!
}

input ChangeOrganizationMemberRoleInput {
  clientMutationId: String
  id: String!
  role: OrganizationMemberRole!
}

input ChangeOrganizationMembersStatusInput {
  clientMutationId: String
  ids: [String!]!
  status: OrganizationMemberStatus!
}

input ChangeTeamMemberRoleInput {
  clientMutationId: String
  id: String!
  role: TeamMemberRole!
}

input ChangeTeamMembersStatusInput {
  clientMutationId: String
  ids: [String!]!
  status: TeamMemberStatus!
}

input ClearCustomerDefaultOrganizationInput {
  clientMutationId: String
}

input CompleteDefaultOrganizationOnboardingInput {
  clientMutationId: String
}

input CompleteLocationOnboardingInput {
  clientMutationId: String
}

input CompleteOrganizationMemberOnboardingInput {
  clientMutationId: String
  organizationId: String!
}

input CompleteOrganizationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredLocationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredZoneOnboardingInput {
  clientMutationId: String
}

input CompleteTeamOnboardingInput {
  clientMutationId: String
}

input CustomTagOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

input CustomerOrderInput {
  direction: OrderDirection!
  field: CustomerOrderField!
}

input CustomerTeamWhereInput {
  customerId: String!
  nameContains: String
  organizationId: String
  primaryLocationIds: [String!]
}

input CustomersByPreferredLocationWhereInput {
  locationId: String!
  nameContains: String
}

input DeactivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeactivateResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteBookingInput {
  clientMutationId: String
  id: String!
}

input DeleteCustomTagInput {
  clientMutationId: String
  id: String!
}

input DeleteCustomTagsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteLocationInput {
  clientMutationId: String
  id: String!
}

input DeleteLocationTagInput {
  clientMutationId: String
  id: String!
}

input DeleteLocationTagsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteOrganizationInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationStripeConnectAccountsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteProductTagInput {
  clientMutationId: String
  id: String!
}

input DeleteProductTagsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteResourceInput {
  clientMutationId: String
  id: String!
}

input DeleteResourcesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteTeamInput {
  clientMutationId: String
  id: String!
}

input DeleteZoneInput {
  clientMutationId: String
  id: String!
}

input DeleteZonesInput {
  clientMutationId: String
  ids: [String!]!
}

input InviteCustomersToJoinOrganizationInput {
  clientMutationId: String
  emails: [String!]!
  organizationId: String!
}

input InviteCustomersToJoinTeamInput {
  clientMutationId: String
  emails: [String!]!
  teamId: String!
}

input LineItemInput {
  productVersionId: String!
  quantity: Int!
}

input LocationAddressDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  country: String!
  province: String
  suburb: String!
  zipcode: String!
}

input LocationOrderInput {
  direction: OrderDirection!
  field: LocationOrderField!
}

input LocationTagOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

input LocationWhereInput {
  customTagIds: [String!]
  locationIds: [String!]
  nameContains: String
  organizationId: String
  zoneIds: [String!]
}

input MyNotificationWhereInput {
  organizationId: String
}

input NotificationOrderInput {
  direction: OrderDirection!
  field: NotificationOrderField!
}

input OpeningHoursDetailsInput {
  closed: Boolean!
  from: String
  openAllDay: Boolean!
  until: String
}

input OrganizationAddressDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  country: String!
  province: String
  suburb: String!
  zipcode: String!
}

input OrganizationAvailableResourcesWhereInput {
  from: DateTime!
  organizationId: String!
  until: DateTime!
}

input OrganizationMemberOrderInput {
  direction: OrderDirection!
  field: OrganizationMemberOrderField!
}

input OrganizationMemberWhereInput {
  customerId: String
  nameContains: String
  organizationId: String!
}

input OrganizationOrderInput {
  direction: OrderDirection!
  field: OrganizationOrderField!
}

input OrganizationStripeConnectAccountOrderInput {
  direction: OrderDirection!
  field: OrganizationStripeConnectAccountOrderField!
}

input OrganizationStripeConnectAccountWhereInput {
  nameContains: String
  onboardingCompleted: Boolean
  organizationId: String!
}

input OrganizationTagOrderInput {
  direction: OrderDirection!
  field: OrganizationTagOrderField!
}

input OrganizationWhereInput {
  nameContains: String
}

input ProductOrderInput {
  direction: OrderDirection!
  field: ProductOrderField!
}

input ProductTagOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

input ProductWhereInput {
  includeInactive: Boolean!
  nameContains: String
  organizationIds: [String!]
  productIds: [String!]
}

input RejectInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input RejectInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input RemoveCustomerPaymentMethodInput {
  clientMutationId: String
  id: String!
}

input RemoveCustomerPreferredLocationInput {
  clientMutationId: String
  locationId: String!
}

input RemoveCustomerPreferredOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input RemoveCustomerPreferredResourceInput {
  clientMutationId: String
  resourceId: String!
}

input RemoveCustomerPreferredTeamInput {
  clientMutationId: String
  teamId: String!
}

input RemoveOrganizationMembersInput {
  clientMutationId: String
  ids: [String!]!
}

input RemoveOrganizationPaymentMethodInput {
  clientMutationId: String
  id: String!
}

input RemoveOrganizationSsoSettingsInput {
  clientMutationId: String
  organizationId: String!
}

input RemoveTeamMemberInput {
  clientMutationId: String
  id: String!
}

input RemoveTeamMembersInput {
  clientMutationId: String
  ids: [String!]!
}

input ResourceOrderInput {
  direction: OrderDirection!
  field: ResourceOrderField!
}

input ResourceWhereInput {
  customTagIds: [String!]
  locationId: String!
  nameContains: String
  productTagIds: [String!]
  zoneIds: [String!]
}

input SetCustomerDefaultOrganizationInput {
  clientMutationId: String
  organizationId: String!
}

input SubmitCustomerFeedbackInput {
  channel: FeedbackChannelType!
  clientMutationId: String
  feedbackContent: String!
  id: String
}

input TeamMemberOrderInput {
  direction: OrderDirection!
  field: TeamMemberOrderField!
}

input TeamMemberWhereInput {
  nameContains: String
  teamId: String!
}

input TeamOrderInput {
  direction: OrderDirection!
  field: TeamOrderField!
}

input TeamWhereInput {
  nameContains: String
  organizationId: String
  primaryLocationIds: [String!]
}

input ToggleOrganizationSsoInput {
  clientMutationId: String
  isActive: Boolean!
  organizationId: String!
}

input UpdateBookingInput {
  clientMutationId: String
  customerIds: [String!]!
  from: DateTime!
  id: String!
  notes: String
  organizationIds: [String!]!
  resourceIds: [String!]!
  teamIds: [String!]!
  type: BookingType!
  until: DateTime!
}

input UpdateCustomTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String!
  name: String!
}

input UpdateCustomerDetailsInput {
  clientMutationId: String
  designation: String
  familyName: String
  givenName: String
  id: String!
  middleName: String
  name: String
  phoneNumber: String
  timezone: String
  title: String
}

input UpdateLocationInput {
  about: String
  clientMutationId: String
  contactEmail: String
  contactPhone: String
  id: String!
  locationTagIds: [String!]!
  name: String!
  physicalAddress: LocationAddressDetailsInput!
  primaryFeatureImageUrl: String
  timezone: String
}

input UpdateLocationOpeningHoursInput {
  clientMutationId: String
  id: String!
  weekOpeningHours: WeekOpeningHoursInput!
}

input UpdateLocationResourceAvailableHoursInput {
  availableHours: WeekOpeningHoursInput
  clientMutationId: String
  id: String!
  overrideAvailableHours: Boolean!
}

input UpdateLocationTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String!
  name: String!
}

input UpdateMyBillingDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  clientMutationId: String
  companyName: String
  country: String!
  email: String!
  id: String!
  province: String
  suburb: String!
  zipcode: String!
}

input UpdateMyCustomerDetailsInput {
  clientMutationId: String
  designation: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  timezone: String
  title: String
}

input UpdateOrganizationBillingDetailsInput {
  addressLine1: String!
  addressLine2: String
  city: String!
  clientMutationId: String
  companyName: String
  country: String!
  email: String!
  id: String!
  province: String
  suburb: String!
  zipcode: String!
}

input UpdateOrganizationInput {
  about: String
  clientMutationId: String
  contactEmail: String
  contactPhone: String
  id: String!
  industrySubCategoryIds: [String!]!
  memberVisibilityPolicy: OrganizationMemberVisibilityPolicy!
  name: String!
  physicalAddress: OrganizationAddressDetailsInput!
  type: OrganizationType!
  website: String
}

input UpdateOrganizationOfferingInput {
  clientMutationId: String
  id: String!
  offeringCode: String!
}

input UpdateOrganizationSsoSettingsInput {
  appFederationMetadataUrl: String!
  clientMutationId: String
  entityId: String!
  isActive: Boolean!
  loginUrl: String!
  organizationId: String!
}

input UpdateOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String!
  name: String!
}

input UpdateProductInput {
  bookAllLocationResources: Boolean!
  clientMutationId: String
  currency: Currency!
  description: String
  id: String!
  locationTagIds: [String!]!
  maxBookingSpreadDays: Int
  maxDurationMinutes: Int
  minDurationMinutes: Int
  name: String!
  numberOfResourcesToBook: Int!
  organizationId: String!
  price: String!
  priceUnit: PriceUnit!
  primaryFeatureImageUrl: String
  productTagIds: [String!]!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
}

input UpdateProductTagInput {
  clientMutationId: String
  color: String
  description: String
  id: String!
  name: String!
}

input UpdateResourceInput {
  capacity: Int!
  clientMutationId: String
  color: String
  customTagIds: [String!]!
  id: String!
  inactive: Boolean!
  name: String!
  organizationResourceTypeId: String!
  productTagIds: [String!]!
  requireBookingApproval: Boolean!
  zoneIds: [String!]!
}

input UpdateTeamAndTeamMembersInput {
  about: String
  clientMutationId: String
  customerIds: [String!]!
  id: String!
  name: String!
  organizationId: String!
  organizationMemberIds: [String!]!
  primaryFeatureImageUrl: String
  primaryLocationId: String
  timezone: String
}

input UpdateTeamInput {
  about: String
  clientMutationId: String
  id: String!
  name: String!
  primaryFeatureImageUrl: String
  primaryLocationId: String
  timezone: String
}

input UpdateTeamMembersInput {
  clientMutationId: String
  customerIds: [String!]!
  id: String!
  organizationMemberIds: [String!]!
}

input UpdateZoneInput {
  clientMutationId: String
  color: String
  description: String
  id: String!
  name: String!
}

input WeekOpeningHoursInput {
  friday: OpeningHoursDetailsInput!
  monday: OpeningHoursDetailsInput!
  saturday: OpeningHoursDetailsInput!
  sunday: OpeningHoursDetailsInput!
  thursday: OpeningHoursDetailsInput!
  tuesday: OpeningHoursDetailsInput!
  wednesday: OpeningHoursDetailsInput!
}

input ZoneOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

enum BookingOrderField {
  FROM
  NOTES
  STATUS
  TO
  TYPE
}

enum BookingStatus {
  CONFIRMED
  PAYMENT_EXPIRED
  PAYMENT_RECORD_NEVER_CREATED
  PENDING
  REJECTED
}

enum BookingType {
  ANNUAL_LEAVE
  CLIENT_OFFICE
  NON_WORKING_DAY
  SICK_LEAVE
  TRAVELING_FOR_WORK
  VACATION
  WELLBEING_LEAVE
  WORKING_FROM_COWORKING_SPACE
  WORKING_FROM_HOME
  WORKING_FROM_OFFICE
}

enum Currency {
  NZD
  USD
}

enum CustomerOrderField {
  DESIGNATION
  FAMILY_NAME
  GIVEN_NAME
  LOCALE
  MIDDLE_NAME
  NAME
  PHONE_NUMBER
  TIMEZONE
  TITLE
}

enum FeedbackChannelType {
  MS_TEAMS
  SLACK
  WEB
}

enum LocationOrderField {
  ABOUT
  NAME
  TIMEZONE
}

enum NotificationOrderField {
  DATE
  TYPE
}

enum NotificationType {
  INVITATION_TO_JOIN_ORGANIZATION
  INVITATION_TO_JOIN_TEAM
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

enum OrganizationMemberOrderField {
  FAMILY_NAME
  GIVEN_NAME
  MIDDLE_NAME
  NAME
  PHONE_NUMBER
  ROLE
  STATUS
}

enum OrganizationMemberRole {
  ADMINISTRATOR
  MEMBER
  OWNER
}

enum OrganizationMemberStatus {
  ACTIVE
  INACTIVE
}

enum OrganizationMemberVisibilityPolicy {
  FULL_ACCESS
  LIMITED_ACCESS
}

enum OrganizationOrderField {
  NAME
}

enum OrganizationStripeConnectAccountOrderField {
  NAME
}

enum OrganizationTagOrderField {
  DESCRIPTION
  NAME
  TYPE
}

enum OrganizationType {
  MARKETPLACE
  PRIVATE
}

enum PaymentStatus {
  EXPIRED
  NO_PAYMENT_REQUIRED
  PAID
  PENDING
  UNPAID
}

enum PriceUnit {
  PER_HOUR
  PER_MINUTE
  PER_USE
}

enum ProductOrderField {
  NAME
}

enum ResourceOrderField {
  NAME
}

enum TeamMemberOrderField {
  FAMILY_NAME
  GIVEN_NAME
  MIDDLE_NAME
  NAME
  PHONE_NUMBER
  ROLE
  STATUS
}

enum TeamMemberRole {
  ADMINISTRATOR
  MEMBER
  OWNER
}

enum TeamMemberStatus {
  ACTIVE
  INACTIVE
}

enum TeamOrderField {
  ABOUT
  NAME
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")