schema {
  query: Query
  mutation: Mutation
}

type AcceptInvitationToJoinLocationPayload {
  clientMutationId: String
}

type AcceptInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type AcceptInvitationToJoinTeamPayload {
  clientMutationId: String
}

type AddOrganizationPaymentMethodIntentResponse {
  clientMutationId: String
  clientSecret: String!
  publishedKeys: String!
}

type BookingConnection {
  edges: [BookingEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type BookingCustomerDetails {
  familyName: String
  givenName: String
  middleName: String
  name: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type BookingDeskDetails {
  deactivated: Boolean!
  deskTypes: [BookingOrganizationDeskTypeDetails!]!
  location: BookingLocationDetails
  name: String!
  requireBookingApproval: Boolean!
  uniqueId: ID!
  zones: [BookingOrganizationZoneDetails!]!
}

type BookingDetails {
  customer: BookingCustomerDetails!
  desks: [BookingDeskDetails!]!
  from: DateTime!
  id: ID!
  location: BookingLocationDetails
  notes: String
  organization: BookingOrganizationDetails
  team: BookingTeamDetails
  to: DateTime!
  type: BookingType!
}

type BookingEdge {
  cursor: String!
  node: BookingDetails!
}

type BookingLocationDetails {
  name: String!
  uniqueId: ID!
}

type BookingOrganizationDeskTypeDetails {
  name: String!
  uniqueId: ID!
}

type BookingOrganizationDetails {
  name: String!
  uniqueId: ID!
}

type BookingOrganizationZoneDetails {
  name: String!
  uniqueId: ID!
}

type BookingPayload {
  booking: BookingDetails!
  clientMutationId: String
}

type BookingTeamDetails {
  name: String!
  uniqueId: ID!
}

type BulkDeskPayload {
  clientMutationId: String
  desks: [DeskDetails!]!
}

type CancelInvitationToJoinLocationPayload {
  clientMutationId: String
}

type CancelInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type CancelInvitationToJoinTeamPayload {
  clientMutationId: String
}

type CancelOrganizationOfferingPayload {
  clientMutationId: String
}

type CustomerConnection {
  edges: [CustomerEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type CustomerDeskDetails {
  name: String
  uniqueId: ID!
}

type CustomerDetails {
  createdAt: DateTime!
  defaultLocations: [CustomerLocationDetails!]!
  defaultOrganization: CustomerOrganizationDetails
  defaultTeams: [CustomerTeamDetails!]!
  designation: String
  email: String
  familyName: String
  givenName: String
  id: ID!
  identities: [CustomerEmail!]!
  isDefaultLocationOnboardingDone: Boolean!
  isDefaultOrganizationOnboardingDone: Boolean!
  isLocationOnboardingDone: Boolean!
  isOrganizationOnboardingDone: Boolean!
  isPreferredDeskOnboardingDone: Boolean!
  isPreferredZoneOnboardingDone: Boolean!
  isTeamOnboardingDone: Boolean!
  locale: String
  middleName: String
  name: String
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  preferredDesks: [CustomerDeskDetails!]!
  preferredDeskTypes: [CustomerOrganizationTagDetails!]!
  preferredZones: [CustomerOrganizationTagDetails!]!
  timezone: String
  title: String
}

type CustomerEdge {
  cursor: String!
  node: CustomerDetails!
}

type CustomerEmail {
  email: String
  id: ID!
  verified: Boolean!
}

type CustomerLocationDetails {
  name: String
  organization: CustomerOrganizationDetails
  uniqueId: ID!
}

type CustomerOrganizationDetails {
  logoUrl: String
  name: String
  uniqueId: ID!
}

type CustomerOrganizationTagDetails {
  name: String
  uniqueId: ID!
}

type CustomerPayload {
  clientMutationId: String
  customer: CustomerDetails!
}

type CustomerTeamDetails {
  name: String
  organization: CustomerOrganizationDetails
  uniqueId: ID!
}

type DeskConnection {
  edges: [DeskEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type DeskDetails {
  deactivated: Boolean!
  deskTypes: [Organization_OrganizationTagDetails!]!
  id: ID!
  name: String!
  requireBookingApproval: Boolean!
  zones: [Organization_OrganizationTagDetails!]!
}

type DeskEdge {
  cursor: String!
  node: DeskDetails!
}

type DeskPayload {
  clientMutationId: String
  desk: DeskDetails!
}

type DesksPayload {
  clientMutationId: String
  desks: [DeskDetails!]!
}

type InviteCustomersToJoinLocationPayload {
  clientMutationId: String
}

type InviteCustomersToJoinOrganizationPayload {
  clientMutationId: String
}

type InviteCustomersToJoinTeamPayload {
  clientMutationId: String
}

type LocationAddressDetails {
  addressLine1: String
  addressLine2: String
  city: String
  country: String
  formattedAddress: String
  province: String
  suburb: String
  zipcode: String
}

type LocationAnalytics {
  dailyBookingsTotals: [LocationDailyBookingsTotal!]!
  desksOccupancyPercentage: [LocationDesksOccupancyPercentage!]!
}

type LocationBookingPermissions {
  canAddBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canDeleteBooking: Boolean!
  canDeleteBookingOnBehalf: Boolean!
  canUpdateBooking: Boolean!
  canUpdateBookingOnBehalf: Boolean!
}

type LocationConnection {
  edges: [LocationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type LocationCustomerDetails {
  familyName: String
  givenName: String
  middleName: String
  name: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type LocationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type LocationDesksOccupancyPercentage {
  date: DateTime!
  percentage: Float!
}

type LocationDetails {
  about: String
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canModify: Boolean!
  canViewAnalytics: Boolean!
  deskCapacity: Int!
  desks: [DeskDetails!]!
  deskTypes: [Organization_OrganizationTagDetails!]!
  hasFutureBooking: Boolean!
  id: ID!
  name: String!
  organization: LocationOrganizationDetails
  physicalAddress: LocationAddressDetails
  timezone: String
  zones: [Organization_OrganizationTagDetails!]!
}

type LocationEdge {
  cursor: String!
  node: LocationDetails!
}

type LocationMemberConnection {
  edges: [LocationMemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type LocationMemberDetails {
  customer: LocationCustomerDetails!
  id: ID!
  role: LocationMemberRole
}

type LocationMemberDetailsPayload {
  clientMutationId: String
  member: LocationMemberDetails
}

type LocationMemberEdge {
  cursor: String!
  node: LocationMemberDetails!
}

type LocationOrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type LocationPayload {
  clientMutationId: String
  location: LocationDetails!
}

type Mutation {
  acceptInvitationToJoinLocation(input: AcceptInvitationToJoinLocationInput!): AcceptInvitationToJoinLocationPayload @cost(weight: "10")
  acceptInvitationToJoinOrganization(input: AcceptInvitationToJoinOrganizationInput!): AcceptInvitationToJoinOrganizationPayload @cost(weight: "10")
  acceptInvitationToJoinTeam(input: AcceptInvitationToJoinTeamInput!): AcceptInvitationToJoinTeamPayload @cost(weight: "10")
  activateDesks(input: ActivateDesksInput!): DesksPayload @cost(weight: "10")
  addBooking(input: AddBookingInput!): BookingPayload @cost(weight: "10")
  addCustomerDefaultDesk(input: AddCustomerDefaultDeskInput!): CustomerPayload @cost(weight: "10")
  addCustomerDefaultLocation(input: AddCustomerDefaultLocationInput!): CustomerPayload @cost(weight: "10")
  addCustomerDefaultOrganizationTag(input: AddCustomerDefaultOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  addCustomerDefaultTeam(input: AddCustomerDefaultTeamInput!): CustomerPayload @cost(weight: "10")
  addDesk(input: AddDeskInput!): DeskPayload @cost(weight: "10")
  addDeskType(input: AddDeskTypeInput!): OrganizationTagPayload @cost(weight: "10")
  addLocation(input: AddLocationInput!): LocationPayload @cost(weight: "10")
  addOrganization(input: AddOrganizationInput!): OrganizationPayload @cost(weight: "10")
  addOrganizationPaymentMethodIntent(input: AddOrganizationPaymentMethodIntentInput!): AddOrganizationPaymentMethodIntentResponse @cost(weight: "10")
  addTeam(input: AddTeamInput!): TeamPayload @cost(weight: "10")
  addTeamMember(input: AddTeamMemberInput!): TeamMemberPayload @cost(weight: "10")
  addZone(input: AddZoneInput!): OrganizationTagPayload @cost(weight: "10")
  bulkAddDesk(input: BulkAddDeskInput!): BulkDeskPayload @cost(weight: "10")
  cancelInvitationToJoinLocation(input: CancelInvitationToJoinLocationInput!): CancelInvitationToJoinLocationPayload @cost(weight: "10")
  cancelInvitationToJoinOrganization(input: CancelInvitationToJoinOrganizationInput!): CancelInvitationToJoinOrganizationPayload @cost(weight: "10")
  cancelInvitationToJoinTeam(input: CancelInvitationToJoinTeamInput!): CancelInvitationToJoinTeamPayload @cost(weight: "10")
  cancelOrganizationOffering(input: CancelOrganizationOfferingInput!): CancelOrganizationOfferingPayload @cost(weight: "10")
  changeLocationMemberRole(input: ChangeLocationMemberRoleInput!): LocationMemberDetailsPayload @cost(weight: "10")
  changeOrganizationMemberRole(input: ChangeOrganizationMemberRoleInput!): OrganizationMemberDetailsPayload @cost(weight: "10")
  changeOrganizationMembersStatus(input: ChangeOrganizationMembersStatusInput!): OrganizationMembersDetailsPayload @cost(weight: "10")
  changeTeamMemberRole(input: ChangeTeamMemberRoleInput!): TeamMemberDetailsPayload @cost(weight: "10")
  changeTeamMembersStatus(input: ChangeTeamMembersStatusInput!): TeamMembersDetailsPayload @cost(weight: "10")
  clearCustomerDefaultOrganization(input: ClearCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  completeDefaultLocationOnboarding(input: CompleteDefaultLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeDefaultOrganizationOnboarding(input: CompleteDefaultOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeLocationOnboarding(input: CompleteLocationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeOrganizationMemberOnboarding(input: CompleteOrganizationMemberOnboardingInput!): OrganizationMemberPayload @cost(weight: "10")
  completeOrganizationOnboarding(input: CompleteOrganizationOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredDeskOnboarding(input: CompletePreferredDeskOnboardingInput!): CustomerPayload @cost(weight: "10")
  completePreferredZoneOnboarding(input: CompletePreferredZoneOnboardingInput!): CustomerPayload @cost(weight: "10")
  completeTeamOnboarding(input: CompleteTeamOnboardingInput!): CustomerPayload @cost(weight: "10")
  deactivateDesks(input: DeactivateDesksInput!): DesksPayload @cost(weight: "10")
  deleteBooking(input: DeleteBookingInput!): BookingPayload @cost(weight: "10")
  deleteDesk(input: DeleteDeskInput!): DeskPayload @cost(weight: "10")
  deleteDesks(input: DeleteDesksInput!): DesksPayload @cost(weight: "10")
  deleteDeskType(input: DeleteDeskTypeInput!): OrganizationTagPayload @cost(weight: "10")
  deleteDeskTypes(input: DeleteDeskTypesInput!): OrganizationTagsPayload @cost(weight: "10")
  deleteLocation(input: DeleteLocationInput!): LocationPayload @cost(weight: "10")
  deleteOrganization(input: DeleteOrganizationInput!): OrganizationPayload @cost(weight: "10")
  deleteTeam(input: DeleteTeamInput!): TeamPayload @cost(weight: "10")
  deleteZone(input: DeleteZoneInput!): OrganizationTagPayload @cost(weight: "10")
  deleteZones(input: DeleteZonesInput!): OrganizationTagsPayload @cost(weight: "10")
  inviteCustomersToJoinLocation(input: InviteCustomersToJoinLocationInput!): InviteCustomersToJoinLocationPayload @cost(weight: "10")
  inviteCustomersToJoinOrganization(input: InviteCustomersToJoinOrganizationInput!): InviteCustomersToJoinOrganizationPayload @cost(weight: "10")
  inviteCustomersToJoinTeam(input: InviteCustomersToJoinTeamInput!): InviteCustomersToJoinTeamPayload @cost(weight: "10")
  rejectInvitationToJoinLocation(input: RejectInvitationToJoinLocationInput!): RejectInvitationToJoinLocationPayload @cost(weight: "10")
  rejectInvitationToJoinOrganization(input: RejectInvitationToJoinOrganizationInput!): RejectInvitationToJoinOrganizationPayload @cost(weight: "10")
  rejectInvitationToJoinTeam(input: RejectInvitationToJoinTeamInput!): RejectInvitationToJoinTeamPayload @cost(weight: "10")
  removeCustomerDefaultDesk(input: RemoveCustomerDefaultDeskInput!): CustomerPayload @cost(weight: "10")
  removeCustomerDefaultLocation(input: RemoveCustomerDefaultLocationInput!): CustomerPayload @cost(weight: "10")
  removeCustomerDefaultOrganizationTag(input: RemoveCustomerDefaultOrganizationTagInput!): CustomerPayload @cost(weight: "10")
  removeCustomerDefaultTeam(input: RemoveCustomerDefaultTeamInput!): CustomerPayload @cost(weight: "10")
  removeOrganizationMembers(input: RemoveOrganizationMembersInput!): OrganizationMembersDetailsPayload @cost(weight: "10")
  removeOrganizationPaymentMethod(input: RemoveOrganizationPaymentMethodInput!): RemoveOrganizationPaymentMethodResponse @cost(weight: "10")
  removeTeamMember(input: RemoveTeamMemberInput!): TeamMemberPayload @cost(weight: "10")
  removeTeamMembers(input: RemoveTeamMembersInput!): TeamMembersDetailsPayload @cost(weight: "10")
  setCustomerDefaultOrganization(input: SetCustomerDefaultOrganizationInput!): CustomerPayload @cost(weight: "10")
  setOrganizationBillingInfo(input: SetOrganizationBillingInfoInput!): OrganizationBillingInfoPayload @cost(weight: "10")
  submitCustomerFeedback(input: SubmitCustomerFeedbackInput!): SubmitCustomerFeedbackPayload @cost(weight: "10")
  updateBooking(input: UpdateBookingInput!): BookingPayload @cost(weight: "10")
  updateDesk(input: UpdateDeskInput!): DeskPayload @cost(weight: "10")
  updateDeskType(input: UpdateDeskTypeInput!): OrganizationTagPayload @cost(weight: "10")
  updateLocation(input: UpdateLocationInput!): LocationPayload @cost(weight: "10")
  updateMyCustomerDetails(input: UpdateMyCustomerDetailsInput!): CustomerPayload @cost(weight: "10")
  updateOrganization(input: UpdateOrganizationInput!): OrganizationPayload @cost(weight: "10")
  updateOrganizationOffering(input: UpdateOrganizationOfferingInput!): UpdateOrganizationOfferingPayload @cost(weight: "10")
  updateTeam(input: UpdateTeamInput!): TeamPayload @cost(weight: "10")
  updateTeamAndTeamMembers(input: UpdateTeamAndTeamMembersInput!): TeamPayload @cost(weight: "10")
  updateTeamMembers(input: UpdateTeamMembersInput!): TeamPayload @cost(weight: "10")
  updateZone(input: UpdateZoneInput!): OrganizationTagPayload @cost(weight: "10")
}

type Notification {
  eventRaisedAt: DateTime!
  id: ID!
  invitedBy: NotificationCustomerDetails
  invitee: NotificationCustomerDetails
  location: NotificationLocationDetails
  notificationType: NotificationType!
  organization: NotificationOrganizationDetails
  sourceId: ID!
  team: NotificationTeamDetails
}

type NotificationConnection {
  edges: [NotificationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type NotificationCustomerDetails {
  emails: [String!]!
  familyName: String
  givenName: String
  middleName: String
  name: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type NotificationEdge {
  cursor: String!
  node: Notification!
}

type NotificationLocationDetails {
  name: String!
  uniqueId: ID!
}

type NotificationOrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type NotificationTeamDetails {
  name: String!
  uniqueId: ID!
}

type OrganizationAnalytics {
  dailyBookingsTotals: [OrganizationDailyBookingsTotal!]!
  memberAttendancePercentage: [OrganizationMemberAttendancePercentage!]!
}

type OrganizationAvailableOfferingDetails {
  code: String!
  featureSet: [OrganizationFeatureSetDetails!]!
  free: Boolean!
  name: String!
  unitPrice: Int!
}

type OrganizationBillingInfo {
  addressLine1: String
  addressLine2: String
  city: String
  country: String
  email: String
  organizationId: ID!
  province: String
  suburb: String
  zipcode: String
}

type OrganizationBillingInfoPayload {
  clientMutationId: String
  organizationBillingInfo: OrganizationBillingInfo!
}

type OrganizationBookingPermissions {
  canAddBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canDeleteBooking: Boolean!
  canDeleteBookingOnBehalf: Boolean!
  canUpdateBooking: Boolean!
  canUpdateBookingOnBehalf: Boolean!
}

type OrganizationConnection {
  edges: [OrganizationEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationCurrentOfferingChargesDetails {
  end: DateTime!
  offeringName: String!
  start: DateTime!
  totalCost: Int!
  totalNumberOfActiveCustomers: Int!
  unitPrice: Int!
}

type OrganizationCustomerDetails {
  email: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type OrganizationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type OrganizationDetails {
  about: String
  agreedToTermsOfUse: Boolean!
  availableOfferings: [OrganizationAvailableOfferingDetails!]!
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canModify: Boolean!
  canViewAnalytics: Boolean!
  hasAttachedPaymentMethod: Boolean!
  hasFutureBooking: Boolean!
  hasLocation: Boolean!
  hasTeam: Boolean!
  id: ID!
  industrySubCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  isMyOnboardingDone: Boolean!
  logoUrl: String
  members: [OrganizationMemberDetails!]!
  name: String!
  offering: OrganizationOfferingDetails!
  termsOfUse: OrganizationTermsOfUse
  website: String
}

type OrganizationEdge {
  cursor: String!
  node: OrganizationDetails!
}

type OrganizationFeatureSetDetails {
  description: String!
  name: String!
}

type OrganizationIndustryMainCategoryReferenceDetails {
  id: ID!
  name: String!
  subCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
}

type OrganizationIndustrySubCategoryReferenceDetails {
  id: ID!
  mainCategoryName: String!
  name: String!
}

type OrganizationMemberAttendancePercentage {
  date: DateTime!
  percentage: Float!
}

type OrganizationMemberConnection {
  edges: [OrganizationMemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationMemberDetails {
  customer: OrganizationCustomerDetails!
  id: ID!
  isOrganizationOnboardingDone: Boolean!
  role: OrganizationMemberRole
  status: OrganizationMemberStatus!
}

type OrganizationMemberDetailsPayload {
  clientMutationId: String
  member: OrganizationMemberDetails
}

type OrganizationMemberEdge {
  cursor: String!
  node: OrganizationMemberDetails!
}

type OrganizationMemberPayload {
  clientMutationId: String
}

type OrganizationMembersDetailsPayload {
  clientMutationId: String
  members: [OrganizationMemberDetails!]!
}

type OrganizationOfferingDetails {
  code: String!
  end: DateTime!
  featureSet: [OrganizationFeatureSetDetails!]!
  free: Boolean!
  id: ID!
  name: String!
  start: DateTime!
  unitPrice: Int!
}

type OrganizationPayload {
  clientMutationId: String
  organization: OrganizationDetails!
}

type OrganizationPaymentMethod {
  cardBrand: String
  cardCountry: String
  cardDescription: String
  cardExpiryMonth: Int
  cardExpiryYear: Int
  cardFingerprint: String
  cardFunding: String
  cardIssuer: String
  cardLastFourDigit: String
  id: ID!
}

type OrganizationTagConnection {
  edges: [OrganizationTagEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type OrganizationTagDetails {
  description: String
  id: ID!
  name: String!
  tagType: String!
}

type OrganizationTagEdge {
  cursor: String!
  node: OrganizationTagDetails!
}

type OrganizationTagPayload {
  clientMutationId: String
  organizationTag: OrganizationTagDetails!
}

type OrganizationTagsPayload {
  clientMutationId: String
  organizationTags: [OrganizationTagDetails!]!
}

type OrganizationTermsOfUse {
  id: ID!
  terms: String!
}

type Organization_OrganizationTagDetails {
  name: String
  tagType: String
  uniqueId: ID!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type Query {
  activeOrganizationTermsOfUse: OrganizationTermsOfUse! @cost(weight: "10")
  allBookings(where: BookingWhereInput!): [BookingDetails!] @cost(weight: "10")
  availableDesks(where: AvailableDesksWhereInput!): [BookingDeskDetails!] @cost(weight: "10")
  azureTenantAdminConsentUrl: String! @cost(weight: "10")
  azureTenantOrganization: OrganizationDetails @cost(weight: "10")
  billingCustomerRecordSynced: Boolean! @cost(weight: "10")
  billingVersion: Version!
  booking(id: String!): BookingDetails @cost(weight: "10")
  bookingCustomerRecordSynced: Boolean! @cost(weight: "10")
  bookings(after: String before: String first: Int last: Int orderBy: [BookingOrderInput!] where: BookingWhereInput!): BookingConnection @cost(weight: "10")
  bookingVersion: Version!
  customersByDefaultLocation(after: String before: String first: Int last: Int orderBy: [CustomerOrderInput!] where: CustomersByDefaultLocationWhereInput!): CustomerConnection @cost(weight: "10")
  customerVersion: Version!
  deskType(id: String!): OrganizationTagDetails @cost(weight: "10")
  deskTypes(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: DeskTypeOrganizationTagWhereInput!): OrganizationTagConnection @cost(weight: "10")
  isAzureTenantInstalled: Boolean! @cost(weight: "10")
  location(id: String!): LocationDetails @cost(weight: "10")
  locationAnalytics(from: DateTime! locationId: String! until: DateTime!): LocationAnalytics @cost(weight: "10")
  locationBookingPermissions(locationId: String!): LocationBookingPermissions @cost(weight: "10")
  locationCustomerRecordSynced: Boolean! @cost(weight: "10")
  locationDesk(id: String!): DeskDetails @cost(weight: "10")
  locationDesks(after: String before: String first: Int last: Int orderBy: [DeskOrderInput!] where: DeskWhereInput!): DeskConnection @cost(weight: "10")
  locationMemberRoles: [LocationMemberRole!]!
  locationMembers(after: String before: String first: Int last: Int orderBy: [LocationMemberOrderInput!] where: LocationMemberWhereInput!): LocationMemberConnection @cost(weight: "10")
  locations(after: String before: String first: Int last: Int orderBy: [LocationOrderInput!] where: LocationWhereInput!): LocationConnection @cost(weight: "10")
  locationVersion: Version!
  me: CustomerDetails @cost(weight: "10")
  msTeamsCustomerRecordSynced: Boolean! @cost(weight: "10")
  msTeamsVersion: Version!
  myLocations(organizationId: String): [LocationDetails!] @cost(weight: "10")
  myNotifications(after: String before: String first: Int last: Int orderBy: [NotificationOrderInput!]): NotificationConnection @cost(weight: "10")
  myOrganizations: [OrganizationDetails!] @cost(weight: "10")
  myTeams(organizationId: String): [TeamDetails!] @cost(weight: "10")
  notificationCustomerRecordSynced: Boolean! @cost(weight: "10")
  notificationVersion: Version!
  organization(id: String!): OrganizationDetails @cost(weight: "10")
  organizationAnalytics(from: DateTime! organizationId: String! until: DateTime!): OrganizationAnalytics @cost(weight: "10")
  organizationBillingInfo(organizationId: String!): OrganizationBillingInfo @cost(weight: "10")
  organizationBookingPermissions(organizationId: String!): OrganizationBookingPermissions @cost(weight: "10")
  organizationCurrentOfferingCharges(organizationId: String!): [OrganizationCurrentOfferingChargesDetails!] @cost(weight: "10")
  organizationCustomerRecordSynced: Boolean! @cost(weight: "10")
  organizationIndustryMainCategoriesReferences: [OrganizationIndustryMainCategoryReferenceDetails!]! @cost(weight: "10")
  organizationMemberRoles: [OrganizationMemberRole!]!
  organizationMembers(after: String before: String first: Int last: Int orderBy: [OrganizationMemberOrderInput!] where: OrganizationMemberWhereInput!): OrganizationMemberConnection @cost(weight: "10")
  organizationPaymentMethodsDetails(organizationId: String!): [OrganizationPaymentMethod!] @cost(weight: "10")
  organizations(after: String before: String first: Int last: Int orderBy: [OrganizationOrderInput!] where: OrganizationWhereInput!): OrganizationConnection @cost(weight: "10")
  organizationVersion: Version!
  paymentCustomerRecordSynced: Boolean! @cost(weight: "10")
  paymentVersion: Version!
  slackCustomerRecordSynced: Boolean! @cost(weight: "10")
  slackVersion: Version!
  team(id: String!): TeamDetails @cost(weight: "10")
  teamBookingPermissions(teamId: String!): TeamBookingPermissions @cost(weight: "10")
  teamCustomerRecordSynced: Boolean! @cost(weight: "10")
  teamMemberRoles: [TeamMemberRole!]!
  teamMembers(after: String before: String first: Int last: Int orderBy: [TeamMemberOrderInput!] where: TeamMemberWhereInput!): TeamMemberConnection @cost(weight: "10")
  teams(after: String before: String first: Int last: Int orderBy: [TeamOrderInput!] where: TeamWhereInput!): TeamConnection @cost(weight: "10")
  teamVersion: Version!
  zone(id: String!): OrganizationTagDetails @cost(weight: "10")
  zones(after: String before: String first: Int last: Int orderBy: [OrganizationTagOrderInput!] where: ZoneOrganizationTagWhereInput!): OrganizationTagConnection @cost(weight: "10")
}

type RejectInvitationToJoinLocationPayload {
  clientMutationId: String
}

type RejectInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type RejectInvitationToJoinTeamPayload {
  clientMutationId: String
}

type RemoveOrganizationPaymentMethodResponse {
  clientMutationId: String
}

type SubmitCustomerFeedbackPayload {
  clientMutationId: String
  id: ID!
}

type TeamBookingPermissions {
  canAddBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canDeleteBooking: Boolean!
  canDeleteBookingOnBehalf: Boolean!
  canUpdateBooking: Boolean!
  canUpdateBookingOnBehalf: Boolean!
}

type TeamConnection {
  edges: [TeamEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type TeamCustomerDetails {
  email: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  photoUrl: String
  photoUrl192: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl512: String
  photoUrl72: String
  uniqueId: ID!
}

type TeamDetails {
  about: String
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canModify: Boolean!
  hasFutureBooking: Boolean!
  id: ID!
  members: [TeamMemberDetails!]!
  name: String!
  organization: TeamOrganizationDetails
  primaryLocation: TeamLocationDetails
  timezone: String
}

type TeamEdge {
  cursor: String!
  node: TeamDetails!
}

type TeamLocationDetails {
  name: String!
  uniqueId: ID!
}

type TeamMemberConnection {
  edges: [TeamMemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type TeamMemberDetails {
  customer: TeamCustomerDetails!
  id: ID!
  organizationMember: TeamOrganizationMemberDetails
  role: TeamMemberRole
  status: TeamMemberStatus!
}

type TeamMemberDetailsPayload {
  clientMutationId: String
  member: TeamMemberDetails
}

type TeamMemberEdge {
  cursor: String!
  node: TeamMemberDetails!
}

type TeamMemberPayload {
  clientMutationId: String
  teamMember: TeamMemberDetails!
}

type TeamMembersDetailsPayload {
  clientMutationId: String
  members: [TeamMemberDetails!]!
}

type TeamOrganizationDetails {
  logoUrl: String
  name: String!
  uniqueId: ID!
}

type TeamOrganizationMemberDetails {
  customer: TeamCustomerDetails!
  uniqueId: ID!
}

type TeamPayload {
  clientMutationId: String
  team: TeamDetails!
}

type UpdateOrganizationOfferingPayload {
  clientMutationId: String
}

type Version {
  build: Int!
  major: Int!
  minor: Int!
  revision: Int!
}

input AcceptInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input AcceptInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input AcceptInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input ActivateDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input AddBookingInput {
  clientMutationId: String
  customerId: String!
  deskIds: [String!]!
  from: DateTime!
  id: String
  locationId: String
  notes: String
  organizationId: String
  teamId: String
  to: DateTime!
  type: BookingType!
}

input AddCustomerDefaultDeskInput {
  clientMutationId: String
  deskId: String!
}

input AddCustomerDefaultLocationInput {
  clientMutationId: String
  locationId: String!
}

input AddCustomerDefaultOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input AddCustomerDefaultTeamInput {
  clientMutationId: String
  teamId: String!
}

input AddDeskInput {
  clientMutationId: String
  deskTypeIds: [String!]!
  id: String
  locationId: String!
  name: String!
  zoneIds: [String!]!
}

input AddDeskTypeInput {
  clientMutationId: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AddLocationInput {
  about: String
  clientMutationId: String
  id: String
  name: String!
  organizationId: String
  physicalAddress: LocationAddressDetailsInput
  timezone: String
}

input AddOrganizationInput {
  about: String
  agreedToTermsOfUse: Boolean!
  clientMutationId: String
  id: String
  industrySubCategoryIds: [String!]!
  name: String!
  termsOfUseId: String!
  website: String
}

input AddOrganizationPaymentMethodIntentInput {
  clientMutationId: String
  organizationId: String!
}

input AddTeamInput {
  about: String
  clientMutationId: String
  customerIds: [String!]!
  id: String
  name: String!
  organizationId: String
  organizationMemberIds: [String!]!
  primaryLocationId: String
  timezone: String
}

input AddTeamMemberInput {
  clientMutationId: String
  customerId: String
  id: String!
  organizationMemberId: String
}

input AddZoneInput {
  clientMutationId: String
  description: String
  id: String
  name: String!
  organizationId: String!
}

input AvailableDesksWhereInput {
  combineDeskTypesZones: Boolean
  date: DateTime!
  deskIdsToInclude: [String!]
  deskTypeIds: [String!]
  locationId: String
  organizationId: String
  zoneIds: [String!]
}

input BookingOrderInput {
  direction: OrderDirection!
  field: BookingOrderField!
}

input BookingWhereInput {
  combineOrganizationsLocationsTeams: Boolean
  fromGT: DateTime
  fromGTE: DateTime
  fromLT: DateTime
  fromLTE: DateTime
  includeFutureBookingsOnly: Boolean
  includeMineOnly: Boolean
  locationIds: [String!]
  nameContains: String
  notesContains: String
  organizationIds: [String!]
  teamIds: [String!]
  toGT: DateTime
  toGTE: DateTime
  toLT: DateTime
  toLTE: DateTime
  type: String
}

input BulkAddDeskInput {
  clientMutationId: String
  count: Int!
  deactivated: Boolean!
  deskTypeIds: [String!]!
  id: String
  locationId: String!
  namePrefix: String
  requireBookingApproval: Boolean!
  zoneIds: [String!]!
}

input CancelInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input CancelInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input CancelInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input CancelOrganizationOfferingInput {
  clientMutationId: String
  id: String!
}

input ChangeLocationMemberRoleInput {
  clientMutationId: String
  id: String!
  role: LocationMemberRole!
}

input ChangeOrganizationMemberRoleInput {
  clientMutationId: String
  id: String!
  role: OrganizationMemberRole!
}

input ChangeOrganizationMembersStatusInput {
  clientMutationId: String
  ids: [String!]!
  status: OrganizationMemberStatus!
}

input ChangeTeamMemberRoleInput {
  clientMutationId: String
  id: String!
  role: TeamMemberRole!
}

input ChangeTeamMembersStatusInput {
  clientMutationId: String
  ids: [String!]!
  status: TeamMemberStatus!
}

input ClearCustomerDefaultOrganizationInput {
  clientMutationId: String
}

input CompleteDefaultLocationOnboardingInput {
  clientMutationId: String
}

input CompleteDefaultOrganizationOnboardingInput {
  clientMutationId: String
}

input CompleteLocationOnboardingInput {
  clientMutationId: String
}

input CompleteOrganizationMemberOnboardingInput {
  clientMutationId: String
  organizationId: String!
}

input CompleteOrganizationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredDeskOnboardingInput {
  clientMutationId: String
}

input CompletePreferredZoneOnboardingInput {
  clientMutationId: String
}

input CompleteTeamOnboardingInput {
  clientMutationId: String
}

input CustomerOrderInput {
  direction: OrderDirection!
  field: CustomerOrderField!
}

input CustomersByDefaultLocationWhereInput {
  locationId: String!
  nameContains: String
}

input DeactivateDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteBookingInput {
  clientMutationId: String
  id: String!
}

input DeleteDeskInput {
  clientMutationId: String
  id: String!
}

input DeleteDeskTypeInput {
  clientMutationId: String
  id: String!
}

input DeleteDeskTypesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteDesksInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteLocationInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationInput {
  clientMutationId: String
  id: String!
}

input DeleteTeamInput {
  clientMutationId: String
  id: String!
}

input DeleteZoneInput {
  clientMutationId: String
  id: String!
}

input DeleteZonesInput {
  clientMutationId: String
  ids: [String!]!
}

input DeskOrderInput {
  direction: OrderDirection!
  field: DeskOrderField!
}

input DeskTypeOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

input DeskWhereInput {
  deskTypeIds: [String!]
  locationId: String!
  nameContains: String
  zoneIds: [String!]
}

input InviteCustomersToJoinLocationInput {
  clientMutationId: String
  emails: [String!]!
  locationId: String!
}

input InviteCustomersToJoinOrganizationInput {
  clientMutationId: String
  emails: [String!]!
  organizationId: String!
}

input InviteCustomersToJoinTeamInput {
  clientMutationId: String
  emails: [String!]!
  teamId: String!
}

input LocationAddressDetailsInput {
  addressLine1: String
  addressLine2: String
  city: String
  country: String
  formattedAddress: String
  province: String
  suburb: String
  zipcode: String
}

input LocationMemberOrderInput {
  direction: OrderDirection!
  field: LocationMemberOrderField!
}

input LocationMemberWhereInput {
  locationId: String!
  nameContains: String
}

input LocationOrderInput {
  direction: OrderDirection!
  field: LocationOrderField!
}

input LocationWhereInput {
  deskTypeIds: [String!]
  nameContains: String
  organizationId: String
  zoneIds: [String!]
}

input NotificationOrderInput {
  direction: OrderDirection!
  field: NotificationOrderField!
}

input OrganizationMemberOrderInput {
  direction: OrderDirection!
  field: OrganizationMemberOrderField!
}

input OrganizationMemberWhereInput {
  nameContains: String
  organizationId: String!
}

input OrganizationOrderInput {
  direction: OrderDirection!
  field: OrganizationOrderField!
}

input OrganizationTagOrderInput {
  direction: OrderDirection!
  field: OrganizationTagOrderField!
}

input OrganizationWhereInput {
  nameContains: String
}

input RejectInvitationToJoinLocationInput {
  clientMutationId: String
  id: String!
}

input RejectInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input RejectInvitationToJoinTeamInput {
  clientMutationId: String
  id: String!
}

input RemoveCustomerDefaultDeskInput {
  clientMutationId: String
  deskId: String!
}

input RemoveCustomerDefaultLocationInput {
  clientMutationId: String
  locationId: String!
}

input RemoveCustomerDefaultOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input RemoveCustomerDefaultTeamInput {
  clientMutationId: String
  teamId: String!
}

input RemoveOrganizationMembersInput {
  clientMutationId: String
  ids: [String!]!
}

input RemoveOrganizationPaymentMethodInput {
  clientMutationId: String
  id: String!
}

input RemoveTeamMemberInput {
  clientMutationId: String
  id: String!
}

input RemoveTeamMembersInput {
  clientMutationId: String
  ids: [String!]!
}

input SetCustomerDefaultOrganizationInput {
  clientMutationId: String
  organizationId: String!
}

input SetOrganizationBillingInfoInput {
  addressLine1: String
  addressLine2: String
  city: String
  clientMutationId: String
  country: String
  email: String
  organizationId: String!
  province: String
  suburb: String
  zipcode: String
}

input SubmitCustomerFeedbackInput {
  channel: FeedbackChannelType!
  clientMutationId: String
  feedbackContent: String!
  id: String
}

input TeamMemberOrderInput {
  direction: OrderDirection!
  field: TeamMemberOrderField!
}

input TeamMemberWhereInput {
  nameContains: String
  teamId: String!
}

input TeamOrderInput {
  direction: OrderDirection!
  field: TeamOrderField!
}

input TeamWhereInput {
  nameContains: String
  organizationId: String
  primaryLocationIds: [String!]
}

input UpdateBookingInput {
  clientMutationId: String
  customerId: String!
  deskIds: [String!]!
  from: DateTime!
  id: String!
  locationId: String
  notes: String
  organizationId: String
  teamId: String
  to: DateTime!
  type: BookingType!
}

input UpdateDeskInput {
  clientMutationId: String
  deactivated: Boolean!
  deskTypeIds: [String!]!
  id: String!
  name: String!
  requireBookingApproval: Boolean!
  zoneIds: [String!]!
}

input UpdateDeskTypeInput {
  clientMutationId: String
  description: String
  id: String!
  name: String!
}

input UpdateLocationInput {
  about: String
  clientMutationId: String
  id: String!
  name: String!
  organizationId: String
  physicalAddress: LocationAddressDetailsInput
  timezone: String
}

input UpdateMyCustomerDetailsInput {
  clientMutationId: String
  designation: String
  familyName: String
  givenName: String
  middleName: String
  name: String
  phoneNumber: String
  timezone: String
  title: String
}

input UpdateOrganizationInput {
  about: String
  clientMutationId: String
  id: String!
  industrySubCategoryIds: [String!]!
  name: String!
  website: String
}

input UpdateOrganizationOfferingInput {
  clientMutationId: String
  id: String!
  offeringCode: String!
}

input UpdateTeamAndTeamMembersInput {
  about: String
  clientMutationId: String
  customerIds: [String!]!
  id: String!
  name: String!
  organizationId: String
  organizationMemberIds: [String!]!
  primaryLocationId: String
  timezone: String
}

input UpdateTeamInput {
  about: String
  clientMutationId: String
  id: String!
  name: String!
  organizationId: String
  primaryLocationId: String
  timezone: String
}

input UpdateTeamMembersInput {
  clientMutationId: String
  customerIds: [String!]!
  id: String!
  organizationMemberIds: [String!]!
}

input UpdateZoneInput {
  clientMutationId: String
  description: String
  id: String!
  name: String!
}

input ZoneOrganizationTagWhereInput {
  nameContains: String
  organizationId: String!
}

enum BookingOrderField {
  BookingType
  FamilyName
  From
  GivenName
  LocationName
  MiddleName
  Name
  Notes
  OrganizationName
  TeamName
  To
}

enum BookingType {
  AnnualLeave
  ClientOffices
  NonWorkingDay
  SickLeave
  TravelingForWork
  Vacation
  WellBeingLeave
  WorkingFromHome
  WorkingFromOffice
}

enum CustomerOrderField {
  Designation
  FamilyName
  GivenName
  Locale
  MiddleName
  Name
  PhoneNumber
  Timezone
  Title
}

enum DeskOrderField {
  Name
}

enum FeedbackChannelType {
  MsTeams
  Slack
  Web
}

enum LocationMemberOrderField {
  FamilyName
  GivenName
  MiddleName
  Name
  Role
}

enum LocationMemberRole {
  Administrator
  Member
  Owner
}

enum LocationOrderField {
  About
  Name
  Timezone
}

enum NotificationOrderField {
  Date
  Type
}

enum NotificationType {
  InvitationToJoinLocation
  InvitationToJoinOrganization
  InvitationToJoinTeam
}

enum OrderDirection {
  Ascending
  Descending
}

enum OrganizationMemberOrderField {
  FamilyName
  GivenName
  MiddleName
  Name
  PhoneNumber
  Role
  Status
}

enum OrganizationMemberRole {
  Administrator
  Member
  Owner
}

enum OrganizationMemberStatus {
  Active
  Inactive
}

enum OrganizationOrderField {
  Name
}

enum OrganizationTagOrderField {
  Description
  Name
  TagType
}

enum TeamMemberOrderField {
  FamilyName
  GivenName
  MiddleName
  Name
  PhoneNumber
  Role
  Status
}

enum TeamMemberRole {
  Administrator
  Member
  Owner
}

enum TeamMemberStatus {
  Active
  Inactive
}

enum TeamOrderField {
  About
  Name
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")