//----------------------
// <auto-generated>
// Generated using Unityhubctl v1.0.0.0. DO NOT EDIT!
// </auto-generated>
//----------------------

using System.Text.RegularExpressions;

using Api.Shared.Events;

using Google.Protobuf.WellKnownTypes;

using NanoidDotNet;

#nullable enable

namespace Api.Shared.Clients.Events.UnityHub.OrganizationInternal.V1.Key;

public partial class Metadata : IMetadata { }

[KafkaTopic(
    topicName: "organization.v1.internal",
    topicPartitionCount: 5,
    retryTopicNamePrefix: "organization.v1.internal.retry",
    retryTopicCount: 1,
    retryTopicPartitionCount: 5,
    deadLetterTopicName: "organization.v1.internal.deadletter",
    deadLetterTopicPartitionCount: 3,
    protobufSchema: "syntax = \"proto3\";package organizationinternal;option csharp_namespace = \"Api.Shared.Clients.Events.UnityHub.OrganizationInternal.V1.Key\";message Key {  string organizationId = 1;  string AzureTenantId = 2;}")]
public partial class Key : IMetadataEvent
{
    private static readonly Regex ValidKafkaTopicCharacters =
        new(@"^[a-z0-9\.\-_]+$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private const string TopicName = "organization.v1.internal";
    private const string RetryTopicNamePrefix = "organization.v1.internal.retry";
    private const int RetryTopicCount = 1;
    private const string DeadLetterTopicName = "organization.v1.internal.deadletter";

    public string GetTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? TopicName : $"{prefix}.{TopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public int GetRetryTopicCount() => RetryTopicCount;

    public string GetRetryTopicName(string prefix, int idx)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? $"{RetryTopicNamePrefix}.{idx}" : $"{prefix}.{RetryTopicNamePrefix}.{idx}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string GetDeadLetterTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? DeadLetterTopicName : $"{prefix}.{DeadLetterTopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string? GetCorrelationId() => null;
}
