<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Skedularctl</AssemblyName>
        <AssemblyTitle>Skedularctl</AssemblyTitle>
        <Product>Skedular Skedularctl</Product>
        <Description>Skedular Skedularctl</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/unityhubio/unityhubio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- CLI / Command Line -->
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>

        <!-- Templating -->
        <PackageReference Include="DotLiquid" Version="2.3.197"/>

        <!-- Code Analysis (Roslyn) -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.6.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Enterprise.Shared/Enterprise.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
