// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: marketplace_v1_value.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value {

  /// <summary>Holder for reflection information generated from marketplace_v1_value.proto</summary>
  public static partial class MarketplaceV1ValueReflection {

    #region Descriptor
    /// <summary>File descriptor for marketplace_v1_value.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MarketplaceV1ValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChptYXJrZXRwbGFjZV92MV92YWx1ZS5wcm90bxILbWFya2V0cGxhY2UaH2dv",
            "b2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8iUQoFRXZlbnQSJwoIbWV0",
            "YWRhdGEYASABKAsyFS5tYXJrZXRwbGFjZS5NZXRhZGF0YRIfCgRkYXRhGAIg",
            "ASgLMhEubWFya2V0cGxhY2UuRGF0YSKhAQoITWV0YWRhdGESCgoCaWQYASAB",
            "KAkSFAoMZG9tYWluU291cmNlGAIgASgJEhEKCWFwcFNvdXJjZRgDIAEoCRIf",
            "CgR0eXBlGAQgASgOMhEubWFya2V0cGxhY2UuVHlwZRIoCgR0aW1lGAUgASgL",
            "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIVCg1jb3JyZWxhdGlvbklk",
            "GAYgASgJIjoKBERhdGESJwoHcHJvZHVjdBgBIAEoCzIULm1hcmtldHBsYWNl",
            "LlByb2R1Y3RIAEIJCgdwYXlsb2FkIqkBCgdQcm9kdWN0EgoKAmlkGAEgASgJ",
            "Ei0KCWRlbGV0ZWRBdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3Rh",
            "bXASEAoIaW5hY3RpdmUYAyABKAgSFgoOb3JnYW5pemF0aW9uSWQYBCABKAkS",
            "OQoUbGF0ZXN0UHJvZHVjdFZlcnNpb24YBSABKAsyGy5tYXJrZXRwbGFjZS5Q",
            "cm9kdWN0VmVyc2lvbiL5AgoOUHJvZHVjdFZlcnNpb24SCgoCaWQYASABKAkS",
            "DAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRINCgVwcmljZRgE",
            "IAEoCRIRCglwcmljZVVuaXQYBSABKAkSEAoIY3VycmVuY3kYBiABKAkSGgoS",
            "bWluRHVyYXRpb25NaW51dGVzGAcgASgFEhoKEm1heER1cmF0aW9uTWludXRl",
            "cxgIIAEoBRIgChhib29rQWxsTG9jYXRpb25SZXNvdXJjZXMYCSABKAgSHAoU",
            "cmVjdXJyZW5jZVdpbmRvd0RheXMYCiABKAUSHgoWcmVxdWlyZUNvbnNlY3V0",
            "aXZlRGF5cxgLIAEoCBIcChRtYXhCb29raW5nU3ByZWFkRGF5cxgMIAEoBRIf",
            "ChdudW1iZXJPZlJlc291cmNlc1RvQm9vaxgNIAEoBRIVCg1wcm9kdWN0VGFn",
            "SWRzGA4gAygJEhYKDmxvY2F0aW9uVGFnSWRzGA8gAygJKi8KBFR5cGUSEwoP",
            "UHJvZHVjdFVwc2VydGVkEAASEgoOUHJvZHVjdERlbGV0ZWQQAUI6qgI3QXBp",
            "LlNoYXJlZC5DbGllbnRzLkV2ZW50cy5Ta2VkdWxhci5NYXJrZXRwbGFjZS5W",
            "MS5WYWx1ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Event), global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Event.Parser, new[]{ "Metadata", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata), global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata.Parser, new[]{ "Id", "DomainSource", "AppSource", "Type", "Time", "CorrelationId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data), global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data.Parser, new[]{ "Product" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product), global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product.Parser, new[]{ "Id", "DeletedAt", "Inactive", "OrganizationId", "LatestProductVersion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion), global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion.Parser, new[]{ "Id", "Name", "Description", "Price", "PriceUnit", "Currency", "MinDurationMinutes", "MaxDurationMinutes", "BookAllLocationResources", "RecurrenceWindowDays", "RequireConsecutiveDays", "MaxBookingSpreadDays", "NumberOfResourcesToBook", "ProductTagIds", "LocationTagIds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Type {
    [pbr::OriginalName("ProductUpserted")] ProductUpserted = 0,
    [pbr::OriginalName("ProductDeleted")] ProductDeleted = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.MarketplaceV1ValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event(Event other) : this() {
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 1;
    private global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (metadata_ == null) {
              Metadata = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (metadata_ == null) {
              Metadata = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Metadata();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Data();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Metadata : pb::IMessage<Metadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Metadata> _parser = new pb::MessageParser<Metadata>(() => new Metadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Metadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.MarketplaceV1ValueReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata(Metadata other) : this() {
      id_ = other.id_;
      domainSource_ = other.domainSource_;
      appSource_ = other.appSource_;
      type_ = other.type_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      correlationId_ = other.correlationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata Clone() {
      return new Metadata(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "domainSource" field.</summary>
    public const int DomainSourceFieldNumber = 2;
    private string domainSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DomainSource {
      get { return domainSource_; }
      set {
        domainSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "appSource" field.</summary>
    public const int AppSourceFieldNumber = 3;
    private string appSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppSource {
      get { return appSource_; }
      set {
        appSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type type_ = global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 6;
    private string correlationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Metadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Metadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DomainSource != other.DomainSource) return false;
      if (AppSource != other.AppSource) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(Time, other.Time)) return false;
      if (CorrelationId != other.CorrelationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (DomainSource.Length != 0) hash ^= DomainSource.GetHashCode();
      if (AppSource.Length != 0) hash ^= AppSource.GetHashCode();
      if (Type != global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted) hash ^= Type.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (CorrelationId.Length != 0) hash ^= CorrelationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (DomainSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DomainSource);
      }
      if (AppSource.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (DomainSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DomainSource);
      }
      if (AppSource.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (DomainSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DomainSource);
      }
      if (AppSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (CorrelationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrelationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Metadata other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.DomainSource.Length != 0) {
        DomainSource = other.DomainSource;
      }
      if (other.AppSource.Length != 0) {
        AppSource = other.AppSource;
      }
      if (other.Type != global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type.ProductUpserted) {
        Type = other.Type;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.CorrelationId.Length != 0) {
        CorrelationId = other.CorrelationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            DomainSource = input.ReadString();
            break;
          }
          case 26: {
            AppSource = input.ReadString();
            break;
          }
          case 32: {
            Type = (global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 50: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            DomainSource = input.ReadString();
            break;
          }
          case 26: {
            AppSource = input.ReadString();
            break;
          }
          case 32: {
            Type = (global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Type) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 50: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Data : pb::IMessage<Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.MarketplaceV1ValueReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data(Data other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.Product:
          Product = other.Product.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data Clone() {
      return new Data(this);
    }

    /// <summary>Field number for the "product" field.</summary>
    public const int ProductFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product Product {
      get { return payloadCase_ == PayloadOneofCase.Product ? (global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Product;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Product = 1,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Product, other.Product)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Product) hash ^= Product.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.Product) {
        output.WriteRawTag(10);
        output.WriteMessage(Product);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.Product) {
        output.WriteRawTag(10);
        output.WriteMessage(Product);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Product) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Product);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Data other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Product:
          if (Product == null) {
            Product = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product();
          }
          Product.MergeFrom(other.Product);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product subBuilder = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product();
            if (payloadCase_ == PayloadOneofCase.Product) {
              subBuilder.MergeFrom(Product);
            }
            input.ReadMessage(subBuilder);
            Product = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product subBuilder = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.Product();
            if (payloadCase_ == PayloadOneofCase.Product) {
              subBuilder.MergeFrom(Product);
            }
            input.ReadMessage(subBuilder);
            Product = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Product : pb::IMessage<Product>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Product> _parser = new pb::MessageParser<Product>(() => new Product());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Product> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.MarketplaceV1ValueReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product(Product other) : this() {
      id_ = other.id_;
      deletedAt_ = other.deletedAt_ != null ? other.deletedAt_.Clone() : null;
      inactive_ = other.inactive_;
      organizationId_ = other.organizationId_;
      latestProductVersion_ = other.latestProductVersion_ != null ? other.latestProductVersion_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product Clone() {
      return new Product(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deletedAt" field.</summary>
    public const int DeletedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp deletedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DeletedAt {
      get { return deletedAt_; }
      set {
        deletedAt_ = value;
      }
    }

    /// <summary>Field number for the "inactive" field.</summary>
    public const int InactiveFieldNumber = 3;
    private bool inactive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Inactive {
      get { return inactive_; }
      set {
        inactive_ = value;
      }
    }

    /// <summary>Field number for the "organizationId" field.</summary>
    public const int OrganizationIdFieldNumber = 4;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "latestProductVersion" field.</summary>
    public const int LatestProductVersionFieldNumber = 5;
    private global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion latestProductVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion LatestProductVersion {
      get { return latestProductVersion_; }
      set {
        latestProductVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Product);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Product other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(DeletedAt, other.DeletedAt)) return false;
      if (Inactive != other.Inactive) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (!object.Equals(LatestProductVersion, other.LatestProductVersion)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (deletedAt_ != null) hash ^= DeletedAt.GetHashCode();
      if (Inactive != false) hash ^= Inactive.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (latestProductVersion_ != null) hash ^= LatestProductVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (deletedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeletedAt);
      }
      if (Inactive != false) {
        output.WriteRawTag(24);
        output.WriteBool(Inactive);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OrganizationId);
      }
      if (latestProductVersion_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LatestProductVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (deletedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeletedAt);
      }
      if (Inactive != false) {
        output.WriteRawTag(24);
        output.WriteBool(Inactive);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OrganizationId);
      }
      if (latestProductVersion_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LatestProductVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (deletedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeletedAt);
      }
      if (Inactive != false) {
        size += 1 + 1;
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (latestProductVersion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LatestProductVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Product other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.deletedAt_ != null) {
        if (deletedAt_ == null) {
          DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DeletedAt.MergeFrom(other.DeletedAt);
      }
      if (other.Inactive != false) {
        Inactive = other.Inactive;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.latestProductVersion_ != null) {
        if (latestProductVersion_ == null) {
          LatestProductVersion = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion();
        }
        LatestProductVersion.MergeFrom(other.LatestProductVersion);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (deletedAt_ == null) {
              DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeletedAt);
            break;
          }
          case 24: {
            Inactive = input.ReadBool();
            break;
          }
          case 34: {
            OrganizationId = input.ReadString();
            break;
          }
          case 42: {
            if (latestProductVersion_ == null) {
              LatestProductVersion = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion();
            }
            input.ReadMessage(LatestProductVersion);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (deletedAt_ == null) {
              DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeletedAt);
            break;
          }
          case 24: {
            Inactive = input.ReadBool();
            break;
          }
          case 34: {
            OrganizationId = input.ReadString();
            break;
          }
          case 42: {
            if (latestProductVersion_ == null) {
              LatestProductVersion = new global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.ProductVersion();
            }
            input.ReadMessage(LatestProductVersion);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProductVersion : pb::IMessage<ProductVersion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductVersion> _parser = new pb::MessageParser<ProductVersion>(() => new ProductVersion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProductVersion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Marketplace.V1.Value.MarketplaceV1ValueReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductVersion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductVersion(ProductVersion other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      description_ = other.description_;
      price_ = other.price_;
      priceUnit_ = other.priceUnit_;
      currency_ = other.currency_;
      minDurationMinutes_ = other.minDurationMinutes_;
      maxDurationMinutes_ = other.maxDurationMinutes_;
      bookAllLocationResources_ = other.bookAllLocationResources_;
      recurrenceWindowDays_ = other.recurrenceWindowDays_;
      requireConsecutiveDays_ = other.requireConsecutiveDays_;
      maxBookingSpreadDays_ = other.maxBookingSpreadDays_;
      numberOfResourcesToBook_ = other.numberOfResourcesToBook_;
      productTagIds_ = other.productTagIds_.Clone();
      locationTagIds_ = other.locationTagIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductVersion Clone() {
      return new ProductVersion(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 4;
    private string price_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Price {
      get { return price_; }
      set {
        price_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "priceUnit" field.</summary>
    public const int PriceUnitFieldNumber = 5;
    private string priceUnit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PriceUnit {
      get { return priceUnit_; }
      set {
        priceUnit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 6;
    private string currency_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "minDurationMinutes" field.</summary>
    public const int MinDurationMinutesFieldNumber = 7;
    private int minDurationMinutes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MinDurationMinutes {
      get { return minDurationMinutes_; }
      set {
        minDurationMinutes_ = value;
      }
    }

    /// <summary>Field number for the "maxDurationMinutes" field.</summary>
    public const int MaxDurationMinutesFieldNumber = 8;
    private int maxDurationMinutes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxDurationMinutes {
      get { return maxDurationMinutes_; }
      set {
        maxDurationMinutes_ = value;
      }
    }

    /// <summary>Field number for the "bookAllLocationResources" field.</summary>
    public const int BookAllLocationResourcesFieldNumber = 9;
    private bool bookAllLocationResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BookAllLocationResources {
      get { return bookAllLocationResources_; }
      set {
        bookAllLocationResources_ = value;
      }
    }

    /// <summary>Field number for the "recurrenceWindowDays" field.</summary>
    public const int RecurrenceWindowDaysFieldNumber = 10;
    private int recurrenceWindowDays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RecurrenceWindowDays {
      get { return recurrenceWindowDays_; }
      set {
        recurrenceWindowDays_ = value;
      }
    }

    /// <summary>Field number for the "requireConsecutiveDays" field.</summary>
    public const int RequireConsecutiveDaysFieldNumber = 11;
    private bool requireConsecutiveDays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RequireConsecutiveDays {
      get { return requireConsecutiveDays_; }
      set {
        requireConsecutiveDays_ = value;
      }
    }

    /// <summary>Field number for the "maxBookingSpreadDays" field.</summary>
    public const int MaxBookingSpreadDaysFieldNumber = 12;
    private int maxBookingSpreadDays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxBookingSpreadDays {
      get { return maxBookingSpreadDays_; }
      set {
        maxBookingSpreadDays_ = value;
      }
    }

    /// <summary>Field number for the "numberOfResourcesToBook" field.</summary>
    public const int NumberOfResourcesToBookFieldNumber = 13;
    private int numberOfResourcesToBook_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfResourcesToBook {
      get { return numberOfResourcesToBook_; }
      set {
        numberOfResourcesToBook_ = value;
      }
    }

    /// <summary>Field number for the "productTagIds" field.</summary>
    public const int ProductTagIdsFieldNumber = 14;
    private static readonly pb::FieldCodec<string> _repeated_productTagIds_codec
        = pb::FieldCodec.ForString(114);
    private readonly pbc::RepeatedField<string> productTagIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ProductTagIds {
      get { return productTagIds_; }
    }

    /// <summary>Field number for the "locationTagIds" field.</summary>
    public const int LocationTagIdsFieldNumber = 15;
    private static readonly pb::FieldCodec<string> _repeated_locationTagIds_codec
        = pb::FieldCodec.ForString(122);
    private readonly pbc::RepeatedField<string> locationTagIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> LocationTagIds {
      get { return locationTagIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProductVersion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProductVersion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Price != other.Price) return false;
      if (PriceUnit != other.PriceUnit) return false;
      if (Currency != other.Currency) return false;
      if (MinDurationMinutes != other.MinDurationMinutes) return false;
      if (MaxDurationMinutes != other.MaxDurationMinutes) return false;
      if (BookAllLocationResources != other.BookAllLocationResources) return false;
      if (RecurrenceWindowDays != other.RecurrenceWindowDays) return false;
      if (RequireConsecutiveDays != other.RequireConsecutiveDays) return false;
      if (MaxBookingSpreadDays != other.MaxBookingSpreadDays) return false;
      if (NumberOfResourcesToBook != other.NumberOfResourcesToBook) return false;
      if(!productTagIds_.Equals(other.productTagIds_)) return false;
      if(!locationTagIds_.Equals(other.locationTagIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Price.Length != 0) hash ^= Price.GetHashCode();
      if (PriceUnit.Length != 0) hash ^= PriceUnit.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (MinDurationMinutes != 0) hash ^= MinDurationMinutes.GetHashCode();
      if (MaxDurationMinutes != 0) hash ^= MaxDurationMinutes.GetHashCode();
      if (BookAllLocationResources != false) hash ^= BookAllLocationResources.GetHashCode();
      if (RecurrenceWindowDays != 0) hash ^= RecurrenceWindowDays.GetHashCode();
      if (RequireConsecutiveDays != false) hash ^= RequireConsecutiveDays.GetHashCode();
      if (MaxBookingSpreadDays != 0) hash ^= MaxBookingSpreadDays.GetHashCode();
      if (NumberOfResourcesToBook != 0) hash ^= NumberOfResourcesToBook.GetHashCode();
      hash ^= productTagIds_.GetHashCode();
      hash ^= locationTagIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (Price.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Price);
      }
      if (PriceUnit.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PriceUnit);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Currency);
      }
      if (MinDurationMinutes != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(MinDurationMinutes);
      }
      if (MaxDurationMinutes != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MaxDurationMinutes);
      }
      if (BookAllLocationResources != false) {
        output.WriteRawTag(72);
        output.WriteBool(BookAllLocationResources);
      }
      if (RecurrenceWindowDays != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RecurrenceWindowDays);
      }
      if (RequireConsecutiveDays != false) {
        output.WriteRawTag(88);
        output.WriteBool(RequireConsecutiveDays);
      }
      if (MaxBookingSpreadDays != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(MaxBookingSpreadDays);
      }
      if (NumberOfResourcesToBook != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(NumberOfResourcesToBook);
      }
      productTagIds_.WriteTo(output, _repeated_productTagIds_codec);
      locationTagIds_.WriteTo(output, _repeated_locationTagIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (Price.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Price);
      }
      if (PriceUnit.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PriceUnit);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Currency);
      }
      if (MinDurationMinutes != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(MinDurationMinutes);
      }
      if (MaxDurationMinutes != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MaxDurationMinutes);
      }
      if (BookAllLocationResources != false) {
        output.WriteRawTag(72);
        output.WriteBool(BookAllLocationResources);
      }
      if (RecurrenceWindowDays != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RecurrenceWindowDays);
      }
      if (RequireConsecutiveDays != false) {
        output.WriteRawTag(88);
        output.WriteBool(RequireConsecutiveDays);
      }
      if (MaxBookingSpreadDays != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(MaxBookingSpreadDays);
      }
      if (NumberOfResourcesToBook != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(NumberOfResourcesToBook);
      }
      productTagIds_.WriteTo(ref output, _repeated_productTagIds_codec);
      locationTagIds_.WriteTo(ref output, _repeated_locationTagIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Price.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Price);
      }
      if (PriceUnit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PriceUnit);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (MinDurationMinutes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinDurationMinutes);
      }
      if (MaxDurationMinutes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxDurationMinutes);
      }
      if (BookAllLocationResources != false) {
        size += 1 + 1;
      }
      if (RecurrenceWindowDays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RecurrenceWindowDays);
      }
      if (RequireConsecutiveDays != false) {
        size += 1 + 1;
      }
      if (MaxBookingSpreadDays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxBookingSpreadDays);
      }
      if (NumberOfResourcesToBook != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfResourcesToBook);
      }
      size += productTagIds_.CalculateSize(_repeated_productTagIds_codec);
      size += locationTagIds_.CalculateSize(_repeated_locationTagIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProductVersion other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Price.Length != 0) {
        Price = other.Price;
      }
      if (other.PriceUnit.Length != 0) {
        PriceUnit = other.PriceUnit;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.MinDurationMinutes != 0) {
        MinDurationMinutes = other.MinDurationMinutes;
      }
      if (other.MaxDurationMinutes != 0) {
        MaxDurationMinutes = other.MaxDurationMinutes;
      }
      if (other.BookAllLocationResources != false) {
        BookAllLocationResources = other.BookAllLocationResources;
      }
      if (other.RecurrenceWindowDays != 0) {
        RecurrenceWindowDays = other.RecurrenceWindowDays;
      }
      if (other.RequireConsecutiveDays != false) {
        RequireConsecutiveDays = other.RequireConsecutiveDays;
      }
      if (other.MaxBookingSpreadDays != 0) {
        MaxBookingSpreadDays = other.MaxBookingSpreadDays;
      }
      if (other.NumberOfResourcesToBook != 0) {
        NumberOfResourcesToBook = other.NumberOfResourcesToBook;
      }
      productTagIds_.Add(other.productTagIds_);
      locationTagIds_.Add(other.locationTagIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            Price = input.ReadString();
            break;
          }
          case 42: {
            PriceUnit = input.ReadString();
            break;
          }
          case 50: {
            Currency = input.ReadString();
            break;
          }
          case 56: {
            MinDurationMinutes = input.ReadInt32();
            break;
          }
          case 64: {
            MaxDurationMinutes = input.ReadInt32();
            break;
          }
          case 72: {
            BookAllLocationResources = input.ReadBool();
            break;
          }
          case 80: {
            RecurrenceWindowDays = input.ReadInt32();
            break;
          }
          case 88: {
            RequireConsecutiveDays = input.ReadBool();
            break;
          }
          case 96: {
            MaxBookingSpreadDays = input.ReadInt32();
            break;
          }
          case 104: {
            NumberOfResourcesToBook = input.ReadInt32();
            break;
          }
          case 114: {
            productTagIds_.AddEntriesFrom(input, _repeated_productTagIds_codec);
            break;
          }
          case 122: {
            locationTagIds_.AddEntriesFrom(input, _repeated_locationTagIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 34: {
            Price = input.ReadString();
            break;
          }
          case 42: {
            PriceUnit = input.ReadString();
            break;
          }
          case 50: {
            Currency = input.ReadString();
            break;
          }
          case 56: {
            MinDurationMinutes = input.ReadInt32();
            break;
          }
          case 64: {
            MaxDurationMinutes = input.ReadInt32();
            break;
          }
          case 72: {
            BookAllLocationResources = input.ReadBool();
            break;
          }
          case 80: {
            RecurrenceWindowDays = input.ReadInt32();
            break;
          }
          case 88: {
            RequireConsecutiveDays = input.ReadBool();
            break;
          }
          case 96: {
            MaxBookingSpreadDays = input.ReadInt32();
            break;
          }
          case 104: {
            NumberOfResourcesToBook = input.ReadInt32();
            break;
          }
          case 114: {
            productTagIds_.AddEntriesFrom(ref input, _repeated_productTagIds_codec);
            break;
          }
          case 122: {
            locationTagIds_.AddEntriesFrom(ref input, _repeated_locationTagIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
