//----------------------
// <auto-generated>
// Generated using Skedularctl v1.0.0.0. DO NOT EDIT!
// </auto-generated>
//----------------------

using System.Text.RegularExpressions;
using Enterprise.Shared.Events;
using Google.Protobuf.WellKnownTypes;

using NanoidDotNet;

#nullable enable

namespace Api.Shared.Clients.Events.Skedular.Marketplace.V1.Key;

public partial class Metadata : IMetadata { }

[KafkaTopic(
    topicName: "marketplace.v1.event",
    topicPartitionCount: 3,
    retryTopicNamePrefix: "marketplace.v1.event.retry",
    retryTopicCount: 1,
    retryTopicPartitionCount: 3,
    deadLetterTopicName: "marketplace.v1.event.deadletter",
    deadLetterTopicPartitionCount: 3,
    protobufSchema: "syntax = \"proto3\";package marketplace;option csharp_namespace = \"Api.Shared.Clients.Events.Skedular.Marketplace.V1.Key\";message Key {  string productId = 1;}")]
public partial class Key : IMetadataEvent
{
    private static readonly Regex ValidKafkaTopicCharacters =
        new(@"^[a-z0-9\.\-_]+$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private const string TopicName = "marketplace.v1.event";
    private const string RetryTopicNamePrefix = "marketplace.v1.event.retry";
    private const int RetryTopicCount = 1;
    private const string DeadLetterTopicName = "marketplace.v1.event.deadletter";

    public string GetTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? TopicName : $"{prefix}.{TopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public int GetRetryTopicCount() => RetryTopicCount;

    public string GetRetryTopicName(string prefix, int idx)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? $"{RetryTopicNamePrefix}.{idx}" : $"{prefix}.{RetryTopicNamePrefix}.{idx}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string GetDeadLetterTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? DeadLetterTopicName : $"{prefix}.{DeadLetterTopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string? GetCorrelationId() => null;
}
