schema {
  query: Query
  mutation: Mutation
}

type BookingCheckoutSessionDetails {
  uniqueId: ID!
  checkoutUrl: String!
  paymentStatus: PaymentStatus!
}

type BookingConnection {
  pageInfo: PageInfo!
  edges: [BookingEdge!]!
  totalCount: Int
}

type BookingDetails {
  from: DateTime!
  until: DateTime!
  notes: String
  type: BookingTypeDetails!
  status: BookingStatusDetails!
  resources: [BookingResourceDetails!]!
  lineItems: [LineItemDetails!]!
  involvedCustomers: [Booking_CustomerDetails!]!
  involvedOrganizations: [Booking_OrganizationDetails!]!
  involvedLocations: [Booking_LocationDetails!]!
  involvedTeams: [Booking_TeamDetails!]!
  paidByCustomer: Booking_CustomerDetails
  paidByOrganization: Booking_OrganizationDetails
  createdByCustomer: Booking_CustomerDetails
  lastModifiedByCustomer: Booking_CustomerDetails
  deletedByCustomer: Booking_CustomerDetails
  isPaymentRequired: Boolean!
  bookingCheckoutSession: BookingCheckoutSessionDetails
  bookedOnMarketplace: Boolean!
  id: ID!
}

type BookingEdge {
  node: BookingDetails!
  cursor: String!
}

type BookingPayload {
  clientMutationId: String
  booking: BookingDetails!
}

type BookingResourceDetails {
  uniqueId: ID!
  name: String!
  inactive: Boolean!
  color: String
  capacity: Int!
  requireBookingApproval: Boolean!
  location: Booking_LocationDetails
  customTags: [Booking_OrganizationCustomTagDetails!]!
  zones: [Booking_OrganizationZoneDetails!]!
  customers: [Booking_CustomerDetails!]!
}

type BookingStatusDetails {
  type: BookingStatus!
  name: String!
}

type BookingTypeDetails {
  type: BookingType!
  name: String!
}

type Booking_CurrencyDetails {
  type: Currency!
  name: String!
}

type Booking_CustomerDetails {
  uniqueId: ID!
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
}

type Booking_LocationDetails {
  uniqueId: ID!
  name: String!
}

type Booking_OrganizationCustomTagDetails {
  uniqueId: ID!
  name: String
  color: String
}

type Booking_OrganizationDetails {
  uniqueId: ID!
  name: String!
}

type Booking_OrganizationZoneDetails {
  uniqueId: ID!
  name: String
  color: String
}

type Booking_PriceUnitDetails {
  type: PriceUnit!
  name: String!
}

type Booking_ProductVersionDetails {
  uniqueId: ID!
  name: String!
  price: String!
  priceToDisplay: String!
  priceUnit: Booking_PriceUnitDetails!
  currency: Booking_CurrencyDetails!
  organization: Booking_OrganizationDetails!
}

type Booking_TeamDetails {
  uniqueId: ID!
  name: String!
}

type LineItemDetails {
  productVersion: Booking_ProductVersionDetails!
  quantity: Int!
}

type Mutation {
  addBooking(input: AddBookingInput!): BookingPayload @cost(weight: "10")
  updateBooking(input: UpdateBookingInput!): BookingPayload @cost(weight: "10")
  deleteBooking(input: DeleteBookingInput!): BookingPayload @cost(weight: "10")
}

type OrganizationAvailableResources {
  resourcesCount: Int!
  availableResourcesCount: Int!
}

type OrganizationBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  bookingVersion: Version!
  bookingCustomerRecordSynced: Boolean! @cost(weight: "10")
  bookingTypes: [BookingTypeDetails!]!
  marketplaceBookingTypes: [BookingTypeDetails!]!
  bookingStatuses: [BookingStatusDetails!]!
  booking(id: String!): BookingDetails @cost(weight: "10")
  bookings(after: String first: Int before: String last: Int where: BookingWhereInput! orderBy: [BookingOrderInput!]): BookingConnection! @cost(weight: "10")
  allBookings(where: BookingWhereInput!): [BookingDetails!]! @cost(weight: "10")
  organizationBookingPermissions(organizationId: String!): OrganizationBookingPermissions! @cost(weight: "10")
  teamBookingPermissions(teamId: String!): TeamBookingPermissions! @cost(weight: "10")
  availableResources(where: AvailableResourcesWhereInput!): [BookingResourceDetails!]! @cost(weight: "10")
  organizationResourcesAvailability(where: OrganizationAvailableResourcesWhereInput!): OrganizationAvailableResources! @cost(weight: "10")
}

type TeamBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddBookingInput {
  clientMutationId: String
  id: String
  customerIds: [String!]!
  organizationIds: [String!]!
  teamIds: [String!]!
  from: DateTime!
  until: DateTime!
  notes: String
  type: BookingType!
  resourceIds: [String!]!
  lineItems: [LineItemInput!]!
}

input AvailableResourcesWhereInput {
  organizationId: String!
  locationId: String
  from: DateTime!
  until: DateTime!
  customTagIds: [String!]
  zoneIds: [String!]
  resourceIdsToInclude: [String!]
  productId: String
}

input BookingOrderInput {
  direction: OrderDirection!
  field: BookingOrderField!
}

input BookingWhereInput {
  fromGt: DateTime
  fromGte: DateTime
  fromLt: DateTime
  fromLte: DateTime
  toGt: DateTime
  toGte: DateTime
  toLt: DateTime
  toLte: DateTime
  notesContains: String
  type: BookingType
  status: BookingStatus
  nameContains: String
  organizationIds: [String!]
  locationIds: [String!]
  teamIds: [String!]
  customerIds: [String!]
  includeMineOnly: Boolean
  includeFutureBookingsOnly: Boolean
}

input DeleteBookingInput {
  clientMutationId: String
  id: String!
}

input LineItemInput {
  productVersionId: String!
  quantity: Int!
}

input OrganizationAvailableResourcesWhereInput {
  organizationId: String!
  from: DateTime!
  until: DateTime!
}

input UpdateBookingInput {
  clientMutationId: String
  id: String!
  customerIds: [String!]!
  organizationIds: [String!]!
  teamIds: [String!]!
  from: DateTime!
  until: DateTime!
  notes: String
  type: BookingType!
  resourceIds: [String!]!
}

enum BookingOrderField {
  From
  To
  Notes
  Type
  Status
}

enum BookingStatus {
  Pending
  Rejected
  Confirmed
  PaymentExpired
  PaymentRecordNeverCreated
}

enum BookingType {
  WorkingFromHome
  WorkingFromOffice
  WorkingFromCoworkingSpace
  SickLeave
  AnnualLeave
  WellbeingLeave
  ClientOffice
  Vacation
  TravelingForWork
  NonWorkingDay
}

enum Currency {
  Nzd
  Usd
}

enum OrderDirection {
  Ascending
  Descending
}

enum PaymentStatus {
  NoPaymentRequired
  Pending
  Paid
  Unpaid
}

enum PriceUnit {
  PerMinute
  PerHour
  PerUse
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")