schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type BookingCategoryDetails {
  category: BookingCategory!
  name: String!
}

type BookingChannelDetails {
  channel: BookingChannel!
  name: String!
}

type BookingCheckoutSessionDetails {
  uniqueId: ID!
  checkoutUrl: String!
}

type BookingDetails {
  involvedCustomers: [CustomerDetails!]!
  createdByCustomer: CustomerDetails
  lastModifiedByCustomer: CustomerDetails
  deletedByCustomer: CustomerDetails
  involvedOrganizations: [OrganizationDetails!]!
  involvedLocations: [LocationDetails!]!
  involvedTeams: [TeamDetails!]!
  from: DateTime!
  until: DateTime!
  notes: String
  category: BookingCategoryDetails!
  channel: BookingChannelDetails!
  bookingResources: [BookingResourceDetails!]!
  marketplaceBooking: MarketplaceBookingDetails
  hasRecurringInstanceOverrides: Boolean
  id: ID!
}

type BookingEdge {
  node: BookingDetails!
  cursor: String!
}

type BookingFrequencyDetails {
  frequency: BookingFrequency!
  name: String!
}

type BookingPayload {
  clientMutationId: String
  booking: BookingDetails!
}

type BookingRecurrenceEndTypeDetails {
  endType: RecurringBookingEndType!
  name: String!
}

type BookingResourceDetails {
  resource: ResourceDetails!
  location: LocationDetails
  customers: [CustomerDetails!]!
}

type ConnectionOfBookingEdge {
  pageInfo: PageInfo!
  edges: [BookingEdge!]!
  totalCount: Int!
}

type CustomerDetails {
  id: ID!
}

type DayOfWeekDetails {
  dayOfWeek: DayOfWeek!
  name: String!
}

type LineItemDetails {
  productVersion: ProductVersionDetails!
  quantity: Int!
}

type LocationDetails {
  id: ID!
}

type MarketplaceBookingDetails {
  paidByCustomer: CustomerDetails
  paidByOrganization: OrganizationDetails
  lineItems: [LineItemDetails!]!
  paymentMethod: PaymentMethodTypeDetails!
  totalAmountExcludeTax: Decimal
  totalAmountExcludeTaxToDisplay: String!
  taxAmount: Decimal
  taxAmountToDisplay: String!
  taxRatePercentage: Decimal
  taxRatePercentageToDisplay: String!
  totalAmount: Decimal
  totalAmountToDisplay: String!
  currency: String
  currencyToDisplay: String!
  invoiceUrl: String
  invoiceNumber: String
  invoiceEmailList: [String!]!
  isPaymentRequired: Boolean!
  bookingCheckoutSession: BookingCheckoutSessionDetails
  paymentExpiry: DateTime!
  paymentStatus: PaymentStatusDetails!
  id: ID!
}

type Mutation {
  addPrivateBooking(input: AddPrivateBookingInput!): BookingPayload! @cost(weight: "10")
  updatePrivateBooking(input: UpdatePrivateBookingInput!): BookingPayload! @cost(weight: "10")
  deletePrivateBooking(input: DeletePrivateBookingInput!): BookingPayload! @cost(weight: "10")
  addMarketplaceBooking(input: AddMarketplaceBookingInput!): BookingPayload! @cost(weight: "10")
  updateMarketplaceBooking(input: UpdateMarketplaceBookingInput!): BookingPayload! @cost(weight: "10")
  deleteMarketplaceBooking(input: DeleteMarketplaceBookingInput!): BookingPayload! @cost(weight: "10")
  confirmBookingPayment(input: ConfirmBookingPaymentInput!): BookingPayload! @cost(weight: "10")
  rejectBookingPayment(input: RejectBookingPaymentInput!): BookingPayload! @cost(weight: "10")
  makeBookingPaymentNotRequired(input: MakeBookingPaymentNotRequiredInput!): BookingPayload! @cost(weight: "10")
  addPrivateRecurringBooking(input: AddPrivateRecurringBookingInput!): RecurringBookingPayload! @cost(weight: "10")
  updatePrivateRecurringBooking(input: UpdatePrivateRecurringBookingInput!): RecurringBookingPayload! @cost(weight: "10")
  deletePrivateRecurringBooking(input: DeletePrivateRecurringBookingInput!): RecurringBookingPayload! @cost(weight: "10")
}

type OrganizationAvailableResources {
  resourcesCount: Int!
  availableResourcesCount: Int!
}

type OrganizationBookingPermissions {
  canViewBookings: Boolean!
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
  canModifyPaymentMethod: Boolean!
}

type OrganizationDetails {
  uniqueAlphanumericName: String
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type PaymentMethodTypeDetails {
  type: PaymentMethod!
  name: String!
}

type PaymentStatusDetails {
  type: PaymentStatus!
  name: String!
}

type ProductVersionDetails {
  id: ID!
}

type Query {
  bookingCategories: [BookingCategoryDetails!]!
  marketplaceBookingCategories: [BookingCategoryDetails!]!
  booking(id: String!): BookingDetails @cost(weight: "10")
  bookingById(id: String!): BookingDetails @lookup @internal @cost(weight: "10")
  bookings(after: String first: Int before: String last: Int where: BookingWhereInput! orderBy: [BookingOrderInput!]): ConnectionOfBookingEdge! @cost(weight: "10")
  allBookings(where: BookingWhereInput!): [BookingDetails!]! @cost(weight: "10")
  paymentMethodTypes: [PaymentMethodTypeDetails!]!
  paymentStatuses: [PaymentStatusDetails!]!
  organizationBookingPermissions(organizationId: String organizationUniqueAlphanumericName: String): OrganizationBookingPermissions! @cost(weight: "10")
  teamBookingPermissions(teamId: String!): TeamBookingPermissions! @cost(weight: "10")
  availableResources(where: AvailableResourcesWhereInput!): [BookingResourceDetails!]! @cost(weight: "10")
  organizationResourcesAvailability(where: OrganizationAvailableResourcesWhereInput!): OrganizationAvailableResources! @cost(weight: "10")
  bookingVersion: Version!
  bookingCustomerRecordSynced: Boolean! @cost(weight: "10")
}

type RecurringBookingDetails {
  involvedCustomers: [CustomerDetails!]!
  createdByCustomer: CustomerDetails
  lastModifiedByCustomer: CustomerDetails
  deletedByCustomer: CustomerDetails
  involvedOrganizations: [OrganizationDetails!]!
  involvedTeams: [TeamDetails!]!
  from: DateTime!
  until: DateTime!
  category: BookingCategoryDetails!
  channel: BookingChannelDetails!
  frequency: BookingFrequencyDetails!
  interval: Int!
  byMonthDay: Int
  bySetPosition: Int
  byWeekDays: [DayOfWeekDetails!]!
  endType: BookingRecurrenceEndTypeDetails!
  startDate: DateTime!
  endDate: DateTime
  occurrenceCount: Int
  skippedDates: [DateTime!]!
  id: ID!
}

type RecurringBookingPayload {
  clientMutationId: String
  recurringBooking: RecurringBookingDetails!
}

type ResourceDetails {
  id: ID!
}

type Subscription {
  booking(id: String!): BookingDetails!
}

type TeamBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
}

type TeamDetails {
  id: ID!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddMarketplaceBookingInput {
  clientMutationId: String
  id: String
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  from: DateTime!
  until: DateTime!
  notes: String
  category: BookingCategory
  resourceIds: [String!]
  lineItems: [LineItemInput!]!
  paymentMethod: PaymentMethod!
  invoiceEmailList: [String!]
}

input AddPrivateBookingInput {
  clientMutationId: String
  id: String
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  from: DateTime!
  until: DateTime!
  notes: String
  category: BookingCategory
  resourceIds: [String!]
}

input AddPrivateRecurringBookingInput {
  clientMutationId: String
  id: String
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  from: DateTime!
  until: DateTime!
  frequency: BookingFrequency!
  interval: Int!
  byMonthDay: Int
  bySetPosition: Int
  byWeekDays: [DayOfWeek!]!
  endType: RecurringBookingEndType!
  startDate: DateTime!
  endDate: DateTime
  occurrenceCount: Int
  skippedDates: [DateTime!]
  category: BookingCategory
}

input AvailableResourcesWhereInput {
  organizationId: String
  organizationUniqueAlphanumericName: String
  locationId: String
  from: DateTime!
  until: DateTime!
  customTagIds: [String!]
  zoneIds: [String!]
  resourceIdsToInclude: [String!]
  productId: String
}

input BookingOrderInput {
  direction: OrderDirection!
  field: BookingOrderField!
}

input BookingWhereInput {
  fromGt: DateTime
  fromGte: DateTime
  fromLt: DateTime
  fromLte: DateTime
  toGt: DateTime
  toGte: DateTime
  toLt: DateTime
  toLte: DateTime
  notesContains: String
  category: BookingCategory
  channel: BookingChannel
  paymentStatuses: [PaymentStatus!]
  nameContains: String
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  locationIds: [String!]
  teamIds: [String!]
  customerIds: [String!]
  includeMineOnly: Boolean
  includeFutureBookingsOnly: Boolean
}

input ConfirmBookingPaymentInput {
  clientMutationId: String
  id: String!
}

input DeleteMarketplaceBookingInput {
  clientMutationId: String
  id: String!
}

input DeletePrivateBookingInput {
  clientMutationId: String
  id: String!
}

input DeletePrivateRecurringBookingInput {
  clientMutationId: String
  id: String!
}

input LineItemInput {
  productVersionId: String!
  quantity: Int!
}

input MakeBookingPaymentNotRequiredInput {
  clientMutationId: String
  id: String!
}

input OrganizationAvailableResourcesWhereInput {
  organizationId: String
  organizationUniqueAlphanumericName: String
  from: DateTime!
  until: DateTime!
}

input RejectBookingPaymentInput {
  clientMutationId: String
  id: String!
}

input UpdateMarketplaceBookingInput {
  clientMutationId: String
  id: String!
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  notes: String
  category: BookingCategory
}

input UpdatePrivateBookingInput {
  clientMutationId: String
  id: String!
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  from: DateTime!
  until: DateTime!
  notes: String
  category: BookingCategory
  resourceIds: [String!]
}

input UpdatePrivateRecurringBookingInput {
  clientMutationId: String
  id: String!
  customerIds: [String!]!
  organizationIds: [String!]
  organizationUniqueAlphanumericNames: [String!]
  teamIds: [String!]
  from: DateTime!
  until: DateTime!
  frequency: BookingFrequency!
  interval: Int!
  byMonthDay: Int
  bySetPosition: Int
  byWeekDays: [DayOfWeek!]!
  endType: RecurringBookingEndType!
  startDate: DateTime!
  endDate: DateTime
  occurrenceCount: Int
  skippedDates: [DateTime!]
  category: BookingCategory
}

enum BookingCategory {
  WORKING_FROM_HOME
  WORKING_FROM_OFFICE
  WORKING_FROM_COWORKING_SPACE
  SICK_LEAVE
  ANNUAL_LEAVE
  WELLBEING_LEAVE
  CLIENT_OFFICE
  VACATION
  TRAVELING_FOR_WORK
  NON_WORKING_DAY
}

enum BookingChannel {
  PRIVATE
  MARKETPLACE
}

enum BookingFrequency {
  DAILY
  WEEKLY
  MONTHLY
}

enum BookingOrderField {
  FROM
  TO
  NOTES
  CATEGORY
  CHANNEL
}

enum DayOfWeek {
  SUNDAY
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

enum PaymentMethod {
  CARD
  BANK_TRANSFER
}

enum PaymentStatus {
  PENDING
  REJECTED
  CONFIRMED
  EXPIRED
  RECORD_NEVER_CREATED
  NO_PAYMENT_REQUIRED
}

enum RecurringBookingEndType {
  NEVER
  UNTIL_DATE
  AFTER_OCCURRENCES
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

directive @internal on FIELD_DEFINITION

directive @lookup on FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")

"The `Decimal` scalar type represents a decimal floating-point number."
scalar Decimal