<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\Api.Shared.Clients\Api.Shared.Clients.csproj"/>
        <ProjectReference Include="..\..\..\shared\Api.Shared.Services\Api.Shared.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Database\Migrations\20250831062335_ReplacedLocationContactDetailsWithExtraMetadata.cs"/>
        <Compile Remove="Database\Migrations\20250831062335_ReplacedLocationContactDetailsWithExtraMetadata.Designer.cs"/>
        <Compile Remove="Database\Migrations\20250831063001_ReplacedLocationContactDetailsWithExtraMetadata.cs"/>
        <Compile Remove="Database\Migrations\20250831063001_ReplacedLocationContactDetailsWithExtraMetadata.Designer.cs"/>
    </ItemGroup>

</Project>
