// <auto-generated />
using System;
using Customer.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Shared.Database.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260416052935_MakeOutboxJsonProviderAgnostic")]
    partial class MakeOutboxJsonProviderAgnostic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer.Shared.Database.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultOrganizationId")
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsOnboardingDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PersonalInformationVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("VISIBLE");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl192")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl24")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl32")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl48")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl512")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoUrl72")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DefaultOrganizationId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Designation");

                    b.HasIndex("FamilyName");

                    b.HasIndex("GivenName");

                    b.HasIndex("IsOnboardingDone");

                    b.HasIndex("Locale");

                    b.HasIndex("MiddleName");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Name");

                    b.HasIndex("PersonalInformationVisibility");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Timezone");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.CustomerBillingDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Coordinates")
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OsmId")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OsmType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Coordinates");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OsmId");

                    b.HasIndex("OsmType");

                    b.HasIndex("PlaceId");

                    b.ToTable("CustomerBillingDetails");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.CustomerFeedback", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("WEB");

                    b.Property<string>("Content")
                        .HasMaxLength(10240)
                        .HasColumnType("character varying(10240)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("CustomerFeedback");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Identity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Email");

                    b.HasIndex("EmailVerified");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Type");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsOwnershipVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PRIVATE");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomDomain")
                        .IsUnique();

                    b.HasIndex("DeletedAt");

                    b.HasIndex("IsOwnershipVerified");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationMember");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationSsoSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AppFederationMetadataUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationSsoSetting");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationTag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Type");

                    b.ToTable("OrganizationTag");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripeCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("StripeCustomer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripePaymentIntent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Currency");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("StripePaymentMethodId");

                    b.ToTable("StripePaymentIntent");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripePaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CardCountry")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CardDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte?>("CardExpiryMonth")
                        .HasColumnType("smallint");

                    b.Property<short?>("CardExpiryYear")
                        .HasColumnType("smallint");

                    b.Property<string>("CardFingerprint")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CardFunding")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CardIssuer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CardLastFourDigit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("EntityFrameworkVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SetupIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SetupIntentId")
                        .IsUnique();

                    b.HasIndex("CardExpiryMonth", "CardExpiryYear");

                    b.ToTable("StripePaymentMethod");
                });

            modelBuilder.Entity("CustomerLocation", b =>
                {
                    b.Property<string>("PreferredByCustomersId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredLocationsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("PreferredByCustomersId", "PreferredLocationsId");

                    b.HasIndex("PreferredLocationsId");

                    b.ToTable("CustomerLocation");
                });

            modelBuilder.Entity("CustomerLocation1", b =>
                {
                    b.Property<string>("FavouredByCustomersId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FavouriteLocationsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("FavouredByCustomersId", "FavouriteLocationsId");

                    b.HasIndex("FavouriteLocationsId");

                    b.ToTable("CustomerLocation1");
                });

            modelBuilder.Entity("CustomerOrganizationTag", b =>
                {
                    b.Property<string>("PreferredByCustomersId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredOrganizationTagsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("PreferredByCustomersId", "PreferredOrganizationTagsId");

                    b.HasIndex("PreferredOrganizationTagsId");

                    b.ToTable("CustomerOrganizationTag");
                });

            modelBuilder.Entity("CustomerResource", b =>
                {
                    b.Property<string>("PreferredByCustomersId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredResourcesId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("PreferredByCustomersId", "PreferredResourcesId");

                    b.HasIndex("PreferredResourcesId");

                    b.ToTable("CustomerResource");
                });

            modelBuilder.Entity("Enterprise.Shared.Outbox.Kafka.KafkaOutbox", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastRetry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ProcessingErrors")
                        .HasMaxLength(102400)
                        .HasColumnType("character varying(102400)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)");

                    b.HasKey("Id");

                    b.HasIndex("LastRetry");

                    b.HasIndex("RetryCount");

                    b.ToTable("KafkaOutbox");
                });

            modelBuilder.Entity("Enterprise.Shared.Outbox.Temporal.TemporalOutbox", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExecutionArgs")
                        .HasMaxLength(10240)
                        .HasColumnType("character varying(10240)");

                    b.Property<DateTimeOffset?>("LastRetry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingErrors")
                        .HasMaxLength(102400)
                        .HasColumnType("character varying(102400)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LastRetry");

                    b.HasIndex("RetryCount");

                    b.ToTable("TemporalOutbox");
                });

            modelBuilder.Entity("Enterprise.Shared.Outbox.Temporal.TemporalSignalOutbox", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExecutionArgs")
                        .HasMaxLength(10240)
                        .HasColumnType("character varying(10240)");

                    b.Property<DateTimeOffset?>("LastRetry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingErrors")
                        .HasMaxLength(102400)
                        .HasColumnType("character varying(102400)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("WorkflowSignalOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastRetry");

                    b.HasIndex("RetryCount");

                    b.ToTable("TemporalSignalOutbox");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Customer", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Organization", "DefaultOrganization")
                        .WithMany("DefaultedByCustomers")
                        .HasForeignKey("DefaultOrganizationId");

                    b.Navigation("DefaultOrganization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.CustomerBillingDetails", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithOne("BillingDetails")
                        .HasForeignKey("Customer.Shared.Database.Entities.CustomerBillingDetails", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.CustomerFeedback", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("CustomerFeedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Identity", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("Identities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Location", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("Locations")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationMember", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationSsoSetting", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Organization", "Organization")
                        .WithOne("OrganizationSsoSettings")
                        .HasForeignKey("Customer.Shared.Database.Entities.OrganizationSsoSetting", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.OrganizationTag", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("Tags")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Resource", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Location", "Location")
                        .WithMany("Resources")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripeCustomer", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithOne("StripeCustomer")
                        .HasForeignKey("Customer.Shared.Database.Entities.StripeCustomer", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripePaymentIntent", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.StripePaymentMethod", "StripePaymentMethod")
                        .WithMany("StripePaymentIntents")
                        .HasForeignKey("StripePaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StripePaymentMethod");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripePaymentMethod", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("StripePaymentMethods")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerLocation", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("PreferredByCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer.Shared.Database.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("PreferredLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerLocation1", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("FavouredByCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer.Shared.Database.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("FavouriteLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerOrganizationTag", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("PreferredByCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer.Shared.Database.Entities.OrganizationTag", null)
                        .WithMany()
                        .HasForeignKey("PreferredOrganizationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerResource", b =>
                {
                    b.HasOne("Customer.Shared.Database.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("PreferredByCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer.Shared.Database.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("PreferredResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Customer", b =>
                {
                    b.Navigation("BillingDetails");

                    b.Navigation("CustomerFeedbacks");

                    b.Navigation("Identities");

                    b.Navigation("OrganizationMembers");

                    b.Navigation("StripeCustomer");

                    b.Navigation("StripePaymentMethods");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Location", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.Organization", b =>
                {
                    b.Navigation("DefaultedByCustomers");

                    b.Navigation("Locations");

                    b.Navigation("OrganizationMembers");

                    b.Navigation("OrganizationSsoSettings");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Customer.Shared.Database.Entities.StripePaymentMethod", b =>
                {
                    b.Navigation("StripePaymentIntents");
                });
#pragma warning restore 612, 618
        }
    }
}
