schema {
  query: BillingQuery
  mutation: BillingMutation
}

type BillingMutation {
  setOrganizationBillingInfo(input: SetOrganizationBillingInfoInput!): OrganizationBillingInfoPayload
}

type BillingQuery {
  billingVersion: Version!
  billingCustomerRecordSynced: Boolean!
  organizationCurrentOfferingCharges(organizationId: String!): [OrganizationCurrentOfferingChargesDetails!]
  organizationBillingInfo(organizationId: String!): OrganizationBillingInfo
}

type OrganizationBillingInfo {
  organizationId: ID!
  email: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
}

type OrganizationBillingInfoPayload {
  clientMutationId: String
  organizationBillingInfo: OrganizationBillingInfo!
}

type OrganizationCurrentOfferingChargesDetails {
  offeringName: String!
  start: DateTime!
  end: DateTime!
  totalNumberOfActiveCustomers: Int!
  unitPrice: Int!
  totalCost: Int!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input SetOrganizationBillingInfoInput {
  clientMutationId: String
  organizationId: String!
  email: String
  addressLine1: String
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String
  country: String
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")