schema {
  query: BookingQuery
  mutation: BookingMutation
}

type BookingConnection {
  pageInfo: PageInfo!
  edges: [BookingEdge!]!
  totalCount: Int
}

type BookingCustomerDetails {
  uniqueId: ID!
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
}

type BookingDeskDetails {
  uniqueId: ID!
  name: String!
  deactivated: Boolean!
  requireBookingApproval: Boolean!
  location: BookingLocationDetails
  deskTypes: [BookingOrganizationDeskTypeDetails!]!
  zones: [BookingOrganizationZoneDetails!]!
}

type BookingDetails {
  from: DateTime!
  to: DateTime!
  notes: String
  customer: BookingCustomerDetails!
  organization: BookingOrganizationDetails
  location: BookingLocationDetails
  desks: [BookingDeskDetails!]!
  team: BookingTeamDetails
  id: ID!
}

type BookingEdge {
  node: BookingDetails!
  cursor: String!
}

type BookingLocationDetails {
  uniqueId: ID!
  name: String!
}

type BookingMutation {
  addBooking(input: AddBookingInput!): BookingPayload
  updateBooking(input: UpdateBookingInput!): BookingPayload
  deleteBooking(input: DeleteBookingInput!): BookingPayload
}

type BookingOrganizationDeskTypeDetails {
  uniqueId: ID!
  name: String!
}

type BookingOrganizationDetails {
  uniqueId: ID!
  name: String!
}

type BookingOrganizationZoneDetails {
  uniqueId: ID!
  name: String!
}

type BookingPayload {
  clientMutationId: String
  booking: BookingDetails!
}

type BookingQuery {
  bookingVersion: Version!
  bookingCustomerRecordSynced: Boolean!
  booking(id: String!): BookingDetails
  bookings(after: String first: Int before: String last: Int where: BookingWhereInput! orderBy: [BookingOrderInput!]): BookingConnection
  allBookings(where: BookingWhereInput!): [BookingDetails!]
  availableDesks(where: AvailableDesksWhereInput!): [BookingDeskDetails!]
  organizationBookingPermissions(organizationId: String!): OrganizationBookingPermissions
  locationBookingPermissions(locationId: String!): LocationBookingPermissions
  teamBookingPermissions(teamId: String!): TeamBookingPermissions
}

type BookingTeamDetails {
  uniqueId: ID!
  name: String!
}

type LocationBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canUpdateBookingOnBehalf: Boolean!
  canDeleteBookingOnBehalf: Boolean!
}

type OrganizationBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canUpdateBookingOnBehalf: Boolean!
  canDeleteBookingOnBehalf: Boolean!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type TeamBookingPermissions {
  canAddBooking: Boolean!
  canUpdateBooking: Boolean!
  canDeleteBooking: Boolean!
  canAddBookingOnBehalf: Boolean!
  canUpdateBookingOnBehalf: Boolean!
  canDeleteBookingOnBehalf: Boolean!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddBookingInput {
  clientMutationId: String
  id: String
  customerId: String!
  from: DateTime!
  to: DateTime!
  notes: String
  organizationId: String
  locationId: String
  deskIds: [String!]!
  teamId: String
}

input AvailableDesksWhereInput {
  organizationId: String
  locationId: String
  date: DateTime!
  deskIdsToInclude: [String!]
  deskTypeIds: [String!]
  zoneIds: [String!]
  combineDeskTypesZones: Boolean
}

input BookingOrderInput {
  direction: OrderDirection!
  field: BookingOrderField!
}

input BookingWhereInput {
  fromGT: DateTime
  fromGTE: DateTime
  fromLT: DateTime
  fromLTE: DateTime
  toGT: DateTime
  toGTE: DateTime
  toLT: DateTime
  toLTE: DateTime
  notesContains: String
  nameContains: String
  organizationIds: [String!]
  locationIds: [String!]
  teamIds: [String!]
  includeMineOnly: Boolean
  includeFutureBookingsOnly: Boolean
  combineOrganizationsLocationsTeams: Boolean
}

input DeleteBookingInput {
  clientMutationId: String
  id: String!
}

input UpdateBookingInput {
  clientMutationId: String
  id: String!
  customerId: String!
  from: DateTime!
  to: DateTime!
  notes: String
  organizationId: String
  locationId: String
  deskIds: [String!]!
  teamId: String
}

enum BookingOrderField {
  From
  To
  Notes
  Name
  GivenName
  MiddleName
  FamilyName
  OrganizationName
  LocationName
  TeamName
}

enum OrderDirection {
  Ascending
  Descending
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")