schema {
  query: CustomerQuery
  mutation: CustomerMutation
}

type CustomerConnection {
  pageInfo: PageInfo!
  edges: [CustomerEdge!]!
  totalCount: Int
}

type CustomerDeskDetails {
  uniqueId: ID!
  name: String
}

type CustomerDetails {
  createdAt: DateTime!
  email: String
  identities: [CustomerEmail!]!
  designation: String
  title: String
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
  timezone: String
  locale: String
  isOrganizationOnboardingDone: Boolean!
  isLocationOnboardingDone: Boolean!
  isTeamOnboardingDone: Boolean!
  isDefaultOrganizationOnboardingDone: Boolean!
  isDefaultLocationOnboardingDone: Boolean!
  isPreferredZoneOnboardingDone: Boolean!
  isPreferredDeskOnboardingDone: Boolean!
  defaultLocations: [CustomerLocationDetails!]!
  defaultTeams: [CustomerTeamDetails!]!
  defaultOrganization: CustomerOrganizationDetails
  preferredZones: [CustomerOrganizationTagDetails!]!
  preferredDeskTypes: [CustomerOrganizationTagDetails!]!
  preferredDesks: [CustomerDeskDetails!]!
  id: ID!
}

type CustomerEdge {
  node: CustomerDetails!
  cursor: String!
}

type CustomerEmail {
  email: String
  verified: Boolean!
  id: ID!
}

type CustomerLocationDetails {
  uniqueId: ID!
  name: String
  organization: CustomerOrganizationDetails
}

type CustomerMutation {
  completeOrganizationOnboarding(input: CompleteOrganizationOnboardingInput!): CustomerPayload
  completeLocationOnboarding(input: CompleteLocationOnboardingInput!): CustomerPayload
  completeTeamOnboarding(input: CompleteTeamOnboardingInput!): CustomerPayload
  completeDefaultOrganizationOnboarding(input: CompleteDefaultOrganizationOnboardingInput!): CustomerPayload
  completeDefaultLocationOnboarding(input: CompleteDefaultLocationOnboardingInput!): CustomerPayload
  completePreferredZoneOnboarding(input: CompletePreferredZoneOnboardingInput!): CustomerPayload
  completePreferredDeskOnboarding(input: CompletePreferredDeskOnboardingInput!): CustomerPayload
  addCustomerDefaultLocation(input: AddCustomerDefaultLocationInput!): CustomerPayload
  removeCustomerDefaultLocation(input: RemoveCustomerDefaultLocationInput!): CustomerPayload
  addCustomerDefaultTeam(input: AddCustomerDefaultTeamInput!): CustomerPayload
  removeCustomerDefaultTeam(input: RemoveCustomerDefaultTeamInput!): CustomerPayload
  setCustomerDefaultOrganization(input: SetCustomerDefaultOrganizationInput!): CustomerPayload
  clearCustomerDefaultOrganization(input: ClearCustomerDefaultOrganizationInput!): CustomerPayload
  addCustomerDefaultDesk(input: AddCustomerDefaultDeskInput!): CustomerPayload
  removeCustomerDefaultDesk(input: RemoveCustomerDefaultDeskInput!): CustomerPayload
  submitCustomerFeedback(input: SubmitCustomerFeedbackInput!): SubmitCustomerFeedbackPayload
  updateMyCustomerDetails(input: UpdateMyCustomerDetailsInput!): CustomerPayload
  addCustomerDefaultOrganizationTag(input: AddCustomerDefaultOrganizationTagInput!): CustomerPayload
  removeCustomerDefaultOrganizationTag(input: RemoveCustomerDefaultOrganizationTagInput!): CustomerPayload
}

type CustomerOrganizationDetails {
  uniqueId: ID!
  name: String
  logoUrl: String
}

type CustomerOrganizationTagDetails {
  uniqueId: ID!
  name: String
}

type CustomerPayload {
  clientMutationId: String
  customer: CustomerDetails!
}

type CustomerQuery {
  customerVersion: Version!
  me: CustomerDetails
  customersByDefaultLocation(after: String first: Int before: String last: Int where: CustomerWhereInput! orderBy: [CustomerOrderInput!]): CustomerConnection
}

type CustomerTeamDetails {
  uniqueId: ID!
  name: String
  organization: CustomerOrganizationDetails
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type SubmitCustomerFeedbackPayload {
  clientMutationId: String
  id: ID!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddCustomerDefaultDeskInput {
  clientMutationId: String
  deskId: String!
}

input AddCustomerDefaultLocationInput {
  clientMutationId: String
  locationId: String!
}

input AddCustomerDefaultOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input AddCustomerDefaultTeamInput {
  clientMutationId: String
  teamId: String!
}

input ClearCustomerDefaultOrganizationInput {
  clientMutationId: String
}

input CompleteDefaultLocationOnboardingInput {
  clientMutationId: String
}

input CompleteDefaultOrganizationOnboardingInput {
  clientMutationId: String
}

input CompleteLocationOnboardingInput {
  clientMutationId: String
}

input CompleteOrganizationOnboardingInput {
  clientMutationId: String
}

input CompletePreferredDeskOnboardingInput {
  clientMutationId: String
}

input CompletePreferredZoneOnboardingInput {
  clientMutationId: String
}

input CompleteTeamOnboardingInput {
  clientMutationId: String
}

input CustomerOrderInput {
  direction: OrderDirection!
  field: CustomerOrderField!
}

input CustomerWhereInput {
  locationId: String!
  nameContains: String
}

input RemoveCustomerDefaultDeskInput {
  clientMutationId: String
  deskId: String!
}

input RemoveCustomerDefaultLocationInput {
  clientMutationId: String
  locationId: String!
}

input RemoveCustomerDefaultOrganizationTagInput {
  clientMutationId: String
  organizationTagId: String!
}

input RemoveCustomerDefaultTeamInput {
  clientMutationId: String
  teamId: String!
}

input SetCustomerDefaultOrganizationInput {
  clientMutationId: String
  organizationId: String!
}

input SubmitCustomerFeedbackInput {
  clientMutationId: String
  id: String
  feedbackContent: String!
  channel: FeedbackChannel!
}

input UpdateMyCustomerDetailsInput {
  clientMutationId: String
  timezone: String
  designation: String
  title: String
  name: String
  givenName: String
  middleName: String
  familyName: String
}

enum CustomerOrderField {
  Designation
  Title
  Name
  GivenName
  MiddleName
  FamilyName
  Timezone
  Locale
}

enum FeedbackChannel {
  Web
  Slack
  MsTeams
}

enum OrderDirection {
  Ascending
  Descending
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")