schema {
  query: OrganizationQuery
  mutation: OrganizationMutation
}

type AcceptInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type CancelInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type CancelOrganizationOfferingPayload {
  clientMutationId: String
}

type InviteCustomersToJoinOrganizationPayload {
  clientMutationId: String
}

type OrganizationAnalytics {
  memberAttendancePercentage: [OrganizationMemberAttendancePercentage!]!
  dailyBookingsTotals: [OrganizationDailyBookingsTotal!]!
}

type OrganizationAvailableOfferingDetails {
  code: String!
  name: String!
  unitPrice: Int!
  featureSet: [OrganizationFeatureSetDetails!]!
  free: Boolean!
}

type OrganizationConnection {
  pageInfo: PageInfo!
  edges: [OrganizationEdge!]!
  totalCount: Int
}

type OrganizationCustomerDetails {
  uniqueId: ID!
  email: String
  name: String
  givenName: String
  middleName: String
  familyName: String
  photoUrl: String
  photoUrl24: String
  photoUrl32: String
  photoUrl48: String
  photoUrl72: String
  photoUrl192: String
  photoUrl512: String
}

type OrganizationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type OrganizationDetails {
  name: String!
  about: String
  website: String
  logoUrl: String
  agreedToTermsOfUse: Boolean!
  termsOfUse: OrganizationTermsOfUse
  industrySubCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  availableOfferings: [OrganizationAvailableOfferingDetails!]!
  offering: OrganizationOfferingDetails!
  hasAttachedPaymentMethod: Boolean!
  hasFutureBooking: Boolean!
  hasLocation: Boolean!
  hasTeam: Boolean!
  canModify: Boolean!
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canViewAnalytics: Boolean!
  isMyOnboardingDone: Boolean!
  members: [OrganizationMemberDetails!]!
  id: ID!
}

type OrganizationEdge {
  node: OrganizationDetails!
  cursor: String!
}

type OrganizationFeatureSetDetails {
  name: String!
  description: String!
}

type OrganizationIndustryMainCategoryReferenceDetails {
  name: String!
  subCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  id: ID!
}

type OrganizationIndustrySubCategoryReferenceDetails {
  name: String!
  mainCategoryName: String!
  id: ID!
}

type OrganizationMemberAttendancePercentage {
  date: DateTime!
  percentage: Float!
}

type OrganizationMemberConnection {
  pageInfo: PageInfo!
  edges: [OrganizationMemberEdge!]!
  totalCount: Int
}

type OrganizationMemberDetails {
  membershipType: OrganizationMemberMembershipType
  isOrganizationOnboardingDone: Boolean!
  customer: OrganizationCustomerDetails!
  id: ID!
}

type OrganizationMemberDetailsPayload {
  clientMutationId: String
  member: OrganizationMemberDetails
}

type OrganizationMemberEdge {
  node: OrganizationMemberDetails!
  cursor: String!
}

type OrganizationMemberPayload {
  clientMutationId: String
}

type OrganizationMutation {
  addOrganization(input: AddOrganizationInput!): OrganizationPayload
  updateOrganization(input: UpdateOrganizationInput!): OrganizationPayload
  deleteOrganization(input: DeleteOrganizationInput!): OrganizationPayload
  updateOrganizationOffering(input: UpdateOrganizationOfferingInput!): UpdateOrganizationOfferingPayload
  cancelOrganizationOffering(input: CancelOrganizationOfferingInput!): CancelOrganizationOfferingPayload
  changeOrganizationMemberOwnershipType(input: ChangeOrganizationMemberOwnershipTypeInput!): OrganizationMemberDetailsPayload
  inviteCustomersToJoinOrganization(input: InviteCustomersToJoinOrganizationInput!): InviteCustomersToJoinOrganizationPayload
  acceptInvitationToJoinOrganization(input: AcceptInvitationToJoinOrganizationInput!): AcceptInvitationToJoinOrganizationPayload
  rejectInvitationToJoinOrganization(input: RejectInvitationToJoinOrganizationInput!): RejectInvitationToJoinOrganizationPayload
  cancelInvitationToJoinOrganization(input: CancelInvitationToJoinOrganizationInput!): CancelInvitationToJoinOrganizationPayload
  completeOrganizationMemberOnboarding(input: CompleteOrganizationMemberOnboardingInput!): OrganizationMemberPayload
  addDeskType(input: AddDeskTypeInput!): OrganizationTagPayload
  updateDeskType(input: UpdateDeskTypeInput!): OrganizationTagPayload
  deleteDeskType(input: DeleteDeskTypeInput!): OrganizationTagPayload
  addZone(input: AddZoneInput!): OrganizationTagPayload
  updateZone(input: UpdateZoneInput!): OrganizationTagPayload
  deleteZone(input: DeleteZoneInput!): OrganizationTagPayload
}

type OrganizationOfferingDetails {
  code: String!
  name: String!
  start: DateTime!
  end: DateTime!
  unitPrice: Int!
  featureSet: [OrganizationFeatureSetDetails!]!
  free: Boolean!
  id: ID!
}

type OrganizationPayload {
  clientMutationId: String
  organization: OrganizationDetails!
}

type OrganizationQuery {
  organizationVersion: Version!
  organizationCustomerRecordSynced: Boolean!
  activeOrganizationTermsOfUse: OrganizationTermsOfUse!
  organizationMemberMembershipTypes: [OrganizationMemberMembershipType!]!
  organizationIndustryMainCategoriesReferences: [OrganizationIndustryMainCategoryReferenceDetails!]!
  organization(id: String!): OrganizationDetails
  organizations(after: String first: Int before: String last: Int where: OrganizationWhereInput! orderBy: [OrganizationOrderInput!]): OrganizationConnection
  myOrganizations: [OrganizationDetails!]
  organizationMembers(after: String first: Int before: String last: Int where: OrganizationMemberWhereInput! orderBy: [OrganizationMemberOrderInput!]): OrganizationMemberConnection
  organizationAnalytics(organizationId: String! from: DateTime! until: DateTime!): OrganizationAnalytics
  isAzureTenantInstalled: Boolean!
  azureTenantAdminConsentUrl: String!
  azureTenantOrganization: OrganizationDetails
  deskTypes(after: String first: Int before: String last: Int where: DeskTypeOrganizationTagWhereInput! orderBy: [OrganizationTagOrderInput!]): OrganizationTagConnection
  zones(after: String first: Int before: String last: Int where: ZoneOrganizationTagWhereInput! orderBy: [OrganizationTagOrderInput!]): OrganizationTagConnection
}

type OrganizationTagConnection {
  pageInfo: PageInfo!
  edges: [OrganizationTagEdge!]!
  totalCount: Int
}

type OrganizationTagDetails {
  name: String!
  description: String
  tagType: String!
  id: ID!
}

type OrganizationTagEdge {
  node: OrganizationTagDetails!
  cursor: String!
}

type OrganizationTagPayload {
  clientMutationId: String
  organizationTag: OrganizationTagDetails!
}

type OrganizationTermsOfUse {
  terms: String!
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type RejectInvitationToJoinOrganizationPayload {
  clientMutationId: String
}

type UpdateOrganizationOfferingPayload {
  clientMutationId: String
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AcceptInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input AddDeskTypeInput {
  clientMutationId: String
  id: String
  name: String!
  description: String
  organizationId: String!
}

input AddOrganizationInput {
  clientMutationId: String
  id: String
  name: String!
  about: String
  website: String
  agreedToTermsOfUse: Boolean!
  termsOfUseId: String!
  industrySubCategoryIds: [String!]!
}

input AddZoneInput {
  clientMutationId: String
  id: String
  name: String!
  description: String
  organizationId: String!
}

input CancelInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input CancelOrganizationOfferingInput {
  clientMutationId: String
  id: String!
}

input ChangeOrganizationMemberOwnershipTypeInput {
  clientMutationId: String
  id: String!
  membershipType: OrganizationMemberMembershipType!
}

input CompleteOrganizationMemberOnboardingInput {
  clientMutationId: String
  organizationId: String!
}

input DeleteDeskTypeInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationInput {
  clientMutationId: String
  id: String!
}

input DeleteZoneInput {
  clientMutationId: String
  id: String!
}

input DeskTypeOrganizationTagWhereInput {
  organizationId: String!
  nameContains: String
}

input InviteCustomersToJoinOrganizationInput {
  clientMutationId: String
  organizationId: String!
  emails: [String!]!
}

input OrganizationMemberOrderInput {
  direction: OrderDirection!
  field: OrganizationMemberOrderField!
}

input OrganizationMemberWhereInput {
  organizationId: String!
  nameContains: String
}

input OrganizationOrderInput {
  direction: OrderDirection!
  field: OrganizationOrderField!
}

input OrganizationTagOrderInput {
  direction: OrderDirection!
  field: OrganizationTagOrderField!
}

input OrganizationWhereInput {
  nameContains: String
}

input RejectInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input UpdateDeskTypeInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
}

input UpdateOrganizationInput {
  clientMutationId: String
  id: String!
  name: String!
  about: String
  website: String
  industrySubCategoryIds: [String!]!
}

input UpdateOrganizationOfferingInput {
  clientMutationId: String
  id: String!
  offeringCode: String!
}

input UpdateZoneInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
}

input ZoneOrganizationTagWhereInput {
  organizationId: String!
  nameContains: String
}

enum OrderDirection {
  Ascending
  Descending
}

enum OrganizationMemberMembershipType {
  Owner
  Administrator
  Member
}

enum OrganizationMemberOrderField {
  MembershipType
  Name
  GivenName
  MiddleName
  FamilyName
}

enum OrganizationOrderField {
  Name
}

enum OrganizationTagOrderField {
  Name
  Description
  TagType
}

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")