schema {
  query: PaymentQuery
  mutation: PaymentMutation
}

type AddOrganizationPaymentMethodIntentResponse {
  clientMutationId: String
  publishedKeys: String!
  clientSecret: String!
}

type OrganizationPaymentMethod {
  cardBrand: String
  cardCountry: String
  cardDescription: String
  cardExpiryMonth: Int
  cardExpiryYear: Int
  cardFingerprint: String
  cardFunding: String
  cardIssuer: String
  cardLastFourDigit: String
  id: ID!
}

type PaymentMutation {
  addOrganizationPaymentMethodIntent(input: AddOrganizationPaymentMethodIntentInput!): AddOrganizationPaymentMethodIntentResponse
  removeOrganizationPaymentMethod(input: RemoveOrganizationPaymentMethodInput!): RemoveOrganizationPaymentMethodResponse
}

type PaymentQuery {
  paymentVersion: Version!
  paymentCustomerRecordSynced: Boolean!
  organizationPaymentMethodsDetails(organizationId: String!): [OrganizationPaymentMethod!]
}

type RemoveOrganizationPaymentMethodResponse {
  clientMutationId: String
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AddOrganizationPaymentMethodIntentInput {
  clientMutationId: String
  organizationId: String!
}

input RemoveOrganizationPaymentMethodInput {
  clientMutationId: String
  id: String!
}