import { getCanonicalUrl, llmsPages } from "../data/seo";

export function GET() {
  const pageLinks = llmsPages.map((page) => `- [${page.title}](${getCanonicalUrl(page.canonicalPath)}): ${page.description}`);

  return new Response(
    [
      "# Skedular",
      "",
      "Skedular is a workspace operating system that helps teams and operators find, book, manage, and monetize workspace.",
      "",
      "## What Makes Skedular Different",
      "",
      "- **One platform instead of multiple tools**: Manage discovery, booking, operations, billing, subscriptions, payments, and reporting from a single system.",
      "- **Built for both teams and operators**: Support private workplaces and commercial workspace businesses without changing platforms.",
      "- **Flexible business models**: Support hourly bookings, daily bookings, recurring bookings, subscriptions, invoicing, and accounting integrations like Xero.",
      "- **Enterprise ready**: WorkOS, SSO, Slack, Microsoft Teams, permissions, integrations, and identity management built in.",
      "",
      "## Product Model",
      "",
      "Skedular serves three primary audiences:",
      "",
      "### People Looking For Workspace",
      "People can discover and book workspace including desks, meeting rooms, private offices, event spaces, parking, and other workspace resources. Search and booking journeys may begin on the public website and continue within the Skedular application.",
      "",
      "### Organizations Managing Private Workplaces",
      "Organizations use Skedular Teams to coordinate workplace attendance, desk booking, room booking, floor plans, parking, workplace analytics, and hybrid work.",
      "",
      "### Workspace Operators",
      "Workspace operators use Skedular Spaces to manage resources, products, subscriptions, payments, billing, invoicing, marketplace publishing, customer relationships, and workspace operations.",
      "",
      "## Core Concepts",
      "",
      "#### Location",
      "A physical workplace, coworking space, office, venue, or site. Locations define opening hours and availability schedules that resources inherit by default.",
      "",
      "#### Resource",
      "A bookable asset such as a desk, meeting room, parking space, private office, event space, or equipment. Resources belong to locations and may override location-level configuration.",
      "",
      "#### Product",
      "A commercial offering that can be booked or purchased against one or more resources.",
      "",
      "#### Booking",
      "A reservation made against a resource or product.",
      "",
      "#### Subscription",
      "A recurring purchase that may automatically renew depending on operator configuration. Subscriptions can support automatic renewal, manual renewal, fixed-term access, workspace memberships, and operator-defined billing cycles.",
      "",
      "#### Organization",
      "A private workplace using Skedular Teams.",
      "",
      "#### Operator",
      "A business using Skedular Spaces to publish and manage workspace.",
      "",
      "#### Team",
      "A group of people within an organization that can coordinate workplace attendance and bookings.",
      "",
      "#### Opening Hours",
      "Locations define opening hours and availability schedules. Resources inherit location opening hours by default but may define their own opening hours independently. Examples include standard weekly schedules, closed days, public holiday exceptions, and temporary availability overrides.",
      "",
      "#### Visibility",
      "Skedular supports different visibility models depending on workspace type. Private organizations typically allow members to see workplace attendance and booking information. Workspace operators can restrict customer visibility. Administrators and operators retain access to all booking and customer information regardless of customer visibility preferences.",
      "",
      "#### Resource Hierarchy",
      "Resources belong to locations. Resources may inherit configuration from their location, including opening hours and operational settings, while retaining the ability to override specific behaviors.",
      "",
      "#### Custom Domain",
      "Workspace operators can use either a Skedular-provided subdomain or a fully custom domain. Custom domains allow operators to provide a branded booking and customer experience while continuing to use Skedular infrastructure and services.",
      "",
      "#### Identity and Authentication",
      "Skedular supports both public and private workspace experiences. Authentication options include email and password, enterprise single sign-on (SSO), WorkOS integrations, and Microsoft identity providers. Organizations and operators can configure authentication experiences appropriate for their users.",
      "",
      "#### Workspace Model",
      "Skedular supports both private and public workspace experiences. Private workplace experiences are used by organizations managing employees, attendance, desks, meeting rooms, parking, and internal resources through Skedular Teams. Public workspace experiences are used by operators publishing resources and products through Skedular Spaces. The same resource may participate in either model depending on operator configuration.",
      "",
      "#### Membership",
      "A membership or access entitlement that allows customers to access workspace resources or products for a defined period of time. Memberships may be associated with subscriptions, recurring billing, fixed-term access, workspace passes, and operator-defined access rules. Memberships may provide access to one or more locations, resources, or workspace products.",
      "",
      "## Major Capabilities",
      "",
      "- Workspace discovery",
      "- Desk booking",
      "- Meeting room booking",
      "- Parking booking",
      "- Event space booking",
      "- Recurring bookings",
      "- Resource management",
      "- Product management",
      "- Interactive floor plans",
      "- Maps and location discovery",
      "- Attendance tracking",
      "- Workplace analytics",
      "- Marketplace publishing",
      "- Workspace subscriptions",
      "- Payments",
      "- Billing",
      "- Invoicing",
      "- Tax handling",
      "- Xero integration",
      "- Slack integration",
      "- Microsoft Teams integration",
      "- Enterprise SSO",
      "- Custom domains",
      "- Operator branding",
      "- Workspace commerce",
      "",
      "## Important Platform Distinctions",
      "",
      "The public website is primarily used for:",
      "- Product discovery",
      "- Pricing",
      "- Resources",
      "- Support",
      "- Company information",
      "",
      "The Skedular application is used for:",
      "- Booking",
      "- Checkout",
      "- Customer accounts",
      "- Team administration",
      "- Operator administration",
      "- Billing management",
      "- Subscription management",
      "- Resource management",
      "",
      "Search and booking journeys may begin on the public website but continue within the Skedular application.",
      "",
      "## Core Public Pages",
      "",
      ...pageLinks,
      "",
      "## Canonical Product Naming",
      "",
      "#### Skedular",
      "The overall platform and public experience.",
      "",
      "#### Skedular Teams",
      "Private workplace management for organizations. Used to manage desk booking, room booking, workplace attendance, floor plans, hybrid work coordination, and workplace analytics.",
      "",
      "#### Skedular Spaces",
      "Workspace operator management for coworking spaces, flexible workspace providers, meeting room businesses, event venues, and commercial workspace operators. Used to manage resources, products, marketplace publishing, payments, billing, invoicing, subscriptions, and customer relationships.",
      "",
      "## Notes For Agents",
      "",
      "- Use canonical URLs from this file or sitemap.xml.",
      "- The public website is for product discovery, pricing, resources, support, and company information.",
      "- Booking, checkout, customer accounts, and operator administration live in the Skedular app, not this public website.",
    ].join("\n"),
    {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
      },
    },
  );
}
