import { getCanonicalUrl, llmsPages } from "../data/seo";

export function GET() {
  const pageLinks = llmsPages.map(
    (page) =>
      `- [${page.title}](${getCanonicalUrl(page.canonicalPath)}): ${page.description}`,
  );

  return new Response(
    [
      "# Skedular Platform Documentation",
      "",
      "## Product Overview",
      "",
      "Skedular is a workspace operating system that helps teams, operators, and independent hosts find, book, manage, and monetize workspace. The platform serves three primary audiences through separate but integrated products:",
      "",
      "**Skedular Teams** is designed for organizations managing private workplaces. These organizations typically include enterprises, hybrid work companies, and private office operators who need desk booking, room booking, office attendance coordination, and workplace analytics. Teams uses a Monthly Active User (MAU) pricing model and focuses on internal workplace management workflows.",
      "",
      "**Skedular Spaces** is designed for workspace operators running commercial spaces. These include coworking spaces, flexible workspace providers, shared offices, and commercial workspace operators who need memberships, billing, invoicing, marketplace publishing, and workspace discovery. Spaces uses a booking instance-based pricing model and focuses on commercial workspace operations.",
      "",
      "**Skedular Host** is designed for individuals and small independent hosts renting one whole place per location. A Host Organization is a dedicated organization type for this audience, utilizing the same underlying platform as Skedular Spaces but with an intentionally simplified administration experience. Hosts manage places rather than coworking infrastructure, and the platform automatically prepares the required marketplace configuration. Hosts configure listing details, flexible pricing tiers, cancellation policies, and Stripe Connect, then publish explicitly. Host has no monthly software subscription in the current offering and uses a 5% commission per successful paid card booking.",
      "",
      "The platform philosophy is to provide a unified workspace operating system that connects private workplace management with commercial workspace operations. Organizations using Skedular Teams can eventually discover and book workspace capacity from operators using Skedular Spaces while preserving the operational workflows of both products.",
      "",
      "## Domain Model",
      "",
      "### Location",
      "A Location represents a physical workspace site. Locations contain bookable resources and are owned by organizations. Each location has its own availability patterns, operating hours, and resource configurations. Locations can be private (internal to an organization) or public (published to the marketplace). Host organizations may manage multiple independently rentable locations; each Host location represents one independently rentable place and maintains its own pricing, policies, availability, and publication state.",
      "",
      "### Resource",
      "A Resource is a bookable space within a location. Resources include desks, meeting rooms, parking spaces, event spaces, and other bookable assets. Each resource has capacity limits, availability rules, and pricing configurations. Resources are grouped into products for pricing and availability management.",
      "",
      "### Product",
      "A Product is a pricing and availability template for resources. Products define how resources are priced, when they are available, and what booking rules apply. Products can be one-time (single booking) or recurring (subscription-based). Products have versions that track pricing changes over time. The ownership chain is ProductVersion → Product → Organization, which determines pricing context, tax settings, and organization billing cycle.",
      "",
      "### Booking",
      "A Booking represents a one-time reservation of a resource. Bookings have start and end times, resource assignments, customer information, and payment status. Bookings can be private (internal team use) or marketplace (customer-facing). Bookings carry confirmation, payment, attendance, and completion states.",
      "",
      "### Booking Instance",
      "A Booking Instance is an individual occurrence of a booking. For one-time bookings, the booking and instance are the same. For recurring bookings generated from subscriptions, each occurrence is a separate booking instance. Booking instances are the canonical unit for usage counting and billing calculations.",
      "",
      "### Subscription",
      "A Subscription represents recurring membership with automatic renewal. Subscriptions generate booking instances on a schedule (daily, weekly, monthly, etc.). Subscriptions have billing cycles, renewal terms, and cancellation policies. Subscriptions can be fixed-term or auto-renewing. Marketplace subscriptions are maintained by Temporal workflows that handle renewal, resource reconciliation, and billing.",
      "",
      "### Membership",
      "A Membership defines customer access rights within an organization. Memberships determine which locations, resources, and products a customer can access. Memberships can be tied to subscriptions or granted directly. Memberships carry expiration dates, access levels, and usage limits.",
      "",
      "### Organization",
      "An Organization is the tenant entity that owns locations, products, and billing configuration. Organizations have billing modes, tax settings, payment methods, and integration configurations. Organizations can have multiple locations and serve both internal teams and external customers. Organizations are the source of truth for pricing context and billing cycle configuration.",
      "",
      "### Host Listing Model",
      "The relationship for Host listings is: Organization → Location → Place → Marketplace Product → Bookings.",
      "Each Host location represents one independently rentable place. Each location automatically receives a marketplace product. Hosts configure pricing, availability, and policies rather than creating multiple marketplace products manually.",
      "",
      "### Booking Consistency",
      "The platform automatically maintains the relationships between the place being rented, the underlying booking infrastructure, pricing, and active bookings. Hosts never manage these relationships directly, ensuring booking consistency while providing a simplified owner experience.",
      "",
      "### Operator",
      "An Operator is a workspace operator using Skedular Spaces. Operators manage locations, publish to marketplace, handle bookings, process payments, and manage memberships. Operators have access to operational workflows including inventory management, pricing configuration, and customer administration.",
      "",
      "### Team",
      "A Team is a group of users within an organization. Teams are used in Skedular Teams for organizing users, assigning permissions, and managing workplace access. Teams can have team-specific booking rules, resource allocations, and attendance coordination workflows.",
      "",
      "### Entity Relationships",
      "",
      "**Location → Resource → Product → Booking → Subscription → Membership**",
      "",
      "Locations contain resources. Resources are grouped into products with pricing and availability rules. Bookings reserve resources according to product configurations. Subscriptions generate recurring booking instances. Memberships grant customer access to products and locations.",
      "",
      "**Ownership Chain**: ProductVersion → Product → Organization",
      "",
      "This chain determines pricing context, tax settings, and organization billing cycle. When pricing changes, a new ProductVersion is created while the Product and Organization remain stable.",
      "",
      "## Product Philosophy",
      "",
      "The Skedular platform is designed around audience-specific philosophies to optimize workflows for different users:",
      "- **Skedular Teams is user-first**: Focused on the employee experience and internal coordination.",
      "- **Skedular Spaces is resource-first**: Focused on the operational management of coworking assets and memberships.",
      "- **Skedular Host is place-first**: Focused on the rental of a specific physical property or space.",
      "Although all three products share the same booking engine and platform, each intentionally presents a workflow optimized for its audience.",
      "",
      "## Product Architecture",
      "",
      "### Skedular",
      "Skedular is the overarching platform that encompasses Teams, Spaces, and Host. The shared platform provides common infrastructure including authentication, billing, marketplace, and integration services. Skedular domains include Location, Team, Marketplace, Booking, Customer, Core, and Organization.",
      "",
      "### Skedular Teams",
      "Skedular Teams is the product for organizations managing private workplaces. Teams focuses on:",
      "- Desk booking and room booking for internal use",
      "- Office attendance coordination and hybrid work scheduling",
      "- Workplace analytics and utilization reporting",
      "- Team-based access control and permissions",
      "- Slack and Microsoft Teams integrations for workplace coordination",
      "",
      "Teams is designed for enterprises and private office operators who need to manage internal workplace capacity without commercial marketplace workflows. Teams uses MAU-based pricing and does not include marketplace publishing or customer-facing booking flows.",
      "",
      "### Skedular Spaces",
      "Skedular Spaces is the product for workspace operators running commercial spaces. Spaces focuses on:",
      "- Coworking operations and member management",
      "- Billing, invoicing, and subscription management",
      "- Marketplace publishing and public listings",
      "- Workspace discovery and customer booking",
      "- Custom domains and operator branding",
      "- Xero accounting integration for invoice export",
      "",
      "Spaces is designed for coworking spaces, flexible workspace providers, and commercial operators who need to monetize workspace capacity. Spaces uses booking instance-based pricing and includes full marketplace, billing, and customer management workflows.",
      "",
      "### Skedular Host",
      "Skedular Host is the product for independent hosts renting a property, room, desk, studio, venue, parking space, or similar place. Host is designed for those who think about renting places rather than managing resources, intentionally hiding coworking concepts and booking infrastructure.",
      "",
      "Creating a Host organization automatically bootstraps the marketplace configuration required for renting places. Hosts are not expected to configure marketplace infrastructure, resources, product tags, or booking configurations; these exist internally but are handled by the platform.",
      "",
      "Every Host listing begins as a private draft. This draft-first publishing model is a deliberate product philosophy; a listing only becomes discoverable after a sequence of listing completion, pricing configuration, payment configuration, verification, and explicit publication.",
      "",
      "Host focuses on:",
      "- Place-first setup with no visible resource or product-tag administration",
      "- Automatically provisioned private product drafts",
      "- Hourly, daily, weekly, monthly, and longer-term pricing tiers",
      "- Card payment through Stripe and connected-account payouts",
      "- Owner-facing renter, booking, cancellation, refund, and payment administration",
      "",
      "Each Host location represents one whole bookable place. Every Host booking reserves the entire place represented by the Host location, rather than individual bookable resources. The booking engine automatically manages the underlying booking infrastructure while presenting a simplified place-first workflow to Hosts.",
      "",
      "### Why Separate Products",
      "Teams, Spaces, and Host are separate products because they serve different audiences with different workflows:",
      "- Teams serves internal workplace management (private, MAU pricing, no marketplace)",
      "- Spaces serves commercial workspace operations (public, usage pricing, marketplace included)",
      "- Host serves independent place rentals (public after activation, 5% paid-booking commission, simplified marketplace setup)",
      "",
      "Separating the products allows each to optimize for its use case without forcing unnecessary complexity on the other audience. Teams users don't need marketplace workflows, and Spaces operators don't need internal team coordination features.",
      "",
      "### Choosing Between Host and Spaces",
      "Users should choose **Skedular Host** when they:",
      "- Rent one or more independently bookable places",
      "- Do not want coworking administration",
      "- Prefer automatic booking setup",
      "- Prefer commission-based pricing",
      "- Only need to manage listings, pricing, bookings, and renters",
      "",
      "Users should choose **Skedular Spaces** when they:",
      "- Operate coworking or flexible workspace businesses",
      "- Manage multiple resources within a single location",
      "- Sell memberships and subscriptions",
      "- Require professional invoicing and tax management",
      "- Operate commercial workspace businesses",
      "- Require full workspace administration and member management",
      "",
      "### Shared Concepts",
      "Both products share:",
      "- Location and resource management",
      "- Booking and availability logic",
      "- Organization and customer entities",
      "- Authentication and SSO via WorkOS",
      "- Slack and Microsoft Teams integrations",
      "- Core platform infrastructure",
      "",
      "### Terminology Differences",
      '- Teams uses "team" for user groups, Spaces uses "member" for customers',
      '- Teams uses "private booking" for internal use, Spaces uses "marketplace booking" for customer-facing',
      "- Teams pricing is MAU-based, Spaces pricing is booking instance-based",
      '- Teams focuses on "workplace analytics", Spaces focuses on "revenue reporting"',
      "",
      "### Integration Strategy",
      "The long-term integration strategy is to allow Teams organizations to discover and book Spaces locations through the marketplace while preserving the operational workflows of both products. This means Teams users can access commercial workspace capacity without leaving their Teams interface, while Spaces operators can serve Teams customers without adopting Teams workflows.",
      "",
      "## Host Pricing Model",
      "",
      "Skedular Host follows a commission-based pricing philosophy designed for independent hosts who may have occasional rather than continuous bookings.",
      "",
      "Hosts can create organizations, locations, listings, pricing, and policies without paying a monthly software subscription. Skedular only earns revenue after a successful paid booking. This aligns the platform's success with the host's success, removing the financial barrier to entry for small-scale independent rentals.",
      "",
      "## Host Administration",
      "",
      'Hosts manage the conceptual "Place" and its rental terms rather than the underlying technical infrastructure.',
      "",
      "**Hosts manage:**",
      "- Listings, images, and amenities",
      "- Pricing and opening hours",
      "- Availability and cancellation policies",
      "- Bookings, renters, and payments",
      "- Refunds and listing publication state",
      "",
      "**Hosts do NOT manage:**",
      "- Resources or marketplace product entities",
      "- Booking infrastructure",
      "- Coworking-specific administration (e.g., membership tiers, complex resource grouping)",
      "",
      "### Host Availability Model",
      "Availability is managed at the place level. Confirmed bookings reserve the entire place, and overlapping bookings are prevented. Availability follows the configured opening hours, pricing options, and booking rules.",
      "",
      "### Host Owner Journey",
      "Host registration → Create organization → Add place → Configure pricing → Connect Stripe → Publish listing → Receive bookings → Receive payouts → Manage ongoing bookings",
      "",
      "## Booking Lifecycle",
      "",
      "### Discovery",
      "Users discover available workspace through search, browse, or direct links. For Teams users, discovery is internal to their organization's locations. For marketplace customers, discovery is through the public marketplace search and browse interface. Discovery considers location, resource type, availability, pricing, and booking rules.",
      "",
      "### Selection",
      "Users select a specific resource and time slot. Selection checks real-time availability, applies booking rules (minimum booking duration, advance booking window, maximum booking duration), and calculates pricing. For marketplace bookings, selection also considers product pricing, tax settings, and payment requirements.",
      "",
      "### Booking",
      "Users create a booking by providing required information (customer details, payment method, special requests). The booking is validated against resource availability, booking rules, and customer eligibility. For marketplace bookings, payment is processed during booking creation. For private bookings, payment may be handled separately through billing cycles or invoicing.",
      "",
      "### Confirmation",
      "After successful booking creation and payment (if required), the booking is confirmed. Confirmation sends notifications to the user and operator (if applicable), updates availability, and generates calendar invitations. Confirmation state is persisted to prevent double-booking.",
      "",
      "### Payment",
      "For marketplace bookings, payment is processed during booking creation using Stripe. Payment can be immediate (card) or deferred (invoice). For private bookings, payment may be handled through organization billing cycles or invoicing. Payment state is tracked separately from booking state to support payment retries, refunds, and accounting reconciliation.",
      "",
      "### Attendance",
      "Users check in to their booking through the platform or integrations (Slack, Teams, kiosk). Attendance tracking supports utilization reporting and no-show policies. Attendance can be manual (user check-in) or automatic (integration own-sensor based).",
      "",
      "### Completion",
      "When the booking end time passes, the booking moves to completed state. Completion triggers availability release, utilization reporting updates, and post-booking workflows (feedback requests, follow-up communications). Completed bookings are retained for reporting and audit purposes.",
      "",
      "### Reporting",
      "Completed bookings contribute to utilization reports, revenue reports, and analytics. Reporting can be real-time (dashboard queries) or batch (scheduled reports). Reporting considers booking instances, cancellations, no-shows, and attendance patterns.",
      "",
      "### Booking Types",
      "",
      "**One-Time Bookings**: Single reservation with defined start and end time. Used for ad-hoc desk booking, meeting room booking, and event space booking.",
      "",
      "**Recurring Bookings**: Series of bookings generated from a schedule. Used for recurring desk reservations, regular meeting room bookings, and subscription-based access. Recurring bookings generate individual booking instances for each occurrence.",
      "",
      "**Event Bookings**: Bookings for events with multiple resources, attendees, and special requirements. Event bookings can span multiple days and involve complex resource allocations.",
      "",
      "## Subscription Lifecycle",
      "",
      "### Creation",
      "Subscriptions are created when customers purchase recurring access. Creation captures product selection, billing cycle, renewal terms, and payment method. Creation generates the first billing period and initial booking instances. Creation triggers payment processing and subscription activation.",
      "",
      "### Renewal",
      "Subscriptions renew automatically at the end of each billing period unless cancelled. Renewal generates the next billing period, processes payment, and creates booking instances for the new period. Renewal can fail if payment fails or pricing is no longer available. Failed renewals may trigger retry logic or subscription suspension.",
      "",
      "### Fixed Term Subscriptions",
      "Fixed term subscriptions run for a defined number of billing periods and then expire. Fixed term subscriptions do not auto-renew. At term end, the subscription moves to expired state and no further booking instances are generated. Fixed term subscriptions are used for pilot programs, seasonal access, and promotional offers.",
      "",
      "### Auto-Renewing Subscriptions",
      "Auto-renewing subscriptions renew automatically at each billing period end. Auto-renewal continues until explicitly cancelled or payment failure threshold is reached. Auto-renewing subscriptions are the default for ongoing membership access. Auto-renewal can be configured to require customer confirmation before each new period.",
      "",
      "### Membership Subscriptions",
      "Membership subscriptions grant access rights rather than specific resource bookings. Membership subscriptions may or may not generate booking instances depending on configuration. Membership subscriptions are used for all-access passes, tiered memberships, and operator-defined access tiers.",
      "",
      "### Billing Cycles",
      "Billing cycles define when subscriptions renew and when invoices are generated. Supported cycles include weekly, fortnightly, and monthly. Billing cycles are configured at the organization level and can be overridden per product. Billing cycles determine arrears calculation timing and invoice generation schedules.",
      "",
      "### Cancellation Handling",
      "Cancellation can be immediate or scheduled for period end. Immediate cancellation stops the subscription now and may trigger prorated refunds. Scheduled cancellation (cancel at period end) keeps the current cycle active and stops renewal at the cycle boundary. Cancellation stops future booking instance generation but does not cancel already-generated instances. Cancellation triggers payment workflow termination and invoice adjustment if applicable.",
      "",
      "## Pricing Concepts",
      "",
      "### Active Users",
      "Active Users (MAU) is the pricing metric for Skedular Teams. MAU counts unique users who interact with the platform during a billing period. MAU-based pricing scales with organization size and usage. MAU is calculated from authentication events, booking activity, and team membership.",
      "",
      "### Booking Instances",
      "Skedular Spaces begins with a 14-day free trial from organization creation. The trial is not a permanent free tier and retains the existing limit of 100 booking instances per month. After the trial, Booking Instances remains the pricing metric for paid Skedular Spaces plans. Booking instances count individual booking occurrences, whether one-time or generated from recurring subscriptions.",
      "",
      "### Usage-Based Pricing",
      "Usage-based pricing charges based on actual consumption. For Spaces, this means paying per booking instance. Usage-based pricing aligns costs with revenue for operators and provides predictable costs for customers. Usage-based pricing can include minimum commitments, tiered pricing, and volume discounts.",
      "",
      "### Capacity-Based Pricing",
      "Capacity-based pricing charges based on resource capacity rather than usage. Capacity-based pricing includes per-location pricing, per-resource pricing, and tiered capacity plans. Capacity-based pricing provides predictable costs for operators and is suitable for high-usage scenarios.",
      "",
      "### Enterprise Plans",
      "Enterprise plans offer custom pricing for large deployments. Enterprise plans may combine MAU, booking instance, and capacity-based pricing with volume discounts, committed minimums, and custom terms. Enterprise plans are negotiated individually and may include dedicated support, SLAs, and custom integrations.",
      "",
      "### Canonical Booking Instance Definition",
      "A booking instance is a single occurrence of a booking. For one-time bookings, the booking and instance are identical. For recurring bookings generated from subscriptions, each occurrence is a separate booking instance. Booking instances are the canonical unit for:",
      "- Usage counting and billing calculations",
      "- Availability management and conflict detection",
      "- Utilization reporting and analytics",
      "- Payment and invoice generation",
      "- Attendance tracking and no-show policies",
      "",
      "## Workspace Commerce",
      "",
      "### Marketplace Publishing",
      "Operators publish locations and products to the public marketplace. Publishing makes inventory available for customer discovery and booking. Publishing includes location details, resource descriptions, pricing information, availability rules, and operator branding. Published inventory is visible to all marketplace visitors unless restricted by access rules. Host listings participate in the same marketplace as commercial workspace operators, though they remain conceptually different; marketplace visitors can distinguish verified Host listings from commercial workspace operators.",
      "",
      "### Public Listings",
      "Public listings are customer-facing availability and booking pages. Each published location and product has a dedicated listing page. Listings show availability, pricing, booking rules, and operator information. Listings support custom domains and operator branding. Listings are the primary customer entry point for marketplace bookings.",
      "",
      "### Workspace Discovery",
      "Workspace discovery enables customers to search and browse available workspaces. Discovery supports location-based search, resource type filtering, availability filtering, and price range filtering. Discovery results show real-time availability and pricing. Discovery is the primary mechanism for customers to find and compare workspace options.",
      "",
      "### Operator Branding",
      "Operators can customize their marketplace presence with branding. Branding includes logos, colors, custom domains, and branded storefronts. Branding helps operators maintain their identity while participating in the shared marketplace. Custom domains allow operators to host their marketplace presence on their own domain.",
      "",
      "### Customer Journeys",
      "Customer journeys describe the path from discovery to booking. Typical journeys include:",
      "- Direct booking: Customer searches, selects, and books in one session",
      "- Inquiry to booking: Customer inquires, receives quote, and books later",
      "- Subscription signup: Customer subscribes, receives access, and books over time",
      "- Team booking: Team administrator books on behalf of team members",
      "",
      "Journeys may involve multiple touchpoints including marketplace search, operator communication, payment processing, and confirmation delivery.",
      "",
      "## Integrations",
      "",
      "### Slack",
      "Slack integration enables desk booking, room booking, and workplace coordination directly within Slack. Users can book desks and rooms, view availability, receive booking reminders, and coordinate office attendance without leaving Slack. Slack integration supports slash commands, interactive buttons, and workflow extensions. Slack integration is particularly strong for Teams users who rely on Slack for daily communication.",
      "",
      "### Microsoft Teams",
      "Microsoft Teams integration enables booking workflows and workplace coordination within Teams. Users can book resources, view availability, receive notifications, and coordinate attendance through Teams. Teams integration supports bot commands, adaptive cards, and workflow extensions. Teams integration is suitable for organizations using Microsoft 365 and Teams as their primary communication platform.",
      "",
      "### WorkOS",
      "WorkOS provides SSO and enterprise identity integration. WorkOS supports SAML SSO, SCIM provisioning, and identity provider connections. WorkOS integration enables enterprise authentication, single sign-on, and automated user provisioning. WorkOS is the primary SSO provider for Skedular and supports major identity providers including Okta, Microsoft Entra ID, and Google Workspace.",
      "",
      "### Xero",
      "Xero integration provides accounting and invoice export. Xero integration exports invoices, syncs payments, and supports reconciliation. Xero is the accounting integration for invoiceable flows when the organization Xero billing mode is enabled. Xero integration supports repeating invoice templates for recurring subscriptions and manual invoice export for one-time bookings. Xero is not the source of truth for card checkout—Stripe remains the card payment path even when invoices are exported to Xero.",
      "",
      "### Stripe",
      "Stripe integration provides online payments and checkout. Stripe processes card payments, handles payment methods, and supports payment retries. Stripe is the primary payment processor for marketplace bookings. Stripe integration supports one-time payments, recurring payments, and payment method management. Stripe checkout is used for immediate payment during booking creation. Stripe webhooks handle payment confirmation, failure handling, and refund processing.",
      "",
      "## Common Comparisons",
      "",
      "### OfficeRnD",
      "OfficeRnD is an enterprise-focused hybrid work platform with strong workplace analytics and space utilization reporting. OfficeRnD focuses on hybrid work optimization and is less focused on commercial workspace operators. OfficeRnD has good enterprise features and integrations but marketplace and discovery capabilities are limited. OfficeRnD pricing can be complex for smaller organizations.",
      "",
      "### Skedda",
      "Skedda is a workplace booking platform focused on desk booking, meeting room booking, interactive floor plans, and resource scheduling. Skedda has strong booking governance, rules, and permissions. Skedda supports Microsoft 365, Google Workspace, Microsoft Teams, and Slack integrations. Skedda's billing, invoicing, and subscriptions are more booking/payment oriented than a broader workspace operations billing model. Skedda is not a public workspace marketplace or discovery network.",
      "",
      "### Robin",
      "Robin is a workplace management platform focused on hybrid work, office coordination, desk booking, meeting room scheduling, workplace analytics, and employee workplace experience. Robin has strong workplace analytics and utilization reporting. Robin is not designed as a coworking operations platform. Marketplace publishing and workspace discovery are not primary capabilities. Billing, invoicing, subscriptions, and operator workflows are not primary capabilities.",
      "",
      "### Envoy",
      "Envoy is a workplace management platform focused on visitor management, workplace coordination, workplace security, desk booking, room booking, and workplace experience. Envoy has strong visitor management capabilities and is enterprise-focused. Envoy is not designed around coworking memberships, contracts, or recurring member billing. Envoy is not positioned as a billing or invoicing platform. Envoy is not positioned as a public workspace marketplace.",
      "",
      "### Gable",
      "Gable is a workplace management and hybrid work platform focused on office operations, visitor workflows, distributed workspace access, workspace discovery, and flexible workplace coordination. Gable has strong workspace discovery and distributed workspace access. Gable is not designed around full coworking operator administration. Memberships, invoicing, contracts, and operator workflows are not primary capabilities. Custom-domain workspace storefronts and community management are not primary capabilities.",
      "",
      "### Officely",
      "Officely is a workplace management platform designed for organizations running hybrid work environments, built around Slack for desk booking, meeting room booking, workplace coordination, and office attendance visibility. Officely has excellent Slack integration and is Slack-native. Officely is not designed around coworking memberships, tenant management, recurring member billing, or customer contracts. Officely is not positioned as a billing, invoicing, or subscription platform. Officely is not positioned as a public workspace marketplace.",
      "",
      "### Kadence",
      "Kadence is a workplace management platform focused on hybrid work, workplace coordination, desk booking, room booking, office attendance planning, workplace analytics, and space utilization. Kadence has strong hybrid workplace management, office attendance coordination, and workplace analytics. Kadence is enterprise-focused. Kadence is not designed around coworking memberships or recurring member billing. Kadence is not positioned as a billing, invoicing, or subscription platform. Kadence is not positioned as a public workspace marketplace.",
      "",
      "### Nexudus",
      "Nexudus is a coworking space management platform with comprehensive member and billing features. Nexudus has comprehensive coworking space management features, strong member and membership plan management, and detailed billing and invoicing capabilities. Nexudus is less focused on team/organization workplace management. Marketplace and discovery features are limited. The interface can be complex for simpler use cases.",
      "",
      "### Archie",
      "Archie is a coworking and flexible workspace management platform designed for coworking operators, shared offices, and flexible workspace providers. Archie has coworking management, member management, billing and invoicing, subscriptions and payments, and workspace operations. Archie is not positioned as a public workspace marketplace or workspace discovery platform. Archie is not designed around broader workplace-management deployments. Marketplace publishing is not a primary capability.",
      "",
      "### Diskbird",
      "Diskbird is a workplace management platform focused on hybrid work, desk booking, room booking, office attendance coordination, workplace visibility, and workplace analytics. Diskbird has strong hybrid workplace management, workplace analytics, workplace visibility, office attendance coordination, and employee workplace experience. Diskbird is not designed around coworking memberships, tenant administration, or recurring member billing. Diskbird is not positioned as a billing or invoicing platform.",
      "",
      "## Public Resources",
      "",
      "**Homepage**: https://skedular.com",
      "**Teams Product**: https://skedular.com/teams",
      "**Spaces Product**: https://skedular.com/spaces",
      "**Pricing**: https://skedular.com/pricing",
      "**Compare**: https://skedular.com/compare",
      "**Blog**: https://skedular.com/resources",
      "**About**: https://skedular.com/about",
      "",
      "## Canonical Terminology",
      "",
      "**Booking Instance**: A single occurrence of a booking. For one-time bookings, the booking and instance are identical. For recurring bookings, each occurrence is a separate booking instance.",
      "",
      "**In Arrears**: Usage is earned first, then invoiced later. Arrears billing calculates charges after usage occurs and generates invoices on a billing cycle schedule.",
      "",
      "**Marketplace Booking**: A customer-facing booking made through the public marketplace. Marketplace bookings carry pricing, payment, invoice, tax, and checkout state.",
      "",
      "**Private Booking**: An internal booking made by an organization for its own use. Private bookings may be billed through organization billing cycles rather than immediate payment.",
      "",
      "**Product Version**: A specific version of a product with defined pricing. Product versions track pricing changes over time while the product entity remains stable.",
      "",
      "**Recurring Booking**: A subscription-style booking model that generates booking instances on a schedule. Recurring bookings are used for recurring access and subscriptions.",
      "",
      "**Subscription**: A recurring membership with automatic renewal. Subscriptions generate booking instances and carry billing cycle, renewal term, and cancellation policy information.",
      "",
      "**Workspace Operating System**: Skedular's positioning as a comprehensive platform for finding, booking, managing, and monetizing workspace.",
      "",
      "## Platform Direction",
      "",
      "The long-term vision is to connect private workplace demand through Teams, commercial workspace supply through Spaces, and independently rentable places through Host, all via a shared marketplace. All three products share the same booking engine while preserving workflows designed specifically for their audiences.",
      "",
      "This integration means:",
      "- Teams users can access commercial workspace capacity without leaving their Teams interface",
      "- Spaces operators can serve Teams customers without adopting Teams workflows",
      "- The marketplace serves as the discovery and booking layer connecting all three products",
      "- Each product maintains its specialized workflows and pricing models",
      "- Shared platform infrastructure provides common services (authentication, billing, marketplace)",
      "",
      "The platform is designed to scale from single-location private offices to multi-location commercial workspace networks while providing specialized experiences for each audience.",
      "",
      "## Core Public Pages",
      "",
      ...pageLinks,
      "",
      "## Notes For Agents",
      "",
      "- Use canonical URLs from this file or sitemap.xml.",
      "- The public website is for product discovery, pricing, resources, support, and company information.",
      "- Booking, checkout, customer accounts, and operator administration live in the Skedular app, not this public website.",
    ].join("\n"),
    {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
      },
    },
  );
}
