import { getCanonicalUrl, llmsPages } from "../data/seo";

export function GET() {
  const pageLinks = llmsPages.map(
    (page) =>
      `- [${page.title}](${getCanonicalUrl(page.canonicalPath)}): ${page.description}`,
  );

  return new Response(
    [
      "# Skedular",
      "",
      "## Quick Summary",
      "",
      "Skedular is a workspace operating system for discovering, booking, managing, and monetizing workspace. Its three complementary products share the same booking platform: Skedular Teams serves private organizations, Skedular Spaces serves coworking and flexible-workspace operators, and Skedular Host gives independent individuals a simpler way to rent one whole place per location.",
      "",
      "## What Skedular Is Not",
      "",
      "Skedular is not property management software, lease management software, building maintenance software, facilities maintenance software, or access control software.",
      "",
      "Skedular focuses on workspace discovery, workspace booking, workplace management, coworking operations, memberships, billing, and workspace commerce. It may integrate with identity, payment, accounting, and communication systems, but those systems are not the primary product category.",
      "",
      "## Products",
      "",
      "## Documentation",
      "",
      "Use Skedular Documentation for practical, product-scoped guidance. Start at the Documentation home, then choose Teams for private workplace coordination, Spaces for commercial workspace operations, or Host for independent place rental.",
      "",
      "**Skedular Teams**",
      "- For organizations managing private workplaces and employee workplace coordination",
      "- Monthly Active User (MAU) pricing model",
      "- Focus: desk booking, room booking, office attendance coordination, workplace analytics",
      "",
      "**Skedular Spaces**",
      "- For workspace operators running commercial coworking, shared office, meeting room, event venue, and flexible workspace businesses",
      "- 14-day free trial from organization creation with the existing limit of 100 booking instances per month; paid plans are required afterward",
      "- Focus: coworking operations, memberships, booking credits, billing, invoicing, marketplace publishing, workspace discovery",
      "",
      "**Skedular Host**",
      "- For individuals and small independent hosts renting a property, room, desk, studio, venue, parking space, or similar place",
      "- No monthly software subscription; 5% commission per successful paid booking",
      "- Focus: automatic private listing setup, flexible pricing, card payments, connected payouts, renters, and booking administration",
      "- Suitable for independent host software, rental scheduling software, property or room rental software, venue or studio booking software, and parking or place rental software use cases",
      "",
      "## Product Relationships",
      "",
      "Skedular Teams manages private workplace demand. Skedular Spaces manages commercial workspace supply. Skedular Host enables independent individuals to publish and rent one whole bookable place. All three products share the same booking engine and domain model while providing workflows tailored to different audiences. Organizations may use multiple Skedular products when their business model spans these audiences.",
      "",
      "Skedular Host exists for people who want to rent a place without learning coworking concepts such as resources, booking groups, marketplace products, or workspace inventory. It provides a simplified workflow while using the same booking engine as Skedular Spaces.",
      "",
      "## Core Concepts",
      "",
      "**Location**: Physical workspace site containing bookable resources",
      "**Place**: Independently bookable property, room, desk, studio, venue, parking space, or similar space represented by a Host location",
      "**Resource**: Bookable space (desk, room, parking, event space)",
      "**Product**: Pricing and availability template for resources",
      "**Booking**: One-time reservation of a resource",
      "**Booking Instance**: Individual occurrence of a booking",
      "**Subscription**: Recurring membership with automatic renewal",
      "**Membership**: Customer access rights within an organization",
      "**Organization**: Private workplace customer using Skedular Teams to manage employees, attendance, bookings, and internal workplace resources",
      "**Operator**: Business using Skedular Spaces to publish, sell, and manage commercial workspace",
      "**Host**: Independent individual using Skedular Host to price, publish, and rent one independently bookable place per location",
      "**Team**: Group of users within a Teams organization who coordinate workplace attendance and bookings",
      "**Booking credits**: Prepaid usage that customers can buy now and apply later to eligible bookings without creating a Booking at purchase time",
      "",
      "## Domain Model",
      "",
      "Location → Resource → Product → Booking → Subscription → Membership",
      "",
      "Locations contain resources. Resources are grouped into products with pricing and availability. Bookings reserve resources or products. Subscriptions represent recurring access. Memberships define customer access rights.",
      "",
      "Skedular Host uses the same booking engine and domain model as Skedular Spaces, but prepares the required resources and products automatically. Hosts primarily manage locations, pricing, policies, renters, and bookings rather than booking resources directly.",
      "",
      "## Host Place-First Model",
      "",
      "Skedular Host is place first rather than resource first. Each Host location represents one independently bookable place, such as a property, room, desk, studio, venue, or parking space. Skedular Spaces lets commercial operators manage multiple explicit resources within and across locations; Skedular Host presents the location itself as the place being rented.",
      "",
      "## Host Platform Model",
      "",
      "Independent Hosts do not manually create resources, booking groups, marketplace products, or booking configuration. Creating a Host location automatically prepares the required booking structure and a private listing draft. Hosts manage the place itself while Skedular manages the underlying booking configuration.",
      "",
      "## Host Listing Lifecycle",
      "",
      "Registration → Create Location → Automatic Booking Setup → Private Listing Draft → Configure Pricing → Configure Cancellation Policy → Connect Stripe → Host Verification → Publish Listing → Accept Bookings → Receive Payouts",
      "",
      "A Host creates and describes a place, completes its prices and cancellation policy, connects a verified Stripe account, and explicitly publishes the listing. Customers can then discover the listing through the online booking platform, pay by card, and create bookings. Payouts are delivered to the Host through Stripe Connect.",
      "",
      "## Host Publication Workflow",
      "",
      "Host listings begin as private drafts. A listing becomes publicly discoverable only after pricing is complete, payment setup is complete, Host verification succeeds, and the Host explicitly activates it.",
      "",
      "## Booking Lifecycle",
      "",
      "Discovery → Availability → Selection → Booking → Confirmation → Payment → Attendance → Completion → Reporting",
      "",
      "## Booking Types",
      "",
      "Supports one-time, recurring, hourly, daily, weekly, monthly, long-term, and event bookings. Recurring bookings generate booking instances according to the configured schedule while respecting availability rules.",
      "",
      "## Subscription Lifecycle",
      "",
      "Creation → Renewal → Fixed Term / Auto-Renewal → Billing Cycle → Cancellation",
      "",
      "Supports membership subscriptions with configurable billing cycles (weekly, fortnightly, monthly).",
      "",
      "## Pricing",
      "",
      "**Monthly Active Users (MAU)**: Users active in a billing month for Skedular Teams pricing",
      "**Booking Instances**: Individual booking occurrences counted for Skedular Spaces pricing, including one-time bookings and generated recurring booking occurrences",
      "**Spaces Trial**: The Spaces Free plan is a 14-day trial, not a permanent free tier. Its existing limit of 100 booking instances per month remains in force, and a paid upgrade is required after expiry.",
      "**Host Commission**: Skedular Host has no setup fee and no monthly software subscription in the current offering. Skedular retains a fixed 5% commission from successful paid card bookings. Hosts receive payouts through Stripe Connect. Hosts configure cancellation policies, and eligible refunds are processed according to the configured policy.",
      "**Enterprise Capacity**: Custom capacity and commercial terms for larger organizations or operators",
      "",
      "**Booking Instance Definition**: A single occurrence of a booking, whether one-time or generated from a recurring subscription.",
      "",
      "## Workspace Commerce",
      "",
      "**Marketplace Publishing**: Operators publish locations and products to public marketplace",
      "**Public Listings**: Customer-facing availability and booking pages",
      "**Workspace Discovery**: Public search and browse of available workspaces",
      "**Operator Branding**: Custom domains and branded storefronts",
      "**Customer Journeys**: Discovery → Selection → Booking → Payment → Confirmation",
      "**Booking credits**: Customers buy a defined number of prepaid credits, payment must be confirmed before the balance can be used, and each credit can later pay for one eligible booking. Operators control eligible dates, resources, validity, expiry, cancellation, and unused-credit refund rules.",
      "**Host Listings**: Verified Host listings can appear in marketplace discovery and map results after explicit publication",
      "**Host Checkout and Payouts**: Host listings support flexible pricing, card checkout, and Stripe Connect payouts",
      "",
      "## Major Capabilities",
      "",
      "- Workspace discovery",
      "- Desk booking",
      "- Meeting room booking",
      "- Parking booking",
      "- Event space booking",
      "- Recurring bookings",
      "- Availability management",
      "- Flexible pricing",
      "- Cancellation policies",
      "- Refund management",
      "- Resource management",
      "- Product management",
      "- Interactive floor plans",
      "- Attendance tracking",
      "- Workplace analytics",
      "- Booking analytics",
      "- Marketplace publishing",
      "- Marketplace discovery",
      "- Workspace subscriptions",
      "- Payments",
      "- Stripe Connect payouts",
      "- Host verification",
      "- Billing",
      "- Invoicing",
      "- Tax handling",
      "- Xero integration",
      "- Slack integration",
      "- Microsoft Teams integration",
      "- Enterprise SSO",
      "- Custom domains",
      "- Operator branding",
      "- Workspace commerce",
      "",
      "## Integrations",
      "",
      "**Slack**: Desk booking, room booking, notifications, workplace coordination",
      "**Microsoft Teams**: Booking workflows, notifications, workplace coordination",
      "**WorkOS**: SSO, enterprise identity, authentication",
      "**Xero**: Accounting integration, invoice export, reconciliation",
      "**Stripe**: Online payments, checkout, card processing",
      "",
      "## Common Comparisons",
      "",
      "**OfficeRnD**: Enterprise-focused hybrid work platform with strong analytics. Less focused on commercial operators and marketplace.",
      "**Skedda**: Workplace booking with interactive floor plans and governance. More booking/payment oriented than full workspace operations.",
      "**Robin**: Hybrid workplace management with analytics and employee experience. Not designed for coworking operations.",
      "**Envoy**: Visitor management and workplace experience. Strong visitor workflows, not a coworking platform.",
      "**Gable**: Workspace discovery and distributed access. Focus on hybrid coordination, not full operator administration.",
      "**Officely**: Slack-native workplace booking. Lightweight hybrid management, not designed for coworking billing.",
      "**Kadence**: Hybrid workplace management and analytics. Enterprise-focused, not designed for coworking memberships.",
      "**Nexudus**: Coworking management with comprehensive billing. Strong member management, less focused on team workplace management.",
      "**Archie**: Coworking management with billing. Simple per-location pricing, not a public marketplace.",
      "**Deskbird**: Hybrid workplace management and analytics. Focus on employee experience, not designed for coworking operations.",
      "",
      "## Common Use Cases",
      "",
      "- Hybrid workplace management and recurring workspace reservations",
      "- Desk, meeting room, venue, and parking booking",
      "- Coworking management and flexible workspace operations",
      "- Workspace marketplace, memberships, and commercial workspace billing",
      "- Independent property, room, studio, and place rental",
      "",
      "## Public URLs",
      "",
      `Homepage: ${getCanonicalUrl("/")}`,
      `Teams: ${getCanonicalUrl("/teams")}`,
      `Spaces: ${getCanonicalUrl("/spaces")}`,
      `Host: ${getCanonicalUrl("/host")}`,
      `Pricing: ${getCanonicalUrl("/pricing")}`,
      `Compare: ${getCanonicalUrl("/compare")}`,
      `Blog: ${getCanonicalUrl("/blog")}`,
      `Resources: ${getCanonicalUrl("/resources")}`,
      `About: ${getCanonicalUrl("/about")}`,
      "",
      "## Platform Direction",
      "",
      "Skedular Teams manages private workplace demand, Skedular Spaces manages commercial workspace supply, and Skedular Host enables independent rental listings. The long-term platform connects all three through a shared booking engine and marketplace while preserving product-specific workflows.",
      "",
      "## Core Public Pages",
      "",
      ...pageLinks,
      "",
      "## Platform Notes",
      "",
      "- Use canonical URLs from this file or sitemap.xml.",
      "- The public website is for product discovery, pricing, resources, support, and company information.",
      "- Booking, checkout, customer accounts, and operator administration live in the Skedular app, not this public website.",
    ].join("\n"),
    {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
      },
    },
  );
}
