schema {
  query: Query
  mutation: Mutation
}

type Query {
  product(id: String!): ProductDetails
  productById(id: String!): ProductDetails
  productVersion(id: String!): ProductVersionDetails
  productVersionById(id: String!): ProductVersionDetails
  products(after: String first: Int before: String last: Int where: ProductWhereInput! orderBy: [ProductOrderInput!]): ConnectionOfProductEdge!
  defaultMaxAllowedResourcesLockTimePaidViaCard: Int!
  defaultMaxAllowedResourcesLockTimePaidViaBankTransfer: Int!
  marketplaceVersion: Version!
  marketplaceCustomerRecordSynced: Boolean!
  currencies: [CurrencyDetails!]!
  priceUnits: [PriceUnitDetails!]!
}

type Mutation {
  addProduct(input: AddProductInput!): ProductPayload!
  updateProduct(input: UpdateProductInput!): ProductPayload!
  deleteProducts(input: DeleteProductsInput!): ProductsPayload!
  activateProducts(input: ActivateProductsInput!): ProductsPayload!
  deactivateProducts(input: DeactivateProductsInput!): ProductsPayload!
}

type ProductDetails {
  organization: OrganizationDetails!
  productTags: [OrganizationTagDetails!]!
  locationTags: [OrganizationTagDetails!]!
  inactive: Boolean!
  name: String!
  description: String
  price: String!
  priceToDisplay: String!
  currencyToDisplay: String!
  priceUnit: PriceUnitDetails!
  isPriceTaxInclusive: Boolean!
  currency: CurrencyDetails!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  maxAllowedResourcesLockTimePaidViaCard: Int!
  maxAllowedResourcesLockTimePaidViaBankTransfer: Int!
  acceptedBookingPaymentMethods: [Marketplace_PaymentMethodTypeDetails!]!
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  latestProductVersionId: String!
  featureImages: [CdnImageFile!]!
  id: ID!
}

type ProductVersionDetails {
  productTags: [OrganizationTagDetails!]!
  locationTags: [OrganizationTagDetails!]!
  inactive: Boolean!
  name: String!
  description: String
  price: String!
  priceToDisplay: String!
  currencyToDisplay: String!
  priceUnit: PriceUnitDetails!
  isPriceTaxInclusive: Boolean!
  currency: CurrencyDetails!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  maxAllowedResourcesLockTimePaidViaCard: Int!
  maxAllowedResourcesLockTimePaidViaBankTransfer: Int!
  acceptedBookingPaymentMethods: [Marketplace_PaymentMethodTypeDetails!]!
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  featureImages: [CdnImageFile!]!
  id: ID!
}

type OrganizationDetails {
  uniqueAlphanumericName: String
  id: ID!
}

type OrganizationTagDetails {
  id: ID!
}

type PriceUnitDetails {
  type: PriceUnit!
  name: String!
}

type CurrencyDetails {
  type: Currency!
  name: String!
}

type Marketplace_PaymentMethodTypeDetails {
  type: PaymentMethod!
  name: String!
}

type CdnImageFile {
  original: CdnFile
  thumbnail: CdnFile
}

type ConnectionOfProductEdge {
  pageInfo: PageInfo!
  edges: [ProductEdge!]!
  totalCount: Int!
}

input DeactivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input ActivateProductsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteProductsInput {
  clientMutationId: String
  ids: [String!]!
}

type ProductsPayload {
  clientMutationId: String
  products: [ProductDetails!]!
}

input UpdateProductInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
  price: String!
  priceUnit: PriceUnit!
  isPriceTaxInclusive: Boolean!
  currency: Currency!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  maxAllowedResourcesLockTimePaidViaCard: Int!
  maxAllowedResourcesLockTimePaidViaBankTransfer: Int!
  acceptedBookingPaymentMethods: [PaymentMethod!]!
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  productTagIds: [String!]!
  locationTagIds: [String!]!
  featureImages: [CdnImageFileInput!]!
}

input AddProductInput {
  clientMutationId: String
  id: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  name: String!
  description: String
  price: String!
  priceUnit: PriceUnit!
  isPriceTaxInclusive: Boolean!
  currency: Currency!
  minDurationMinutes: Int
  maxDurationMinutes: Int
  maxAllowedResourcesLockTimePaidViaCard: Int!
  maxAllowedResourcesLockTimePaidViaBankTransfer: Int!
  acceptedBookingPaymentMethods: [PaymentMethod!]!
  bookAllLocationResources: Boolean!
  recurrenceWindowDays: Int!
  requireConsecutiveDays: Boolean!
  maxBookingSpreadDays: Int
  numberOfResourcesToBook: Int!
  productTagIds: [String!]!
  locationTagIds: [String!]!
  featureImages: [CdnImageFileInput!]!
}

type ProductPayload {
  clientMutationId: String
  product: ProductDetails!
}

input ProductWhereInput {
  organizationUniqueAlphanumericNames: [String!]
  productIds: [String!]
  nameContains: String
  includeInactive: Boolean!
}

input ProductOrderInput {
  direction: OrderDirection!
  field: ProductOrderField!
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

enum PriceUnit {
  PER_MINUTE
  PER_HOUR
  PER_USE
}

enum Currency {
  NZD
  USD
}

enum PaymentMethod {
  CARD
  BANK_TRANSFER
}

type CdnFile {
  url: String!
  height: Int
  width: Int
}

enum ProductOrderField {
  NAME
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

input CdnImageFileInput {
  original: CdnFileInput
  thumbnail: CdnFileInput
}

type ProductEdge {
  node: ProductDetails!
  cursor: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

input CdnFileInput {
  url: String!
  height: Int
  width: Int
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

directive @internal on FIELD_DEFINITION

directive @lookup on FIELD_DEFINITION