openapi: 3.1.0
info:
  title: Organization API v1
  description: "Organization REST API"
  version: 1.0.0

paths:
  /organization/api/v1/{organizationId}/republish:
    put:
      tags:
        - organization
      summary: republish organization
      operationId: republish
      parameters:
        - in: path
          name: organizationId
          schema:
            type: string
          required: true

      responses:
        "200":
          description: the status of organization republishing

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /organization/api/v1/republish-all:
    put:
      tags:
        - organization
      summary: republish all organizations
      operationId: republishAll

      responses:
        "200":
          description: the status of organization republishing

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /organization/api/v1/azure-tenant-admin-consent-url:
    get:
      tags:
        - organization
        - azure
        - tenant
      summary: generate an admin consent Url for the given tenant
      operationId: azureTenantAdminConsentUrl
      responses:
        "302":
          description: redirect status response code

  /organization/api/v1/onboard-azure-tenant:
    get:
      tags:
        - organization
        - azure
        - tenant
      summary: OnBoard a tenant
      operationId: onboardAzureTenant
      parameters:
        - in: query
          name: tenant
          schema:
            type: string
          required: true
        - in: query
          name: admin_consent
          schema:
            type: boolean
          required: true
        - in: query
          name: state
          schema:
            type: string
          required: true
        - in: query
          name: error
          schema:
            type: string
        - in: query
          name: error_description
          schema:
            type: string
      responses:
        "200":
          description: onboarding response

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
