<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>Infrastructure.Shared</AssemblyName>
        <AssemblyTitle>Infrastructure.Shared</AssemblyTitle>
        <Product>Skedular Shared Infrastructure</Product>
        <Description>Skedular Shared Infrastructure</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/skedular/skedular</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Api.Shared.Clients/Api.Shared.Clients.csproj"/>
        <ProjectReference Include="../Enterprise.Shared/Enterprise.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
