//----------------------
// <auto-generated>
// Generated using Skedularctl v1.0.0.0. DO NOT EDIT!
// </auto-generated>
//----------------------

using System.Text.RegularExpressions;

using Api.Shared.Events;

using Google.Protobuf.WellKnownTypes;

using NanoidDotNet;

#nullable enable

namespace Api.Shared.Clients.Events.Skedular.Notification.V1.Value;

public partial class Metadata : IMetadata { }

[KafkaTopic(
    topicName: "notification.v1.event",
    topicPartitionCount: 3,
    retryTopicNamePrefix: "notification.v1.event.retry",
    retryTopicCount: 1,
    retryTopicPartitionCount: 3,
    deadLetterTopicName: "notification.v1.event.deadletter",
    deadLetterTopicPartitionCount: 3,
    protobufSchema: "syntax = \"proto3\";package notification;import \"google/protobuf/timestamp.proto\";option csharp_namespace = \"Api.Shared.Clients.Events.Skedular.Notification.V1.Value\";enum Type {  NotificationUpserted = 0;}message Event {  Metadata metadata = 1;  Data data = 2;}message Metadata {  string id = 1;  string domainSource = 2;  string appSource = 3;  Type type = 4;  google.protobuf.Timestamp time = 5;  string correlationId = 6;}message Data {   Notification notification = 1; }enum NotificationType { Email = 0; }message Notification {  string id = 1;  google.protobuf.Timestamp deletedAt = 2;  NotificationType notificationType = 3;  EmailDetails email = 4;}message EmailDetails {  string id = 1;  string templateId = 2;  string templateData = 3;  string sender = 4;  repeated string toAddresses = 5;  repeated string ccAddresses = 6;  repeated string bccAddresses = 7;}")]
public partial class Event : IMetadataEvent
{
    private static readonly Regex ValidKafkaTopicCharacters =
        new(@"^[a-z0-9\.\-_]+$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private const string TopicName = "notification.v1.event";
    private const string RetryTopicNamePrefix = "notification.v1.event.retry";
    private const int RetryTopicCount = 1;
    private const string DeadLetterTopicName = "notification.v1.event.deadletter";

    public static Metadata NewMetadata(
        string domainSource,
        string appSource,
        Type type,
        string correlationId,
        string? id = null) =>
        new() {
            Id = id ?? NanoidDotNet.Nanoid.Generate(),
            DomainSource = domainSource,
            AppSource = appSource,
            Type = type,
            Time = Timestamp.FromDateTime(System.DateTime.UtcNow),
            CorrelationId = correlationId,
    };

    public string GetTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? TopicName : $"{prefix}.{TopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public int GetRetryTopicCount() => RetryTopicCount;

    public string GetRetryTopicName(string prefix, int idx)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? $"{RetryTopicNamePrefix}.{idx}" : $"{prefix}.{RetryTopicNamePrefix}.{idx}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string GetDeadLetterTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? DeadLetterTopicName : $"{prefix}.{DeadLetterTopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string? GetCorrelationId() => Metadata.CorrelationId;
}
