schema {
  query: Query
  mutation: Mutation
}

type AddOrganizationPaymentMethodIntentPayload {
  clientMutationId: String
  publishedKeys: String!
  clientSecret: String!
}

type CancelOrganizationOfferingPayload {
  clientMutationId: String
}

type CdnFile {
  url: String!
  height: Int
  width: Int
}

type CdnImageFile {
  original: CdnFile
  thumbnail: CdnFile
}

type ConnectionOfOrganizationBankAccountEdge {
  pageInfo: PageInfo!
  edges: [OrganizationBankAccountEdge!]!
  totalCount: Int!
}

type ConnectionOfOrganizationEdge {
  pageInfo: PageInfo!
  edges: [OrganizationEdge!]!
  totalCount: Int!
}

type ConnectionOfOrganizationJoinInvitationEdge {
  pageInfo: PageInfo!
  edges: [OrganizationJoinInvitationEdge!]!
  totalCount: Int!
}

type ConnectionOfOrganizationMemberEdge {
  pageInfo: PageInfo!
  edges: [OrganizationMemberEdge!]!
  totalCount: Int!
}

type ConnectionOfOrganizationStripeConnectAccountEdge {
  pageInfo: PageInfo!
  edges: [OrganizationStripeConnectAccountEdge!]!
  totalCount: Int!
}

type ConnectionOfOrganizationTagEdge {
  pageInfo: PageInfo!
  edges: [OrganizationTagEdge!]!
  totalCount: Int!
}

type CustomerDetails {
  id: ID!
}

type InvitationToJoinOrganizationPayload {
  clientMutationId: String
  inviteCustomerToJoinOrganization: InviteCustomerToJoinOrganizationDetails!
}

type InvitationsToJoinOrganizationPayload {
  clientMutationId: String
  invitesCustomersToJoinOrganization: [InviteCustomerToJoinOrganizationDetails!]!
}

type InviteCustomerToJoinOrganizationDetails {
  createdBy: CustomerDetails!
  invitee: CustomerDetails
  email: String
  status: OrganizationInvitationStatusDetails!
  role: OrganizationMemberRole!
  organization: OrganizationDetails!
  id: ID!
}

type ListingMetadata {
  about: String
  title: String
  subTitle: String
}

type Mutation {
  addOrganizationBankAccount(input: AddOrganizationBankAccountInput!): OrganizationBankAccountPayload! @cost(weight: "10")
  updateOrganizationBankAccount(input: UpdateOrganizationBankAccountInput!): OrganizationBankAccountPayload! @cost(weight: "10")
  deleteOrganizationBankAccount(input: DeleteOrganizationBankAccountInput!): OrganizationBankAccountPayload! @cost(weight: "10")
  deleteOrganizationBankAccounts(input: DeleteOrganizationBankAccountsInput!): OrganizationBankAccountsPayload! @cost(weight: "10")
  setOrganizationBankAccountAsDefault(input: SetOrganizationBankAccountAsDefaultInput!): OrganizationBankAccountPayload! @cost(weight: "10")
  addOrganizationBillingDetails(input: AddOrganizationBillingDetailsInput!): OrganizationPayload! @cost(weight: "10")
  updateOrganizationBillingDetails(input: UpdateOrganizationBillingDetailsInput!): OrganizationPayload! @cost(weight: "10")
  inviteCustomersToJoinOrganization(input: InviteCustomersToJoinOrganizationInput!): InvitationsToJoinOrganizationPayload! @cost(weight: "10")
  acceptInvitationToJoinOrganization(input: AcceptInvitationToJoinOrganizationInput!): InvitationToJoinOrganizationPayload! @cost(weight: "10")
  rejectInvitationToJoinOrganization(input: RejectInvitationToJoinOrganizationInput!): InvitationToJoinOrganizationPayload! @cost(weight: "10")
  cancelInvitationToJoinOrganization(input: CancelInvitationToJoinOrganizationInput!): InvitationToJoinOrganizationPayload! @cost(weight: "10")
  changeOrganizationMemberRole(input: ChangeOrganizationMemberRoleInput!): OrganizationMemberDetailsPayload! @cost(weight: "10")
  changeOrganizationMembersStatus(input: ChangeOrganizationMembersStatusInput!): OrganizationMembersDetailsPayload! @cost(weight: "10")
  removeOrganizationMembers(input: RemoveOrganizationMembersInput!): OrganizationMembersDetailsPayload! @cost(weight: "10")
  completeOrganizationMemberOnboarding(input: CompleteOrganizationMemberOnboardingInput!): OrganizationMemberPayload! @cost(weight: "10")
  updateOrganizationOffering(input: UpdateOrganizationOfferingInput!): UpdateOrganizationOfferingPayload! @cost(weight: "10")
  cancelOrganizationOffering(input: CancelOrganizationOfferingInput!): CancelOrganizationOfferingPayload! @cost(weight: "10")
  addOrganization(input: AddOrganizationInput!): OrganizationPayload! @cost(weight: "10")
  updateOrganization(input: UpdateOrganizationInput!): OrganizationPayload! @cost(weight: "10")
  deleteOrganization(input: DeleteOrganizationInput!): OrganizationPayload! @cost(weight: "10")
  updateOrganizationMarketplaceListingMetadata(input: UpdateOrganizationMarketplaceListingMetadataInput!): OrganizationPayload! @cost(weight: "10")
  addOrganizationPaymentMethodIntent(input: AddOrganizationPaymentMethodIntentInput!): AddOrganizationPaymentMethodIntentPayload! @cost(weight: "10")
  removeOrganizationPaymentMethod(input: RemoveOrganizationPaymentMethodInput!): RemoveOrganizationPaymentMethodPayload! @cost(weight: "10")
  addOrganizationPhysicalAddress(input: AddOrganizationPhysicalAddressInput!): OrganizationPayload! @cost(weight: "10")
  updateOrganizationPhysicalAddress(input: UpdateOrganizationPhysicalAddressInput!): OrganizationPayload! @cost(weight: "10")
  updateOrganizationSsoSettings(input: UpdateOrganizationSsoSettingsInput!): OrganizationPayload! @cost(weight: "10")
  removeOrganizationSsoSettings(input: RemoveOrganizationSsoSettingsInput!): OrganizationPayload! @cost(weight: "10")
  addOrganizationStripeConnectAccount(input: AddOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload! @cost(weight: "10")
  updateOrganizationStripeConnectAccount(input: UpdateOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload! @cost(weight: "10")
  deleteOrganizationStripeConnectAccount(input: DeleteOrganizationStripeConnectAccountInput!): OrganizationStripeConnectAccountPayload! @cost(weight: "10")
  deleteOrganizationStripeConnectAccounts(input: DeleteOrganizationStripeConnectAccountsInput!): OrganizationStripeConnectAccountsPayload! @cost(weight: "10")
  setOrganizationStripeConnectAccountAsDefault(input: SetOrganizationStripeConnectAccountAsDefaultInput!): OrganizationStripeConnectAccountPayload! @cost(weight: "10")
  addCustomTag(input: AddCustomTagInput!): OrganizationTagPayload! @cost(weight: "10")
  updateCustomTag(input: UpdateCustomTagInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteCustomTag(input: DeleteCustomTagInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteCustomTags(input: DeleteCustomTagsInput!): OrganizationTagsPayload! @cost(weight: "10")
  addZone(input: AddZoneInput!): OrganizationTagPayload! @cost(weight: "10")
  updateZone(input: UpdateZoneInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteZone(input: DeleteZoneInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteZones(input: DeleteZonesInput!): OrganizationTagsPayload! @cost(weight: "10")
  addProductTag(input: AddProductTagInput!): OrganizationTagPayload! @cost(weight: "10")
  updateProductTag(input: UpdateProductTagInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteProductTag(input: DeleteProductTagInput!): OrganizationTagPayload! @cost(weight: "10")
  deleteProductTags(input: DeleteProductTagsInput!): OrganizationTagsPayload! @cost(weight: "10")
  updateOrganizationTaxDetails(input: UpdateOrganizationTaxDetailsInput!): OrganizationPayload! @cost(weight: "10")
  removeOrganizationTaxDetails(input: RemoveOrganizationTaxDetailsInput!): OrganizationPayload! @cost(weight: "10")
}

type OrganizationActiveOfferingDetails {
  code: String!
  isEnterprise: Boolean!
  name: String!
  start: DateTime!
  end: DateTime!
  unitPrice: Int!
  underPriceLines: [String!]!
  featureSet: [String!]!
  free: Boolean!
  earlyBird: Boolean!
  id: ID!
}

type OrganizationAnalytics {
  memberAttendancePercentage: [OrganizationMemberAttendancePercentage!]!
  dailyBookingsTotals: [OrganizationDailyBookingsTotal!]!
}

type OrganizationBankAccountDetails {
  isDefault: Boolean!
  name: String!
  bankName: String!
  accountHolderName: String!
  accountNumber: String!
  country: String!
  countryCode: String
  organization: OrganizationDetails!
  id: ID!
}

type OrganizationBankAccountEdge {
  node: OrganizationBankAccountDetails!
  cursor: String!
}

type OrganizationBankAccountPayload {
  clientMutationId: String
  organizationBankAccount: OrganizationBankAccountDetails!
}

type OrganizationBankAccountsPayload {
  clientMutationId: String
  organizationBankAccounts: [OrganizationBankAccountDetails!]!
}

type OrganizationBillingDetails {
  companyName: String
  email: String!
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  multilinesFormattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
  id: ID!
}

type OrganizationDailyBookingsTotal {
  date: DateTime!
  total: Int!
}

type OrganizationDetails {
  members(after: String first: Int before: String last: Int where: OrganizationMemberWhereInput orderBy: [OrganizationMemberOrderInput!]): ConnectionOfOrganizationMemberEdge! @cost(weight: "10")
  customTags(after: String first: Int before: String last: Int where: CustomTagOrganizationTagWhereInput orderBy: [OrganizationTagOrderInput!]): ConnectionOfOrganizationTagEdge! @cost(weight: "10")
  zones(after: String first: Int before: String last: Int where: ZoneOrganizationTagWhereInput orderBy: [OrganizationTagOrderInput!]): ConnectionOfOrganizationTagEdge! @cost(weight: "10")
  productTags(after: String first: Int before: String last: Int where: ProductTagOrganizationTagWhereInput orderBy: [OrganizationTagOrderInput!]): ConnectionOfOrganizationTagEdge! @cost(weight: "10")
  analytics(from: DateTime! until: DateTime!): OrganizationAnalytics! @cost(weight: "10")
  isSsoTokenValid: Boolean! @cost(weight: "10")
  ssoLoginUrl(redirectUrl: String!): String! @cost(weight: "10")
  uniqueAlphanumericName: String
  name: String!
  website: String
  logoUrl: String
  type: OrganizationTypeDetails!
  agreedToTermsOfUse: Boolean!
  termsOfUse: OrganizationTermsOfUse
  industrySubCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  contactEmail: String
  contactPhone: String
  isOwnershipVerified: Boolean!
  stripeAuthorizeExistingConnectAccountUrl: String!
  physicalAddress: OrganizationPhysicalAddressDetails
  billingDetails: OrganizationBillingDetails
  availableOfferings: [OrganizationOfferingDetails!]!
  activeOffering: OrganizationActiveOfferingDetails!
  hasFutureBooking: Boolean!
  hasLocation: Boolean!
  hasTeam: Boolean!
  canModify: Boolean!
  canDelete: Boolean!
  canInvitePeople: Boolean!
  canViewAnalytics: Boolean!
  isMyOnboardingDone: Boolean!
  resourceTypes: [OrganizationTagDetails!]!
  locationSpaceTypes: [OrganizationTagDetails!]!
  paymentMethods: [OrganizationPaymentMethod!]!
  hasAttachedPaymentMethod: Boolean!
  ssoSettings: OrganizationSsoSettingsDetails
  taxDetails: OrganizationTaxDetails
  featureImages: [CdnImageFile!]!
  listingMetadata: ListingMetadata!
  marketplaceListingMetadata: ListingMetadata!
  id: ID!
}

type OrganizationEdge {
  node: OrganizationDetails!
  cursor: String!
}

type OrganizationIndustryMainCategoryReferenceDetails {
  name: String!
  subCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  id: ID!
}

type OrganizationIndustrySubCategoryReferenceDetails {
  name: String!
  mainCategoryName: String!
  id: ID!
}

type OrganizationInvitationStatusDetails {
  type: InvitationStatus!
  name: String!
}

type OrganizationJoinInvitationEdge {
  node: InviteCustomerToJoinOrganizationDetails!
  cursor: String!
}

type OrganizationMemberAttendancePercentage {
  date: DateTime!
  percentage: Float!
}

type OrganizationMemberDetails {
  customer: CustomerDetails!
  role: OrganizationMemberRole
  status: OrganizationMemberStatus!
  isOrganizationOnboardingDone: Boolean!
  id: ID!
}

type OrganizationMemberDetailsPayload {
  clientMutationId: String
  member: OrganizationMemberDetails
}

type OrganizationMemberEdge {
  node: OrganizationMemberDetails!
  cursor: String!
}

type OrganizationMemberPayload {
  clientMutationId: String
}

type OrganizationMembersDetailsPayload {
  clientMutationId: String
  members: [OrganizationMemberDetails!]!
}

type OrganizationOfferingDetails {
  code: String!
  isEnterprise: Boolean!
  name: String!
  unitPrice: Int!
  underPriceLines: [String!]!
  featureSet: [String!]!
  free: Boolean!
  earlyBird: Boolean!
}

type OrganizationPayload {
  clientMutationId: String
  organization: OrganizationDetails!
}

type OrganizationPaymentMethod {
  cardBrand: String
  cardCountry: String
  cardDescription: String
  cardExpiryMonth: Int
  cardExpiryYear: Int
  cardFingerprint: String
  cardFunding: String
  cardIssuer: String
  cardLastFourDigit: String
  id: ID!
}

type OrganizationPhysicalAddressDetails {
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  multilinesFormattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
  organization: OrganizationDetails!
  id: ID!
}

type OrganizationPublicDetails {
  customTags(after: String first: Int before: String last: Int where: CustomTagOrganizationTagWhereInput orderBy: [OrganizationTagOrderInput!]): ConnectionOfOrganizationTagEdge! @cost(weight: "10")
  zones(after: String first: Int before: String last: Int where: ZoneOrganizationTagWhereInput orderBy: [OrganizationTagOrderInput!]): ConnectionOfOrganizationTagEdge! @cost(weight: "10")
  uniqueId: String!
  uniqueAlphanumericName: String
  name: String!
  website: String
  logoUrl: String
  industrySubCategories: [OrganizationIndustrySubCategoryReferenceDetails!]!
  contactEmail: String
  contactPhone: String
  physicalAddress: OrganizationPhysicalAddressDetails
  resourceTypes: [OrganizationTagDetails!]!
  locationSpaceTypes: [OrganizationTagDetails!]!
  featureImages: [CdnImageFile!]!
  listingMetadata: ListingMetadata!
  marketplaceListingMetadata: ListingMetadata!
}

type OrganizationSsoSettingsDetails {
  isActive: Boolean!
  entityId: String!
  loginUrl: String!
  appFederationMetadataUrl: String!
  id: ID!
}

type OrganizationStripeConnectAccountDetails {
  isDefault: Boolean!
  name: String!
  chargesEnabled: Boolean!
  payoutsEnabled: Boolean!
  type: String!
  country: String
  defaultCurrency: String
  businessType: String
  companyName: String
  url: String
  supportUrl: String
  contactEmail: String
  contactPhone: String
  detailsSubmitted: Boolean!
  capabilitiesTransfers: String!
  capabilitiesCardPayments: String!
  onboardingUrl: String!
  isOnboardingCompleted: Boolean!
  isAuthorized: Boolean!
  organization: OrganizationDetails!
  id: ID!
}

type OrganizationStripeConnectAccountEdge {
  node: OrganizationStripeConnectAccountDetails!
  cursor: String!
}

type OrganizationStripeConnectAccountPayload {
  clientMutationId: String
  organizationStripeConnectAccount: OrganizationStripeConnectAccountDetails!
}

type OrganizationStripeConnectAccountsPayload {
  clientMutationId: String
  organizationStripeConnectAccounts: [OrganizationStripeConnectAccountDetails!]!
}

type OrganizationTagDetails {
  name: String!
  description: String
  tagType: OrganizationTagType!
  color: String
  id: ID!
}

type OrganizationTagEdge {
  node: OrganizationTagDetails!
  cursor: String!
}

type OrganizationTagPayload {
  clientMutationId: String
  organizationTag: OrganizationTagDetails!
}

type OrganizationTagTypeDetails {
  tagType: OrganizationTagType!
  name: String!
}

type OrganizationTagsPayload {
  clientMutationId: String
  organizationTags: [OrganizationTagDetails!]!
}

type OrganizationTaxDetails {
  taxId: String!
  taxRatePercentage: Decimal!
  id: ID!
}

type OrganizationTermsOfUse {
  terms: String!
  id: ID!
}

type OrganizationTypeDetails {
  type: OrganizationType!
  name: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  isAzureTenantInstalled: Boolean! @cost(weight: "10")
  azureTenantAdminConsentUrl: String! @cost(weight: "10")
  azureTenantOrganization: OrganizationDetails @cost(weight: "10")
  organizationBankAccount(id: String!): OrganizationBankAccountDetails @cost(weight: "10")
  organizationBankAccountById(id: String!): OrganizationBankAccountDetails @lookup @internal @cost(weight: "10")
  organizationBankAccounts(after: String first: Int before: String last: Int where: OrganizationBankAccountWhereInput! orderBy: [OrganizationBankAccountOrderInput!]): ConnectionOfOrganizationBankAccountEdge! @cost(weight: "10")
  organizationInvitationStatuses: [OrganizationInvitationStatusDetails!]!
  pendingOrganizationInvitationsCount: Int! @cost(weight: "10")
  myInvitationsToJoinOrganizations(after: String first: Int before: String last: Int where: MyInvitationsToJoinOrganizationsWhereInput! orderBy: [JoinOrganizationInvitationOrderInput!]): ConnectionOfOrganizationJoinInvitationEdge! @cost(weight: "10")
  organizationMemberRoles: [OrganizationMemberRole!]!
  organizationOffering(code: String!): OrganizationOfferingDetails!
  organizationTypes: [OrganizationTypeDetails!]!
  organizationCustomerRecordSynced: Boolean! @cost(weight: "10")
  activeOrganizationTermsOfUse: OrganizationTermsOfUse! @cost(weight: "10")
  organizationIndustryMainCategoriesReferences: [OrganizationIndustryMainCategoryReferenceDetails!]! @cost(weight: "10")
  organization(id: String uniqueAlphanumericName: String): OrganizationDetails @cost(weight: "10")
  organizationPublic(id: String uniqueAlphanumericName: String): OrganizationPublicDetails @cost(weight: "10")
  organizationById(id: String!): OrganizationDetails @lookup @internal @cost(weight: "10")
  organizations(after: String first: Int before: String last: Int where: OrganizationWhereInput! orderBy: [OrganizationOrderInput!]): ConnectionOfOrganizationEdge! @cost(weight: "10")
  myOrganizations: [OrganizationDetails!]! @cost(weight: "10")
  organizationVersion: Version!
  bookingSlotSizeInMinutes: Int!
  resourceTypes: [OrganizationTagTypeDetails!]!
  locationSpaceTypes: [OrganizationTagTypeDetails!]!
  emailsToShowLatestCapabilities: [String!]!
  emailsToIgnoreObservability: [String!]!
  organizationStripeConnectAccount(id: String!): OrganizationStripeConnectAccountDetails @cost(weight: "10")
  organizationStripeConnectAccountById(id: String!): OrganizationStripeConnectAccountDetails @lookup @internal @cost(weight: "10")
  organizationStripeConnectAccounts(after: String first: Int before: String last: Int where: OrganizationStripeConnectAccountWhereInput! orderBy: [OrganizationStripeConnectAccountOrderInput!]): ConnectionOfOrganizationStripeConnectAccountEdge! @cost(weight: "10")
  deskResourceType: OrganizationTagType!
  roomResourceType: OrganizationTagType!
  parkingResourceType: OrganizationTagType!
  otherResourceType: OrganizationTagType!
  customTag(id: String!): OrganizationTagDetails @cost(weight: "10")
  customTagById(id: String!): OrganizationTagDetails @lookup @internal @cost(weight: "10")
  zone(id: String!): OrganizationTagDetails @cost(weight: "10")
  zoneById(id: String!): OrganizationTagDetails @lookup @internal @cost(weight: "10")
  productTag(id: String!): OrganizationTagDetails @cost(weight: "10")
  productTagById(id: String!): OrganizationTagDetails @lookup @internal @cost(weight: "10")
}

type RemoveOrganizationPaymentMethodPayload {
  clientMutationId: String
}

type UpdateOrganizationOfferingPayload {
  clientMutationId: String
}

type Version {
  major: Int!
  minor: Int!
  build: Int!
  revision: Int!
}

input AcceptInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input AddCustomTagInput {
  clientMutationId: String
  id: String
  name: String!
  description: String
  color: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input AddOrganizationBankAccountInput {
  clientMutationId: String
  id: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  name: String!
  bankName: String!
  accountHolderName: String!
  accountNumber: String!
  country: String!
  countryCode: String
}

input AddOrganizationBillingDetailsInput {
  clientMutationId: String
  id: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  companyName: String
  email: String!
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
}

input AddOrganizationInput {
  clientMutationId: String
  id: String
  uniqueAlphanumericName: String
  name: String!
  website: String
  type: OrganizationType!
  contactEmail: String
  contactPhone: String
  agreedToTermsOfUse: Boolean!
  termsOfUseId: String!
  industrySubCategoryIds: [String!]!
  featureImages: [CdnImageFileInput!]
  listingMetadata: ListingMetadataInput
  marketplaceListingMetadata: ListingMetadataInput
}

input AddOrganizationPaymentMethodIntentInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input AddOrganizationPhysicalAddressInput {
  clientMutationId: String
  id: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
}

input AddOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  name: String!
  redirectUrl: String!
}

input AddProductTagInput {
  clientMutationId: String
  id: String
  name: String!
  description: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  color: String
}

input AddZoneInput {
  clientMutationId: String
  id: String
  name: String!
  description: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  color: String
}

input CancelInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input CancelOrganizationOfferingInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input CdnFileInput {
  url: String!
  height: Int
  width: Int
}

input CdnImageFileInput {
  original: CdnFileInput
  thumbnail: CdnFileInput
}

input ChangeOrganizationMemberRoleInput {
  clientMutationId: String
  id: String!
  role: OrganizationMemberRole!
}

input ChangeOrganizationMembersStatusInput {
  clientMutationId: String
  ids: [String!]!
  status: OrganizationMemberStatus!
}

input CompleteOrganizationMemberOnboardingInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input CustomTagOrganizationTagWhereInput {
  nameContains: String
}

input DeleteCustomTagInput {
  clientMutationId: String
  id: String!
}

input DeleteCustomTagsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteOrganizationBankAccountInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationBankAccountsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteOrganizationInput {
  clientMutationId: String
  id: String
  uniqueAlphanumericName: String
}

input DeleteOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String!
}

input DeleteOrganizationStripeConnectAccountsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteProductTagInput {
  clientMutationId: String
  id: String!
}

input DeleteProductTagsInput {
  clientMutationId: String
  ids: [String!]!
}

input DeleteZoneInput {
  clientMutationId: String
  id: String!
}

input DeleteZonesInput {
  clientMutationId: String
  ids: [String!]!
}

input InviteCustomersToJoinOrganizationInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  emails: [String!]!
}

input JoinOrganizationInvitationOrderInput {
  direction: OrderDirection!
  field: JoinOrganizationInvitationOrderField!
}

input ListingMetadataInput {
  about: String
  title: String
  subTitle: String
}

input MyInvitationsToJoinOrganizationsWhereInput {
  organizationUniqueAlphanumericName: String
  status: InvitationStatus
}

input OrganizationBankAccountOrderInput {
  direction: OrderDirection!
  field: OrganizationBankAccountOrderField!
}

input OrganizationBankAccountWhereInput {
  organizationUniqueAlphanumericName: String!
  nameContains: String
  onboardingCompleted: Boolean
}

input OrganizationMemberOrderInput {
  direction: OrderDirection!
  field: OrganizationMemberOrderField!
}

input OrganizationMemberWhereInput {
  nameContains: String
  customerId: String
}

input OrganizationOrderInput {
  direction: OrderDirection!
  field: OrganizationOrderField!
}

input OrganizationStripeConnectAccountOrderInput {
  direction: OrderDirection!
  field: OrganizationStripeConnectAccountOrderField!
}

input OrganizationStripeConnectAccountWhereInput {
  organizationId: String
  organizationUniqueAlphanumericName: String
  nameContains: String
  onboardingCompleted: Boolean
}

input OrganizationTagOrderInput {
  direction: OrderDirection!
  field: OrganizationTagOrderField!
}

input OrganizationWhereInput {
  nameContains: String
}

input ProductTagOrganizationTagWhereInput {
  nameContains: String
}

input RejectInvitationToJoinOrganizationInput {
  clientMutationId: String
  id: String!
}

input RemoveOrganizationMembersInput {
  clientMutationId: String
  ids: [String!]!
}

input RemoveOrganizationPaymentMethodInput {
  clientMutationId: String
  id: String!
}

input RemoveOrganizationSsoSettingsInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input RemoveOrganizationTaxDetailsInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
}

input SetOrganizationBankAccountAsDefaultInput {
  clientMutationId: String
  id: String!
}

input SetOrganizationStripeConnectAccountAsDefaultInput {
  clientMutationId: String
  id: String!
}

input UpdateCustomTagInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
  color: String
}

input UpdateOrganizationBankAccountInput {
  clientMutationId: String
  id: String!
  name: String!
  bankName: String!
  accountHolderName: String!
  accountNumber: String!
  country: String!
  countryCode: String
}

input UpdateOrganizationBillingDetailsInput {
  clientMutationId: String
  id: String!
  companyName: String
  email: String!
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
}

input UpdateOrganizationInput {
  clientMutationId: String
  id: String
  uniqueAlphanumericName: String
  name: String!
  website: String
  contactEmail: String
  contactPhone: String
  industrySubCategoryIds: [String!]!
  featureImages: [CdnImageFileInput!]
  listingMetadata: ListingMetadataInput
  marketplaceListingMetadata: ListingMetadataInput
}

input UpdateOrganizationMarketplaceListingMetadataInput {
  clientMutationId: String
  id: String
  uniqueAlphanumericName: String
  marketplaceListingMetadata: ListingMetadataInput!
}

input UpdateOrganizationOfferingInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  offeringCode: String!
}

input UpdateOrganizationPhysicalAddressInput {
  clientMutationId: String
  id: String!
  osmType: String
  osmId: String
  placeId: String
  longitude: Float
  latitude: Float
  formattedAddress: String
  addressLine1: String!
  addressLine2: String
  suburb: String
  city: String
  province: String
  zipcode: String!
  country: String!
  countryCode: String
}

input UpdateOrganizationSsoSettingsInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  entityId: String!
  loginUrl: String!
  appFederationMetadataUrl: String!
  isActive: Boolean!
}

input UpdateOrganizationStripeConnectAccountInput {
  clientMutationId: String
  id: String!
  name: String!
}

input UpdateOrganizationTaxDetailsInput {
  clientMutationId: String
  organizationId: String
  organizationUniqueAlphanumericName: String
  taxId: String!
  taxRatePercentage: Decimal!
}

input UpdateProductTagInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
  color: String
}

input UpdateZoneInput {
  clientMutationId: String
  id: String!
  name: String!
  description: String
  color: String
}

input ZoneOrganizationTagWhereInput {
  nameContains: String
}

enum InvitationStatus {
  PENDING
  ACCEPTED
  REJECTED
  CANCELLED
  EXPIRED
}

enum JoinOrganizationInvitationOrderField {
  CREATED_AT
  STATUS
}

enum OrderDirection {
  ASCENDING
  DESCENDING
}

enum OrganizationBankAccountOrderField {
  NAME
}

enum OrganizationMemberOrderField {
  ROLE
  STATUS
  NAME
  GIVEN_NAME
  MIDDLE_NAME
  FAMILY_NAME
  PHONE_NUMBER
}

enum OrganizationMemberRole {
  OWNER
  ADMINISTRATOR
  MEMBER
}

enum OrganizationMemberStatus {
  ACTIVE
  INACTIVE
}

enum OrganizationOrderField {
  NAME
}

enum OrganizationStripeConnectAccountOrderField {
  NAME
}

enum OrganizationTagOrderField {
  NAME
  DESCRIPTION
  TYPE
}

enum OrganizationTagType {
  CUSTOM
  ZONE
  PRODUCT
  RESOURCE_DESK
  RESOURCE_ROOM
  RESOURCE_PARKING
  RESOURCE_OTHERS
  LOCATION_SPACE_TYPE_CAR_PARK_SPACE
  LOCATION_SPACE_TYPE_EVENT_SPACE
  LOCATION_SPACE_TYPE_MEETING_SPACE
  LOCATION_SPACE_TYPE_OFFICE_SPACE
  LOCATION_SPACE_TYPE_RETAIL_SPACE
  LOCATION_SPACE_TYPE_STORAGE_SPACE
  LOCATION_SPACE_TYPE_STUDIO_SPACE
  LOCATION_SPACE_TYPE_COMMERCIAL_KITCHEN
  LOCATION_SPACE_TYPE_SHOOT_LOCATION
  LOCATION_SPACE_TYPE_OTHERS
}

enum OrganizationType {
  PRIVATE
  MARKETPLACE
  INDIVIDUAL
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

directive @internal on FIELD_DEFINITION

directive @lookup on FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")

"The `Decimal` scalar type represents a decimal floating-point number."
scalar Decimal