//----------------------
// <auto-generated>
// Generated using Skedularctl v1.0.0.0. DO NOT EDIT!
// </auto-generated>
//----------------------

using System.Text.RegularExpressions;
using Enterprise.Shared.Events;
using Google.Protobuf.WellKnownTypes;

#nullable enable

namespace Api.Shared.Clients.Events.Skedular.Location.V1.Value;

public partial class Metadata : IMetadata { }

[KafkaTopic(
    topicPartitionCount: 3,
    retryTopicCount: 1,
    retryTopicPartitionCount: 3,
    deadLetterTopicPartitionCount: 3)]
public partial class Event : IMetadataEvent
{
    private static readonly Regex ValidKafkaTopicCharacters =
        new(@"^[a-z0-9\.\-_]+$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private const string TopicName = "location.v1.event";
    private const string RetryTopicNamePrefix = "location.v1.event.retry";
    private const int RetryTopicCount = 1;
    private const string DeadLetterTopicName = "location.v1.event.deadletter";

    public static Metadata NewMetadata(
        string domainSource,
        string appSource,
        global::Api.Shared.Clients.Events.Skedular.Location.V1.Value.Type type,
        string? correlationId,
        Guid? id = null) =>
        new() {
            Id = id.HasValue ? id.Value.ToString() : Guid.CreateVersion7().ToString(),
            DomainSource = domainSource,
            AppSource = appSource,
            Type = type,
            Time = Timestamp.FromDateTimeOffset(TimeProvider.System.GetUtcNow()),
            CorrelationId = string.IsNullOrWhiteSpace(correlationId) ? Guid.CreateVersion7().ToString() : correlationId,
    };

    public string GetTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? TopicName : $"{prefix}.{TopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public int GetRetryTopicCount() => RetryTopicCount;

    public string GetRetryTopicName(string prefix, int idx)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? $"{RetryTopicNamePrefix}.{idx}" : $"{prefix}.{RetryTopicNamePrefix}.{idx}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string GetDeadLetterTopicName(string prefix)
    {
        var name = string.IsNullOrWhiteSpace(prefix) ? DeadLetterTopicName : $"{prefix}.{DeadLetterTopicName}";
        if (ValidKafkaTopicCharacters.IsMatch(name))
        {
            return name;
        }

        throw new ArgumentException($"Invalid characters in topic name `{name}`", nameof(prefix));
    }

    public string? GetCorrelationId() => Metadata.CorrelationId;
}
