syntax = "proto3";
package organization;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Grpc.Skedular.Organization.Core.V1";

service OrganizationService {

  rpc Admin_Get (Admin_GetInput) returns (Organization);
  rpc Admin_Add (Admin_AddInput) returns (Organization);
  rpc Admin_AddMember (Admin_AddMemberInput) returns (Organization);

  rpc GetVersion (VersionInput) returns (Version);
  rpc GetActiveOrganizationTermsOfUse (GetActiveOrganizationTermsOfUseInput) returns (TermsOfUse);
  rpc Get (GetInput) returns (Organization);
  rpc GetPaginatedMembers (GetPaginatedMembersInput) returns (MemberConnection);
  rpc GetPermissions (GetPermissionsInput) returns (Permissions);

}

message VersionInput {
}

message Version {
  int32 major    = 1;
  int32 minor    = 2;
  int32 build    = 3;
  int32 revision = 4;
}

enum OrderDirection {
  OrderDirection_Ascending  = 0;
  OrderDirection_Descending = 1;
}

message PageInfo {
  bool   hasNextPage     = 1;
  bool   hasPreviousPage = 2;
  string startCursor     = 3;
  string endCursor       = 4;
}

message GetActiveOrganizationTermsOfUseInput {
}

message TermsOfUse {
  string id    = 1;
  string terms = 2;
}

message Admin_AddInput {
  string                   id                                  = 1;
  string                   customDomain                        = 2;
  string                   name                                = 3;
  string                   logoUrl                             = 4;
  string                   website                             = 5;
  bool                     agreedToTermsOfUse                  = 6;
  string                   termsOfUseId                        = 7;
  repeated string          industrySubCategoryIds              = 8;
  string                   offeringCode                        = 9;
  OrganizationType         type                                = 10;
  string                   contactEmail                        = 11;
  string                   contactPhone                        = 12;
  repeated CdnImageFile    featureImages                       = 13;
  ListingMetadata          marketplaceListingMetadata          = 14;
  string                   customerFacingTermsAndConditionsUrl = 15;
  OrganizationBillingCycle billingCycle                        = 16;
  int32                    invoiceDueInDays                    = 17;
}

enum OrganizationType {
  OrganizationType_Private     = 0;
  OrganizationType_Marketplace = 1;
  OrganizationType_Individual  = 2;
}

enum OrganizationBillingCycle {
  OrganizationBillingCycle_Weekly      = 0;
  OrganizationBillingCycle_Fortnightly = 1;
  OrganizationBillingCycle_Monthly     = 2;
}

message Admin_GetOrganizationStripeConnectAccountsResponse {
  repeated StripeConnectAccount accounts = 1;
}

message Organization {
  string                        id                                  = 1;
  string                        customDomain                        = 2;
  string                        name                                = 3;
  string                        logoUrl                             = 4;
  string                        website                             = 5;
  bool                          agreedToTermsOfUse                  = 6;
  string                        termsOfUseId                        = 7;
  repeated IndustrySubCategory  industrySubCategories               = 8;
  repeated OrganizationMember   members                             = 9;
  Offering                      Offering                            = 10;
  bool                          hasAttachedPaymentMethod            = 11;
  bool                          hasFutureBooking                    = 12;
  repeated Tag                  tags                                = 13;
  repeated ResourceType         resourceTypes                       = 14;
  OrganizationType              type                                = 15;
  string                        contactEmail                        = 16;
  string                        contactPhone                        = 17;
  bool                          isListable                          = 18;
  BillingDetails                billingDetails                      = 19;
  StripeCustomer                stripeCustomer                      = 20;
  repeated StripePaymentMethod  stripePaymentMethods                = 21;
  repeated StripeConnectAccount stripeConnectAccounts               = 22;
  TaxDetails                    taxDetails                          = 23;
  PhysicalAddress               physicalAddress                     = 24;
  bool                          isOwnershipVerified                 = 25;
  repeated CdnImageFile         featureImages                       = 26;
  ListingMetadata               marketplaceListingMetadata          = 27;
  OrganizationBillingCycle      billingCycle                        = 28;
  string                        customerFacingTermsAndConditionsUrl = 29;
}

message IndustrySubCategory {
  string id               = 1;
  string name             = 2;
  string mainCategoryName = 3;
}

message Offering {
  string                    id                        = 1;
  string                    code                      = 2;
  google.protobuf.Timestamp start                     = 3;
  google.protobuf.Timestamp end                       = 4;
  bool                      autoRenew                 = 5;
  optional int32            unitPrice                 = 6;
  repeated string           activeCustomerIds         = 7;
  string                    organizationId            = 8;
  Currency                  currency                  = 9;
  optional int32            purchasedUserCapacity     = 10;
  optional int32            purchasedLocationCapacity = 11;
  optional int32            purchasedTeamCapacity     = 12;
  optional int32            fixedPrice                = 13;
}

message Admin_GetInput {
  string id           = 1;
  string customDomain = 2;
}

message GetInput {
  string id           = 1;
  string customDomain = 2;
}

enum OrganizationMemberRole {
  OrganizationMemberRole_Owner         = 0;
  OrganizationMemberRole_Administrator = 1;
  OrganizationMemberRole_Member        = 2;
}

message OrganizationMember {
  string                   id                           = 1;
  string                   customerId                   = 2;
  OrganizationMemberRole   role                         = 3;
  bool                     isOrganizationOnboardingDone = 4;
  OrganizationMemberStatus status                       = 5;
}

enum OrganizationMemberStatus
{
  OrganizationMemberStatus_Active   = 0;
  OrganizationMemberStatus_Inactive = 1;
}

message Admin_AddMemberInput {
  string             id     = 1;
  OrganizationMember member = 2;
}

message GetPaginatedMembersInput {
  string                    after   = 1;
  int32                     first   = 2;
  string                    before  = 3;
  int32                     last    = 4;
  MemberWhereInput          where   = 5;
  repeated MemberOrderInput orderBy = 6;
}

message MemberWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
  string customerId     = 3;
}

message MemberOrderInput {
  OrderDirection   direction = 1;
  MemberOrderField field     = 2;
}

enum MemberOrderField {
  MemberOrderField_RoleType    = 0;
  MemberOrderField_Status      = 1;
  MemberOrderField_Name        = 2;
  MemberOrderField_GivenName   = 3;
  MemberOrderField_MiddleName  = 4;
  MemberOrderField_FamilyName  = 5;
  MemberOrderField_PhoneNumber = 6;
}

message MemberConnection {
  PageInfo            pageInfo   = 1;
  repeated MemberEdge edges      = 2;
  int32               totalCount = 3;
}

message MemberEdge {
  OrganizationMember node   = 1;
  string             cursor = 2;
}

message GetPermissionsInput {
  string id = 1;
}

message Permissions {
  bool canView                            = 1;
  bool canModify                          = 2;
  bool canDelete                          = 3;
  bool canInvitePeople                    = 4;
  bool canCancelPeopleExistingInvitations = 5;
  bool canViewAnalytics                   = 6;
}

message Tag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string tagType     = 4;
  string color       = 5;
}

message CustomTag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message ResourceType {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string tagType     = 4;
  string color       = 5;
}

message BillingDetails {
  string      id               = 1;
  string      companyName      = 2;
  string      email            = 3;
  string      addressLine1     = 4;
  string      addressLine2     = 5;
  string      suburb           = 6;
  string      city             = 7;
  string      province         = 8;
  string      zipcode          = 9;
  string      country          = 10;
  string      countryCode      = 11;
  string      formattedAddress = 12;
  string      osmType          = 13;
  string      osmId            = 14;
  string      placeId          = 15;
  Coordinates coordinates      = 16;
  int32       invoiceDueInDays = 17;
}

message StripeCustomer {
  string id               = 1;
  string stripeCustomerId = 2;
}

message StripePaymentMethod {
  string id            = 1;
  string setupIntentId = 2;
}

message StripeConnectAccount {
  string id                       = 1;
  bool   isDefault                = 2;
  string stripeAccountId          = 3;
  string name                     = 4;
  bool   chargesEnabled           = 5;
  bool   payoutsEnabled           = 6;
  string type                     = 7;
  string country                  = 8;
  string defaultCurrency          = 9;
  string businessType             = 10;
  string companyName              = 11;
  string url                      = 12;
  string supportUrl               = 13;
  string contactEmail             = 14;
  string contactPhone             = 15;
  bool   detailsSubmitted         = 16;
  string capabilitiesTransfers    = 17;
  string capabilitiesCardPayments = 18;
  string onboardingUrl            = 19;
  bool   onboardingCompleted      = 20;
}

message TaxDetails {
  string id                = 1;
  string taxId             = 2;
  double taxRatePercentage = 3;
  bool   isRegistered      = 4;
}

message PhysicalAddress {
  string      id               = 1;
  string      addressLine1     = 2;
  string      addressLine2     = 3;
  string      suburb           = 4;
  string      city             = 5;
  string      province         = 6;
  string      zipcode          = 7;
  string      country          = 8;
  string      countryCode      = 9;
  string      formattedAddress = 10;
  string      osmType          = 11;
  string      osmId            = 12;
  string      placeId          = 13;
  Coordinates coordinates      = 14;
}

message Coordinates {
  double longitude = 1;
  double latitude  = 2;
}

message ProductTag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message CdnImageFile {
  CdnFile original  = 1;
  CdnFile thumbnail = 2;
}

message CdnFile {
  string url    = 1;
  int32  height = 2;
  int32  width  = 3;
}

message ListingMetadata {
  string          about            = 1;
  string          title            = 2;
  string          subTitle         = 3;
  repeated string includedFeatures = 4;
}

enum Currency {
  Currency_Nzd = 0;
  Currency_Usd = 1;
}
