syntax = "proto3";
package billing;

option csharp_namespace = "Api.Shared.Services.Grpc.Skedular.Billing.V1";

service BillingService {
    rpc GetVersion (VersionInput) returns (Version);
    rpc GetOrganizationPermissions (GetOrganizationPermissionsInput) returns (OrganizationPermissions);
    rpc GetOrganizationBillingInfo (GetOrganizationBillingInfoInput) returns (OrganizationBillingInfo);
    rpc SetOrganizationBillingInfo (SetOrganizationBillingInfoInput) returns (OrganizationBillingInfo);
}

message VersionInput {
}

message Version {
    int32 major = 1;
    int32 minor = 2;
    int32 build = 3;
    int32 revision = 4;
}

message GetOrganizationPermissionsInput {
    string organizationId = 1;
}

message OrganizationPermissions {
    bool canViewBillingInfo = 1;
    bool canManageBillingInfo = 2;
}

message GetOrganizationBillingInfoInput {
    string organizationId = 1;
}

message OrganizationBillingInfo {
    string email = 1;
    string addressLine1 = 2;
    string addressLine2 = 3;
    string suburb = 4;
    string city = 5;
    string province = 6;
    string zipcode = 7;
    string country = 8;
}

message SetOrganizationBillingInfoInput {
    string organizationId = 1;
    string email = 2;
    string addressLine1 = 3;
    string addressLine2 = 4;
    string suburb = 5;
    string city = 6;
    string province = 7;
    string zipcode = 8;
    string country = 9;
}
