syntax = "proto3";
package booking;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Services.Grpc.Skedular.Booking.V1";

service BookingService {
    rpc Admin_GetPaginatedBookings (Admin_GetPaginatedBookingsInput) returns (BookingConnection);
    rpc Admin_Add (Admin_AddInput) returns (Booking);

    rpc GetVersion (VersionInput) returns (Version);
    rpc GetPaginatedBookings (GetPaginatedBookingsInput) returns (BookingConnection);
    rpc GetOrganizationPermissions (GetOrganizationPermissionsInput) returns (OrganizationPermissions);
    rpc GetLocationPermissions (GetLocationPermissionsInput) returns (LocationPermissions);
    rpc GetTeamPermissions (GetTeamPermissionsInput) returns (TeamPermissions);
    rpc Get (GetInput) returns (Booking);
    rpc Add (AddInput) returns (Booking);
    rpc Update (UpdateInput) returns (Booking);
    rpc Delete (DeleteInput) returns (Booking);
    rpc GetAvailableResources (GetAvailableResourcesInput) returns (AvailableResources);
}

message VersionInput {
}

message Version {
    int32 major = 1;
    int32 minor = 2;
    int32 build = 3;
    int32 revision = 4;
}

enum OrderDirection {
    Ascending = 0;
    Descending = 1;
}

message PageInfo {
    bool hasNextPage = 1;
    bool hasPreviousPage =2;
    string startCursor =3;
    string endCursor =4;
}

message Admin_GetPaginatedBookingsInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    BookingWhereInput where = 5;
    repeated BookingOrderInput orderBy = 6;
}

message GetPaginatedBookingsInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    BookingWhereInput where = 5;
    repeated BookingOrderInput orderBy = 6;
}

message BookingWhereInput {
    google.protobuf.Timestamp fromGT = 1;
    google.protobuf.Timestamp fromGTE  = 2;
    google.protobuf.Timestamp fromLT  = 3;
    google.protobuf.Timestamp fromLTE  = 4;
    google.protobuf.Timestamp toGT  = 5;
    google.protobuf.Timestamp toGTE  = 6;
    google.protobuf.Timestamp toLT  = 7;
    google.protobuf.Timestamp toLTE  = 8;
    string notesContains  = 9;
    string nameContains  = 10;
    repeated string  organizationIds  = 11;
    repeated string locationIds  = 12;
    repeated string teamIds  = 13;
    repeated string customerIds  = 14;
    bool includeMineOnly  = 15;
    bool includeFutureBookingsOnly  = 16;
    bool combineOrganizationsLocationsTeams = 17;
    string type = 18;
}

message BookingOrderInput {
    OrderDirection direction = 1;
    BookingOrderField field = 2;
}

enum BookingOrderField {
    From= 0;
    To= 1;
    Notes= 2;
    Name= 3;
    GivenName= 4;
    MiddleName= 5;
    FamilyName= 6;
    OrganizationName= 7;
    LocationName= 8;
    TeamName= 9;
    Type= 10;
}

enum BookingType
{
    WorkingFromHome = 0;
    WorkingFromOffice = 1;
    SickLeave = 2;
    AnnualLeave = 3;
    WellBeingLeave = 4;
    ClientOffices = 5;
    Vacation = 6;
    TravelingForWork = 7;
    NonWorkingDay = 8;
}

message BookingConnection {
    PageInfo pageInfo = 1;
    repeated BookingEdge edges = 2;
    int32 totalCount = 3;
}

message BookingEdge {
    Booking node = 1;
    string cursor = 2;
}

message Booking {
    string id = 1;
    google.protobuf.Timestamp from = 2;
    google.protobuf.Timestamp to = 3;
    string notes = 4;
    Customer customer = 5;
    Organization organization = 6;
    Location location = 7;
    Team team = 8;
    repeated Resource resources = 9;
    BookingType type = 10;
}

message Customer {
    string id = 1;
    string name = 2;
    string givenName = 3;
    string middleName = 4;
    string familyName = 5;
    string photoUrl = 6;
    string photoUrl24 = 7;
    string photoUrl32 = 8;
    string photoUrl48 = 9;
    string photoUrl72 = 10;
    string photoUrl192 = 11;
    string photoUrl512 = 12;
    repeated Identity identities = 13;
}

message Identity {
    string id = 1;
    string email = 2;
    bool emailVerified = 3;
}

message Organization {
    string id = 1;
    string name = 2;
}

message Location {
    string id = 1;
    string name = 2;
}

message Team {
    string id = 1;
    string name = 2;
}

message OrganizationCustomTag {
    string id = 1;
    string name = 2;
    string color = 3;
}

message OrganizationZone {
    string id = 1;
    string name = 2;
    string color = 3;
}

message GetOrganizationPermissionsInput {
    string organizationId = 1;
}

message OrganizationPermissions {
    bool canViewBookings = 1;
    bool canAddBooking = 2;
    bool canUpdateBooking = 3;
    bool canDeleteBooking = 4;
    bool canAddBookingOnBehalf = 5;
    bool canUpdateBookingOnBehalf = 6;
    bool canDeleteBookingOnBehalf = 7;
}

message GetLocationPermissionsInput {
    string locationId = 1;
}

message LocationPermissions {
    bool canViewBookings = 1;
    bool canAddBooking = 2;
    bool canUpdateBooking = 3;
    bool canDeleteBooking = 4;
    bool canAddBookingOnBehalf = 5;
    bool canUpdateBookingOnBehalf = 6;
    bool canDeleteBookingOnBehalf = 7;
}

message GetTeamPermissionsInput {
    string teamId = 1;
}

message TeamPermissions {
    bool canViewBookings = 1;
    bool canAddBooking = 2;
    bool canUpdateBooking = 3;
    bool canDeleteBooking = 4;
    bool canAddBookingOnBehalf = 5;
    bool canUpdateBookingOnBehalf = 6;
    bool canDeleteBookingOnBehalf = 7;
}

message GetInput {
    string id = 1;
}

message Admin_AddInput {
    string id = 1;
    google.protobuf.Timestamp from = 2;
    google.protobuf.Timestamp until = 3;
    string notes = 4;
    string customerId = 5;
    string organizationId = 6;
    string locationId = 7;
    string teamId = 8;
    repeated string resourceIds = 9;
    BookingType type = 10;
}

message AddInput {
    string id = 1;
    google.protobuf.Timestamp from = 2;
    google.protobuf.Timestamp until = 3;
    string notes = 4;
    string customerId = 5;
    string organizationId = 6;
    string locationId = 7;
    string teamId = 8;
    repeated string resourceIds = 9;
    BookingType type = 10;
}

message UpdateInput {
    string id = 1;
    google.protobuf.Timestamp from = 2;
    google.protobuf.Timestamp until = 3;
    string notes = 4;
    string customerId = 5;
    string organizationId = 6;
    string locationId = 7;
    string teamId = 8;
    repeated string resourceIds = 9;
    BookingType type = 10;
}

message DeleteInput {
    string id = 1;
}

message Resource {
    string id = 1;
    string name = 2;
    Location location = 3;
    repeated OrganizationCustomTag organizationCustomTags = 4;
    repeated OrganizationZone organizationZones = 5;
    string color = 6;
    repeated Customer customers = 7;
    ResourceType resourceType = 8;
    int32 capacity = 9;
}

message GetAvailableResourcesInput {
    string organizationId = 1;
    string locationId = 2;
    google.protobuf.Timestamp from = 3;
    google.protobuf.Timestamp until = 4;
    repeated string CustomTagIds = 5;
    repeated string ZoneIds = 6;
    repeated string resourceIdsToInclude = 7;
}

message AvailableResources {
    repeated Resource resources = 1;
}

message ResourceType {
    string id = 1;
    string name = 2;
    string color = 3;
}
