syntax = "proto3";
package location;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Services.Grpc.Skedular.Location.V1";

service LocationService {
  rpc RaiseGraphqlChange (RaiseGraphqlChangeInput) returns (RaiseGraphqlChangeResponse);

  rpc Admin_Add (Admin_AddInput) returns (Location);
  rpc Admin_Update (Admin_UpdateInput) returns (Location);
  rpc Admin_GetPaginatedLocations (Admin_GetPaginatedLocationsInput) returns (LocationConnection);
  rpc Admin_Get (Admin_GetInput) returns (Location);
  rpc Admin_GetResource (Admin_GetResourceInput) returns (Resource);

  rpc GetVersion (VersionInput) returns (Version);
  rpc Get (GetInput) returns (Location);
  rpc GetPaginatedLocations (GetPaginatedLocationsInput) returns (LocationConnection);
  rpc GetPermissions (GetPermissionsInput) returns (Permissions);
  rpc Add (AddInput) returns (Location);
  rpc Update (UpdateInput) returns (Location);
  rpc Remove (RemoveInput) returns (Location);

  rpc GetPaginatedResources (GetPaginatedResourcesInput) returns (ResourceConnection);
  rpc GetResource (GetResourceInput) returns (Resource);
  rpc AddResource (AddResourceInput) returns (Resource);
  rpc UpdateResource (UpdateResourceInput) returns (Resource);
  rpc RemoveResource (RemoveResourceInput) returns (Resource);
}

message RaiseGraphqlChangeInput {
  string topicName = 1;
  string id        = 2;
}

message RaiseGraphqlChangeResponse {
}

message VersionInput {
}

message Version {
  int32 major    = 1;
  int32 minor    = 2;
  int32 build    = 3;
  int32 revision = 4;
}

enum OrderDirection {
  OrderDirection_Ascending  = 0;
  OrderDirection_Descending = 1;
}

message PageInfo {
  bool   hasNextPage     = 1;
  bool   hasPreviousPage = 2;
  string startCursor     = 3;
  string endCursor       = 4;
}

message Customer {
  string            id          = 1;
  string            name        = 2;
  string            givenName   = 3;
  string            middleName  = 4;
  string            familyName  = 5;
  string            photoUrl    = 6;
  string            photoUrl24  = 7;
  string            photoUrl32  = 8;
  string            photoUrl48  = 9;
  string            photoUrl72  = 10;
  string            photoUrl192 = 11;
  string            photoUrl512 = 12;
  repeated Identity identities  = 13;
}

message Identity {
  string id            = 1;
  string email         = 2;
  bool   emailVerified = 3;
}

enum LocationType {
  LocationType_Private     = 0;
  LocationType_Marketplace = 1;
}

message Admin_AddInput {
  string                id              = 1;
  string                name            = 2;
  ListingMetadata       listingMetadata = 3;
  string                organizationId  = 4;
  string                timezone        = 5;
  repeated string       tagIds          = 6;
  repeated CdnImageFile featureImages   = 7;
  LocationType          type            = 8;
  ExtraMetadata         ExtraMetadata   = 9;
  PhysicalAddress       physicalAddress = 10;
  string                uniqueClaimCode = 11;
}

message Admin_UpdateInput {
  string                id              = 1;
  string                name            = 2;
  ListingMetadata       listingMetadata = 3;
  string                organizationId  = 4;
  string                timezone        = 5;
  repeated string       tagIds          = 6;
  repeated CdnImageFile featureImages   = 7;
  LocationType          type            = 8;
  ExtraMetadata         ExtraMetadata   = 9;
  PhysicalAddress       physicalAddress = 10;
  string                uniqueClaimCode = 11;
}

message LocationConnection {
  PageInfo              pageInfo   = 1;
  repeated LocationEdge edges      = 2;
  int32                 totalCount = 3;
}

message LocationEdge {
  Location node   = 1;
  string   cursor = 2;
}

message Location {
  string                id                   = 1;
  string                name                 = 2;
  ListingMetadata       listingMetadata      = 3;
  string                organizationId       = 4;
  string                timezone             = 5;
  repeated Resource     resources            = 6;
  Permissions           permissions          = 7;
  repeated string       tagIds               = 8;
  repeated string       customTagIds         = 9;
  repeated string       zoneIds              = 10;
  repeated string       spaceTypeIds         = 11;
  OpeningHours          openingHours         = 12;
  repeated CdnImageFile featureImages        = 13;
  LocationType          type                 = 14;
  ExtraMetadata         ExtraMetadata        = 15;
  PhysicalAddress       physicalAddress      = 16;
  string                uniqueClaimCode      = 17;
  bool                  contactedViaEmail    = 18;
  bool                  contactedViaSms      = 19;
  bool                  contactedViaCall     = 20;
  bool                  contactedViaWhatsapp = 21;
}

message Admin_GetInput {
  string id = 1;
}

message GetInput {
  string id = 1;
}

message Admin_GetPaginatedLocationsInput {
  string                      after   = 1;
  int32                       first   = 2;
  string                      before  = 3;
  int32                       last    = 4;
  LocationWhereInput          where   = 5;
  repeated LocationOrderInput orderBy = 6;
}

message GetPaginatedLocationsInput {
  string                      after   = 1;
  int32                       first   = 2;
  string                      before  = 3;
  int32                       last    = 4;
  LocationWhereInput          where   = 5;
  repeated LocationOrderInput orderBy = 6;
}

message LocationWhereInput {
  string                organizationId                     = 1;
  string                organizationUniqueAlphanumericName = 2;
  repeated string       locationIds                        = 3;
  string                nameContains                       = 4;
  repeated string       tagIds                             = 5;
  repeated LocationType types                              = 6;
  bool                  notContactedYet                    = 7;
}

message LocationOrderInput {
  OrderDirection     direction = 1;
  LocationOrderField field     = 2;
}

enum LocationOrderField {
  LocationOrderField_Name     = 0;
  LocationOrderField_Timezone = 1;
}

message GetPermissionsInput {
  string id = 1;
}

message Permissions {
  bool canView          = 1;
  bool canModify        = 2;
  bool canDelete        = 3;
  bool canViewAnalytics = 4;
}

message AddInput {
  string                id              = 1;
  string                name            = 2;
  ListingMetadata       listingMetadata = 3;
  string                organizationId  = 4;
  string                timezone        = 5;
  repeated string       tagIds          = 6;
  repeated CdnImageFile featureImages   = 7;
  LocationType          type            = 8;
  ExtraMetadata         ExtraMetadata   = 9;
  PhysicalAddress       physicalAddress = 10;
  string                uniqueClaimCode = 11;
}

message UpdateInput {
  string                id              = 1;
  string                name            = 2;
  ListingMetadata       listingMetadata = 3;
  string                organizationId  = 4;
  string                timezone        = 5;
  repeated string       tagIds          = 6;
  repeated CdnImageFile featureImages   = 7;
  LocationType          type            = 8;
  ExtraMetadata         ExtraMetadata   = 9;
  PhysicalAddress       physicalAddress = 10;
  string                uniqueClaimCode = 11;
}

message RemoveInput {
  string id = 1;
}

message Resource {
  string          id                         = 1;
  string          name                       = 2;
  bool            inactive                   = 3;
  bool            requireBookingApproval     = 4;
  repeated string customTagIds               = 5;
  repeated string zoneIds                    = 6;
  repeated string productTagIds              = 7;
  string          color                      = 8;
  bool            isAvailableHoursOverridden = 9;
  OpeningHours    availableHours             = 10;
  string          resourceTypeId             = 11;
  int32           capacity                   = 12;
}

message ResourceConnection {
  PageInfo              pageInfo   = 1;
  repeated ResourceEdge edges      = 2;
  int32                 totalCount = 3;
}

message ResourceEdge {
  Resource node   = 1;
  string   cursor = 2;
}

message GetPaginatedResourcesInput {
  string                      after   = 1;
  int32                       first   = 2;
  string                      before  = 3;
  int32                       last    = 4;
  ResourceWhereInput          where   = 5;
  repeated ResourceOrderInput orderBy = 6;
}

message ResourceWhereInput {
  string          locationId   = 1;
  string          nameContains = 2;
  repeated string tagIds       = 3;
  string          floorPlanId  = 4;
}

message ResourceOrderInput {
  OrderDirection     direction = 1;
  ResourceOrderField field     = 2;
}

enum ResourceOrderField {
  ResourceOrderField_ResourceName = 0;
}

message Admin_GetResourceInput {
  string id = 1;
}

message GetResourceInput {
  string id = 1;
}

message AddResourceInput {
  string          id                     = 1;
  string          locationId             = 2;
  string          name                   = 3;
  bool            inactive               = 4;
  bool            requireBookingApproval = 5;
  repeated string tagIds                 = 6;
  string          color                  = 7;
  int32           capacity               = 8;
}

message UpdateResourceInput {
  string          id                     = 1;
  string          name                   = 2;
  bool            inactive               = 3;
  bool            requireBookingApproval = 4;
  repeated string tagIds                 = 5;
  string          color                  = 6;
  int32           capacity               = 7;
}

message RemoveResourceInput {
  string id = 1;
}

message OpeningHours {
  WeekOpeningHours                   weekOpeningHours            = 1;
  repeated google.protobuf.Timestamp closedDates                 = 2;
  repeated VariedDateOpeningHours    DatesWithVariedOpeningHours = 3;
}

message WeekOpeningHours {
  OpeningHoursDetails monday    = 1;
  OpeningHoursDetails tuesday   = 2;
  OpeningHoursDetails wednesday = 3;
  OpeningHoursDetails thursday  = 4;
  OpeningHoursDetails friday    = 5;
  OpeningHoursDetails saturday  = 6;
  OpeningHoursDetails sunday    = 7;
}

message VariedDateOpeningHours {
  google.protobuf.Timestamp date                = 1;
  OpeningHoursDetails       openingHoursDetails = 2;
}

message OpeningHoursDetails {
  bool   closed     = 1;
  bool   openAllDay = 2;
  string from       = 3;
  string until      = 4;
}

message CdnImageFile {
  CdnFile original  = 1;
  CdnFile thumbnail = 2;
}

message CdnFile {
  string url    = 1;
  int32  height = 2;
  int32  width  = 3;
}

message ContactDetails {
  repeated string contactPeople = 1;
  repeated string contactEmails = 2;
  repeated string contactPhones = 3;
}

message AreaRange {
  string fromInSqm = 1;
  string toInSqm   = 2;
}

message PeopleCapacity {
  string from = 1;
  string to   = 2;
}

message ExtraMetadata {
  ContactDetails  contactDetails    = 1;
  AreaRange       areaRange         = 2;
  PeopleCapacity  peopleCapacity    = 3;
  string          website           = 4;
  repeated string RelatedImageLinks = 5;
  repeated string RelatedVideoLinks = 6;
  repeated string OtherLinks        = 7;
}

message PhysicalAddress {
  string      id               = 1;
  string      addressLine1     = 2;
  string      addressLine2     = 3;
  string      suburb           = 4;
  string      city             = 5;
  string      province         = 6;
  string      zipcode          = 7;
  string      country          = 8;
  string      countryCode      = 9;
  string      formattedAddress = 10;
  string      osmType          = 11;
  string      osmId            = 12;
  string      placeId          = 13;
  Coordinates coordinates      = 14;
}

message Coordinates {
  double longitude = 1;
  double latitude  = 2;
}

message ListingMetadata {
  string about      = 1;
  string mainHeader = 2;
  string subHeader  = 3;
}
