syntax = "proto3";
package organization;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Services.Grpc.Skedular.Organization.V1";

service OrganizationService {
    rpc Admin_Add (Admin_AddInput) returns (Organization);
    rpc Admin_AddMember (Admin_AddMemberInput) returns (Organization);
    rpc Admin_GetStripeConnectAccounts (Admin_GeStripeConnectAccountsInput) returns (StripeConnectAccountConnection);

    rpc GetVersion (VersionInput) returns (Version);
    rpc GetActiveOrganizationTermsOfUse (GetActiveOrganizationTermsOfUseInput) returns (TermsOfUse);
    rpc Get (GetInput) returns (Organization);
    rpc GetPaginatedMembers (GetPaginatedMembersInput) returns (MemberConnection);
    rpc GetPermissions (GetPermissionsInput) returns (Permissions);

    rpc GetPaginatedCustomTags (GetPaginatedCustomTagsInput) returns (CustomTagConnection);
    rpc GetCustomTag (GetCustomTagInput) returns (CustomTag);
    rpc AddCustomTag (AddCustomTagInput) returns (CustomTag);
    rpc UpdateCustomTag (UpdateCustomTagInput) returns (CustomTag);
    rpc RemoveCustomTag (RemoveCustomTagInput) returns (CustomTag);

    rpc GetPaginatedZones (GetPaginatedZonesInput) returns (ZoneConnection);
    rpc GetZone (GetZoneInput) returns (Zone);
    rpc AddZone (AddZoneInput) returns (Zone);
    rpc UpdateZone (UpdateZoneInput) returns (Zone);
    rpc RemoveZone (RemoveZoneInput) returns (Zone);
    rpc GetBillingDetails (GetBillingDetailsInput) returns (BillingDetails);
    rpc AddBillingDetails (AddBillingDetailsInput) returns (BillingDetails);
    rpc UpdateBillingDetails (UpdateBillingDetailsInput) returns (BillingDetails);
}

message VersionInput {
}

message Version {
    int32 major = 1;
    int32 minor = 2;
    int32 build = 3;
    int32 revision = 4;
}

enum OrderDirection {
    OrderDirection_Ascending = 0;
    OrderDirection_Descending = 1;
}

message PageInfo {
    bool hasNextPage = 1;
    bool hasPreviousPage =2;
    string startCursor =3;
    string endCursor =4;
}

message GetActiveOrganizationTermsOfUseInput {
}

message TermsOfUse {
    string id = 1;
    string terms = 2;
}

message Admin_AddInput {
    string id = 1;
    string name = 2;
    string about = 3;
    string logoUrl = 4;
    string website = 5;
    bool agreedToTermsOfUse = 6;
    string termsOfUseId = 7;
    repeated string industrySubCategoryIds = 8;
    string offeringCode = 9;
    string type = 10;
    string memberVisibilityPolicy = 11;
    string contactEmail = 12;
    string contactPhone = 13;
}

message Admin_GetOrganizationStripeConnectAccountsResponse {
    repeated StripeConnectAccount accounts = 1;
}

message Organization {
    string id = 1;
    string name = 2;
    string about = 3;
    string logoUrl = 4;
    string website = 5;
    bool agreedToTermsOfUse = 6;
    string termsOfUseId = 7;
    repeated IndustrySubCategory industrySubCategories = 8;
    repeated OrganizationMember members = 9;
    Offering Offering = 10;
    bool hasAttachedPaymentMethod = 11;
    bool hasFutureBooking = 12;
    repeated Tag tags = 13;
    repeated ResourceType resourceTypes = 14;
    string type = 15;
    string memberVisibilityPolicy = 16;
    string contactEmail = 17;
    string contactPhone = 18;
    BillingDetails billingDetails = 19;
    StripeCustomer stripeCustomer = 20;
    repeated StripePaymentMethod stripePaymentMethods = 21;
    repeated StripeConnectAccount stripeConnectAccounts = 22;
}

message IndustrySubCategory {
    string id = 1;
    string name = 2;
    string mainCategoryName = 3;
}

message Offering {
    string id = 1;
    string code = 2;
    google.protobuf.Timestamp start = 3;
    google.protobuf.Timestamp end = 4;
    bool autoRenew = 5;
    int32 unitPrice = 6;
    repeated string activeCustomerIds = 7;
    string organizationId = 8;
}

message GetInput {
    string id = 1;
}

enum Role {
    Role_Owner = 0;
    Role_Administrator = 1;
    Role_Member = 2;
}

message OrganizationMember {
    string id = 1;
    Customer customer = 2;
    Role role = 3;
    bool isOrganizationOnboardingDone = 4;
    OrganizationMemberStatus status = 5;
}

enum OrganizationMemberStatus
{
    OrganizationMemberStatus_Active = 0;
    OrganizationMemberStatus_Inactive = 1;
}

message Admin_AddMemberInput {
    string id = 1;
    OrganizationMember member = 2;
}

message Admin_GeStripeConnectAccountsInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    StripeConnectAccountWhereInput where = 5;
    repeated StripeConnectAccountOrderInput orderBy = 6;
}

message GetPaginatedMembersInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    MemberWhereInput where = 5;
    repeated MemberOrderInput orderBy = 6;
}

message MemberWhereInput {
    string organizationId  = 1;
    string nameContains  = 2;
    string customerId  = 3;
}

message MemberOrderInput {
    OrderDirection direction = 1;
    MemberOrderField field = 2;
}

enum MemberOrderField {
    MemberOrderField_RoleType = 0;
    MemberOrderField_Status = 1;
    MemberOrderField_Name= 2;
    MemberOrderField_GivenName= 3;
    MemberOrderField_MiddleName= 4;
    MemberOrderField_FamilyName= 5;
    MemberOrderField_PhoneNumber= 6;
}

message MemberConnection {
    PageInfo pageInfo = 1;
    repeated MemberEdge edges = 2;
    int32 totalCount = 3;
}

message MemberEdge {
    OrganizationMember node = 1;
    string cursor = 2;
}

message Customer {
    string id = 1;
    string name = 2;
    string givenName = 3;
    string middleName = 4;
    string familyName = 5;
    string photoUrl = 6;
    string photoUrl24 = 7;
    string photoUrl32 = 8;
    string photoUrl48 = 9;
    string photoUrl72 = 10;
    string photoUrl192 = 11;
    string photoUrl512 = 12;
    repeated Identity identities = 13;
    string phoneNumber = 14;
}

message Identity {
    string id = 1;
    string email = 2;
    bool emailVerified = 3;
}

message GetPermissionsInput {
    string id = 1;
}

message Permissions {
    bool canView = 1;
    bool canModify = 2;
    bool canDelete = 3;
    bool canInvitePeople = 4;
    bool canCancelPeopleExistingInvitations = 5;
    bool canViewAnalytics = 6;
}

message Tag {
    string id = 1;
    string name = 2;
    string description = 3;
    string color = 4;
}

message CustomTag {
    string id = 1;
    string name = 2;
    string description = 3;
    string color = 4;
}

message CustomTagConnection {
    PageInfo pageInfo = 1;
    repeated CustomTagEdge edges = 2;
    int32 totalCount = 3;
}

message CustomTagEdge {
    CustomTag node = 1;
    string cursor = 2;
}

message GetPaginatedCustomTagsInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    CustomTagWhereInput where = 5;
    repeated CustomTagOrderInput orderBy = 6;
}

message CustomTagWhereInput {
    string organizationId = 1;
    string nameContains = 2;
}

message CustomTagOrderInput {
    OrderDirection direction = 1;
    CustomTagOrderField field = 2;
}

enum CustomTagOrderField {
    CustomTagOrderField_Name = 0;
    CustomTagOrderField_Description = 1;
}

message GetCustomTagInput {
    string id = 1;
}

message AddCustomTagInput {
    string id = 1;
    string organizationId = 2;
    string name = 3;
    string description = 4;
    string color = 5;
}

message UpdateCustomTagInput {
    string id = 1;
    string name = 2;
    string description = 3;
    string color = 4;
}

message RemoveCustomTagInput {
    string id = 1;
}

message Zone {
    string id = 1;
    string name = 2;
    string description = 3;
    string color = 4;
}

message ZoneConnection {
    PageInfo pageInfo = 1;
    repeated ZoneEdge edges = 2;
    int32 totalCount = 3;
}

message ZoneEdge {
    Zone node = 1;
    string cursor = 2;
}

message GetPaginatedZonesInput {
    string after = 1;
    int32 first = 2;
    string before = 3;
    int32 last = 4;
    ZoneWhereInput where = 5;
    repeated ZoneOrderInput orderBy = 6;
}

message ZoneWhereInput {
    string organizationId = 1;
    string nameContains = 2;
}

message ZoneOrderInput {
    OrderDirection direction = 1;
    ZoneOrderField field = 2;
}

enum ZoneOrderField {
    ZoneOrderField_Name = 0;
    ZoneOrderField_Description = 1;
}

message GetZoneInput {
    string id = 1;
}

message AddZoneInput {
    string id = 1;
    string organizationId = 2;
    string name = 3;
    string description = 4;
    string color = 5;
}

message UpdateZoneInput {
    string id = 1;
    string name = 2;
    string description = 3;
    string color = 4;
}

message RemoveZoneInput {
    string id = 1;
}

message ResourceType {
    string id = 1;
    string name = 2;
    string description = 3;
    string tagType = 4;
    string color = 5;
}

message GetBillingDetailsInput {
    string organizationId = 1;
}

message AddBillingDetailsInput {
    string id = 1;
    string organizationId = 2;
    string companyName = 3;
    string email = 4;
    string addressLine1 = 5;
    string addressLine2 = 6;
    string suburb = 7;
    string city = 8;
    string province = 9;
    string zipcode = 10;
    string country = 11;
}

message UpdateBillingDetailsInput {
    string id = 1;
    string companyName = 2;
    string email = 3;
    string addressLine1 = 4;
    string addressLine2 = 5;
    string suburb = 6;
    string city = 7;
    string province = 8;
    string zipcode = 9;
    string country = 10;
}

message BillingDetails {
    string id = 1;
    string companyName = 2;
    string email = 3;
    string addressLine1 = 4;
    string addressLine2 = 5;
    string suburb = 6;
    string city = 7;
    string province = 8;
    string zipcode = 9;
    string country = 10;
}

message StripeCustomer {
    string id = 1;
    string stripeCustomerId = 2;
}

message StripePaymentMethod {
    string id = 1;
    string setupIntentId = 2;
}

message StripeConnectAccountWhereInput {
    string organizationId = 1;
    string nameContains = 2;
    bool onboardingCompleted = 3;
}

message StripeConnectAccountOrderInput {
    OrderDirection direction = 1;
    StripeConnectAccountOrderField field = 2;
}

enum StripeConnectAccountOrderField {
    StripeConnectAccountOrderField_Name = 0;
}

message StripeConnectAccountConnection {
    PageInfo pageInfo = 1;
    repeated StripeConnectAccountEdge edges = 2;
    int32 totalCount = 3;
}

message StripeConnectAccountEdge {
    StripeConnectAccount node = 1;
    string cursor = 2;
}

message StripeConnectAccount {
    string id = 1;
    bool isDefault = 2;
    string stripeAccountId = 3;
    string Name = 4;
    bool ChargesEnabled = 5;
    bool PayoutsEnabled = 6;
    string Type = 7;
    string Country = 8;
    string DefaultCurrency = 9;
    string BusinessType = 10;
    string CompanyName = 11;
    string Url = 12;
    string SupportUrl = 13;
    string ContactEmail = 14;
    string ContactPhone = 15;
    bool DetailsSubmitted = 16;
    string CapabilitiesTransfers = 17;
    string CapabilitiesCardPayments = 18;
    string OnboardingUrl = 19;
    bool OnboardingCompleted = 20; 
}
