syntax = "proto3";
package organization;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Api.Shared.Services.Grpc.Skedular.Organization.V1";

service OrganizationService {
  rpc RaiseGraphqlChange (RaiseGraphqlChangeInput) returns (RaiseGraphqlChangeResponse);

  rpc Admin_Get (Admin_GetInput) returns (Organization);
  rpc Admin_Add (Admin_AddInput) returns (Organization);
  rpc Admin_AddMember (Admin_AddMemberInput) returns (Organization);
  rpc Admin_GetStripeConnectAccounts (Admin_GetStripeConnectAccountsInput) returns (StripeConnectAccountConnection);
  rpc Admin_GetBankAccounts (Admin_GetBankAccountsInput) returns (BankAccountConnection);
  rpc Admin_GetXeroConnection (Admin_GetXeroConnectionInput) returns (XeroConnection);
  rpc Admin_RefreshXeroConnectionTokens (Admin_RefreshXeroConnectionTokensInput) returns (XeroConnection);
  rpc Admin_GetTag (Admin_GetTagInput) returns (Tag);
  rpc Admin_GetPaginatedTags (Admin_GetPaginatedTagsInput) returns (TagConnection);
  rpc Admin_GetCustomTag (Admin_GetCustomTagInput) returns (CustomTag);
  rpc Admin_GetZone (Admin_GetZoneInput) returns (Zone);
  rpc Admin_GetProductTag (Admin_GetProductTagInput) returns (ProductTag);

  rpc GetVersion (VersionInput) returns (Version);
  rpc GetActiveOrganizationTermsOfUse (GetActiveOrganizationTermsOfUseInput) returns (TermsOfUse);
  rpc Get (GetInput) returns (Organization);
  rpc GetPaginatedMembers (GetPaginatedMembersInput) returns (MemberConnection);
  rpc GetPermissions (GetPermissionsInput) returns (Permissions);

  rpc GetPaginatedTags (GetPaginatedTagsInput) returns (TagConnection);
  rpc GetTag (GetTagInput) returns (Tag);
  rpc AddTag (AddTagInput) returns (Tag);
  rpc UpdateTag (UpdateTagInput) returns (Tag);
  rpc RemoveTag (RemoveTagInput) returns (Tag);

  rpc GetPaginatedCustomTags (GetPaginatedCustomTagsInput) returns (CustomTagConnection);
  rpc GetCustomTag (GetCustomTagInput) returns (CustomTag);
  rpc AddCustomTag (AddCustomTagInput) returns (CustomTag);
  rpc UpdateCustomTag (UpdateCustomTagInput) returns (CustomTag);
  rpc RemoveCustomTag (RemoveCustomTagInput) returns (CustomTag);

  rpc GetPaginatedZones (GetPaginatedZonesInput) returns (ZoneConnection);
  rpc GetZone (GetZoneInput) returns (Zone);
  rpc AddZone (AddZoneInput) returns (Zone);
  rpc UpdateZone (UpdateZoneInput) returns (Zone);
  rpc RemoveZone (RemoveZoneInput) returns (Zone);

  rpc GetPaginatedProductTags (GetPaginatedProductTagsInput) returns (ProductTagConnection);
  rpc GetProductTag (GetProductTagInput) returns (ProductTag);
  rpc AddProductTag (AddProductTagInput) returns (ProductTag);
  rpc UpdateProductTag (UpdateProductTagInput) returns (ProductTag);
  rpc RemoveProductTag (RemoveProductTagInput) returns (ProductTag);

  rpc GetBillingDetails (GetBillingDetailsInput) returns (BillingDetails);
  rpc AddBillingDetails (AddBillingDetailsInput) returns (BillingDetails);
  rpc UpdateBillingDetails (UpdateBillingDetailsInput) returns (BillingDetails);
}

message RaiseGraphqlChangeInput {
  string topicName = 1;
  string id        = 2;
}

message RaiseGraphqlChangeResponse {
}

message VersionInput {
}

message Version {
  int32 major    = 1;
  int32 minor    = 2;
  int32 build    = 3;
  int32 revision = 4;
}

enum OrderDirection {
  OrderDirection_Ascending  = 0;
  OrderDirection_Descending = 1;
}

message PageInfo {
  bool   hasNextPage     = 1;
  bool   hasPreviousPage = 2;
  string startCursor     = 3;
  string endCursor       = 4;
}

message GetActiveOrganizationTermsOfUseInput {
}

message TermsOfUse {
  string id    = 1;
  string terms = 2;
}

message Admin_AddInput {
  string                   id                                  = 1;
  string                   customDomain                        = 2;
  string                   name                                = 3;
  ListingMetadata          listingMetadata                     = 4;
  string                   logoUrl                             = 5;
  string                   website                             = 6;
  bool                     agreedToTermsOfUse                  = 7;
  string                   termsOfUseId                        = 8;
  repeated string          industrySubCategoryIds              = 9;
  string                   offeringCode                        = 10;
  OrganizationType         type                                = 11;
  string                   contactEmail                        = 12;
  string                   contactPhone                        = 13;
  repeated CdnImageFile    featureImages                       = 14;
  ListingMetadata          marketplaceListingMetadata          = 15;
  OrganizationBillingCycle billingCycle                        = 16;
  string                   customerFacingTermsAndConditionsUrl = 17;
}

enum OrganizationType {
  OrganizationType_Private     = 0;
  OrganizationType_Marketplace = 1;
  OrganizationType_Individual  = 2;
}

enum OrganizationBillingCycle {
  OrganizationBillingCycle_Weekly      = 0;
  OrganizationBillingCycle_Fortnightly = 1;
  OrganizationBillingCycle_Monthly     = 2;
}

message Admin_GetOrganizationStripeConnectAccountsResponse {
  repeated StripeConnectAccount accounts = 1;
}

message Organization {
  string                        id                                  = 1;
  string                        customDomain                        = 2;
  string                        name                                = 3;
  ListingMetadata               listingMetadata                     = 4;
  string                        logoUrl                             = 5;
  string                        website                             = 6;
  bool                          agreedToTermsOfUse                  = 7;
  string                        termsOfUseId                        = 8;
  repeated IndustrySubCategory  industrySubCategories               = 9;
  repeated OrganizationMember   members                             = 10;
  Offering                      Offering                            = 11;
  bool                          hasAttachedPaymentMethod            = 12;
  bool                          hasFutureBooking                    = 13;
  repeated Tag                  tags                                = 14;
  repeated ResourceType         resourceTypes                       = 15;
  OrganizationType              type                                = 16;
  string                        contactEmail                        = 17;
  string                        contactPhone                        = 18;
  bool                          isListable                          = 19;
  BillingDetails                billingDetails                      = 20;
  StripeCustomer                stripeCustomer                      = 21;
  repeated StripePaymentMethod  stripePaymentMethods                = 22;
  repeated StripeConnectAccount stripeConnectAccounts               = 23;
  TaxDetails                    taxDetails                          = 24;
  PhysicalAddress               physicalAddress                     = 25;
  bool                          isOwnershipVerified                 = 26;
  repeated CdnImageFile         featureImages                       = 27;
  ListingMetadata               marketplaceListingMetadata          = 28;
  OrganizationBillingCycle      billingCycle                        = 29;
  string                        customerFacingTermsAndConditionsUrl = 30;
}

message IndustrySubCategory {
  string id               = 1;
  string name             = 2;
  string mainCategoryName = 3;
}

message Offering {
  string                    id                = 1;
  string                    code              = 2;
  google.protobuf.Timestamp start             = 3;
  google.protobuf.Timestamp end               = 4;
  bool                      autoRenew         = 5;
  int32                     unitPrice         = 6;
  repeated string           activeCustomerIds = 7;
  string                    organizationId    = 8;
}

message Admin_GetInput {
  string id           = 1;
  string customDomain = 2;
}

message Admin_GetXeroConnectionInput {
  string organizationId           = 1;
  string organizationCustomDomain = 2;
}

message XeroConnection {
  string                    id                            = 1;
  string                    tenantId                      = 2;
  string                    tenantName                    = 3;
  string                    billingMode                   = 4;
  string                    scopes                        = 5;
  bool                      isActive                      = 6;
  bool                      sendInvoicesViaXero           = 7;
  bool                      autoReconcilePayments         = 8;
  string                    defaultSalesAccountCode       = 9;
  string                    defaultReceivablesAccountCode = 10;
  string                    defaultTrackingCategory1      = 11;
  string                    defaultTrackingCategory2      = 12;
  string                    defaultBrandingThemeId        = 13;
  string                    defaultReferencePrefix        = 14;
  google.protobuf.Timestamp accessTokenExpiresAt          = 15;
  google.protobuf.Timestamp refreshTokenExpiresAt         = 16;
  google.protobuf.Timestamp lastSuccessfulSyncAt          = 17;
  string                    lastError                     = 18;
  bool                      hasAccessToken                = 19;
  bool                      hasRefreshToken               = 20;
  string                    accessTokenEncrypted          = 21;
  string                    refreshTokenEncrypted         = 22;
}

message Admin_RefreshXeroConnectionTokensInput {
  string                    organizationId        = 1;
  string                    accessTokenEncrypted  = 2;
  string                    refreshTokenEncrypted = 3;
  google.protobuf.Timestamp accessTokenExpiresAt  = 4;
  google.protobuf.Timestamp refreshTokenExpiresAt = 5;
}

message GetInput {
  string id           = 1;
  string customDomain = 2;
}

enum OrganizationMemberRole {
  OrganizationMemberRole_Owner         = 0;
  OrganizationMemberRole_Administrator = 1;
  OrganizationMemberRole_Member        = 2;
}

message OrganizationMember {
  string                   id                           = 1;
  string                   customerId                   = 2;
  OrganizationMemberRole   role                         = 3;
  bool                     isOrganizationOnboardingDone = 4;
  OrganizationMemberStatus status                       = 5;
}

enum OrganizationMemberStatus
{
  OrganizationMemberStatus_Active   = 0;
  OrganizationMemberStatus_Inactive = 1;
}

message Admin_AddMemberInput {
  string             id     = 1;
  OrganizationMember member = 2;
}

message GetPaginatedMembersInput {
  string                    after   = 1;
  int32                     first   = 2;
  string                    before  = 3;
  int32                     last    = 4;
  MemberWhereInput          where   = 5;
  repeated MemberOrderInput orderBy = 6;
}

message MemberWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
  string customerId     = 3;
}

message MemberOrderInput {
  OrderDirection   direction = 1;
  MemberOrderField field     = 2;
}

enum MemberOrderField {
  MemberOrderField_RoleType    = 0;
  MemberOrderField_Status      = 1;
  MemberOrderField_Name        = 2;
  MemberOrderField_GivenName   = 3;
  MemberOrderField_MiddleName  = 4;
  MemberOrderField_FamilyName  = 5;
  MemberOrderField_PhoneNumber = 6;
}

message MemberConnection {
  PageInfo            pageInfo   = 1;
  repeated MemberEdge edges      = 2;
  int32               totalCount = 3;
}

message MemberEdge {
  OrganizationMember node   = 1;
  string             cursor = 2;
}

message GetPermissionsInput {
  string id = 1;
}

message Permissions {
  bool canView                            = 1;
  bool canModify                          = 2;
  bool canDelete                          = 3;
  bool canInvitePeople                    = 4;
  bool canCancelPeopleExistingInvitations = 5;
  bool canViewAnalytics                   = 6;
}

message Admin_GetTagInput {
  string id = 1;
}

message Admin_GetPaginatedTagsInput {
  string                 after   = 1;
  int32                  first   = 2;
  string                 before  = 3;
  int32                  last    = 4;
  TagWhereInput          where   = 5;
  repeated TagOrderInput orderBy = 6;
}

message GetTagInput {
  string id = 1;
}

message Tag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string tagType     = 4;
  string color       = 5;
}

message TagConnection {
  PageInfo         pageInfo   = 1;
  repeated TagEdge edges      = 2;
  int32            totalCount = 3;
}

message TagEdge {
  Tag    node   = 1;
  string cursor = 2;
}

message GetPaginatedTagsInput {
  string                 after   = 1;
  int32                  first   = 2;
  string                 before  = 3;
  int32                  last    = 4;
  TagWhereInput          where   = 5;
  repeated TagOrderInput orderBy = 6;
}

message TagWhereInput {
  string          organizationId = 1;
  string          nameContains   = 2;
  repeated string types          = 3;
}

message TagOrderInput {
  OrderDirection direction = 1;
  TagOrderField  field     = 2;
}

enum TagOrderField {
  TagOrderField_Name        = 0;
  TagOrderField_Description = 1;
}

message AddTagInput {
  string id             = 1;
  string organizationId = 2;
  string name           = 3;
  string description    = 4;
  string color          = 5;
  string type           = 6;
}

message UpdateTagInput {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
  string type        = 6;
}

message RemoveTagInput {
  string id = 1;
}

message CustomTag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message CustomTagConnection {
  PageInfo               pageInfo   = 1;
  repeated CustomTagEdge edges      = 2;
  int32                  totalCount = 3;
}

message CustomTagEdge {
  CustomTag node   = 1;
  string    cursor = 2;
}

message GetPaginatedCustomTagsInput {
  string                       after   = 1;
  int32                        first   = 2;
  string                       before  = 3;
  int32                        last    = 4;
  CustomTagWhereInput          where   = 5;
  repeated CustomTagOrderInput orderBy = 6;
}

message CustomTagWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
}

message CustomTagOrderInput {
  OrderDirection      direction = 1;
  CustomTagOrderField field     = 2;
}

enum CustomTagOrderField {
  CustomTagOrderField_Name        = 0;
  CustomTagOrderField_Description = 1;
}

message Admin_GetCustomTagInput {
  string id = 1;
}

message GetCustomTagInput {
  string id = 1;
}

message RemoveCustomTagInput {
  string id = 1;
}

message AddCustomTagInput {
  string id             = 1;
  string organizationId = 2;
  string name           = 3;
  string description    = 4;
  string color          = 5;
}

message UpdateCustomTagInput {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message Zone {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message ZoneConnection {
  PageInfo          pageInfo   = 1;
  repeated ZoneEdge edges      = 2;
  int32             totalCount = 3;
}

message ZoneEdge {
  Zone   node   = 1;
  string cursor = 2;
}

message GetPaginatedZonesInput {
  string                  after   = 1;
  int32                   first   = 2;
  string                  before  = 3;
  int32                   last    = 4;
  ZoneWhereInput          where   = 5;
  repeated ZoneOrderInput orderBy = 6;
}

message ZoneWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
}

message ZoneOrderInput {
  OrderDirection direction = 1;
  ZoneOrderField field     = 2;
}

enum ZoneOrderField {
  ZoneOrderField_Name        = 0;
  ZoneOrderField_Description = 1;
}

message Admin_GetZoneInput {
  string id = 1;
}

message GetZoneInput {
  string id = 1;
}

message AddZoneInput {
  string id             = 1;
  string organizationId = 2;
  string name           = 3;
  string description    = 4;
  string color          = 5;
}

message UpdateZoneInput {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message RemoveZoneInput {
  string id = 1;
}

message ResourceType {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string tagType     = 4;
  string color       = 5;
}

message GetBillingDetailsInput {
  string organizationId = 1;
}

message AddBillingDetailsInput {
  string id             = 1;
  string organizationId = 2;
  string companyName    = 3;
  string email          = 4;
  string addressLine1   = 5;
  string addressLine2   = 6;
  string suburb         = 7;
  string city           = 8;
  string province       = 9;
  string zipcode        = 10;
  string country        = 11;
  string countryCode    = 12;
}

message UpdateBillingDetailsInput {
  string id           = 1;
  string companyName  = 2;
  string email        = 3;
  string addressLine1 = 4;
  string addressLine2 = 5;
  string suburb       = 6;
  string city         = 7;
  string province     = 8;
  string zipcode      = 9;
  string country      = 10;
  string countryCode  = 11;
}

message BillingDetails {
  string      id               = 1;
  string      companyName      = 2;
  string      email            = 3;
  string      addressLine1     = 4;
  string      addressLine2     = 5;
  string      suburb           = 6;
  string      city             = 7;
  string      province         = 8;
  string      zipcode          = 9;
  string      country          = 10;
  string      countryCode      = 11;
  string      formattedAddress = 12;
  string      osmType          = 13;
  string      osmId            = 14;
  string      placeId          = 15;
  Coordinates coordinates      = 16;
}

message StripeCustomer {
  string id               = 1;
  string stripeCustomerId = 2;
}

message StripePaymentMethod {
  string id            = 1;
  string setupIntentId = 2;
}

message Admin_GetStripeConnectAccountsInput {
  string                                  after   = 1;
  int32                                   first   = 2;
  string                                  before  = 3;
  int32                                   last    = 4;
  StripeConnectAccountWhereInput          where   = 5;
  repeated StripeConnectAccountOrderInput orderBy = 6;
}

message StripeConnectAccountWhereInput {
  string organizationId      = 1;
  string nameContains        = 2;
  bool   onboardingCompleted = 3;
}

message StripeConnectAccountOrderInput {
  OrderDirection                 direction = 1;
  StripeConnectAccountOrderField field     = 2;
}

enum StripeConnectAccountOrderField {
  StripeConnectAccountOrderField_Name = 0;
}

message StripeConnectAccountConnection {
  PageInfo                          pageInfo   = 1;
  repeated StripeConnectAccountEdge edges      = 2;
  int32                             totalCount = 3;
}

message StripeConnectAccountEdge {
  StripeConnectAccount node   = 1;
  string               cursor = 2;
}

message StripeConnectAccount {
  string id                       = 1;
  bool   isDefault                = 2;
  string stripeAccountId          = 3;
  string name                     = 4;
  bool   chargesEnabled           = 5;
  bool   payoutsEnabled           = 6;
  string type                     = 7;
  string country                  = 8;
  string defaultCurrency          = 9;
  string businessType             = 10;
  string companyName              = 11;
  string url                      = 12;
  string supportUrl               = 13;
  string contactEmail             = 14;
  string contactPhone             = 15;
  bool   detailsSubmitted         = 16;
  string capabilitiesTransfers    = 17;
  string capabilitiesCardPayments = 18;
  string onboardingUrl            = 19;
  bool   onboardingCompleted      = 20;
}

message Admin_GetBankAccountsInput {
  string                         after   = 1;
  int32                          first   = 2;
  string                         before  = 3;
  int32                          last    = 4;
  BankAccountWhereInput          where   = 5;
  repeated BankAccountOrderInput orderBy = 6;
}

message BankAccountWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
}

message BankAccountOrderInput {
  OrderDirection        direction = 1;
  BankAccountOrderField field     = 2;
}

enum BankAccountOrderField {
  BankAccountOrderField_Name = 0;
}

message BankAccountConnection {
  PageInfo                 pageInfo   = 1;
  repeated BankAccountEdge edges      = 2;
  int32                    totalCount = 3;
}

message BankAccountEdge {
  BankAccount node   = 1;
  string      cursor = 2;
}

message BankAccount {
  string id                = 1;
  bool   isDefault         = 2;
  string name              = 3;
  string bankName          = 4;
  string accountHolderName = 5;
  string accountNumber     = 6;
  string country           = 7;
}

message TaxDetails {
  string id                = 1;
  string taxId             = 2;
  double taxRatePercentage = 3;
}

message PhysicalAddress {
  string      id               = 1;
  string      addressLine1     = 2;
  string      addressLine2     = 3;
  string      suburb           = 4;
  string      city             = 5;
  string      province         = 6;
  string      zipcode          = 7;
  string      country          = 8;
  string      countryCode      = 9;
  string      formattedAddress = 10;
  string      osmType          = 11;
  string      osmId            = 12;
  string      placeId          = 13;
  Coordinates coordinates      = 14;
}

message Coordinates {
  double longitude = 1;
  double latitude  = 2;
}

message ProductTag {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message ProductTagConnection {
  PageInfo                pageInfo   = 1;
  repeated ProductTagEdge edges      = 2;
  int32                   totalCount = 3;
}

message ProductTagEdge {
  ProductTag node   = 1;
  string     cursor = 2;
}

message GetPaginatedProductTagsInput {
  string                        after   = 1;
  int32                         first   = 2;
  string                        before  = 3;
  int32                         last    = 4;
  ProductTagWhereInput          where   = 5;
  repeated ProductTagOrderInput orderBy = 6;
}

message ProductTagWhereInput {
  string organizationId = 1;
  string nameContains   = 2;
}

message ProductTagOrderInput {
  OrderDirection       direction = 1;
  ProductTagOrderField field     = 2;
}

enum ProductTagOrderField {
  ProductTagOrderField_Name        = 0;
  ProductTagOrderField_Description = 1;
}

message Admin_GetProductTagInput {
  string id = 1;
}

message GetProductTagInput {
  string id = 1;
}

message RemoveProductTagInput {
  string id = 1;
}

message AddProductTagInput {
  string id             = 1;
  string organizationId = 2;
  string name           = 3;
  string description    = 4;
  string color          = 5;
}

message UpdateProductTagInput {
  string id          = 1;
  string name        = 2;
  string description = 3;
  string color       = 4;
}

message CdnImageFile {
  CdnFile original  = 1;
  CdnFile thumbnail = 2;
}

message CdnFile {
  string url    = 1;
  int32  height = 2;
  int32  width  = 3;
}

message ListingMetadata {
  string          about            = 1;
  string          title            = 2;
  string          subTitle         = 3;
  repeated string includedFeatures = 4;
}
