// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: organization_internal_v1_key.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Shared.Clients.Events.Skedular.OrganizationInternal.V1.Key {

  /// <summary>Holder for reflection information generated from organization_internal_v1_key.proto</summary>
  public static partial class OrganizationInternalV1KeyReflection {

    #region Descriptor
    /// <summary>File descriptor for organization_internal_v1_key.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrganizationInternalV1KeyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJvcmdhbml6YXRpb25faW50ZXJuYWxfdjFfa2V5LnByb3RvEhRvcmdhbml6",
            "YXRpb25pbnRlcm5hbCJcCgNLZXkSFgoOb3JnYW5pemF0aW9uSWQYASABKAkS",
            "FQoNYXp1cmVUZW5hbnRJZBgCIAEoCRImCh5zdHJpcGVDb25uZWN0QWNjb3Vu",
            "dFdlYmhvb2tLZXkYAyABKAlCQaoCPkFwaS5TaGFyZWQuQ2xpZW50cy5FdmVu",
            "dHMuU2tlZHVsYXIuT3JnYW5pemF0aW9uSW50ZXJuYWwuVjEuS2V5YgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.OrganizationInternal.V1.Key.Key), global::Api.Shared.Clients.Events.Skedular.OrganizationInternal.V1.Key.Key.Parser, new[]{ "OrganizationId", "AzureTenantId", "StripeConnectAccountWebhookKey" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Key : pb::IMessage<Key>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Key> _parser = new pb::MessageParser<Key>(() => new Key());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Key> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.OrganizationInternal.V1.Key.OrganizationInternalV1KeyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Key() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Key(Key other) : this() {
      organizationId_ = other.organizationId_;
      azureTenantId_ = other.azureTenantId_;
      stripeConnectAccountWebhookKey_ = other.stripeConnectAccountWebhookKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Key Clone() {
      return new Key(this);
    }

    /// <summary>Field number for the "organizationId" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "azureTenantId" field.</summary>
    public const int AzureTenantIdFieldNumber = 2;
    private string azureTenantId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AzureTenantId {
      get { return azureTenantId_; }
      set {
        azureTenantId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stripeConnectAccountWebhookKey" field.</summary>
    public const int StripeConnectAccountWebhookKeyFieldNumber = 3;
    private string stripeConnectAccountWebhookKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StripeConnectAccountWebhookKey {
      get { return stripeConnectAccountWebhookKey_; }
      set {
        stripeConnectAccountWebhookKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Key);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Key other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      if (AzureTenantId != other.AzureTenantId) return false;
      if (StripeConnectAccountWebhookKey != other.StripeConnectAccountWebhookKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (AzureTenantId.Length != 0) hash ^= AzureTenantId.GetHashCode();
      if (StripeConnectAccountWebhookKey.Length != 0) hash ^= StripeConnectAccountWebhookKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (AzureTenantId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AzureTenantId);
      }
      if (StripeConnectAccountWebhookKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StripeConnectAccountWebhookKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (AzureTenantId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AzureTenantId);
      }
      if (StripeConnectAccountWebhookKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(StripeConnectAccountWebhookKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (AzureTenantId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AzureTenantId);
      }
      if (StripeConnectAccountWebhookKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StripeConnectAccountWebhookKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Key other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.AzureTenantId.Length != 0) {
        AzureTenantId = other.AzureTenantId;
      }
      if (other.StripeConnectAccountWebhookKey.Length != 0) {
        StripeConnectAccountWebhookKey = other.StripeConnectAccountWebhookKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            AzureTenantId = input.ReadString();
            break;
          }
          case 26: {
            StripeConnectAccountWebhookKey = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 18: {
            AzureTenantId = input.ReadString();
            break;
          }
          case 26: {
            StripeConnectAccountWebhookKey = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
