<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.Stitching" Version="13.9.14"/>
        <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\billing\apis\Billing.Api\Billing.Api.csproj" />
        <ProjectReference Include="..\..\..\booking\apis\Booking.Api\Booking.Api.csproj" />
        <ProjectReference Include="..\..\..\customer\apis\Customer.Api\Customer.Api.csproj" />
        <ProjectReference Include="..\..\..\location\apis\Location.Api\Location.Api.csproj" />
        <ProjectReference Include="..\..\..\msteams\apis\MsTeams.Api\MsTeams.Api.csproj" />
        <ProjectReference Include="..\..\..\notification\apis\Notification.Api\Notification.Api.csproj" />
        <ProjectReference Include="..\..\..\organization\apis\Organization.Api\Organization.Api.csproj" />
        <ProjectReference Include="..\..\..\payment\apis\Payment.Api\Payment.Api.csproj" />
        <ProjectReference Include="..\..\..\slack\apis\Slack.Api\Slack.Api.csproj" />
        <ProjectReference Include="..\..\..\team\apis\Team.Api\Team.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\Api.Shared.Services\Api.Shared.Services.csproj"/>
        <ProjectReference Include="..\..\..\shared\Enterprise.Shared\Enterprise.Shared.csproj"/>
    </ItemGroup>

</Project>
