<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>Slack.Domain.FakeDependencies</AssemblyName>
        <AssemblyTitle>Slack.Domain.FakeDependencies</AssemblyTitle>
        <Product>Skedular Slack Domain Fake Dependencies</Product>
        <Description>Slack domain fake dependency host for integration tests</Description>
        <Author>Skedular Team</Author>
        <Copyright>© Skedular 2026. All rights reserved.</Copyright>
        <Company>Skedular Ltd</Company>
        <RepositoryUrl>https://github.com/skedular/skedular</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- gRPC (Server) -->
        <PackageReference Include="Grpc.AspNetCore" Version="2.83.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../shared/Enterprise.Shared/Enterprise.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="appsettings.json"/>
    </ItemGroup>
</Project>
