packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@mui/x-telemetry': true
  '@vercel/speed-insights': true
  botbuilder-dialogs: true
  esbuild: true
  globalize: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@stripe/stripe-js@9.7.0'
  - '@turbo/darwin-64@2.9.15'
  - '@turbo/darwin-arm64@2.9.15'
  - '@turbo/linux-64@2.9.15'
  - '@turbo/linux-arm64@2.9.15'
  - '@turbo/windows-64@2.9.15'
  - '@turbo/windows-arm64@2.9.15'
  - eslint-plugin-turbo@2.9.15
  - turbo@2.9.15
  - '@workos-inc/authkit-nextjs@4.1.1'
  - react-relay@21.0.1
  - relay-compiler@21.0.1
  - relay-runtime@21.0.1
  - '@turbo/darwin-64@2.9.16'
  - '@turbo/darwin-arm64@2.9.16'
  - '@turbo/linux-64@2.9.16'
  - '@turbo/linux-arm64@2.9.16'
  - '@turbo/windows-64@2.9.16'
  - '@turbo/windows-arm64@2.9.16'
  - eslint-plugin-turbo@2.9.16
  - turbo@2.9.16
overrides:
  '@types/node': 25.9.0
  '@types/react': 19.2.16
  '@mui/x-data-grid': 9.3.0
  '@mui/x-data-grid-pro': 9.3.0
  '@mui/x-data-grid-premium': 9.3.0
  '@mui/x-date-pickers': 9.3.0
  '@mui/x-date-pickers-pro': 9.3.0
  '@mui/x-license': 9.2.0
  react-svg-credit-card-payment-icons: 6.0.3
patchedDependencies:
  globalize@1.7.1: patches/globalize@1.7.1.patch
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
