// <auto-generated />
using System;
using System.Collections.Generic;
using Api.Shared.Services.Models;
using Marketplace.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Shared.Database.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    partial class MarketplaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enterprise.Shared.Outbox.Database.Entities.Outbox", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, string>>("Headers")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastRetry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ProcessingErrors")
                        .HasMaxLength(102400)
                        .HasColumnType("character varying(102400)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)");

                    b.HasKey("Id");

                    b.HasIndex("LastRetry");

                    b.HasIndex("RetryCount");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Timezone");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Identity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Email");

                    b.HasIndex("EmailVerified");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MemberVisibilityPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("FULL_ACCESS");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Offering>("Offering")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PRIVATE");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Type");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationMember");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationSsoSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AppFederationMetadataUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationSsoSetting");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationTag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EventRaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Type");

                    b.ToTable("OrganizationTag");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BookAllLocationResources")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxBookingSpreadDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumberOfResourcesToBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("RecurrenceWindowDays")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireConsecutiveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Currency");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Inactive");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PricePerMinute");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.ProductVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BookAllLocationResources")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("MaxBookingSpreadDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumberOfResourcesToBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RecurrenceWindowDays")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireConsecutiveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Currency");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("Name");

                    b.HasIndex("PricePerMinute");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVersion");
                });

            modelBuilder.Entity("OrganizationTagProduct", b =>
                {
                    b.Property<string>("ProductProductTagId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductTagsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProductProductTagId", "ProductTagsId");

                    b.HasIndex("ProductTagsId");

                    b.ToTable("OrganizationTagProduct");
                });

            modelBuilder.Entity("OrganizationTagProduct1", b =>
                {
                    b.Property<string>("LocationTagsId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductLocationTagsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationTagsId", "ProductLocationTagsId");

                    b.HasIndex("ProductLocationTagsId");

                    b.ToTable("OrganizationTagProduct1");
                });

            modelBuilder.Entity("OrganizationTagProductVersion", b =>
                {
                    b.Property<string>("ProductTagsId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductVersionProductTagId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProductTagsId", "ProductVersionProductTagId");

                    b.HasIndex("ProductVersionProductTagId");

                    b.ToTable("OrganizationTagProductVersion");
                });

            modelBuilder.Entity("OrganizationTagProductVersion1", b =>
                {
                    b.Property<string>("LocationTagsId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductVersionLocationTagsId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationTagsId", "ProductVersionLocationTagsId");

                    b.HasIndex("ProductVersionLocationTagsId");

                    b.ToTable("OrganizationTagProductVersion1");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Identity", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("Identities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationMember", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Customer", "Customer")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationSsoSetting", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Organization", "Organization")
                        .WithOne("OrganizationSsoSettings")
                        .HasForeignKey("Marketplace.Shared.Database.Entities.OrganizationSsoSetting", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.OrganizationTag", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("Tags")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Product", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Organization", "Organization")
                        .WithMany("Products")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.ProductVersion", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Product", "Product")
                        .WithMany("ProductVersions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrganizationTagProduct", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductProductTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Shared.Database.Entities.OrganizationTag", null)
                        .WithMany()
                        .HasForeignKey("ProductTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationTagProduct1", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.OrganizationTag", null)
                        .WithMany()
                        .HasForeignKey("LocationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Shared.Database.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductLocationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationTagProductVersion", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.OrganizationTag", null)
                        .WithMany()
                        .HasForeignKey("ProductTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Shared.Database.Entities.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("ProductVersionProductTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationTagProductVersion1", b =>
                {
                    b.HasOne("Marketplace.Shared.Database.Entities.OrganizationTag", null)
                        .WithMany()
                        .HasForeignKey("LocationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Shared.Database.Entities.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("ProductVersionLocationTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Customer", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("OrganizationMembers");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Organization", b =>
                {
                    b.Navigation("OrganizationMembers");

                    b.Navigation("OrganizationSsoSettings");

                    b.Navigation("Products");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Marketplace.Shared.Database.Entities.Product", b =>
                {
                    b.Navigation("ProductVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
