// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: payment_v1_value.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Shared.Clients.Events.Skedular.Payment.V1.Value {

  /// <summary>Holder for reflection information generated from payment_v1_value.proto</summary>
  public static partial class PaymentV1ValueReflection {

    #region Descriptor
    /// <summary>File descriptor for payment_v1_value.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PaymentV1ValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwYXltZW50X3YxX3ZhbHVlLnByb3RvEgdwYXltZW50Gh9nb29nbGUvcHJv",
            "dG9idWYvdGltZXN0YW1wLnByb3RvIkkKBUV2ZW50EiMKCG1ldGFkYXRhGAEg",
            "ASgLMhEucGF5bWVudC5NZXRhZGF0YRIbCgRkYXRhGAIgASgLMg0ucGF5bWVu",
            "dC5EYXRhIp0BCghNZXRhZGF0YRIKCgJpZBgBIAEoCRIUCgxkb21haW5Tb3Vy",
            "Y2UYAiABKAkSEQoJYXBwU291cmNlGAMgASgJEhsKBHR5cGUYBCABKA4yDS5w",
            "YXltZW50LlR5cGUSKAoEdGltZRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXASFQoNY29ycmVsYXRpb25JZBgGIAEoCSKxAQoERGF0YRJHChlv",
            "cmdhbml6YXRpb25QYXltZW50TWV0aG9kGAEgASgLMiIucGF5bWVudC5Pcmdh",
            "bml6YXRpb25QYXltZW50TWV0aG9kSAASVQogb3JnYW5pemF0aW9uU3RyaXBl",
            "Q29ubmVjdEFjY291bnQYAiABKAsyKS5wYXltZW50Lk9yZ2FuaXphdGlvblN0",
            "cmlwZUNvbm5lY3RBY2NvdW50SABCCQoHcGF5bG9hZCJVChlPcmdhbml6YXRp",
            "b25QYXltZW50TWV0aG9kEhYKDm9yZ2FuaXphdGlvbklkGAEgASgJEiAKGGhh",
            "c0F0dGFjaGVkUGF5bWVudE1ldGhvZBgCIAEoCCLHAwogT3JnYW5pemF0aW9u",
            "U3RyaXBlQ29ubmVjdEFjY291bnQSCgoCaWQYASABKAkSLQoJZGVsZXRlZEF0",
            "GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIWCg5vcmdhbml6",
            "YXRpb25JZBgDIAEoCRIMCgRuYW1lGAQgASgJEhYKDmNoYXJnZXNFbmFibGVk",
            "GAUgASgIEhYKDnBheW91dHNFbmFibGVkGAYgASgIEgwKBHR5cGUYByABKAkS",
            "DwoHY291bnRyeRgIIAEoCRIXCg9kZWZhdWx0Q3VycmVuY3kYCSABKAkSFAoM",
            "YnVzaW5lc3NUeXBlGAogASgJEhMKC2NvbXBhbnlOYW1lGAsgASgJEg0KBWVt",
            "YWlsGAwgASgJEg0KBXBob25lGA0gASgJEh0KFWNhcGFiaWxpdGllc1RyYW5z",
            "ZmVycxgOIAEoCRIgChhjYXBhYmlsaXRpZXNDYXJkUGF5bWVudHMYDyABKAkS",
            "FQoNb25ib2FyZGluZ1VybBgQIAEoCRI5ChVvbmJvYXJkaW5nQ29tcGxldGVk",
            "QXQYESABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKogBCgRUeXBl",
            "EiUKIU9yZ2FuaXphdGlvblBheW1lbnRNZXRob2RzVXBkYXRlZBAAEiwKKE9y",
            "Z2FuaXphdGlvblN0cmlwZUNvbm5lY3RBY2NvdW50VXBzZXJ0ZWQQARIrCidP",
            "cmdhbml6YXRpb25TdHJpcGVDb25uZWN0QWNjb3VudERlbGV0ZWQQAkI2qgIz",
            "QXBpLlNoYXJlZC5DbGllbnRzLkV2ZW50cy5Ta2VkdWxhci5QYXltZW50LlYx",
            "LlZhbHVlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Event), global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Event.Parser, new[]{ "Metadata", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata), global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata.Parser, new[]{ "Id", "DomainSource", "AppSource", "Type", "Time", "CorrelationId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data), global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data.Parser, new[]{ "OrganizationPaymentMethod", "OrganizationStripeConnectAccount" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod), global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod.Parser, new[]{ "OrganizationId", "HasAttachedPaymentMethod" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount), global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount.Parser, new[]{ "Id", "DeletedAt", "OrganizationId", "Name", "ChargesEnabled", "PayoutsEnabled", "Type", "Country", "DefaultCurrency", "BusinessType", "CompanyName", "Email", "Phone", "CapabilitiesTransfers", "CapabilitiesCardPayments", "OnboardingUrl", "OnboardingCompletedAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Type {
    [pbr::OriginalName("OrganizationPaymentMethodsUpdated")] OrganizationPaymentMethodsUpdated = 0,
    [pbr::OriginalName("OrganizationStripeConnectAccountUpserted")] OrganizationStripeConnectAccountUpserted = 1,
    [pbr::OriginalName("OrganizationStripeConnectAccountDeleted")] OrganizationStripeConnectAccountDeleted = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.PaymentV1ValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event(Event other) : this() {
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 1;
    private global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (metadata_ == null) {
              Metadata = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (metadata_ == null) {
              Metadata = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Metadata();
            }
            input.ReadMessage(Metadata);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Data();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Metadata : pb::IMessage<Metadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Metadata> _parser = new pb::MessageParser<Metadata>(() => new Metadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Metadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.PaymentV1ValueReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata(Metadata other) : this() {
      id_ = other.id_;
      domainSource_ = other.domainSource_;
      appSource_ = other.appSource_;
      type_ = other.type_;
      time_ = other.time_ != null ? other.time_.Clone() : null;
      correlationId_ = other.correlationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata Clone() {
      return new Metadata(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "domainSource" field.</summary>
    public const int DomainSourceFieldNumber = 2;
    private string domainSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DomainSource {
      get { return domainSource_; }
      set {
        domainSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "appSource" field.</summary>
    public const int AppSourceFieldNumber = 3;
    private string appSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppSource {
      get { return appSource_; }
      set {
        appSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type type_ = global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 6;
    private string correlationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Metadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Metadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DomainSource != other.DomainSource) return false;
      if (AppSource != other.AppSource) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(Time, other.Time)) return false;
      if (CorrelationId != other.CorrelationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (DomainSource.Length != 0) hash ^= DomainSource.GetHashCode();
      if (AppSource.Length != 0) hash ^= AppSource.GetHashCode();
      if (Type != global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated) hash ^= Type.GetHashCode();
      if (time_ != null) hash ^= Time.GetHashCode();
      if (CorrelationId.Length != 0) hash ^= CorrelationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (DomainSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DomainSource);
      }
      if (AppSource.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (DomainSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DomainSource);
      }
      if (AppSource.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (time_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Time);
      }
      if (CorrelationId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CorrelationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (DomainSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DomainSource);
      }
      if (AppSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppSource);
      }
      if (Type != global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (CorrelationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrelationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Metadata other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.DomainSource.Length != 0) {
        DomainSource = other.DomainSource;
      }
      if (other.AppSource.Length != 0) {
        AppSource = other.AppSource;
      }
      if (other.Type != global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type.OrganizationPaymentMethodsUpdated) {
        Type = other.Type;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      if (other.CorrelationId.Length != 0) {
        CorrelationId = other.CorrelationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            DomainSource = input.ReadString();
            break;
          }
          case 26: {
            AppSource = input.ReadString();
            break;
          }
          case 32: {
            Type = (global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 50: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            DomainSource = input.ReadString();
            break;
          }
          case 26: {
            AppSource = input.ReadString();
            break;
          }
          case 32: {
            Type = (global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.Type) input.ReadEnum();
            break;
          }
          case 42: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
          case 50: {
            CorrelationId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Data : pb::IMessage<Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.PaymentV1ValueReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data(Data other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.OrganizationPaymentMethod:
          OrganizationPaymentMethod = other.OrganizationPaymentMethod.Clone();
          break;
        case PayloadOneofCase.OrganizationStripeConnectAccount:
          OrganizationStripeConnectAccount = other.OrganizationStripeConnectAccount.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data Clone() {
      return new Data(this);
    }

    /// <summary>Field number for the "organizationPaymentMethod" field.</summary>
    public const int OrganizationPaymentMethodFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod OrganizationPaymentMethod {
      get { return payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod ? (global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.OrganizationPaymentMethod;
      }
    }

    /// <summary>Field number for the "organizationStripeConnectAccount" field.</summary>
    public const int OrganizationStripeConnectAccountFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount OrganizationStripeConnectAccount {
      get { return payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount ? (global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.OrganizationStripeConnectAccount;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      OrganizationPaymentMethod = 1,
      OrganizationStripeConnectAccount = 2,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrganizationPaymentMethod, other.OrganizationPaymentMethod)) return false;
      if (!object.Equals(OrganizationStripeConnectAccount, other.OrganizationStripeConnectAccount)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) hash ^= OrganizationPaymentMethod.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) hash ^= OrganizationStripeConnectAccount.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) {
        output.WriteRawTag(10);
        output.WriteMessage(OrganizationPaymentMethod);
      }
      if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) {
        output.WriteRawTag(18);
        output.WriteMessage(OrganizationStripeConnectAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) {
        output.WriteRawTag(10);
        output.WriteMessage(OrganizationPaymentMethod);
      }
      if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) {
        output.WriteRawTag(18);
        output.WriteMessage(OrganizationStripeConnectAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrganizationPaymentMethod);
      }
      if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrganizationStripeConnectAccount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Data other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.OrganizationPaymentMethod:
          if (OrganizationPaymentMethod == null) {
            OrganizationPaymentMethod = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod();
          }
          OrganizationPaymentMethod.MergeFrom(other.OrganizationPaymentMethod);
          break;
        case PayloadOneofCase.OrganizationStripeConnectAccount:
          if (OrganizationStripeConnectAccount == null) {
            OrganizationStripeConnectAccount = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount();
          }
          OrganizationStripeConnectAccount.MergeFrom(other.OrganizationStripeConnectAccount);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod subBuilder = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod();
            if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) {
              subBuilder.MergeFrom(OrganizationPaymentMethod);
            }
            input.ReadMessage(subBuilder);
            OrganizationPaymentMethod = subBuilder;
            break;
          }
          case 18: {
            global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount subBuilder = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount();
            if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) {
              subBuilder.MergeFrom(OrganizationStripeConnectAccount);
            }
            input.ReadMessage(subBuilder);
            OrganizationStripeConnectAccount = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod subBuilder = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationPaymentMethod();
            if (payloadCase_ == PayloadOneofCase.OrganizationPaymentMethod) {
              subBuilder.MergeFrom(OrganizationPaymentMethod);
            }
            input.ReadMessage(subBuilder);
            OrganizationPaymentMethod = subBuilder;
            break;
          }
          case 18: {
            global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount subBuilder = new global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.OrganizationStripeConnectAccount();
            if (payloadCase_ == PayloadOneofCase.OrganizationStripeConnectAccount) {
              subBuilder.MergeFrom(OrganizationStripeConnectAccount);
            }
            input.ReadMessage(subBuilder);
            OrganizationStripeConnectAccount = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrganizationPaymentMethod : pb::IMessage<OrganizationPaymentMethod>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrganizationPaymentMethod> _parser = new pb::MessageParser<OrganizationPaymentMethod>(() => new OrganizationPaymentMethod());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrganizationPaymentMethod> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.PaymentV1ValueReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationPaymentMethod() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationPaymentMethod(OrganizationPaymentMethod other) : this() {
      organizationId_ = other.organizationId_;
      hasAttachedPaymentMethod_ = other.hasAttachedPaymentMethod_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationPaymentMethod Clone() {
      return new OrganizationPaymentMethod(this);
    }

    /// <summary>Field number for the "organizationId" field.</summary>
    public const int OrganizationIdFieldNumber = 1;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hasAttachedPaymentMethod" field.</summary>
    public const int HasAttachedPaymentMethodFieldNumber = 2;
    private bool hasAttachedPaymentMethod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAttachedPaymentMethod {
      get { return hasAttachedPaymentMethod_; }
      set {
        hasAttachedPaymentMethod_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrganizationPaymentMethod);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrganizationPaymentMethod other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrganizationId != other.OrganizationId) return false;
      if (HasAttachedPaymentMethod != other.HasAttachedPaymentMethod) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (HasAttachedPaymentMethod != false) hash ^= HasAttachedPaymentMethod.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (HasAttachedPaymentMethod != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasAttachedPaymentMethod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrganizationId);
      }
      if (HasAttachedPaymentMethod != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasAttachedPaymentMethod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (HasAttachedPaymentMethod != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrganizationPaymentMethod other) {
      if (other == null) {
        return;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.HasAttachedPaymentMethod != false) {
        HasAttachedPaymentMethod = other.HasAttachedPaymentMethod;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 16: {
            HasAttachedPaymentMethod = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrganizationId = input.ReadString();
            break;
          }
          case 16: {
            HasAttachedPaymentMethod = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrganizationStripeConnectAccount : pb::IMessage<OrganizationStripeConnectAccount>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrganizationStripeConnectAccount> _parser = new pb::MessageParser<OrganizationStripeConnectAccount>(() => new OrganizationStripeConnectAccount());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrganizationStripeConnectAccount> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Shared.Clients.Events.Skedular.Payment.V1.Value.PaymentV1ValueReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationStripeConnectAccount() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationStripeConnectAccount(OrganizationStripeConnectAccount other) : this() {
      id_ = other.id_;
      deletedAt_ = other.deletedAt_ != null ? other.deletedAt_.Clone() : null;
      organizationId_ = other.organizationId_;
      name_ = other.name_;
      chargesEnabled_ = other.chargesEnabled_;
      payoutsEnabled_ = other.payoutsEnabled_;
      type_ = other.type_;
      country_ = other.country_;
      defaultCurrency_ = other.defaultCurrency_;
      businessType_ = other.businessType_;
      companyName_ = other.companyName_;
      email_ = other.email_;
      phone_ = other.phone_;
      capabilitiesTransfers_ = other.capabilitiesTransfers_;
      capabilitiesCardPayments_ = other.capabilitiesCardPayments_;
      onboardingUrl_ = other.onboardingUrl_;
      onboardingCompletedAt_ = other.onboardingCompletedAt_ != null ? other.onboardingCompletedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationStripeConnectAccount Clone() {
      return new OrganizationStripeConnectAccount(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deletedAt" field.</summary>
    public const int DeletedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp deletedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DeletedAt {
      get { return deletedAt_; }
      set {
        deletedAt_ = value;
      }
    }

    /// <summary>Field number for the "organizationId" field.</summary>
    public const int OrganizationIdFieldNumber = 3;
    private string organizationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chargesEnabled" field.</summary>
    public const int ChargesEnabledFieldNumber = 5;
    private bool chargesEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ChargesEnabled {
      get { return chargesEnabled_; }
      set {
        chargesEnabled_ = value;
      }
    }

    /// <summary>Field number for the "payoutsEnabled" field.</summary>
    public const int PayoutsEnabledFieldNumber = 6;
    private bool payoutsEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PayoutsEnabled {
      get { return payoutsEnabled_; }
      set {
        payoutsEnabled_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 7;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 8;
    private string country_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "defaultCurrency" field.</summary>
    public const int DefaultCurrencyFieldNumber = 9;
    private string defaultCurrency_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefaultCurrency {
      get { return defaultCurrency_; }
      set {
        defaultCurrency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "businessType" field.</summary>
    public const int BusinessTypeFieldNumber = 10;
    private string businessType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BusinessType {
      get { return businessType_; }
      set {
        businessType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "companyName" field.</summary>
    public const int CompanyNameFieldNumber = 11;
    private string companyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CompanyName {
      get { return companyName_; }
      set {
        companyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 12;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone" field.</summary>
    public const int PhoneFieldNumber = 13;
    private string phone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Phone {
      get { return phone_; }
      set {
        phone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "capabilitiesTransfers" field.</summary>
    public const int CapabilitiesTransfersFieldNumber = 14;
    private string capabilitiesTransfers_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CapabilitiesTransfers {
      get { return capabilitiesTransfers_; }
      set {
        capabilitiesTransfers_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "capabilitiesCardPayments" field.</summary>
    public const int CapabilitiesCardPaymentsFieldNumber = 15;
    private string capabilitiesCardPayments_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CapabilitiesCardPayments {
      get { return capabilitiesCardPayments_; }
      set {
        capabilitiesCardPayments_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "onboardingUrl" field.</summary>
    public const int OnboardingUrlFieldNumber = 16;
    private string onboardingUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OnboardingUrl {
      get { return onboardingUrl_; }
      set {
        onboardingUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "onboardingCompletedAt" field.</summary>
    public const int OnboardingCompletedAtFieldNumber = 17;
    private global::Google.Protobuf.WellKnownTypes.Timestamp onboardingCompletedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp OnboardingCompletedAt {
      get { return onboardingCompletedAt_; }
      set {
        onboardingCompletedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrganizationStripeConnectAccount);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrganizationStripeConnectAccount other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(DeletedAt, other.DeletedAt)) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (Name != other.Name) return false;
      if (ChargesEnabled != other.ChargesEnabled) return false;
      if (PayoutsEnabled != other.PayoutsEnabled) return false;
      if (Type != other.Type) return false;
      if (Country != other.Country) return false;
      if (DefaultCurrency != other.DefaultCurrency) return false;
      if (BusinessType != other.BusinessType) return false;
      if (CompanyName != other.CompanyName) return false;
      if (Email != other.Email) return false;
      if (Phone != other.Phone) return false;
      if (CapabilitiesTransfers != other.CapabilitiesTransfers) return false;
      if (CapabilitiesCardPayments != other.CapabilitiesCardPayments) return false;
      if (OnboardingUrl != other.OnboardingUrl) return false;
      if (!object.Equals(OnboardingCompletedAt, other.OnboardingCompletedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (deletedAt_ != null) hash ^= DeletedAt.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ChargesEnabled != false) hash ^= ChargesEnabled.GetHashCode();
      if (PayoutsEnabled != false) hash ^= PayoutsEnabled.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (DefaultCurrency.Length != 0) hash ^= DefaultCurrency.GetHashCode();
      if (BusinessType.Length != 0) hash ^= BusinessType.GetHashCode();
      if (CompanyName.Length != 0) hash ^= CompanyName.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Phone.Length != 0) hash ^= Phone.GetHashCode();
      if (CapabilitiesTransfers.Length != 0) hash ^= CapabilitiesTransfers.GetHashCode();
      if (CapabilitiesCardPayments.Length != 0) hash ^= CapabilitiesCardPayments.GetHashCode();
      if (OnboardingUrl.Length != 0) hash ^= OnboardingUrl.GetHashCode();
      if (onboardingCompletedAt_ != null) hash ^= OnboardingCompletedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (deletedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeletedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrganizationId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (ChargesEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(ChargesEnabled);
      }
      if (PayoutsEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(PayoutsEnabled);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Type);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Country);
      }
      if (DefaultCurrency.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DefaultCurrency);
      }
      if (BusinessType.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(BusinessType);
      }
      if (CompanyName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CompanyName);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Email);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Phone);
      }
      if (CapabilitiesTransfers.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(CapabilitiesTransfers);
      }
      if (CapabilitiesCardPayments.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(CapabilitiesCardPayments);
      }
      if (OnboardingUrl.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(OnboardingUrl);
      }
      if (onboardingCompletedAt_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(OnboardingCompletedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (deletedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeletedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrganizationId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (ChargesEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(ChargesEnabled);
      }
      if (PayoutsEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(PayoutsEnabled);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Type);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Country);
      }
      if (DefaultCurrency.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DefaultCurrency);
      }
      if (BusinessType.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(BusinessType);
      }
      if (CompanyName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CompanyName);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Email);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Phone);
      }
      if (CapabilitiesTransfers.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(CapabilitiesTransfers);
      }
      if (CapabilitiesCardPayments.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(CapabilitiesCardPayments);
      }
      if (OnboardingUrl.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(OnboardingUrl);
      }
      if (onboardingCompletedAt_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(OnboardingCompletedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (deletedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeletedAt);
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ChargesEnabled != false) {
        size += 1 + 1;
      }
      if (PayoutsEnabled != false) {
        size += 1 + 1;
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (Country.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (DefaultCurrency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefaultCurrency);
      }
      if (BusinessType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BusinessType);
      }
      if (CompanyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CompanyName);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Phone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
      }
      if (CapabilitiesTransfers.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CapabilitiesTransfers);
      }
      if (CapabilitiesCardPayments.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CapabilitiesCardPayments);
      }
      if (OnboardingUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(OnboardingUrl);
      }
      if (onboardingCompletedAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OnboardingCompletedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrganizationStripeConnectAccount other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.deletedAt_ != null) {
        if (deletedAt_ == null) {
          DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DeletedAt.MergeFrom(other.DeletedAt);
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ChargesEnabled != false) {
        ChargesEnabled = other.ChargesEnabled;
      }
      if (other.PayoutsEnabled != false) {
        PayoutsEnabled = other.PayoutsEnabled;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.DefaultCurrency.Length != 0) {
        DefaultCurrency = other.DefaultCurrency;
      }
      if (other.BusinessType.Length != 0) {
        BusinessType = other.BusinessType;
      }
      if (other.CompanyName.Length != 0) {
        CompanyName = other.CompanyName;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Phone.Length != 0) {
        Phone = other.Phone;
      }
      if (other.CapabilitiesTransfers.Length != 0) {
        CapabilitiesTransfers = other.CapabilitiesTransfers;
      }
      if (other.CapabilitiesCardPayments.Length != 0) {
        CapabilitiesCardPayments = other.CapabilitiesCardPayments;
      }
      if (other.OnboardingUrl.Length != 0) {
        OnboardingUrl = other.OnboardingUrl;
      }
      if (other.onboardingCompletedAt_ != null) {
        if (onboardingCompletedAt_ == null) {
          OnboardingCompletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        OnboardingCompletedAt.MergeFrom(other.OnboardingCompletedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (deletedAt_ == null) {
              DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeletedAt);
            break;
          }
          case 26: {
            OrganizationId = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            ChargesEnabled = input.ReadBool();
            break;
          }
          case 48: {
            PayoutsEnabled = input.ReadBool();
            break;
          }
          case 58: {
            Type = input.ReadString();
            break;
          }
          case 66: {
            Country = input.ReadString();
            break;
          }
          case 74: {
            DefaultCurrency = input.ReadString();
            break;
          }
          case 82: {
            BusinessType = input.ReadString();
            break;
          }
          case 90: {
            CompanyName = input.ReadString();
            break;
          }
          case 98: {
            Email = input.ReadString();
            break;
          }
          case 106: {
            Phone = input.ReadString();
            break;
          }
          case 114: {
            CapabilitiesTransfers = input.ReadString();
            break;
          }
          case 122: {
            CapabilitiesCardPayments = input.ReadString();
            break;
          }
          case 130: {
            OnboardingUrl = input.ReadString();
            break;
          }
          case 138: {
            if (onboardingCompletedAt_ == null) {
              OnboardingCompletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OnboardingCompletedAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (deletedAt_ == null) {
              DeletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeletedAt);
            break;
          }
          case 26: {
            OrganizationId = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            ChargesEnabled = input.ReadBool();
            break;
          }
          case 48: {
            PayoutsEnabled = input.ReadBool();
            break;
          }
          case 58: {
            Type = input.ReadString();
            break;
          }
          case 66: {
            Country = input.ReadString();
            break;
          }
          case 74: {
            DefaultCurrency = input.ReadString();
            break;
          }
          case 82: {
            BusinessType = input.ReadString();
            break;
          }
          case 90: {
            CompanyName = input.ReadString();
            break;
          }
          case 98: {
            Email = input.ReadString();
            break;
          }
          case 106: {
            Phone = input.ReadString();
            break;
          }
          case 114: {
            CapabilitiesTransfers = input.ReadString();
            break;
          }
          case 122: {
            CapabilitiesCardPayments = input.ReadString();
            break;
          }
          case 130: {
            OnboardingUrl = input.ReadString();
            break;
          }
          case 138: {
            if (onboardingCompletedAt_ == null) {
              OnboardingCompletedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OnboardingCompletedAt);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
