name: "shared-azure-entra"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/actions/**"
      - ".github/workflows/lint.yml"
      - ".github/workflows/shared-azure-entra.yml"
      - "shared/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/**"
      - ".github/workflows/lint.yml"
      - ".github/workflows/shared-azure-entra.yml"
      - "shared/**"

jobs:
  build:
    name: "Build"
    runs-on: 
      - ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials - staging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.STAGING_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials - staging
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.STAGING_AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Lint, Validate and Plan - staging
        uses: "./.github/actions/lint-validate-infrastructure"
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./shared/infrastructure-azure-entra/workspaces/staging
          componentName: "shared"
          environment: staging

      - name: Configure AWS credentials - production
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.PRODUCTION_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials - production
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.PRODUCTION_AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Lint, Validate and Plan - production
        uses: "./.github/actions/lint-validate-infrastructure"
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./shared/infrastructure-azure-entra/workspaces/production
          componentName: "shared"
          environment: production

  staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Deploy to staging"
    runs-on: 
      - ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all
    environment: staging
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.STAGING_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.STAGING_AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Deploy Infrastructure
        uses: "./.github/actions/deploy-infrastructure"
        with:
          workingDirectory: ./shared/infrastructure-azure-entra/workspaces/staging

  production:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Deploy to production"
    runs-on: 
      - ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all
    environment: production
    needs:
      - staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.PRODUCTION_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.PRODUCTION_AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Deploy Infrastructure
        uses: "./.github/actions/deploy-infrastructure"
        with:
          workingDirectory: ./shared/infrastructure-azure-entra/workspaces/production
