name: "shared"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/actions/**"
      - ".github/workflows/lint.yml"
      - ".github/workflows/shared.yml"
      - "shared/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/**"
      - ".github/workflows/lint.yml"
      - ".github/workflows/shared.yml"
      - "shared/**"

jobs:
  build:
    name: "Build"
    runs-on:
      - ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure AWS credentials - staging
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.STAGING_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials - staging
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.STAGING_AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.STAGING_AZURE_SUBSCRIPTION_ID }}

      - name: Configure GCP credentials - staging
        if: ${{ false }}
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.STAGING_GCP_GITHUB_ACTIONS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.STAGING_GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}

      - name: Lint, Validate and Plan - staging
        uses: "./.github/actions/lint-validate-infrastructure"
        env:
          TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
          TF_VAR_stripe_api_key: ${{ secrets.STAGING_STRIPE_API_KEY }}
          TF_VAR_gcp_web_credentials_client_id: ${{ secrets.STAGING_GCP_WEB_CREDENTIALS_CLIENT_ID }}
          TF_VAR_gcp_web_credentials_client_secret: ${{ secrets.STAGING_GCP_WEB_CREDENTIALS_CLIENT_SECRET }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./shared/infrastructure/workspaces/staging
          componentName: "shared"
          environment: staging

      - name: Configure AWS credentials - production
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.PRODUCTION_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.PRODUCTION_AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.PRODUCTION_AZURE_SUBSCRIPTION_ID }}

      - name: Configure GCP credentials - production
        if: ${{ false }}
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.PRODUCTION_GCP_GITHUB_ACTIONS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.PRODUCTION_GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}

      - name: Lint, Validate and Plan - production
        uses: "./.github/actions/lint-validate-infrastructure"
        env:
          TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
          TF_VAR_stripe_api_key: ${{ secrets.PRODUCTION_STRIPE_API_KEY }}
          TF_VAR_gcp_web_credentials_client_id: ${{ secrets.PRODUCTION_GCP_WEB_CREDENTIALS_CLIENT_ID }}
          TF_VAR_gcp_web_credentials_client_secret: ${{ secrets.PRODUCTION_GCP_WEB_CREDENTIALS_CLIENT_SECRET }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./shared/infrastructure/workspaces/production
          componentName: "shared"
          environment: production

  staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Deploy to staging"
    runs-on:
      - ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all
    environment: staging
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.STAGING_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials - staging
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.STAGING_AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.STAGING_AZURE_SUBSCRIPTION_ID }}

      - name: Configure GCP credentials
        if: ${{ false }}
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.STAGING_GCP_GITHUB_ACTIONS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.STAGING_GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}

      - name: Deploy Infrastructure
        uses: "./.github/actions/deploy-infrastructure"
        env:
          TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
          TF_VAR_stripe_api_key: ${{ secrets.STAGING_STRIPE_API_KEY }}
          TF_VAR_gcp_web_credentials_client_id: ${{ secrets.STAGING_GCP_WEB_CREDENTIALS_CLIENT_ID }}
          TF_VAR_gcp_web_credentials_client_secret: ${{ secrets.STAGING_GCP_WEB_CREDENTIALS_CLIENT_SECRET }}
        with:
          workingDirectory: ./shared/infrastructure/workspaces/staging

  production:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Deploy to production"
    runs-on:
      - ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions: write-all
    environment: production
    needs:
      - staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.PRODUCTION_AWS_GITHUB_ACTIONS_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.PRODUCTION_AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.PRODUCTION_AZURE_SUBSCRIPTION_ID }}

      - name: Configure GCP credentials
        if: ${{ false }}
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.PRODUCTION_GCP_GITHUB_ACTIONS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.PRODUCTION_GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}

      - name: Deploy Infrastructure
        uses: "./.github/actions/deploy-infrastructure"
        env:
          TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
          TF_VAR_stripe_api_key: ${{ secrets.PRODUCTION_STRIPE_API_KEY }}
          TF_VAR_gcp_web_credentials_client_id: ${{ secrets.PRODUCTION_GCP_WEB_CREDENTIALS_CLIENT_ID }}
          TF_VAR_gcp_web_credentials_client_secret: ${{ secrets.PRODUCTION_GCP_WEB_CREDENTIALS_CLIENT_SECRET }}
        with:
          workingDirectory: ./shared/infrastructure/workspaces/production
