packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@mui/x-telemetry': true
  '@vercel/speed-insights': true
  botbuilder-dialogs: true
  esbuild: true
  globalize: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/react@19.2.15'
  - react-svg-credit-card-payment-icons@6.0.3
  - vitest@4.1.7
  - '@mui/x-charts@9.3.0'
  - '@mui/x-data-grid-premium@9.3.0'
  - '@mui/x-data-grid-pro@9.3.0'
  - '@mui/x-data-grid@9.3.0'
  - '@mui/x-date-pickers-pro@9.3.0'
  - '@mui/x-date-pickers@9.3.0'
  - '@mui/x-tree-view-pro@9.3.0'
  - react-error-boundary@6.1.2
overrides:
  '@types/node': 25.9.0
  '@mui/x-data-grid': 9.3.0
  '@mui/x-data-grid-pro': 9.3.0
  '@mui/x-data-grid-premium': 9.3.0
  '@mui/x-date-pickers': 9.3.0
  '@mui/x-date-pickers-pro': 9.3.0
  '@mui/x-license': 9.2.0
  react-svg-credit-card-payment-icons: 6.0.3
patchedDependencies:
  globalize@1.7.1: patches/globalize@1.7.1.patch
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
