packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@mui/x-telemetry': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/react@19.2.15'
  - react-svg-credit-card-payment-icons@6.0.3
overrides:
  '@types/node': 25.9.0
patchedDependencies:
  globalize@1.7.1: patches/globalize@1.7.1.patch
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
